Repository getkirby/kirby, pull requests merged in 2018-08, with the labels that each got.

#811 Add CSRF helper
  config/helpers.php
  tests/Cms/HelpersTest.php
Labels: status: to review 👀, type: feature ⭐️

#812 Track code coverage for config dir
  phpunit.xml.dist
Labels: priority: low-hanging fruit 🍓, status: to review 👀, type: bug 🐛

#913 Add Pages::published
  src/Cms/Pages.php
  tests/Cms/PagesTest.php
Labels: status: to review 👀, type: feature ⭐️

#916 Reimplement basic options aliases
  src/Form/Options.php
Labels: status: to review 👀, type: enhancement ✨
