Repository getkirby/kirby, pull requests merged in 2019-10, with the labels that each got.

#2154 Store User ID in Users field instead of email #1885
  config/fields/users.php
Labels: type: enhancement ✨

#2156 Show correct error messages when exceptions are thrown in hooks #2155
  panel/src/components/Forms/FormButtons.vue
Labels: priority: high 🔥, type: bug 🐛, type: regression ⚡️

#2162 Add smartypants for languages
  src/Cms/App.php
  src/Cms/Language.php
  tests/Cms/App/AppComponentsTest.php
Labels: priority: low 🐌, status: to review 👀, type: enhancement ✨

#2157 Replace email placeholder in lock notification correctly #2134
  panel/src/components/Sections/PagesSection.vue
Labels: priority: medium 🔜, type: bug 🐛

#2171 Fix clickable disabled fields
  panel/src/components/Forms/Field.vue
Labels: difficulty: easy 🍓, priority: medium 🔜, status: to review 👀, type: bug 🐛, type: regression ⚡️

#2174 Allow same chars on file rename as on upload #2164
  panel/src/components/Dialogs/FileRenameDialog.vue
Labels: status: to review 👀, type: bug 🐛

#2137 Fix tab skipping on multiselect field
  panel/src/components/Forms/Field/MultiselectField.vue
Labels: missing: discussion 🗣, priority: low 🐌, type: bug 🐛

#2146 Fix sorting files on edge browser
  panel/src/components/Forms/Input/TextareaInput.vue
  panel/src/components/Layout/Dropzone.vue
  panel/src/config/helpers.js
  panel/src/helpers/isUploadEvent.js
Labels: difficulty: hard 🤯, priority: low 🐌, status: to review 👀, type: bug 🐛

#2093 Return all language info from API #2054
  config/api/collections.php
  config/api/models/Language.php
  config/api/models/System.php
  panel/src/store/modules/languages.js
Labels: status: to review 👀, type: enhancement ✨

#2176 Add idea folder to gitignore for JetBrains editors
  .gitignore
Labels: priority: low 🐌, status: to review 👀, type: feature ⭐️

#2177 Remove deprecated `translations` root
  config/roots.php
  src/Cms/AppTranslations.php
Labels: status: to review 👀, type: refactoring :recycle:

#2182 Fix/pagination exception
  src/Toolkit/Pagination.php
  tests/Toolkit/PaginationTest.php
Labels: status: to review 👀, type: bug 🐛, type: regression ⚡️

#2196 Fix opening multiselect via keys #2187
  panel/src/components/Forms/Field/MultiselectField.vue
  panel/src/components/Forms/Input/MultiselectInput.vue
Labels: status: to review 👀, type: bug 🐛

#2198 Allow ctrl as meta for textarea shortcuts #2113
  panel/src/components/Forms/Input/TextareaInput.vue
Labels: status: to review 👀, type: bug 🐛

#2200 Add missing Control key for Windows shortcut
  panel/src/components/Forms/Input/TextareaInput.vue
Labels: status: to review 👀

#2197 Respect changeTemplate order #2161
  src/Cms/Page.php
Labels: status: to review 👀, type: bug 🐛, type: enhancement ✨

#2199 Login: display errors to user #2161
  panel/src/components/Forms/Login.vue
  panel/src/components/Views/LoginView.vue
Labels: status: to review 👀, type: enhancement ✨

#1980 FormIndicator #1979
  panel/src/components/Forms/FormIndicator.vue
  panel/src/components/Navigation/Topbar.vue
Labels: status: to review 👀, type: feature ⭐️

#2221 Optimize Travis CI
  .travis.yml
  tests/php.ini
Labels: type: refactoring :recycle:

#2232 Added required translation for sections
  i18n/translations/en.json
  panel/src/components/Sections/FilesSection.vue
  panel/src/components/Sections/PagesSection.vue
Labels: priority: low 🐌, status: to review 👀, type: translation 🌏

#2231 Fix pagination dialog with cast integer input
  panel/src/components/Navigation/Pagination.vue
Labels: difficulty: easy 🍓, priority: low 🐌, status: to review 👀, type: bug 🐛

#2241 Check password exists before get length
  panel/src/components/Dialogs/UserPasswordDialog.vue
Labels: status: to review 👀, type: bug 🐛

#2260 Fix missing watch value prop
  panel/src/components/Forms/Input/NumberInput.vue
Labels: type: bug 🐛, type: regression ⚡️
