Repository getkirby/kirby, pull requests merged in 2019-08, with the labels that each got.

#1963 Trim titles/names before saving #1836
  i18n/translations/en.json
  panel/src/components/Dialogs/FileRenameDialog.vue
  panel/src/components/Dialogs/PageCreateDialog.vue
  panel/src/components/Dialogs/PageRenameDialog.vue
  panel/src/components/Dialogs/UserRenameDialog.vue
Labels: status: to review 👀, type: bug 🐛, type: enhancement ✨

#1964 Escape regex for Panel slugs #1946
  panel/src/helpers/slug.js
Labels: type: bug 🐛

#1967 Fix some acii transforms #1903
  src/Toolkit/Str.php
  tests/Toolkit/StrTest.php
Labels: status: to review 👀, type: bug 🐛

#1968 Exception for multiple default languages #1849
  src/Cms/App.php
  src/Cms/Languages.php
  tests/Cms/Languages/LanguagesTest.php
Labels: status: to review 👀, type: enhancement ✨

#1974 Texnixe/missing since info
  config/fields/mixins/upload.php
  src/Form/Field.php
Labels: status: to review 👀, type: enhancement ✨

#1975 Texnixe/textarea spellcheck
  config/fields/textarea.php
Labels: status: to review 👀, type: bug 🐛

#1976 Separate aliases for docs
  config/aliases.php
  config/setup.php
Labels: status: to review 👀, type: refactoring :recycle:

#1977 Revert file models #1971
  src/Cms/AppPlugins.php
  src/Cms/File.php
  tests/Cms/App/AppPluginsTest.php
  tests/Cms/Files/FileTest.php
Labels: status: to review 👀, type: refactoring :recycle:

#1986 Fix redirect after page deletion #1984
  panel/src/components/Dialogs/PageRemoveDialog.vue
Labels: status: to review 👀, type: bug 🐛

#1987 Fix space and escape in multiselect search #1983
  panel/src/components/Forms/Input/MultiselectInput.vue
Labels: status: to review 👀, type: bug 🐛

#1988 Fix checkboxes deselect when object passed #1670
  panel/src/components/Forms/Input/CheckboxesInput.vue
Labels: status: to review 👀, type: bug 🐛

#1989 Fix `num: date` with strftime #1882
  src/Cms/PageActions.php
  tests/Cms/Pages/PageSortTest.php
Labels: status: to review 👀, type: bug 🐛, type: regression ⚡️

#1991 Fix `num: date` with translations #1886
  src/Cms/PageActions.php
  tests/Cms/Pages/PageSortTest.php
Labels: status: to review 👀, type: bug 🐛

#1994 Fix dropping multiple files on textarea #1850
  panel/src/components/Forms/Input/TextareaInput.vue
Labels: status: to review 👀, type: bug 🐛

#1981 Fix SelectInput in Edge browser #1712
  panel/src/components/Forms/Input/SelectInput.vue
Labels: status: to review 👀, type: bug 🐛

#1995 Fix jump when clicking/focus on checkboxes #1657
  panel/src/components/Forms/Input/CheckboxInput.vue
Labels: status: to review 👀, type: bug 🐛

#2013 Sending email with transport props
  src/Cms/Email.php
Labels: status: to review 👀, type: enhancement ✨

#1998 Add translation for `error.access.view` key #1997
  i18n/translations/en.json
Labels: status: to review 👀, type: translation 🌏

#2042 Fix more nested options usage
  config/api/models/System.php
  config/sections/files.php
Labels: difficulty: easy 🍓, type: bug 🐛, type: refactoring :recycle:
