Repository getkirby/kirby, pull requests merged in 2019-04, with the labels that each got.

#1579 Fix File::modified #1559
  src/Cms/File.php
  tests/Cms/FileTest.php
Labels: status: to review 👀, type: bug 🐛

#1668 Support for locale arrays (backend part)
  src/Cms/App.php
  src/Cms/Language.php
  tests/Cms/LanguageTest.php
Labels: priority: regression ⚡️, status: to review 👀, type: bug 🐛

#1659 Use dayjs.customParseFormat
  panel/src/components/Forms/Calendar.vue
  panel/src/components/Forms/Input/TimeInput.vue
Labels: status: to review 👀, type: refactoring :recycle:

#1660 More reliable session garbage collection
  src/Session/FileSessionStore.php
  tests/Session/FileSessionStoreTest.php
Labels: priority: low-hanging fruit 🍓, status: to review 👀, type: bug 🐛

#1676 ContentTranslation: Cache content in memory
  src/Cms/ContentTranslation.php
Labels: priority: low-hanging fruit 🍓, status: to review 👀, type: bug 🐛

#1678 Support for custom media folder root & URL
  config/routes.php
  tests/Cms/RouterTest.php
Labels: missing: test 🔍, status: to review 👀, type: bug 🐛

#1658 Allow linking an (image:) to a file
  config/tags.php
Labels: status: to review 👀, type: enhancement ✨

#1688 Disable FormButtons on locked form
  panel/src/components/Forms/FormButtons.vue
  panel/src/store/modules/form.js
Labels: status: to review 👀, type: bug 🐛

#1706 Define DS constant in Composer setups as well
  composer.json
  composer.lock
  config/constants.php
  config/setup.php
  config/tests.php
  tests/bootstrap.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_files.php
  vendor/composer/autoload_static.php
Labels: priority: low-hanging fruit 🍓, status: to review 👀, type: refactoring :recycle:
