Repository getkirby/kirby, pull requests merged in 2019-09, with the labels that each got.

#2059 Only run APCu tests when available
  tests/Cache/ApcuCacheTest.php
Labels: difficulty: easy 🍓, priority: high 🔥, status: to review 👀

#2069 Fix unclickable disabled field help links
  panel/src/components/Forms/Field.vue
Labels: type: enhancement ✨

#2074 Fix structure preview for files/images
  panel/src/components/Forms/Previews/FilesFieldPreview.vue
  panel/src/components/Layout/ListItem.vue
  panel/src/helpers/previewThumb.js
Labels: status: to review 👀, type: bug 🐛, type: enhancement ✨

#2072 Fix k-empty layout with a lot of text #2065
  panel/src/components/Layout/Empty.vue
Labels: status: to review 👀, type: bug 🐛

#2073 Better range input baseline #2044
  panel/src/components/Forms/Input/RangeInput.vue
Labels: status: to review 👀, type: enhancement ✨

#2080 Support for returning Response obj from API route
  src/Api/Api.php
  tests/Api/ApiTest.php
Labels: difficulty: easy 🍓, status: to review 👀, type: feature ⭐️

#2029 Implement query templating for more section and field props
  config/fields/info.php
  config/fields/pages.php
  config/fields/users.php
  config/sections/mixins/empty.php
  config/sections/mixins/headline.php
  config/sections/mixins/help.php
  src/Form/Field.php
  src/Toolkit/Component.php
  tests/Cms/App/AppPluginsTest.php
  tests/Form/FieldTest.php
  tests/Form/Fields/CheckboxesFieldTest.php
  tests/Form/Fields/DateFieldTest.php
  tests/Form/Fields/EmailFieldTest.php
  tests/Form/Fields/FilesFieldTest.php
  tests/Form/Fields/HeadlineFieldTest.php
  tests/Form/Fields/HiddenFieldTest.php
  tests/Form/Fields/InfoFieldTest.php
  tests/Form/Fields/LineFieldTest.php
  tests/Form/Fields/Mixins/FilePickerMixinTest.php
  tests/Form/Fields/Mixins/PagePickerMixinTest.php
  tests/Form/Fields/Mixins/UserPickerMixinTest.php
  tests/Form/Fields/MultiselectFieldTest.php
  tests/Form/Fields/NumberFieldTest.php
  tests/Form/Fields/PagesFieldTest.php
  tests/Form/Fields/RadioFieldTest.php
  tests/Form/Fields/RangeFieldTest.php
  tests/Form/Fields/SelectFieldTest.php
  tests/Form/Fields/StructureFieldTest.php
  tests/Form/Fields/TagsFieldTest.php
  tests/Form/Fields/TelFieldTest.php
  tests/Form/Fields/TestCase.php
  tests/Form/Fields/TextFieldTest.php
  tests/Form/Fields/TextareaFieldTest.php
  tests/Form/Fields/TimeFieldTest.php
  tests/Form/Fields/ToggleFieldTest.php
  tests/Form/Fields/UrlFieldTest.php
  tests/Form/Fields/UsersFieldTest.php
  tests/Form/FieldsTest.php
  tests/Form/FormTest.php
  tests/Form/ValidationsTest.php
Labels: status: to review 👀, type: bug 🐛, type: enhancement ✨

#2086 Cache bust panel css #1729
  src/Cms/Panel.php
  views/panel.php
Labels: type: enhancement ✨

#2084 Don't save untranslatable fields
  src/Cms/ModelWithContent.php
Labels: status: to review 👀, type: bug 🐛

#2102 Update collection after updating model #1401
  src/Cms/ModelWithContent.php
  tests/Cms/Pages/PageActionsTest.php
Labels: status: to review 👀, type: bug 🐛

#2095 Pattern validation for text fields #2041
  config/fields/text.php
  panel/src/components/Forms/Input/TextInput.vue
  src/Form/Validations.php
  tests/Form/ValidationsTest.php
Labels: status: to review 👀, type: bug 🐛

#2098 Panel default lang on install and user creat #1940
  config/api/models/System.php
  panel/src/components/Dialogs/UserCreateDialog.vue
  panel/src/components/Views/InstallationView.vue
  panel/src/components/Views/UserView.vue
Labels: status: to review 👀, type: enhancement ✨

#2096 Prevent invalid fields during routing #2007
  panel/src/components/Forms/FormButtons.vue
  panel/src/components/Views/BrowserView.vue
  panel/src/components/Views/CustomView.vue
  panel/src/components/Views/InstallationView.vue
  panel/src/components/Views/LoginView.vue
  panel/src/components/Views/SettingsView.vue
  panel/src/components/Views/UsersView.vue
  panel/src/config/router.js
  panel/src/store/modules/form.js
  panel/src/store/modules/heartbeat.js
Labels: status: to review 👀, type: bug 🐛

#2097 Disable change role if only 1 role exists #1948
  src/Cms/UserPermissions.php
  tests/Cms/Users/UserPermissionsTest.php
Labels: status: to review 👀, type: enhancement ✨

#2103 Dropdown: ignore disabled on navigate #1661
  panel/src/components/Navigation/DropdownContent.vue
Labels: status: to review 👀, type: bug 🐛

#2092 Prevent non-admins promoting users to admins #1920
  i18n/translations/en.json
  panel/src/components/Dialogs/UserRoleDialog.vue
  src/Cms/UserRules.php
  tests/Cms/Users/UserRulesTest.php
Labels: status: to review 👀, type: bug 🐛

#2106 Admins should always be able to create users
  src/Cms/UserRules.php
Labels: status: to review 👀, type: bug 🐛

#2067 Fix saving always default value for all fields on structure field
  config/fields/structure.php
Labels: status: to review 👀

#2105 Api: user language as locale #1872
  src/Api/Api.php
  tests/Api/ApiTest.php
Labels: type: enhancement ✨

#2124 Update issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: type: refactoring :recycle:

#2116 Fix jump clicking select multiselect field
  panel/src/components/Forms/Input/MultiselectInput.vue
Labels: type: bug 🐛

#1993 Expose $library and $helper #1846
  panel/src/components/Dialogs/FileRenameDialog.vue
  panel/src/components/Dialogs/LanguageCreateDialog.vue
  panel/src/components/Dialogs/PageCreateDialog.vue
  panel/src/components/Dialogs/PageDuplicateDialog.vue
  panel/src/components/Dialogs/PageUrlDialog.vue
  panel/src/components/Forms/Autocomplete.vue
  panel/src/components/Forms/Calendar.vue
  panel/src/components/Forms/Field/StructureField.vue
  panel/src/components/Forms/Input/DateInput.vue
  panel/src/components/Forms/Input/DateTimeInput.vue
  panel/src/components/Forms/Input/MultiselectInput.vue
  panel/src/components/Forms/Input/TextareaInput.vue
  panel/src/components/Forms/Input/TimeInput.vue
  panel/src/components/Forms/Upload.vue
  panel/src/components/Layout/Card.vue
  panel/src/components/Misc/Image.vue
  panel/src/components/Navigation/Search.vue
  panel/src/config/events.js
  panel/src/config/helpers.js
  panel/src/config/libraries.js
  panel/src/helpers/pad.js
  panel/src/helpers/ratio.js
  panel/src/helpers/slug.js
  panel/src/helpers/string.js
  panel/src/helpers/stringCase.js
  panel/src/helpers/upload.js
  panel/src/main.js
Labels: type: enhancement ✨

#2151 assertEquals() -> assertSame() for the first tests
  tests/Cache/ApcuCacheTest.php
  tests/Cache/CacheTest.php
  tests/Cache/FileCacheTest.php
  tests/Cache/MemCachedTest.php
  tests/Cache/MemoryCacheTest.php
  tests/Cache/ValueTest.php
  tests/Data/DataTest.php
  tests/Data/HandlerTest.php
  tests/Data/JsonTest.php
  tests/Data/PHPTest.php
  tests/Data/TxtTest.php
  tests/Data/YamlTest.php
  tests/Exception/BadMethodCallExceptionTest.php
  tests/Exception/DuplicateExceptionTest.php
  tests/Exception/ExceptionTest.php
  tests/Exception/InvalidArgumentExceptionTest.php
  tests/Exception/LogicExceptionTest.php
  tests/Exception/NotFoundExceptionTest.php
  tests/Exception/PermissionExceptionTest.php
  tests/Session/AutoSessionTest.php
  tests/Session/FileSessionStoreTest.php
  tests/Session/SessionDataTest.php
  tests/Session/SessionStoreTest.php
  tests/Session/SessionTest.php
  tests/Session/SessionsTest.php
  tests/Text/KirbyTagTest.php
  tests/Text/KirbyTagsTest.php
  tests/Text/MarkdownTest.php
  tests/Text/SmartyPantsTest.php
Labels: status: to review 👀, type: refactoring :recycle:

#2149 Improve dropdown behavior when using tab
  panel/src/components/Navigation/DropdownContent.vue
Labels: difficulty: easy 🍓, priority: low 🐌, status: to review 👀, type: enhancement ✨
