Repository getkirby/kirby, pull requests merged in 2019-11, with the labels that each got.

#2310 Add missing since information
  config/helpers.php
  config/methods.php
  src/Cms/App.php
  src/Cms/ModelWithContent.php
  src/Cms/Pages.php
  src/Exception/ErrorPageException.php
  src/Http/Visitor.php
  src/Toolkit/Collection.php
  src/Toolkit/Mime.php
Labels: type: refactoring :recycle:

#2269 Immediately update app state on user login/logout
  src/Cms/Auth.php
  src/Cms/User.php
  tests/Cms/Users/UserAuthTest.php
  tests/Cms/Users/UserTest.php
Labels: status: to review 👀, type: bug 🐛

#2284 Fix structure field sortBy
  panel/src/components/Forms/Field/StructureField.vue
Labels: priority: medium 🔜, status: to review 👀, type: bug 🐛, type: regression ⚡️

#2285 Fix users field text property
  panel/src/components/Forms/Field/UsersField.vue
Labels: status: to review 👀, type: bug 🐛

#2303 Fix multiselect issues
  panel/src/components/Forms/Input/MultiselectInput.vue
Labels: priority: high 🔥, status: to review 👀, type: bug 🐛, type: regression ⚡️

#2315 Fix unicode support
  panel/src/helpers/regex.js
Labels: status: to review 👀, type: bug 🐛, type: regression ⚡️

#2317 Add text/csv MIME type
  src/Toolkit/Mime.php
Labels: status: to review 👀, type: enhancement ✨

#2319 Use default lang for page num query #2256
  src/Cms/PageActions.php
  tests/Cms/Pages/PageSortTest.php
Labels: status: to review 👀, type: enhancement ✨

#2324 Remote: Enhancements to headers #2322
  src/Http/Remote.php
  tests/Http/RemoteTest.php
Labels: status: to review 👀, type: enhancement ✨
