Repository getkirby/kirby, pull requests merged in 2019-02, with the labels that each got.

#1434 Multiselect field: unset `accept` option
  config/fields/multiselect.php
Labels: status: to review 👀, type: refactoring :recycle:

#1430 Fix for Blueprint Datetime Usage #1424
  src/Cms/PageActions.php
Labels: status: to review 👀, type: bug 🐛

#1435 Fix pages section `templates` option
  config/sections/pages.php
  tests/Cms/PagesSectionTest.php
Labels: status: to review 👀, type: enhancement ✨

#1441 Files field: update when file gets deleted #1347
  panel/src/components/Dialogs/FileRemoveDialog.vue
  panel/src/ui/components/Forms/Field/FilesField.vue
Labels: status: to review 👀, type: bug 🐛

#1439 Fix new Collection from array #1429
  src/Cms/Collection.php
  tests/Cms/CollectionTest.php
Labels: status: to review 👀, type: bug 🐛

#1454 Use semantic versioning for Composer installer
  composer.json
Labels: priority: low-hanging fruit 🍓, type: enhancement ✨
