Repository getkirby/kirby, pull requests merged in 2020-05, with the labels that each got.

#2597 Fix a typo
  src/Toolkit/Dir.php
Labels: difficulty: easy 🤩, type: refactoring :recycle:

#2560 Options API: Use cURL instead of file_get_contents
  src/Form/OptionsApi.php
  tests/Form/OptionsApiTest.php
Labels: type: enhancement ✨, type: refactoring :recycle:

#2546 error control operator @ triggers Notice
  src/Image/Camera.php
Labels: difficulty: easy 🤩, type: bug 🐛, type: refactoring :recycle:

#2561 Don't fetch children if there are no more path keys to check
  src/Cms/Pages.php
Labels: difficulty: easy 🤩, type: refactoring :recycle:

#2565 Add support for embedding YouTube playlists and for URL options in embed URLs
  src/Toolkit/Html.php
  tests/Toolkit/HtmlTest.php
Labels: type: feature ⭐️

#2571 $content->update(): Clear fields cache #2569
  src/Cms/Content.php
  tests/Cms/Content/ContentTest.php
Labels: type: bug 🐛

#2574 $page->changeTemplate(): Base on intended template
  src/Cms/PageActions.php
Labels: type: bug 🐛

#2587 Form\Field: Support for string validate rule
  src/Form/Field.php
  tests/Form/FieldTest.php
Labels: difficulty: easy 🤩, type: regression ⚡️

#2589 panel -> Panel in user-facing messages
  .github/ISSUE_TEMPLATE/bug_report.md
  panel/README.md
  panel/src/App.vue
  panel/src/config/errors.js
  src/Cms/Panel.php
Labels: difficulty: easy 🤩, type: refactoring :recycle:

#2596 ready callback option: Support for more options
  src/Cms/App.php
  tests/Cms/App/AppTest.php
Labels: status: blocked 🚧, type: bug 🐛, type: enhancement ✨

#2572 New A::nest() and A::nestByKeys() methods, Two-way support for option dot notation
  src/Cms/App.php
  src/Cms/AppPlugins.php
  src/Toolkit/A.php
  tests/Cms/App/AppPluginsTest.php
  tests/Cms/App/AppTest.php
  tests/Toolkit/ATest.php
Labels: type: bug 🐛

#2432 Improved I18n::translateCount() method
  src/Toolkit/I18n.php
  tests/Toolkit/I18nTest.php
Labels: type: enhancement ✨

#2549 Fix zero value on range field
  panel/src/components/Forms/Input/RangeInput.vue
Labels: type: bug 🐛, type: regression ⚡️

#2605 $page->go()
  src/Cms/Page.php
  src/Http/Response.php
Labels: type: feature ⭐️

#2608 F::niceSize(): kB -> KB #2607
  src/Toolkit/F.php
  tests/Toolkit/FTest.php
  tests/Toolkit/FileTest.php
Labels: difficulty: easy 🤩, type: bug 🐛
