Repository getkirby/kirby, pull requests merged in 2020-02, with the labels that each got.

#2424 Structure displayText method return string always
  panel/src/components/Forms/Field/StructureField.vue
Labels: difficulty: easy 🍓, status: to review 👀, type: bug 🐛

#2413 Fix disabled status position on card layouts
  panel/src/components/Navigation/ButtonDisabled.vue
Labels: difficulty: easy 🍓, status: to review 👀, type: bug 🐛

#2404 Fix deleting tag with backspace
  panel/src/components/Forms/Input/TagsInput.vue
Labels: status: to review 👀, type: bug 🐛

#2434 New $fileCache->root() method
  src/Cache/FileCache.php
  tests/Cache/FileCacheTest.php
Labels: difficulty: easy 🍓, status: to review 👀, type: enhancement ✨

#2433 Error views: Fix viewport scale on mobile
  views/snippets/header.php
Labels: difficulty: easy 🍓, status: to review 👀, type: enhancement ✨

#2411 Fix language path for pattern
  src/Cms/Language.php
Labels: status: to review 👀, type: bug 🐛, type: regression ⚡️

#2439 Fix icon option for tags field
  panel/src/components/Forms/Input/TagsInput.vue
Labels: difficulty: easy 🍓, status: to review 👀, type: bug 🐛

#2442 Translate page title error on creating
  panel/src/components/Dialogs/PageCreateDialog.vue
Labels: difficulty: easy 🍓, status: to review 👀, type: bug 🐛

#2353 Add sticky option to columns
  panel/src/components/Layout/Column.vue
  panel/src/components/Sections/Sections.vue
Labels: status: to review 👀, type: feature ⭐️
