Repository getkirby/kirby, pull requests merged in 2020-03, with the labels that each got.

#2448 Fix site title on language switch #2396
  panel/src/store/store.js
Labels: status: to review 👀, type: bug 🐛

#2465 Support numeric parts in query
  src/Toolkit/Query.php
  tests/Toolkit/QueryTest.php
Labels: difficulty: medium 🤞, status: to review 👀, type: enhancement ✨

#2459 Add support for late binding in FileActions to enable subclasses of File
  src/Cms/FileActions.php
Labels: difficulty: easy 🍓, type: enhancement ✨

#2454 Fix dialog width on mobile #2415
  panel/src/components/Dialogs/Dialog.vue
Labels: status: to review 👀, type: bug 🐛

#2464 Fix upload progress bar
  panel/src/helpers/upload.js
Labels: difficulty: easy 🍓, status: to review 👀, type: bug 🐛

#2469 Fix overflow long filename
  panel/src/components/Layout/Header.vue
  panel/src/components/Misc/Text.vue
Labels: difficulty: easy 🍓, priority: low 🐌, type: bug 🐛

#2457 Validate empty locale in language editor
  panel/src/components/Dialogs/LanguageCreateDialog.vue
  panel/src/components/Dialogs/LanguageUpdateDialog.vue
Labels: priority: low 🐌, status: to review 👀, type: bug 🐛

#2483 Check uploads option on drop textarea field
  panel/src/components/Forms/Input/TextareaInput.vue
Labels: difficulty: easy 🍓, status: to review 👀, type: bug 🐛

#2484 Improve page redirection on languages detect
  src/Cms/LanguageRoutes.php
Labels: status: to review 👀, type: feature ⭐️

#2478 Fix dialog with sticky columns
  panel/src/components/Layout/Column.vue
Labels: difficulty: easy 🤩, type: bug 🐛, type: regression ⚡️

#2489 $page->isPublished()
  src/Cms/Page.php
  tests/Cms/Pages/PageStatesTest.php
Labels: type: feature ⭐️

#2494 Fix cards overflowing in narrow columns #1666
  panel/src/components/Layout/Cards.vue
Labels: type: bug 🐛

#2495 Picker fields: “change” not “add” for non-multi
  config/fields/mixins/picker.php
  panel/src/components/Forms/Field/FilesField.vue
  panel/src/components/Forms/Field/PagesField.vue
  panel/src/components/Forms/Field/UsersField.vue
  panel/src/mixins/picker/field.js
Labels: type: enhancement ✨

#2499 Textarea: use cmd + K for link shortcut #1898
  panel/src/components/Forms/Toolbar.vue
Labels: type: enhancement ✨

#2376 Update PHP version support checks
  bootstrap.php
  composer.json
  composer.lock
  views/php.php
Labels: priority: this release 🚩

#2371 Add Panel search for files
  config/api/routes/files.php
  panel/src/components/Navigation/Search.vue
Labels: type: feature ⭐️

#2401 New Kirby\Data\Xml class
  src/Data/Data.php
  src/Data/Xml.php
  tests/Data/DataTest.php
  tests/Data/XmlTest.php
Labels: status: blocked 🚧, type: feature ⭐️

#2529 Fix duplicate keys in file components
  panel/src/components/Dialogs/FilesDialog.vue
  panel/src/components/Forms/Field/FilesField.vue
Labels: type: enhancement ✨

#2520 Uploads with different mime, same extension #2519
  panel/src/components/Views/FileView.vue
Labels: difficulty: easy 🤩, type: enhancement ✨

#2503 Unsaved changes: add confirm dialog to revert
  i18n/translations/en.json
  panel/src/components/Forms/FormButtons.vue
Labels: type: enhancement ✨

#2500 Cards: more sensible min-width for `size: tiny`
  panel/src/components/Layout/Cards.vue
Labels: type: enhancement ✨

#2497 Small Whoops facelift
  assets/whoops.css
  src/Cms/AppErrors.php
Labels: type: enhancement ✨

#2545 Str::excerpt - optional space before $rep
  src/Toolkit/Str.php
  tests/Toolkit/StrTest.php
Labels: type: enhancement ✨
