Repository getkirby/kirby, pull requests merged in 2020-07, with the labels that each got.

#2668 Fix duplicate action on structure field
  panel/src/components/Forms/Field/StructureField.vue
Labels: type: bug 🐛

#2671 Fix missing button in Dialogs #2670
  panel/src/components/Dialogs/Dialog.vue
Labels: type: bug 🐛, type: regression ⚡️

#2675 Implement prepend to duplicate action
  panel/src/components/Forms/Field/StructureField.vue
Labels: type: enhancement ✨

#2672 Fix broken toString method in ModelWithContent after new Str::template behaviour
  config/methods.php
  src/Cms/ModelWithContent.php
Labels: type: bug 🐛, type: regression ⚡️

#2677 Introduce new $go method to handle routing more safely #2665
  panel/src/components/Dialogs/UserRemoveDialog.vue
  panel/src/components/Forms/FormIndicator.vue
  panel/src/components/Navigation/Link.vue
  panel/src/components/Navigation/Search.vue
  panel/src/components/Sections/FilesSection.vue
  panel/src/components/Views/BrowserView.vue
  panel/src/components/Views/FileView.vue
  panel/src/components/Views/InstallationView.vue
  panel/src/components/Views/LoginView.vue
  panel/src/components/Views/UsersView.vue
  panel/src/main.js
Labels: type: bug 🐛, type: regression ⚡️

#2682 Fix image icon
  src/Cms/ModelWithContent.php
Labels: type: bug 🐛

#2684 `replace` field method: Always use fallback
  config/methods.php
Labels: difficulty: easy 🤩, type: bug 🐛

#2685 Improvements to the Data classes
  src/Data/Data.php
  src/Data/Handler.php
  src/Data/Json.php
  src/Data/PHP.php
  src/Data/Txt.php
  src/Data/Xml.php
  src/Data/Yaml.php
  tests/Data/DataTest.php
  tests/Data/JsonTest.php
  tests/Data/PHPTest.php
  tests/Data/TxtTest.php
  tests/Data/XmlTest.php
  tests/Data/YamlTest.php
Labels: type: enhancement ✨

#2686 Fix image icon feature
  panel/src/helpers/previewThumb.js
  src/Cms/ModelWithContent.php
Labels: type: bug 🐛

#2683 Dialogs: don’t close on mouseup
  panel/src/components/Dialogs/Dialog.vue
Labels: type: bug 🐛

#2699 Fix search words option
  config/components.php
  src/Image/Exif.php
  tests/Cms/Pages/PagesTest.php
Labels: type: bug 🐛

#2693 Supports accessible phpMailer instance on SMTP
  src/Email/Email.php
  src/Email/PHPMailer.php
  tests/Email/EmailTest.php
Labels: missing: discussion 🗣, type: feature ⭐️

#2701 Fix error page on multilang
  src/Cms/LanguageRoutes.php
  tests/Cms/Languages/LanguageRoutesTest.php
Labels: difficulty: hard 🤯, type: bug 🐛

#2649 Keep user email as original
  src/Cms/Auth.php
  src/Cms/User.php
  src/Cms/UserActions.php
  src/Cms/Users.php
  src/Http/Idn.php
  src/Toolkit/V.php
  tests/Cms/Auth/AuthProtectionTest.php
  tests/Cms/Users/UserActionsTest.php
  tests/Http/IdnTest.php
Labels: priority: high 🔥, type: bug 🐛

#2706 page.duplicate:after hook: Pass original page object
  src/Cms/PageActions.php
Labels: type: bug 🐛, type: regression ⚡️

#2707 Add missing hooks unit tests
  tests/Cms/Files/FileActionsTest.php
  tests/Cms/Pages/PageActionsTest.php
  tests/Cms/Site/SiteActionsTest.php
  tests/Cms/Users/UserActionsTest.php
Labels: type: enhancement ✨

#2711 Bring Http\Request\Query in line with Http\Query
  src/Http/Request.php
  src/Http/Request/Query.php
  tests/Http/Request/QueryTest.php
Labels: type: bug 🐛, type: enhancement ✨

#2708 Add new content() method to Form class
  config/fields/structure.php
  src/Form/Field.php
  src/Form/Form.php
  tests/Form/FormTest.php
Labels: type: bug 🐛

#2717 Don’t load languages in SettingsView if multilang is not set to true
  panel/src/components/Views/SettingsView.vue
Labels: type: bug 🐛, type: regression ⚡️

#2721 Gap field
  config/fields.php
  config/fields/gap.php
  panel/src/components/Forms/Field/GapField.vue
  panel/src/config/components.js
Labels: type: feature ⭐️

#2732 Async store
  panel/src/store/modules/languages.js
  panel/src/store/modules/system.js
  panel/src/store/modules/translation.js
  panel/src/store/modules/user.js
Labels: type: refactoring :recycle:

#2731 Async components
  panel/src/components/Dialogs/FileRemoveDialog.vue
  panel/src/components/Dialogs/FileRenameDialog.vue
  panel/src/components/Dialogs/LanguageCreateDialog.vue
  panel/src/components/Dialogs/LanguageRemoveDialog.vue
  panel/src/components/Dialogs/LanguageUpdateDialog.vue
  panel/src/components/Dialogs/PageCreateDialog.vue
  panel/src/components/Dialogs/PageDuplicateDialog.vue
  panel/src/components/Dialogs/PageRemoveDialog.vue
  panel/src/components/Dialogs/PageRenameDialog.vue
  panel/src/components/Dialogs/PageStatusDialog.vue
  panel/src/components/Dialogs/PageTemplateDialog.vue
  panel/src/components/Dialogs/PageUrlDialog.vue
  panel/src/components/Dialogs/RegistrationDialog.vue
  panel/src/components/Dialogs/SiteRenameDialog.vue
  panel/src/components/Dialogs/UserCreateDialog.vue
  panel/src/components/Dialogs/UserEmailDialog.vue
  panel/src/components/Dialogs/UserLanguageDialog.vue
  panel/src/components/Dialogs/UserPasswordDialog.vue
  panel/src/components/Dialogs/UserRemoveDialog.vue
  panel/src/components/Dialogs/UserRenameDialog.vue
  panel/src/components/Dialogs/UserRoleDialog.vue
  panel/src/components/Forms/Login.vue
  panel/src/components/Navigation/DropdownContent.vue
  panel/src/components/Navigation/Search.vue
  panel/src/mixins/section/collection.js
Labels: type: refactoring :recycle:

#2751 Html::tag(): Treat null as empty tag #2743
  src/Toolkit/Html.php
  tests/Toolkit/HtmlTest.php
Labels: type: regression ⚡️
