Repository getkirby/kirby, pull requests merged in 2020-09, with the labels that each got.

#2785 Fix/progress bar styling
  panel/src/components/Misc/Progress.vue
Labels: type: enhancement ✨

#2788 Fix checking tableWhitelist for Database class
  src/Database/Database.php
Labels: difficulty: easy 🤩, type: bug 🐛

#2797 Support arrays with page/file/user ids in $collection->not()
  src/Cms/Collection.php
  tests/Cms/Collections/CollectionTest.php
Labels: difficulty: easy 🤩, type: feature ⭐️

#2522 Allow required field when not meeting conditions
  src/Form/Field.php
  src/Form/Form.php
  tests/Form/FieldTest.php
Labels: type: enhancement ✨

#2769 Supports predefined beforeSend option
  src/Cms/Email.php
  tests/Cms/Emails/EmailTest.php
Labels: type: enhancement ✨

#2810 RTL supports for text, textarea, tags and structure fields
  panel/src/components/Forms/Field/StructureField.vue
  panel/src/components/Forms/Input/TagsInput.vue
  panel/src/components/Forms/Input/TextInput.vue
  panel/src/components/Forms/Input/TextareaInput.vue
  panel/src/helpers/direction.js
Labels: type: enhancement ✨

#2829 Overridable e() method in helpers
  config/helpers.php
Labels: type: enhancement ✨

#2833 Adds info text for users dialog
  panel/src/components/Dialogs/UsersDialog.vue
Labels: difficulty: easy 🤩, type: enhancement ✨

#2850 FileView: fix updating parent #2849
  panel/src/components/Sections/FieldsSection.vue
  panel/src/components/Sections/FilesSection.vue
  panel/src/components/Views/FileView.vue
Labels: type: bug 🐛

#2851 Fix payload routing for dialogs #2845
  panel/src/components/Dialogs/UserEmailDialog.vue
  panel/src/mixins/dialog.js
Labels: type: bug 🐛

#2852 Fix file preview info for non-images #2842
  panel/src/components/Layout/FilePreview.vue
Labels: type: bug 🐛

#2861 Content representations: Allow custom MIME
  src/Cms/App.php
  tests/Cms/App/AppResolveTest.php
Labels: difficulty: easy 🤩, type: enhancement ✨

#2858 Empty: use button if has click listener
  panel/src/components/Layout/Empty.vue
Labels: type: refactoring :recycle:
