Repository getkirby/kirby, pull requests merged in 2020-01, with the labels that each got.

#2355 Add fallbacks for grab cursor CSS #2354
  panel/src/components/Forms/Field/StructureField.vue
  panel/src/components/Misc/SortHandle.vue
Labels: status: to review 👀, type: bug 🐛

#2360 Fix `Url:to` with link anchors #2280
  config/routes.php
  src/Cms/Url.php
  tests/Cms/KirbyText/KirbyTagsTest.php
Labels: status: to review 👀, type: bug 🐛

#2367 Fix absolute path on dragText property
  src/Cms/File.php
Labels: difficulty: easy 🍓, status: to review 👀, type: bug 🐛

#2381 Update dependencies
  panel/dist/css/app.css
  panel/dist/js/app.js
  panel/dist/js/vendor.js
  panel/package-lock.json
  panel/package.json
Labels: status: to review 👀

#2350 Add Japanese slug rules #2334
  i18n/rules/fa.json
  i18n/rules/ja.json
  i18n/rules/vi.json
Labels: status: to review 👀, type: feature ⭐️

#2359 Uploads with different mime, same extension #1783
  config/sections/files.php
  panel/src/components/Sections/FilesSection.vue
  src/Cms/FileRules.php
  tests/Cms/Files/FileRulesTest.php
Labels: status: to review 👀, type: bug 🐛

#2391 Switch from Zend Framework to Laminas
  composer.json
  composer.lock
  src/Toolkit/Escape.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_files.php
  vendor/composer/autoload_psr4.php
  vendor/composer/autoload_static.php
  vendor/laminas/laminas-escaper/src/Escaper.php
  vendor/laminas/laminas-escaper/src/Exception/ExceptionInterface.php
  vendor/laminas/laminas-escaper/src/Exception/InvalidArgumentException.php
  vendor/laminas/laminas-escaper/src/Exception/RuntimeException.php
  vendor/laminas/laminas-zendframework-bridge/config/replacements.php
  vendor/laminas/laminas-zendframework-bridge/src/Autoloader.php
  vendor/laminas/laminas-zendframework-bridge/src/ConfigPostProcessor.php
  vendor/laminas/laminas-zendframework-bridge/src/Module.php
  vendor/laminas/laminas-zendframework-bridge/src/Replacements.php
  vendor/laminas/laminas-zendframework-bridge/src/RewriteRules.php
  vendor/laminas/laminas-zendframework-bridge/src/autoload.php
  vendor/zendframework/zend-escaper/src/Exception/ExceptionInterface.php
  vendor/zendframework/zend-escaper/src/Exception/InvalidArgumentException.php
  vendor/zendframework/zend-escaper/src/Exception/RuntimeException.php
Labels: difficulty: easy 🍓, priority: medium 🔜, status: to review 👀, type: refactoring :recycle:

#2389 Fix search in textarea filespicker
  config/fields/textarea.php
Labels: status: to review 👀, type: bug 🐛
