Repository getkirby/kirby, pull requests merged in 2020-12, with the labels that each got.

#2957 PHP 8.0 compatibility
  .travis.yml
  bootstrap.php
  composer.json
  composer.lock
  phpunit.xml.dist
  src/Api/Collection.php
  src/Api/Model.php
  src/Cms/Collection.php
  src/Cms/Event.php
  src/Cms/Field.php
  src/Cms/KirbyTag.php
  src/Cms/Plugin.php
  src/Cms/System.php
  src/Cms/UserActions.php
  src/Data/Data.php
  src/Data/Yaml.php
  src/Database/Sql.php
  src/Http/Cookie.php
  src/Http/Route.php
  src/Image/Dimensions.php
  src/Image/Location.php
  src/Toolkit/A.php
  src/Toolkit/F.php
  src/Toolkit/Str.php
  tests/Cache/FileCacheTest.php
  tests/Cms/Auth/AuthProtectionTest.php
  tests/Cms/Content/ContentLockTest.php
  tests/Cms/Files/FileActionsTest.php
  tests/Cms/Pages/PageActionsTest.php
  tests/Cms/Plugins/PluginAssetsTest.php
  tests/Cms/Users/UserActionsTest.php
  tests/Database/Sql/SqliteTest.php
  tests/Database/SqlTest.php
  tests/Email/TestCase.php
  tests/Session/FileSessionStoreTest.php
  tests/Toolkit/CollectionTest.php
  tests/Toolkit/FTest.php
  tests/Toolkit/HtmlTest.php
  tests/Toolkit/StrTest.php
  vendor/composer/autoload_real.php
  vendor/composer/platform_check.php
  views/php.php
Labels: type: feature ⭐️, type: refactoring :recycle:

#2965 [Blocks] Fix multi-language groups labels issue on blocks field
  src/Cms/Fieldset.php
  src/Cms/Fieldsets.php
Labels: type: bug 🐛

#2967 Add more unit tests for layout and blocks field
  .travis.yml
  src/Form/Field/BlocksField.php
  src/Form/Field/LayoutField.php
  tests/Form/Fields/BlocksFieldTest.php
  tests/Form/Fields/LayoutFieldTest.php
Labels: type: refactoring :recycle:

#2970 Use PHP 8.0.0 workaround on Travis CI
  .travis.yml
Labels: type: refactoring :recycle:

#2974 Login view: Don't load login form if logged in
  panel/src/components/Views/LoginView.vue
Labels: difficulty: easy 🤩, type: bug 🐛

#2975 [Blocks] Fixes empty text blocks/layout fields
  src/Form/Field/BlocksField.php
  tests/Form/Fields/BlocksFieldTest.php
  tests/Form/Fields/LayoutFieldTest.php
Labels: type: bug 🐛

#2973 More detailed `accept` options for file blueprints; limit file types by default
  config/fields/mixins/upload.php
  config/sections/files.php
  i18n/translations/en.json
  src/Cms/FileBlueprint.php
  src/Image/Image.php
  src/Toolkit/F.php
  tests/Cms/Files/FileActionsTest.php
  tests/Cms/Files/FileBlueprintTest.php
  tests/Image/ImageTest.php
  tests/Toolkit/FTest.php
Labels: type: feature ⭐️, type: refactoring :recycle:

#2980 Fixes accessing textContent property on empty list
  panel/src/components/Forms/Input/ListInput.vue
Labels: difficulty: easy 🤩, type: bug 🐛

#2983 Fix Block::parse() method on empty input #2982
  .travis.yml
  src/Cms/Blocks.php
  tests/Cms/Blocks/BlocksTest.php
Labels: type: bug 🐛

#2988 Media::publish(): No longer check MIME type
  src/Cms/FileRules.php
  src/Cms/Media.php
  tests/Cms/Files/FileRulesTest.php
Labels: type: enhancement ✨, type: refactoring :recycle:

#2996 Compatibility fixes and performance improvements around F::read()
  config/helpers.php
  src/Cache/FileCache.php
  src/Cms/UserActions.php
  src/Data/Handler.php
  src/Toolkit/F.php
  src/Toolkit/File.php
  tests/Toolkit/FTest.php
Labels: type: bug 🐛, type: refactoring :recycle:

#2999 3.5-RC date field fixes
  config/fields/date.php
  config/fields/mixins/datetime.php
  config/fields/time.php
  config/helpers.php
  panel/src/components/Forms/Calendar.vue
  panel/src/components/Forms/Input/DateInput.vue
  panel/src/components/Forms/Input/DateTimeInput.vue
  panel/src/components/Forms/Input/TimeInput.vue
  panel/src/helpers/validate.js
Labels: type: bug 🐛

#3018 Extendable layout settings
  src/Form/Field/LayoutField.php
  tests/Form/Fields/LayoutFieldTest.php
Labels: type: enhancement ✨

#3017 Add missing when prop for FieldClass
  src/Form/FieldClass.php
  tests/Form/Fields/BlocksFieldTest.php
  tests/Form/Fields/TestCase.php
Labels: difficulty: easy 🤩, type: bug 🐛

#3021 I18n: Support for multiple fallback locales #3006
  src/Cms/AppTranslations.php
  src/Toolkit/I18n.php
  tests/Cms/App/AppTranslationsTest.php
  tests/Toolkit/I18nTest.php
Labels: type: bug 🐛, type: enhancement ✨

#3022 $auth->status() object
  config/api/models/System.php
  config/api/routes/auth.php
  panel/src/components/Views/LoginView.vue
  src/Cms/Auth.php
  src/Cms/Auth/Status.php
  tests/Cms/App/AppPluginsTest.php
  tests/Cms/Auth/AuthChallengeTest.php
  tests/Cms/Auth/AuthTest.php
  tests/Cms/Auth/StatusTest.php
Labels: type: enhancement ✨, type: feature ⭐️

#3025 Improved translation fallback handling
  config/api/models/System.php
  src/Cms/Api.php
  src/Cms/AppTranslations.php
  src/Cms/User.php
  tests/Cms/Api/ApiTest.php
  tests/Cms/App/AppTranslationsTest.php
Labels: type: enhancement ✨
