Repository getkirby/kirby, pull requests merged in 2020-11, with the labels that each got.

#2908 Prefix core session keys with kirby.
  config/helpers.php
  src/Cms/Auth.php
  src/Cms/User.php
  tests/Cms/Auth/AuthCsrfTest.php
  tests/Cms/Auth/AuthTest.php
  tests/Cms/Helpers/HelpersTest.php
Labels: type: refactoring :recycle:

#2910 New $user->nameOrEmail() method
  src/Cms/User.php
  tests/Cms/Users/UserTest.php
Labels: type: enhancement ✨

#2915 user.js: Use Vue.$go instead of router.push
  panel/src/store/modules/user.js
Labels: type: refactoring :recycle:

#2918 Email: Support global debugging
  src/Email/Email.php
Labels: type: enhancement ✨

#2916 Reset password view + k-user-info component
  i18n/translations/en.json
  panel/src/components/Misc/UserInfo.vue
  panel/src/components/Views/LoginView.vue
  panel/src/components/Views/ResetPasswordView.vue
  panel/src/config/components.js
  panel/src/config/routes.js
  panel/src/config/views.js
Labels: type: feature ⭐️

#2920 Change throw exception for toggle field on required fields
  config/fields/toggle.php
  src/Cms/UserPermissions.php
Labels: difficulty: easy 🤩, type: bug 🐛

#2895 Locale option: Support for all locale formats (array/string)
  src/Cms/AppTranslations.php
  src/Cms/Language.php
  src/Toolkit/Locale.php
  tests/Cms/App/AppTranslationsTest.php
  tests/Toolkit/LocaleTest.php
Labels: type: enhancement ✨

#2926 More clear login error message
  panel/src/components/Forms/Login.vue
  src/Cms/Auth.php
  tests/Cms/Auth/AuthProtectionTest.php
  tests/Cms/Auth/AuthTest.php
Labels: type: enhancement ✨

#2927 Mock usleep() function for faster PHPUnit tests
  tests/Cms/mocks.php
Labels: type: refactoring :recycle:

#2923 Passwordless login, password reset via email & 2FA support
  config/api/models/System.php
  config/api/routes/auth.php
  config/templates.php
  config/templates/emails/auth/login.php
  config/templates/emails/auth/password-reset.php
  i18n/translations/en.json
  panel/src/api/auth.js
  panel/src/components/Forms/Login.vue
  panel/src/components/Forms/LoginCode.vue
  panel/src/components/Views/LoginView.vue
  panel/src/store/modules/user.js
  src/Cms/Auth.php
  src/Cms/Auth/Challenge.php
  src/Cms/Auth/EmailChallenge.php
  src/Cms/System.php
  tests/Cms/Auth/AuthChallengeTest.php
  tests/Cms/Auth/AuthProtectionTest.php
  tests/Cms/Auth/Challenge/ChallengeTest.php
  tests/Cms/Auth/Challenge/EmailChallengeTest.php
  tests/Cms/Auth/fixtures/auth.email.html.php
  tests/Cms/Auth/fixtures/auth.email.text.php
  tests/Cms/System/SystemTest.php
Labels: type: feature ⭐️

#2934 Improvements to login flow feature
  src/Cms/Auth.php
  src/Cms/Auth/EmailChallenge.php
  src/Cms/System.php
  tests/Cms/App/AppUsersTest.php
  tests/Cms/Auth/AuthChallengeTest.php
  tests/Cms/Auth/Challenge/EmailChallengeTest.php
  tests/Cms/System/SystemTest.php
Labels: type: enhancement ✨

#2931 Update npm dev dependencies
  panel/package.json
  panel/src/components/Forms/FormButtons.vue
  panel/src/components/Forms/Input/DateInput.vue
  panel/src/components/Views/FileView.vue
  panel/src/components/Views/InstallationView.vue
  panel/src/components/Views/PageView.spec.js
  panel/src/components/Views/PageView.vue
  panel/src/components/Views/SiteView.spec.js
  panel/src/components/Views/UserView.vue
  panel/src/config/config.js
  panel/src/helpers/string.js
  panel/src/mixins/dialog.js
  panel/src/store/modules/content.js
  panel/vue.config.js
Labels: type: refactoring :recycle:

#2894 Improvements to `$app->clone()`
  src/Cms/App.php
  src/Cms/PageActions.php
  tests/Cms/App/AppTest.php
Labels: type: bug 🐛

#2928 Fixes for new date/time fields
  config/fields/date.php
  config/fields/mixins/datetime.php
  config/fields/time.php
  panel/package-lock.json
  panel/src/components/Forms/Field/DateField.vue
  panel/src/components/Forms/Field/TimeField.vue
  panel/src/components/Forms/Input/DateInput.vue
  panel/src/components/Forms/Input/DateTimeInput.vue
  panel/src/components/Forms/Input/TimeInput.vue
  panel/src/components/Forms/Previews/DateFieldPreview.vue
  panel/src/components/Forms/Previews/TimeFieldPreview.vue
  panel/src/config/components.js
  tests/Form/Fields/DateFieldTest.php
  tests/Form/Fields/TimeFieldTest.php
Labels: type: bug 🐛

#2942 Router fixes for custom views
  panel/src/components/Views/CustomView.vue
  panel/src/config/router.js
  panel/src/config/routes.js
  panel/src/main.js
Labels: type: bug 🐛

#2882 Prevent accidental writes from collection methods
  src/Cms/AppUsers.php
  src/Cms/Auth.php
  src/Cms/Collection.php
  src/Cms/User.php
  tests/Cms/App/AppUsersTest.php
  tests/Cms/Auth/AuthTest.php
  tests/Cms/Collections/CollectionTest.php
Labels: type: enhancement ✨

#2939 Plugin API for auth challenges
  src/Cms/AppPlugins.php
  src/Cms/Auth.php
  src/Cms/Auth/Challenge.php
  src/Cms/Auth/EmailChallenge.php
  tests/Cms/App/AppPluginsTest.php
  tests/Cms/Auth/Challenge/ChallengeTest.php
  tests/Cms/Auth/Challenge/EmailChallengeTest.php
Labels: type: feature ⭐️

#2929 Allow extending the core login form in plugins
  panel/src/components/Views/LoginView.vue
  panel/src/config/components.js
Labels: type: enhancement ✨

#2952 Improve Travis CI setup
  .travis.yml
  panel/.travis.yml
  panel/cypress.json
  panel/src/components/Views/FileView.spec.js
  panel/src/components/Views/InstallationView.spec.js
  panel/src/components/Views/LoginView.spec.js
  panel/src/components/Views/PageView.spec.js
  panel/src/components/Views/SiteView.spec.js
  panel/src/components/Views/UsersView.spec.js
Labels: type: enhancement ✨, type: refactoring :recycle:
