Repository getkirby/kirby, pull requests merged in 2020-08, with the labels that each got.

#2753 Html::isVoid(): Allow modifying the void list
  src/Toolkit/Html.php
  tests/Toolkit/HtmlTest.php
Labels: type: enhancement ✨

#2756 Remote: Properly check CA constants #2745
  src/Http/Remote.php
  tests/Http/RemoteTest.php
Labels: type: bug 🐛

#2765 Fix a couple of typos in panel/src/api/request.js
  panel/src/api/request.js
Labels: difficulty: easy 🤩, type: refactoring :recycle:
