Repository getkirby/kirby, pull requests merged in 2020-10, with the labels that each got.

#2875 New `logs` root
  config/roots.php
  tests/Cms/Ingredients/RootsTest.php
Labels: difficulty: easy 🤩, type: enhancement ✨

#2879 Remove deprecated code
  src/Cms/File.php
  src/Cms/FileActions.php
  src/Cms/HasChildren.php
  src/Cms/Languages.php
  src/Cms/Page.php
  src/Cms/PageSiblings.php
  src/Cms/Pages.php
  src/Toolkit/Pagination.php
  tests/Cms/Pages/PagesTest.php
Labels: difficulty: easy 🤩, type: refactoring :recycle:

#2873 Fix extending nested Vue components #1438
  panel/public/js/plugins.js
  panel/src/config/plugins.js
Labels: type: bug 🐛

#2871 Quick fix for replacing Panel views #2506
  panel/src/config/routes.js
Labels: type: bug 🐛

#2872 Prevent concurrent sort API calls #2863
  panel/src/components/Sections/FilesSection.vue
  panel/src/components/Sections/PagesSection.vue
  panel/src/mixins/section/collection.js
Labels: type: bug 🐛

#2878 #2690 Fix files section sort if not sortable
  config/sections/files.php
Labels: difficulty: easy 🤩, type: bug 🐛

#2881 Deprecate $page->sort()
  src/Cms/PageActions.php
Labels: type: refactoring :recycle:

#2888 Fix delete action for paginated structure field
  panel/src/components/Forms/Field/StructureField.vue
Labels: difficulty: easy 🤩, priority: high 🔥, type: bug 🐛

#2900 Fix ESLint errors
  panel/src/App.vue
  panel/src/components/Dialogs/Dialog.vue
  panel/src/components/Forms/Input/TextInput.vue
  panel/src/components/Navigation/Search.vue
  panel/src/components/Views/FileView.vue
  panel/src/components/Views/SiteView.vue
  panel/src/config/plugins.js
  panel/src/config/search.js
Labels: difficulty: easy 🤩, type: refactoring :recycle:

#2898 Help option for headline + info fields
  config/fields/headline.php
  config/fields/info.php
  panel/src/components/Forms/Field/HeadlineField.vue
  panel/src/components/Forms/Field/InfoField.vue
Labels: type: enhancement ✨

#2811 Additional icons
  panel/public/img/icons.svg
  panel/public/index.html
Labels: type: enhancement ✨

#2899 Page create dialog: hide single template select
  panel/src/components/Dialogs/PageCreateDialog.vue
Labels: type: enhancement ✨

#2890 New page status icons
  panel/src/components/Layout/Card.vue
  panel/src/components/Layout/ListItem.vue
  panel/src/components/Misc/StatusIcon.vue
  panel/src/components/Sections/PagesSection.vue
  panel/src/components/Views/PageView.vue
  panel/src/config/components.js
Labels: type: enhancement ✨
