Repository getkirby/kirby, pull requests merged in 2021-12, with the labels that each got.

#3984 Fix empty writer field contains paragraph #3943
  panel/src/components/Forms/Writer/Writer.vue
Labels: type: bug 🐛, type: regression ⚡️

#3989 Upgrade `claviska/simpleimage`
  composer.json
  composer.lock
  vendor/claviska/simpleimage/src/claviska/SimpleImage.php
  vendor/composer/installed.json
  vendor/composer/installed.php
Labels: type: refactoring :recycle:

#3992 `Str::date()` for DRY code
  config/methods.php
  src/Cms/File.php
  src/Cms/User.php
  src/Filesystem/Dir.php
  src/Filesystem/F.php
  src/Toolkit/Str.php
  tests/Toolkit/StrTest.php
Labels: type: enhancement ✨, type: refactoring :recycle:

#3991 `ArrayIterator` return type hint
  src/Toolkit/Iterator.php
Labels: type: refactoring :recycle:

#3993 Upgrade some npm dependencies
  panel/.eslintrc.js
  panel/package-lock.json
  panel/package.json
  panel/src/components/Forms/Blocks/Types/Gallery.vue
Labels: type: refactoring :recycle:

#3990 PHP 8.1: don't pass `null`
  config/fields/list.php
  config/fields/textarea.php
  config/fields/writer.php
  src/Api/Api.php
  src/Cms/AppErrors.php
  src/Cms/System.php
  src/Cms/Template.php
  src/Data/Data.php
  src/Exception/Exception.php
  src/Http/Request.php
  src/Http/Response.php
  src/Http/Server.php
  src/Http/Uri.php
  src/Http/Url.php
  src/Panel/Panel.php
  src/Toolkit/Html.php
  src/Toolkit/Str.php
  src/Toolkit/V.php
Labels: type: refactoring :recycle:

#3995 Run prettier formatting in pre-commit hook
  scripts/pre-commit
Labels: type: refactoring :recycle:

#4001 Sane\Svg: Add additional attributes to allowlist
  src/Sane/Svg.php
  src/Toolkit/Dom.php
  tests/Sane/fixtures/svg/allowed/xmlattrs-1.svg
  tests/Sane/fixtures/svg/allowed/xmlattrs-2.svg
  tests/Sane/fixtures/svg/allowed/xmlattrs-3.svg
  tests/Sane/fixtures/svg/cleaned/xmlattrs-2.svg
  tests/Sane/fixtures/svg/cleaned/xmlattrs-3.svg
  tests/Toolkit/DomTest.php
Labels: type: enhancement ✨, type: bug 🐛

#3988 Replace unmaintained `true/punycode` dependency
  composer.json
  composer.lock
  src/Http/Idn.php
  tests/Filesystem/fixtures/f/test.txt
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_files.php
  vendor/composer/autoload_psr4.php
  vendor/composer/autoload_static.php
  vendor/composer/installed.json
  vendor/composer/installed.php
  vendor/symfony/polyfill-intl-idn/Idn.php
  vendor/symfony/polyfill-intl-idn/Info.php
  vendor/symfony/polyfill-intl-idn/LICENSE
  vendor/symfony/polyfill-intl-idn/Resources/unidata/DisallowedRanges.php
  vendor/symfony/polyfill-intl-idn/Resources/unidata/Regex.php
  vendor/symfony/polyfill-intl-idn/Resources/unidata/deviation.php
  vendor/symfony/polyfill-intl-idn/Resources/unidata/disallowed.php
  vendor/symfony/polyfill-intl-idn/Resources/unidata/disallowed_STD3_mapped.php
  vendor/symfony/polyfill-intl-idn/Resources/unidata/disallowed_STD3_valid.php
  vendor/symfony/polyfill-intl-idn/Resources/unidata/ignored.php
  vendor/symfony/polyfill-intl-idn/Resources/unidata/mapped.php
  vendor/symfony/polyfill-intl-idn/Resources/unidata/virama.php
  vendor/symfony/polyfill-intl-idn/bootstrap.php
  vendor/symfony/polyfill-intl-idn/bootstrap80.php
  vendor/symfony/polyfill-intl-idn/composer.json
  vendor/symfony/polyfill-intl-normalizer/LICENSE
  vendor/symfony/polyfill-intl-normalizer/Normalizer.php
  vendor/symfony/polyfill-intl-normalizer/Resources/stubs/Normalizer.php
  vendor/symfony/polyfill-intl-normalizer/Resources/unidata/canonicalComposition.php
  vendor/symfony/polyfill-intl-normalizer/Resources/unidata/canonicalDecomposition.php
  vendor/symfony/polyfill-intl-normalizer/Resources/unidata/combiningClass.php
  vendor/symfony/polyfill-intl-normalizer/Resources/unidata/compatibilityDecomposition.php
  vendor/symfony/polyfill-intl-normalizer/bootstrap.php
  vendor/symfony/polyfill-intl-normalizer/bootstrap80.php
  vendor/symfony/polyfill-intl-normalizer/composer.json
  vendor/symfony/polyfill-mbstring/Mbstring.php
  vendor/symfony/polyfill-mbstring/Resources/unidata/lowerCase.php
  vendor/symfony/polyfill-mbstring/Resources/unidata/titleCaseRegexp.php
  vendor/symfony/polyfill-mbstring/Resources/unidata/upperCase.php
  vendor/symfony/polyfill-mbstring/bootstrap.php
  vendor/symfony/polyfill-mbstring/bootstrap80.php
  vendor/true/punycode/composer.json
  vendor/true/punycode/src/Exception/DomainOutOfBoundsException.php
  vendor/true/punycode/src/Exception/LabelOutOfBoundsException.php
  vendor/true/punycode/src/Exception/OutOfBoundsException.php
  vendor/true/punycode/src/Punycode.php
Labels: type: refactoring :recycle:

#3649 Keep icc color profiles
  src/Image/Darkroom/ImageMagick.php
  tests/Image/Darkroom/ImageMagickTest.php
  tests/Image/fixtures/image/onigiri-adobe-rgb-gps.jpg
  tests/Image/fixtures/image/onigiri-adobe-rgb-gps.webp
  tests/Image/fixtures/image/png-adobe-rgb-gps.png
  tests/Image/fixtures/image/png-srgb-gps.png
Labels: type: enhancement ✨

#4002 Pin new Composer dependency
  composer.json
  composer.lock
Labels: difficulty: easy 🤩

#3979 Add PHP 8.1 support
  .github/workflows/ci.yml
  bootstrap.php
  config/areas/site/dialogs.php
  src/Cms/System.php
  src/Database/Database.php
  src/Http/Server.php
  src/Toolkit/Str.php
  src/Toolkit/Xml.php
  tests/Cms/Files/FileTest.php
  tests/Cms/Pages/PageTest.php
  tests/Cms/Site/SiteTest.php
  tests/Cms/Users/UserTest.php
  tests/Filesystem/FTest.php
  tests/Filesystem/FileTest.php
  tests/Toolkit/VTest.php
Labels: type: enhancement ✨, type: refactoring :recycle:

#4020 Fix HTTPS check in SystemView
  config/areas/system/views.php
  panel/src/components/Views/SystemView.vue
Labels: type: regression ⚡️

#4021 Upgrade `phpmailer`
  composer.json
  composer.lock
  vendor/composer/installed.json
  vendor/composer/installed.php
  vendor/phpmailer/phpmailer/language/phpmailer.lang-fr.php
  vendor/phpmailer/phpmailer/language/phpmailer.lang-pt_br.php
  vendor/phpmailer/phpmailer/language/phpmailer.lang-ro.php
  vendor/phpmailer/phpmailer/language/phpmailer.lang-sl.php
  vendor/phpmailer/phpmailer/src/PHPMailer.php
  vendor/phpmailer/phpmailer/src/POP3.php
  vendor/phpmailer/phpmailer/src/SMTP.php
Labels: type: refactoring :recycle:

#4022 Fix minor Prettier weirdnesses
  panel/src/components/Layout/Tabs.vue
  panel/src/helpers/object.js
Labels: type: refactoring :recycle:

#4023 PHP 8.1: Fix more arguments of built-in functions
  config/tags.php
  src/Text/KirbyTag.php
  src/Toolkit/Str.php
Labels: type: refactoring :recycle:

#4009 Fix `plugins.js` regression
  panel/src/config/plugins.js
Labels: type: regression ⚡️

#4027 Explicit CSS data attr selectors for styling
  panel/src/components/Drawers/Drawer.vue
  panel/src/components/Forms/Blocks/Block.vue
  panel/src/components/Forms/Blocks/Blocks.vue
  panel/src/components/Forms/Calendar.vue
  panel/src/components/Forms/Counter.vue
  panel/src/components/Forms/Field.vue
  panel/src/components/Forms/Field/FilesField.vue
  panel/src/components/Forms/Field/PagesField.vue
  panel/src/components/Forms/Field/StructureField.vue
  panel/src/components/Forms/Field/UsersField.vue
  panel/src/components/Forms/Input.vue
  panel/src/components/Forms/Input/CheckboxInput.vue
  panel/src/components/Forms/Input/RadioInput.vue
  panel/src/components/Forms/Input/RangeInput.vue
  panel/src/components/Forms/Writer/Writer.vue
  panel/src/components/Layout/AspectRatio.vue
  panel/src/components/Layout/Column.vue
  panel/src/components/Layout/Dropzone.vue
  panel/src/components/Layout/FilePreview.vue
  panel/src/components/Layout/Item.vue
  panel/src/components/Layout/Overlay.vue
  panel/src/components/Layout/Panel.vue
  panel/src/components/Layouter/Layout.vue
  panel/src/components/Misc/Icon.vue
  panel/src/components/Misc/Image.vue
  panel/src/components/Misc/StatusIcon.vue
  panel/src/components/Navigation/Button.vue
  panel/src/components/Navigation/ButtonDisabled.vue
  panel/src/components/Navigation/DropdownContent.vue
  panel/src/components/Navigation/Search.vue
  panel/src/components/Navigation/Tag.vue
  panel/src/components/Sections/FieldsSection.vue
  panel/src/components/Sections/FilesSection.vue
  panel/src/components/Sections/PagesSection.vue
  panel/src/components/Views/UserView.vue
  panel/src/styles/utilities.css
Labels: type: refactoring :recycle:

#4034 Passing empty string for `is_file()` when param `null`
  src/Toolkit/Tpl.php
Labels: type: bug 🐛

#4036 `dayjs` plugins for date field logic
  panel/src/config/libraries.js
  panel/src/index.js
  panel/src/libraries/dayjs-merge.js
  panel/src/libraries/dayjs-merge.test.js
  panel/src/libraries/dayjs-pattern.js
  panel/src/libraries/dayjs-pattern.test.js
  panel/src/libraries/dayjs-round.js
  panel/src/libraries/dayjs-round.test.js
  panel/src/libraries/dayjs-units.js
  panel/src/libraries/dayjs-units.test.js
  panel/src/libraries/dayjs-validate.js
  panel/src/libraries/dayjs-validate.test.js
  panel/src/libraries/dayjs.js
  panel/src/libraries/index.js
Labels: type: refactoring :recycle:

#4030 PHP 8.1 deprecation fixes (null passing, implicit float to int conversion)
  src/Image/Dimensions.php
  src/Text/KirbyTags.php
  src/Toolkit/Str.php
Labels: type: bug 🐛

#4028 More PHP arrow functions
  config/api/collections.php
  config/api/models/File.php
  config/api/models/FileBlueprint.php
  config/api/models/FileVersion.php
  config/api/models/Language.php
  config/api/models/Page.php
  config/api/models/PageBlueprint.php
  config/api/models/Role.php
  config/api/models/Site.php
  config/api/models/SiteBlueprint.php
  config/api/models/System.php
  config/api/models/Translation.php
  config/api/models/User.php
  config/api/models/UserBlueprint.php
  config/areas/account/views.php
  config/areas/installation.php
  config/areas/languages/views.php
  config/areas/site/dropdowns.php
  config/areas/site/views.php
  config/areas/users/views.php
  src/Cms/Collection.php
  src/Cms/Core.php
  src/Cms/FileActions.php
  src/Cms/Files.php
  src/Cms/NestCollection.php
  src/Cms/PageActions.php
  src/Filesystem/Dir.php
  src/Filesystem/F.php
  src/Filesystem/File.php
  src/Form/Field/BlocksField.php
  src/Form/Field/LayoutField.php
  src/Form/Form.php
  src/Panel/File.php
  src/Panel/Page.php
  src/Panel/Panel.php
  src/Panel/View.php
  src/Toolkit/Dom.php
  tests/Toolkit/StrTest.php
Labels: type: refactoring :recycle:

#4050 Use translation as field name in user create dialog #4048
  config/areas/users/dialogs.php
  tests/Panel/Areas/UsersDialogsTest.php
Labels: type: bug 🐛

#4051 Fixes more possible deprecated warnings when `null` passing for PHP 8.1
  config/components.php
  src/Http/Url.php
  src/Text/SmartyPants.php
  tests/Cms/Facades/UrlTest.php
  tests/Http/UrlTest.php
  tests/Text/SmartyPantsTest.php
Labels: type: bug 🐛

#4059 Fix disabling links in picker dialogs #3983
  panel/src/components/Dialogs/FilesDialog.vue
  panel/src/components/Dialogs/PagesDialog.vue
  panel/src/components/Dialogs/UsersDialog.vue
  panel/src/components/Layout/Items.vue
  panel/src/mixins/picker/dialog.js
Labels: type: bug 🐛

#4063 Fix disabling links in picker fields #4062
  panel/src/components/Forms/Field/FilesField.vue
  panel/src/components/Forms/Field/PagesField.vue
  panel/src/components/Forms/Field/UsersField.vue
  panel/src/components/Layout/Item.vue
  panel/src/mixins/forms/picker.js
Labels: type: regression ⚡️

#4057 Tweaks for `$helpers` and their unit tests
  panel/src/fiber/index.js
  panel/src/helpers/clone.js
  panel/src/helpers/clone.test.js
  panel/src/helpers/color.js
  panel/src/helpers/color.test.js
  panel/src/helpers/debounce.js
  panel/src/helpers/debounce.test.js
  panel/src/helpers/index.js
  panel/src/helpers/isComponent.js
  panel/src/helpers/isUploadEvent.js
  panel/src/helpers/keyboard.js
  panel/src/helpers/object.clone.test.js
  panel/src/helpers/object.js
  panel/src/helpers/object.merge.test.js
  panel/src/helpers/pad.js
  panel/src/helpers/ratio.test.js
  panel/src/helpers/slug.js
  panel/src/helpers/sort.js
  panel/src/helpers/string.js
  panel/src/helpers/string.pad.test.js
  panel/src/helpers/string.random.test.js
  panel/src/helpers/string.slug.test.js
  panel/src/helpers/string.stripHTML.test.js
  panel/src/helpers/string.ucwords.test.js
  panel/src/helpers/string.uuid.test.js
  panel/src/helpers/uuid.js
  panel/src/store/modules/content.js
Labels: type: refactoring :recycle:

#4055 Refactor `k-calendar`
  panel/src/components/Forms/Calendar.vue
  panel/src/components/Forms/Field/DateField.vue
  panel/src/libraries/dayjs-iso.js
  panel/src/libraries/dayjs-iso.test.js
  panel/src/libraries/dayjs-merge.test.js
  panel/src/libraries/dayjs-round.test.js
  panel/src/libraries/dayjs-validate.test.js
  panel/src/libraries/dayjs.js
Labels: type: enhancement ✨, type: feature ⭐️, type: refactoring :recycle:

#4065 Fix fiber dispatch payload
  panel/src/components/Dialogs/FiberDialog.vue
Labels: type: regression 🚨

#4066 Update composer api version to 2.2 and tool dependencies
  .github/workflows/ci.yml
  composer.json
  composer.lock
  vendor/composer/ClassLoader.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_real.php
  vendor/composer/autoload_static.php
Labels: type: refactoring :recycle:
