Repository getkirby/kirby, pull requests merged in 2021-04, with the labels that each got.

#3230 Fix DocBlock return type after psalm fix
  src/Cms/ModelWithContent.php
  src/Cms/PageActions.php
  src/Cms/UserActions.php
Labels: type: enhancement ✨

#3223 Fix and extend doc blocks and parameter hinting
  src/Cms/Page.php
  src/Cms/Site.php
  src/Toolkit/Dir.php
Labels: type: enhancement ✨

#3232 More specific type hints
  src/Cms/Page.php
  src/Cms/Site.php
Labels: type: refactoring :recycle:

#3252 esc helper: Remove unused $strict param
  config/helpers.php
Labels: difficulty: easy 🤩, type: bug 🐛

#3254 Update docblocks for esc() helpers/methods
  config/helpers.php
  config/methods.php
Labels: difficulty: easy 🤩, type: refactoring :recycle:

#3256 Fixes link title in writer field #3255
  panel/src/components/Writer/Marks/Link.js
Labels: difficulty: easy 🤩, type: bug 🐛

#3144 Added missing nodes prop for writer field #3125
  config/fields/writer.php
Labels: type: bug 🐛

#3206 Topbar: Configurable menu entry for views
  panel/src/components/Navigation/Topbar.vue
Labels: type: enhancement ✨

#3265 Fixes video block caption marks #3264
  panel/src/components/Blocks/Types/Video.vue
Labels: difficulty: easy 🤩, type: bug 🐛

#3200 Support HTML tags on list items text attribute #3188
  panel/src/components/Layout/ListItem.vue
Labels: difficulty: easy 🤩, type: enhancement ✨

#3228 `overflow: hidden` last column on disabled structure field
  panel/src/components/Forms/Field/StructureField.vue
  panel/src/components/Forms/Previews/UrlFieldPreview.vue
Labels: difficulty: easy 🤩, type: bug 🐛

#3215 Checks slug length on page duplicate
  src/Cms/PageRules.php
  tests/Cms/Pages/PageRulesTest.php
Labels: difficulty: easy 🤩, type: bug 🐛

#3210 Fixes converting paragraph editor to blocks
  src/Cms/BlockConverter.php
  tests/Cms/Blocks/EditorImportTest.php
Labels: difficulty: easy 🤩, type: enhancement ✨

#3209 Fixes validations for no option for `invalid()` helper
  config/helpers.php
  tests/Cms/Helpers/HelpersTest.php
Labels: type: bug 🐛

#3269 Recursively ignore files in Dir::copy
  src/Toolkit/Dir.php
  tests/Toolkit/DirTest.php
Labels: difficulty: easy 🤩, type: bug 🐛

#3182 Casts to string writer&list field value with always trimming
  config/fields/list.php
  config/fields/writer.php
Labels: type: bug 🐛

#3237 Whoops: Allow Exceptions to send custom HTTP code
  src/Cms/AppErrors.php
Labels: difficulty: easy 🤩, type: bug 🐛

#3246 Allow setting the page cache expiry from controllers
  src/Cache/Value.php
  src/Cms/Page.php
  src/Cms/Responder.php
  tests/Cache/ValueTest.php
  tests/Cms/Pages/PageCacheTest.php
  tests/Cms/ResponderTest.php
Labels: type: feature ⭐️

#3273 Send missing `$model` param for options api #3260
  src/Form/Options.php
Labels: difficulty: easy 🤩, type: bug 🐛

#3272 Bring forward delete button of blocks field
  panel/src/components/Blocks/Block.vue
  panel/src/components/Blocks/BlockOptions.vue
Labels: difficulty: easy 🤩, type: enhancement ✨, type: feature ⭐️

#3172 Removes `<p>` and `</p>` tags from value
  panel/src/components/Blocks/Blocks.spec.js
  panel/src/components/Forms/Input/ListInput.vue
  tests/Form/Fields/ListFieldTest.php
Labels: type: bug 🐛, type: regression ⚡️

#3276 Fixes list field unit test #3182
  tests/Form/Fields/ListFieldTest.php
Labels: type: bug 🐛
