Repository getkirby/kirby, pull requests merged in 2021-11, with the labels that each got.

#3876 Drop PHP 7.3 support
  .github/workflows/ci.yml
  bootstrap.php
  composer.json
  composer.lock
  src/Cms/System.php
  vendor/composer/ClassLoader.php
  vendor/composer/InstalledVersions.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_static.php
  vendor/composer/installed.php
  views/php.php
Labels: type: enhancement ✨

#3887 Dom: Proper handling for Unicode in HTML and XML documents; more consistent export
  src/Sane/DomHandler.php
  src/Sane/Html.php
  src/Sane/Sane.php
  src/Toolkit/Dom.php
  tests/Parsley/InlineTest.php
  tests/Parsley/ParsleyTest.php
  tests/Sane/DomHandlerTest.php
  tests/Sane/SaneTest.php
  tests/Sane/SvgTest.php
  tests/Sane/XmlTest.php
  tests/Sane/fixtures/html/allowed/sandbox-blocks.html
  tests/Sane/fixtures/sane/doctype-valid.svg
  tests/Sane/fixtures/sane/external-source-1.sanitized.svg
  tests/Sane/fixtures/sane/external-source-1.svg
  tests/Sane/fixtures/sane/script-1.xml
  tests/Sane/fixtures/sane/script-2.sanitized.xml
  tests/Sane/fixtures/sane/script-2.xml
  tests/Sane/fixtures/svg/allowed/doctype-valid.svg
  tests/Sane/fixtures/svg/allowed/internal-source.svg
  tests/Sane/fixtures/svg/allowed/kirby-logo.svg
  tests/Sane/fixtures/svg/allowed/use-allowed.svg
  tests/Sane/fixtures/svg/cleaned/sketch.svg
  tests/Sane/fixtures/svg/disallowed/external-source-1.svg
  tests/Sane/fixtures/svg/disallowed/external-source-2.svg
  tests/Sane/fixtures/svg/disallowed/external-xmlns-1.svg
  tests/Sane/fixtures/svg/disallowed/external-xmlns-2.svg
  tests/Sane/fixtures/svg/disallowed/use-attack-1.svg
  tests/Sane/fixtures/svg/disallowed/use-attack-2.svg
  tests/Sane/fixtures/svg/disallowed/use-attack-3.svg
  tests/Sane/fixtures/svg/sanitized/doctype-entity-attack.svg
  tests/Sane/fixtures/svg/sanitized/doctype-external-1.svg
  tests/Sane/fixtures/svg/sanitized/doctype-external-2.svg
  tests/Sane/fixtures/svg/sanitized/doctype-wrong.svg
  tests/Sane/fixtures/svg/sanitized/external-source-1.svg
  tests/Sane/fixtures/svg/sanitized/external-source-2.svg
  tests/Sane/fixtures/svg/sanitized/external-xmlns-1.svg
  tests/Sane/fixtures/svg/sanitized/external-xmlns-2.svg
  tests/Sane/fixtures/svg/sanitized/use-attack-1.svg
  tests/Sane/fixtures/svg/sanitized/use-attack-2.svg
  tests/Sane/fixtures/svg/sanitized/use-attack-3.svg
  tests/Sane/fixtures/svgz/sanitized/doctype-entity-attack.svg
  tests/Sane/fixtures/xml/allowed/allowed-external-source.xml
  tests/Sane/fixtures/xml/allowed/doctype-valid.xml
  tests/Sane/fixtures/xml/allowed/internal-source.xml
  tests/Sane/fixtures/xml/disallowed/doctype-external-1.xml
  tests/Sane/fixtures/xml/disallowed/doctype-external-2.xml
  tests/Sane/fixtures/xml/disallowed/external-source-1.xml
  tests/Sane/fixtures/xml/disallowed/external-source-2.xml
  tests/Sane/fixtures/xml/sanitized/doctype-entity-attack.xml
  tests/Sane/fixtures/xml/sanitized/doctype-external-1.xml
  tests/Sane/fixtures/xml/sanitized/doctype-external-2.xml
  tests/Sane/fixtures/xml/sanitized/external-source-1.xml
  tests/Sane/fixtures/xml/sanitized/external-source-2.xml
  tests/Toolkit/DomTest.php
Labels: type: bug 🐛

#3869 Fix blocks stuck as selected in blocks within layout field
  panel/src/components/Forms/Blocks/Blocks.vue
Labels: type: bug 🐛

#3899 Compare JSON docs to avoid unsaved changes loop
  panel/src/components/Forms/Writer/Editor.js
  panel/src/components/Forms/Writer/Writer.vue
Labels: type: bug 🐛, type: regression ⚡️

#3898 Fix parsing of multiple nested spans
  src/Parsley/Parsley.php
  tests/Parsley/ParsleyTest.php
  tests/Parsley/fixtures/span-with-marks.html
  tests/Parsley/fixtures/span-with-marks.php
Labels: type: bug 🐛

#3903 Load language rules in fiber
  src/Panel/View.php
  tests/Panel/ViewTest.php
Labels: type: regression ⚡️

#3904 Fix overwritable site title #3901
  config/areas/site.php
  tests/Panel/Areas/SiteTest.php
Labels: type: regression ⚡️

#3906 Fix breaking change for the multilang dropdown
  src/Panel/Panel.php
  src/Panel/View.php
  tests/Panel/Areas/AreaTestCase.php
  tests/Panel/PanelTest.php
Labels: type: regression ⚡️

#3889 Dom: Allow relative URLs
  src/Toolkit/Dom.php
  tests/Toolkit/DomTest.php
Labels: type: regression ⚡️

#3912 Pin psr/log to v1.1.4
  composer.json
  composer.lock
  vendor/composer/ClassLoader.php
  vendor/composer/InstalledVersions.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_psr4.php
  vendor/composer/autoload_static.php
  vendor/composer/installed.json
  vendor/composer/installed.php
  vendor/psr/log/Psr/Log/AbstractLogger.php
  vendor/psr/log/Psr/Log/InvalidArgumentException.php
  vendor/psr/log/Psr/Log/LogLevel.php
  vendor/psr/log/Psr/Log/LoggerAwareInterface.php
  vendor/psr/log/Psr/Log/LoggerAwareTrait.php
  vendor/psr/log/Psr/Log/LoggerInterface.php
  vendor/psr/log/Psr/Log/LoggerTrait.php
  vendor/psr/log/Psr/Log/NullLogger.php
  vendor/psr/log/composer.json
  vendor/psr/log/src/AbstractLogger.php
Labels: type: regression ⚡️

#3914 Add comment about psr/log to composer.json
  composer.json
Labels: type: refactoring :recycle:

#3917 Minor `FileRules` refactoring to ensure that `.phtml` uploads are never allowed
  src/Cms/FileRules.php
  tests/Cms/Files/FileRulesTest.php
Labels: type: refactoring :recycle:

#3922 Add strikethrough and small html tag for `Sane`
  src/Sane/Html.php
  tests/Sane/fixtures/html/allowed/sandbox-blocks.html
Labels: type: regression ⚡️

#3921 Fix nested blocks drawer breadcrumb
  panel/src/components/Drawers/Drawer.vue
  panel/src/store/modules/drawers.js
Labels: type: bug 🐛

#3929 Dom: Complete unit and integration tests; bug fixes
  src/Sane/DomHandler.php
  src/Sane/Html.php
  src/Toolkit/Dom.php
  tests/Cms/Files/FileRulesTest.php
  tests/Sane/DomHandlerTest.php
  tests/Sane/HandlerTest.php
  tests/Sane/HtmlTest.php
  tests/Sane/SaneTest.php
  tests/Sane/SvgTest.php
  tests/Sane/XmlTest.php
  tests/Toolkit/DomTest.php
Labels: type: refactoring :recycle:, type: regression ⚡️

#3939 Don't throw pages() behavior deprecation warning if single item is an array
  config/helpers.php
Labels: type: refactoring :recycle:

#3937 Refactor plugin loading JS
  panel/public/js/plugins.js
  panel/src/config/plugins.js
Labels: type: refactoring :recycle:

#3908 Use optional chaining `(?.)` in frontend
  panel/src/api/request.js
  panel/src/components/Dialogs/Dialog.vue
  panel/src/components/Dialogs/LanguageDialog.vue
  panel/src/components/Drawers/FormDrawer.vue
  panel/src/components/Forms/Blocks/Block.vue
  panel/src/components/Forms/Blocks/BlockSelector.vue
  panel/src/components/Forms/Blocks/Blocks.vue
  panel/src/components/Forms/Blocks/Types/Image.vue
  panel/src/components/Forms/Field/EmailField.vue
  panel/src/components/Forms/Field/SlugField.vue
  panel/src/components/Forms/Field/StructureField.vue
  panel/src/components/Forms/Fieldset.vue
  panel/src/components/Forms/Form.vue
  panel/src/components/Forms/Input.vue
  panel/src/components/Forms/Input/MultiselectInput.vue
  panel/src/components/Forms/Input/TagsInput.vue
  panel/src/components/Forms/Input/TextareaInput.vue
  panel/src/components/Forms/Previews/EmailFieldPreview.vue
  panel/src/components/Forms/Toolbar.vue
  panel/src/components/Forms/Toolbar/EmailDialog.vue
  panel/src/components/Forms/Upload.vue
  panel/src/components/Forms/Writer/Marks/Email.js
  panel/src/components/Forms/Writer/Marks/Link.js
  panel/src/components/Forms/Writer/Toolbar.vue
  panel/src/components/Forms/Writer/Utils/markPasteRule.js
  panel/src/components/Layout/Overlay.vue
  panel/src/components/Navigation/DropdownContent.vue
  panel/src/components/Views/ModelView.vue
  panel/src/config/plugins.js
  panel/src/helpers/upload.js
Labels: type: refactoring :recycle:

#3884 PHP 7.4 feature: `strip_tags` with array of tags
  config/methods.php
  src/Toolkit/Html.php
Labels: type: refactoring :recycle:

#3942 Fix Panel image for `Asset` objects
  config/components.php
  src/Cms/FileModifications.php
  src/Panel/Model.php
  tests/Cms/Files/FileModificationsTest.php
  tests/Panel/ModelTest.php
Labels: type: regression ⚡️

#3886 PHP 7.4 feature: arrow functions
  config/components.php
  config/helpers.php
  src/Cms/Auth.php
  src/Cms/Blueprint.php
  src/Cms/Fieldsets.php
  src/Cms/FileBlueprint.php
  src/Cms/LanguageRouter.php
  src/Cms/Languages.php
  src/Database/Sql.php
  src/Database/Sql/Sqlite.php
  src/Filesystem/Filename.php
  src/Form/Field.php
  src/Form/Field/LayoutField.php
  src/Form/FieldClass.php
  src/Http/Router.php
  src/Panel/Document.php
  src/Toolkit/A.php
  src/Toolkit/Xml.php
  tests/Data/DataTest.php
  tests/Panel/DocumentTest.php
Labels: type: refactoring :recycle:

#3952 Implement system.exception hook
  src/Cms/AppErrors.php
  tests/Cms/App/AppErrorsTest.php
Labels: type: feature ⭐️

#3960 System view: Rename SSL to HTTPS
  config/areas/system/views.php
  panel/src/components/Views/SystemView.vue
Labels: type: enhancement ✨

#3968 Fix converting blocks from non-existing type #3962
  panel/src/components/Forms/Blocks/Blocks.vue
Labels: type: bug 🐛

#3966 `k-item`: fix z-index for dropdown #3944
  panel/src/components/Layout/Item.vue
Labels: type: bug 🐛

#3964 Support throwing exceptions from Panel route hook
  src/Panel/Panel.php
Labels: type: enhancement ✨

#3958 Minimal fix for `route` hooks only on core routing
  src/Cms/App.php
Labels: type: bug 🐛

#3931 Fix blocks options bar on nested blocks preview
  panel/src/components/Forms/Blocks/Block.vue
Labels: type: bug 🐛

#3969 `Str` methods: handle empty `$needle`
  src/Toolkit/Str.php
  tests/Toolkit/StrTest.php
Labels: type: bug 🐛

#3907 Use srcset for gallery block preview
  panel/src/components/Forms/Blocks/Types/Gallery.vue
Labels: type: enhancement ✨

#3885 PHP 7.4 feature: null coalescing assignment operator
  src/Cms/Blueprint.php
  src/Cms/ContentLock.php
  src/Cms/ContentTranslation.php
  src/Cms/Core.php
  src/Cms/Fieldsets.php
  src/Cms/File.php
  src/Cms/Languages.php
  src/Cms/Model.php
  src/Cms/Page.php
  src/Cms/Pages.php
  src/Cms/Pagination.php
  src/Cms/Role.php
  src/Cms/Section.php
  src/Cms/Site.php
  src/Cms/User.php
  src/Database/Db.php
  src/Database/Sql.php
  src/Filesystem/Dir.php
  src/Filesystem/Mime.php
  src/Form/Field.php
  src/Form/Field/BlocksField.php
  src/Form/Fields.php
  src/Form/Form.php
  src/Form/Options.php
  src/Http/Request.php
  src/Http/Response.php
  src/Http/Router.php
  src/Http/Uri.php
  src/Http/Url.php
  src/Image/Image.php
  src/Panel/File.php
  src/Panel/Json.php
  src/Panel/Model.php
  src/Panel/Page.php
  src/Panel/Panel.php
  src/Panel/User.php
  src/Toolkit/Dom.php
  src/Toolkit/Escape.php
  src/Toolkit/Html.php
  src/Toolkit/I18n.php
  src/Toolkit/Properties.php
  src/Toolkit/Str.php
Labels: type: refactoring :recycle:
