Repository getkirby/kirby, pull requests merged in 2021-01, with the labels that each got.

#3035 Static code analysis with Psalm
  .gitattributes
  .github/workflows/ci.yml
  composer.json
  config/blocks/code/code.php
  config/blocks/gallery/gallery.php
  config/blocks/heading/heading.php
  config/blocks/image/image.php
  config/blocks/list/list.php
  config/blocks/markdown/markdown.php
  config/blocks/quote/quote.php
  config/blocks/text/text.php
  config/blocks/video/video.php
  config/helpers.php
  config/templates/emails/auth/login.php
  config/templates/emails/auth/password-reset.php
  phpstan.neon.dist
  psalm.xml.dist
  src/Cms/Auth.php
  src/Cms/Blocks.php
  src/Cms/Collection.php
  src/Cms/Fieldsets.php
  src/Cms/Files.php
  src/Cms/Item.php
  src/Cms/LanguageRoutes.php
  src/Cms/Layouts.php
  src/Cms/PageActions.php
  src/Cms/Pages.php
  src/Cms/Panel.php
  src/Cms/Section.php
  src/Cms/UserActions.php
  src/Cms/Users.php
  src/Data/PHP.php
  src/Form/Field.php
  src/Http/Params.php
  src/Http/Uri.php
  src/Http/Url.php
  src/Session/Session.php
  src/Toolkit/Collection.php
  src/Toolkit/Html.php
  src/Toolkit/Query.php
  tests/Cms/Blueprints/BlueprintTest.php
  views/panel.php
Labels: type: refactoring :recycle:

#3044 Switch to Codecov
  .codecov.yml
  .gitattributes
  .github/README.md
  .github/workflows/ci.yml
Labels: type: refactoring :recycle:

#3046 Improves `Cookie::forever()` method for 32-bit servers #2968
  src/Http/Cookie.php
  tests/Http/CookieTest.php
Labels: difficulty: easy 🤩, type: bug 🐛

#3029 Date field: fix missing `format` option #3026
  config/fields/date.php
  config/fields/mixins/datetime.php
  config/fields/time.php
Labels: type: regression ⚡️

#3032 Fixes autofocus issue blocks and structure fields
  panel/src/components/Drawers/FormDrawer.vue
  panel/src/components/Forms/Field/StructureField.vue
Labels: type: bug 🐛

#3051 Fix Apcu detection
  tests/Cache/ApcuCacheTest.php
Labels: type: enhancement ✨

#3052 Fix `F::rename` overwriting
  src/Toolkit/F.php
  tests/Toolkit/FTest.php
Labels: type: bug 🐛

#3054 PHPMD: activate UnusedPrivateField rule
  phpmd.xml.dist
Labels: type: refactoring :recycle:

#3053 Remove unused local variables
  src/Cms/AppCaches.php
  src/Cms/PageRules.php
  src/Parsley/Inline.php
  src/Session/FileSessionStore.php
Labels: type: refactoring :recycle:

#3057 Remove unused imports
  src/Cms/AppCaches.php
  src/Cms/AppTranslations.php
  src/Cms/S.php
  src/Database/Database.php
Labels: type: refactoring :recycle:

#3058 Fix ->call() only with Closure
  src/Form/Field.php
  src/Toolkit/Component.php
Labels: type: bug 🐛

#3066 Support 12-columns layout field for panel ui
  panel/src/components/Layout/Column.vue
Labels: type: bug 🐛

#3060 Add undefined class properties
  src/Cms/Fieldset.php
  src/Cms/Item.php
  src/Form/Field/BlocksField.php
  src/Parsley/Parsley.php
Labels: type: refactoring :recycle:

#3020 Adds blocks navigation
  panel/src/components/Blocks/Block.vue
  panel/src/components/Blocks/Blocks.vue
Labels: type: enhancement ✨

#3070 Deactivate the replace action if files cannot be replaced #3031
  src/Cms/File.php
  tests/Cms/Files/FileTest.php
Labels: type: bug 🐛

#3072 Automatic fallback for email security = true #2896
  src/Email/PHPMailer.php
  tests/Email/PHPMailerTest.php
Labels: type: bug 🐛, type: regression ⚡️

#3073 Update PR template for new CI
  .github/PULL_REQUEST_TEMPLATE.md
  composer.json
Labels: type: refactoring :recycle:

#3076 Fixes global search shortcut #3015
  panel/src/App.vue
  panel/src/components/Navigation/Search.vue
Labels: type: bug 🐛, type: regression ⚡️

#3075 Use local time instead UTC getting today #3005
  panel/src/components/Forms/Calendar.vue
Labels: type: bug 🐛

#3091 CI: Unpin Psalm version again
  .github/workflows/ci.yml
Labels: type: refactoring :recycle:

#3092 Reverts using local date #3075
  panel/src/components/Forms/Calendar.vue
Labels: type: bug 🐛, type: regression ⚡️

#3085 Fixes autofocus fields in structure fields #3083
  panel/src/components/Forms/Field/StructureField.vue
Labels: type: bug 🐛

#3103 Adds image url label translation for image block #3087
  config/blocks/image/image.yml
  i18n/translations/en.json
Labels: type: translation 🌏

#3105 Fixes tabs on account page #3098
  panel/src/config/routes.js
Labels: type: bug 🐛, type: regression ⚡️

#3102 Fixes overwriting block tabs #3101
  src/Cms/Fieldset.php
  tests/Cms/Fieldsets/FieldsetTest.php
  tests/Cms/Fieldsets/FieldsetsTest.php
Labels: type: bug 🐛

#3100 Fixes overwriting blueprint columns #3095
  src/Cms/Blueprint.php
  tests/Cms/Blueprints/BlueprintExtendAndUnsetTest.php
Labels: type: bug 🐛

#2936 Add similarity search for Str class
  src/Toolkit/Str.php
  tests/Toolkit/StrTest.php
Labels: type: feature ⭐️

#3061 Fix some return types
  src/Cms/Page.php
  src/Cms/PageActions.php
  src/Image/Location.php
  src/Toolkit/A.php
  src/Toolkit/F.php
  src/Toolkit/Iterator.php
  src/Toolkit/Pagination.php
  src/Toolkit/Str.php
Labels: type: bug 🐛, type: refactoring :recycle:

#3113 CI: Use PHP 7.4 for analysis for now
  .github/workflows/ci.yml
Labels: type: refactoring :recycle:

#3110 Separates caches for draft mode #3082
  src/Cms/Pages.php
  tests/Cms/Pages/PagesTest.php
Labels: difficulty: easy 🤩, type: bug 🐛

#3028 Panel page icons centered correctly for all browsers #2943
  panel/src/components/Misc/Icon.vue
Labels: type: bug 🐛, type: regression ⚡️

#3116 Translatable sections info and text props #3109
  config/sections/files.php
  config/sections/pages.php
  tests/Cms/Sections/FilesSectionTest.php
  tests/Cms/Sections/PagesSectionTest.php
Labels: difficulty: easy 🤩, type: enhancement ✨

#3111 Supports list items in info fields #2946
  panel/src/components/Misc/Text.vue
Labels: difficulty: easy 🤩, type: enhancement ✨

#3119 Enables `fail_ci_if_error` argument for codecov
  .github/workflows/ci.yml
Labels: type: refactoring :recycle:

#3120 Changes files field button to `Select`
  panel/src/components/Forms/Field/FilesField.vue
Labels: difficulty: easy 🤩, type: enhancement ✨

#3128 Emit empty string when editor is empty #3115
  panel/src/components/Writer/Writer.vue
Labels: difficulty: easy 🤩, type: bug 🐛
