Repository getkirby/kirby, pull requests merged in 2021-09, with the labels that each got.

#3631 Fixes writer field email title
  panel/src/components/Writer/Marks/Email.js
Labels: type: bug 🐛, difficulty: easy 🤩

#3666 Use model id for model views
  panel/src/components/Views/ModelView.vue
Labels: type: bug 🐛, type: regression ⚡️

#3669 Enhanced frontend `template()` parser
  panel/src/helpers/string.js
  panel/src/helpers/string.template.spec.js
Labels: type: enhancement ✨

#3667 New sort icon with better alignment
  panel/dist/img/icons.svg
  panel/public/img/icons.svg
  panel/src/components/Layout/Item.vue
  panel/src/components/Misc/SortHandle.vue
Labels: type: regression ⚡️

#3670 Remove outline and set panel to full height
  panel/src/styles/reset.css
Labels: type: bug 🐛, type: regression ⚡️

#3668 Filter unreadable pages in search
  config/areas/site/searches.php
Labels: type: bug 🐛, type: regression ⚡️

#3675 Fix for creating extra content files when changing a template
  src/Cms/PageActions.php
  tests/Cms/Pages/PageActionsTest.php
Labels: type: bug 🐛

#3679 Fix typo
  panel/src/components/Views/UsersView.vue
Labels: type: bug 🐛, difficulty: easy 🤩

#3671 Fix broken image: false and image: icon options
  panel/src/components/Layout/Item.vue
  panel/src/helpers/color.js
  src/Panel/Model.php
Labels: type: bug 🐛, type: regression ⚡️

#3681 Fix autofocus blocks field
  panel/src/components/Blocks/Blocks.vue
  panel/src/components/Forms/Field/BlocksField.vue
Labels: type: bug 🐛

#3680 Allow custom attributes on video helper
  config/tags.php
  src/Toolkit/Html.php
  tests/Cms/Helpers/HelpersTest.php
  tests/Text/KirbyTagsTest.php
  tests/Text/fixtures/kirbytext/video-width-and-height/expected.html
  tests/Text/fixtures/kirbytext/video-youtube/expected.html
  tests/Text/fixtures/kirbytext/vimeo/expected.html
  tests/Text/fixtures/kirbytext/youtube/expected.html
  tests/Toolkit/HtmlTest.php
Labels: type: enhancement ✨

#3678 Remove `module` type and add `defer` for plugins asset
  src/Panel/Document.php
  tests/Panel/DocumentTest.php
  views/panel.php
Labels: type: bug 🐛, type: regression ⚡️

#3686 Fixed opening blocks that have no fields or no editable
  panel/src/components/Forms/Blocks/Block.vue
Labels: type: bug 🐛

#3688 Add `method` prop for upload options
  panel/src/components/Forms/Upload.vue
Labels: type: bug 🐛, type: regression ⚡️

#3689 Fix for display error in narrow columns
  panel/src/components/Layout/Items.vue
Labels: type: regression ⚡️

#3690 Global options for all kirbytags
  config/tags.php
  src/Text/KirbyTag.php
  tests/Text/KirbyTagsTest.php
Labels: type: feature ⭐️

#3694 Refactor async JS code
  panel/src/api/auth.js
  panel/src/api/languages.js
  panel/src/components/Forms/Field/StructureField.vue
  panel/src/components/Forms/FormIndicator.vue
  panel/src/components/Navigation/Pagination.vue
  panel/src/components/Sections/InfoSection.vue
  panel/src/fiber/index.js
Labels: type: refactoring :recycle:

#3701 Fix block loading order
  panel/src/config/components.js
Labels: type: regression ⚡️

#3702 `toggle` field: fix for missing `text` prop
  config/fields/toggle.php
  src/Cms/ModelWithContent.php
  tests/Cms/Models/ModelWithContentTest.php
Labels: type: bug 🐛, type: regression ⚡️

#3707 Additional Fiber unit tests
  config/areas/settings/dialogs.php
  tests/Panel/JsonTest.php
Labels: type: refactoring :recycle:

#3705 Simplify `isLoading` Vuex action
  panel/src/store/store.js
Labels: type: refactoring :recycle:

#3698 `page.create` dialog: fix single template value
  config/areas/site/dialogs.php
  tests/Panel/Areas/PageDialogsTest.php
Labels: type: bug 🐛

#3704 Fix overlay/dialogs/drawers on back navigation
  panel/src/fiber/app.js
  panel/src/store/modules/drawers.js
  panel/src/store/store.js
Labels: type: bug 🐛, type: regression ⚡️

#3711 Bring back aliases for missing CSS vars
  panel/src/styles/variables.css
Labels: type: regression ⚡️

#3710 Fix unsaved changes models
  panel/src/components/Forms/FormIndicator.vue
Labels: type: bug 🐛, type: regression ⚡️

#3449 Reveal the heading node for writer field
  i18n/translations/en.json
  panel/public/img/icons.svg
  panel/src/components/Forms/Writer/Editor.js
  panel/src/components/Forms/Writer/Extensions.js
  panel/src/components/Forms/Writer/Extensions/Toolbar.js
  panel/src/components/Forms/Writer/Nodes/BulletList.js
  panel/src/components/Forms/Writer/Nodes/Heading.js
  panel/src/components/Forms/Writer/Nodes/OrderedList.js
  panel/src/components/Forms/Writer/Nodes/Paragraph.js
  panel/src/components/Forms/Writer/Toolbar.vue
  panel/src/components/Forms/Writer/Utils/index.js
  panel/src/components/Forms/Writer/Utils/toggleBlockType.js
  panel/src/components/Forms/Writer/Utils/toggleList.js
  panel/src/components/Forms/Writer/Writer.vue
Labels: type: feature ⭐️

#3718 Hide paragraph while loading certain nodes
  panel/src/components/Forms/Writer/Toolbar.vue
  panel/src/components/Forms/Writer/Writer.vue
Labels: type: bug 🐛

#3717 Validate empty password
  config/areas/users/dialogs.php
Labels: type: bug 🐛, type: regression ⚡️

#3727 Fixes `minLength` typo on checkboxes validations
  panel/src/components/Forms/Input/CheckboxesInput.vue
Labels: type: bug 🐛, type: regression ⚡️

#3730 Fix empty data value on frontend template parser
  panel/src/helpers/string.js
  panel/src/helpers/string.template.spec.js
Labels: type: bug 🐛, type: regression ⚡️
