Repository getkirby/kirby, pull requests merged in 2021-08, with the labels that each got.

#3597 CSS: don't preserve logical properties for now
  panel/vite.config.js
Labels: type: refactoring :recycle:

#3527 Automatic `api.csrf` via `panel.dev` option
  config/helpers.php
  src/Cms/Auth.php
  src/Panel/View.php
  tests/Cms/Auth/AuthCsrfTest.php
Labels: type: refactoring :recycle:

#3599 Improved fields and info sections
  config/sections/info.php
  panel/dist/js/index.js
  panel/src/components/Navigation/Search.vue
  panel/src/components/Sections/FieldsSection.vue
  panel/src/components/Sections/InfoSection.vue
  src/Form/Field.php
  src/Panel/Model.php
  tests/Cms/Sections/InfoSectionTest.php
Labels: type: enhancement ✨

#3580 Refactor `k-item`
  panel/src/components/Layout/Item.vue
  panel/src/components/Navigation/Tag.vue
Labels: type: refactoring :recycle:

#3578 Improvements: UserView and ButtonGroups
  panel/src/components/Blocks/BlockFigure.vue
  panel/src/components/Blocks/BlockSelector.vue
  panel/src/components/Dialogs/Dialog.vue
  panel/src/components/Drawers/Drawer.vue
  panel/src/components/Forms/Calendar.vue
  panel/src/components/Forms/Field/PagesField.vue
  panel/src/components/Forms/Field/SlugField.vue
  panel/src/components/Forms/Field/StructureField.vue
  panel/src/components/Forms/Field/UsersField.vue
  panel/src/components/Forms/FormButtons.vue
  panel/src/components/Forms/Input/MultiselectInput.vue
  panel/src/components/Forms/Upload.vue
  panel/src/components/Misc/Fatal.vue
  panel/src/components/Misc/StatusIcon.vue
  panel/src/components/Navigation/Button.vue
  panel/src/components/Navigation/ButtonGroup.vue
  panel/src/components/Navigation/ButtonNative.vue
  panel/src/components/Navigation/Languages.vue
  panel/src/components/Navigation/PrevNext.vue
  panel/src/components/Navigation/Search.vue
  panel/src/components/Navigation/Topbar.vue
  panel/src/components/Sections/FilesSection.vue
  panel/src/components/Sections/PagesSection.vue
  panel/src/components/Views/FileView.vue
  panel/src/components/Views/InstallationView.vue
  panel/src/components/Views/PageView.vue
  panel/src/components/Views/SettingsView.vue
  panel/src/components/Views/SiteView.vue
  panel/src/components/Views/UserView.vue
  panel/src/components/Views/UsersView.vue
Labels: type: refactoring :recycle:

#3577 `k-file-preview`: clean CSS, details from backend
  panel/src/components/Layout/FilePreview.vue
  panel/src/components/Views/FileView.spec.js
  panel/src/components/Views/FileView.vue
  src/Panel/File.php
  tests/Panel/FileTest.php
Labels: type: refactoring :recycle:

#3611 Fix CSS syntax
  panel/src/components/Misc/Image.vue
Labels: type: bug 🐛

#3604 Use `csso`
  panel/package-lock.json
  panel/package.json
  panel/vite.config.js
Labels: type: refactoring :recycle:

#3607 CSS: simplify `k-topbar`
  panel/src/components/Misc/Registration.vue
  panel/src/components/Navigation/Topbar.vue
Labels: type: refactoring :recycle:

#3606 Use `ratio` helper for structure column width
  panel/src/components/Forms/Field/StructureField.vue
  panel/src/helpers/ratio.js
  panel/src/helpers/ratio.spec.js
  panel/src/mixins/forms/structure.js
Labels: type: refactoring :recycle:

#3608 CSS `[data-]` utilities
  panel/src/components/Blocks/Types/Table.vue
  panel/src/components/Dialogs/Dialog.vue
  panel/src/components/Forms/Field/StructureField.vue
  panel/src/components/Forms/FormButtons.vue
  panel/src/components/Forms/Input/TextareaInput.vue
  panel/src/components/Layout/Box.vue
  panel/src/components/Layout/Inside.vue
  panel/src/components/Misc/Headline.vue
  panel/src/components/Misc/Icon.vue
  panel/src/components/Misc/Invalid.vue
  panel/src/components/Misc/StatusIcon.vue
  panel/src/components/Misc/Text.vue
  panel/src/components/Navigation/Button.vue
  panel/src/components/Navigation/DropdownContent.vue
  panel/src/components/Navigation/Link.vue
  panel/src/components/Navigation/Pagination.vue
  panel/src/components/Navigation/Topbar.vue
  panel/src/config/components.js
  panel/src/index.js
  panel/src/styles/reset.css
  panel/src/styles/utilities.css
  panel/src/styles/variables.css
Labels: type: refactoring :recycle:

#3600 Panel app setup: more plugins
  panel/src/components/Misc/Fatal.vue
  panel/src/config/errors.js
  panel/src/config/libraries.js
  panel/src/config/plugins.js
  panel/src/fiber/plugin.js
  panel/src/index.js
Labels: type: refactoring :recycle:

#3605 CSS: use `top` and `bottom` again
  panel/src/components/Blocks/Block.vue
  panel/src/components/Blocks/BlockFigure.vue
  panel/src/components/Blocks/BlockOptions.vue
  panel/src/components/Blocks/BlockSelector.vue
  panel/src/components/Blocks/Types/Code.vue
  panel/src/components/Blocks/Types/Gallery.vue
  panel/src/components/Blocks/Types/Line.vue
  panel/src/components/Blocks/Types/Quote.vue
  panel/src/components/Blocks/Types/Table.vue
  panel/src/components/Dialogs/Dialog.vue
  panel/src/components/Dialogs/ErrorDialog.vue
  panel/src/components/Dialogs/PagesDialog.vue
  panel/src/components/Drawers/Drawer.vue
  panel/src/components/Forms/Calendar.vue
  panel/src/components/Forms/Field.vue
  panel/src/components/Forms/Field/HeadlineField.vue
  panel/src/components/Forms/Field/InfoField.vue
  panel/src/components/Forms/Field/LineField.vue
  panel/src/components/Forms/Field/StructureField.vue
  panel/src/components/Forms/FormButtons.vue
  panel/src/components/Forms/Input.vue
  panel/src/components/Forms/Input/MultiselectInput.vue
  panel/src/components/Forms/Input/RadioInput.vue
  panel/src/components/Forms/Input/RangeInput.vue
  panel/src/components/Forms/Input/TextareaInput.vue
  panel/src/components/Forms/LoginAlert.vue
  panel/src/components/Forms/LoginCode.vue
  panel/src/components/Forms/Previews/WriterFieldPreview.vue
  panel/src/components/Forms/Toolbar.vue
  panel/src/components/Forms/Upload.vue
  panel/src/components/Layout/AspectRatio.vue
  panel/src/components/Layout/Box.vue
  panel/src/components/Layout/Column.vue
  panel/src/components/Layout/Empty.vue
  panel/src/components/Layout/Header.vue
  panel/src/components/Layout/Inside.vue
  panel/src/components/Layout/Item.vue
  panel/src/components/Layout/Items.vue
  panel/src/components/Layout/Tabs.vue
  panel/src/components/Layouter/Layout.vue
  panel/src/components/Layouter/Layouts.vue
  panel/src/components/Misc/Fatal.vue
  panel/src/components/Misc/Image.vue
  panel/src/components/Misc/Text.vue
  panel/src/components/Navigation/ButtonGroup.vue
  panel/src/components/Navigation/DropdownContent.vue
  panel/src/components/Navigation/Pagination.vue
  panel/src/components/Navigation/Search.vue
  panel/src/components/Navigation/Topbar.vue
  panel/src/components/Sections/FieldsSection.vue
  panel/src/components/Sections/InfoSection.vue
  panel/src/components/Sections/Sections.vue
  panel/src/components/Views/ErrorView.vue
  panel/src/components/Views/InstallationView.vue
  panel/src/components/Views/LoginView.vue
  panel/src/components/Views/ResetPasswordView.vue
  panel/src/components/Views/SettingsView.vue
  panel/src/components/Writer/Toolbar.vue
  panel/src/components/Writer/Writer.vue
Labels: type: refactoring :recycle:

#3612 Upgrade npm dependencies
  panel/package-lock.json
  panel/package.json
  panel/src/index.js
Labels: type: enhancement ✨

#3620 Fix images in picker field previews
  panel/src/components/Forms/Previews/FilesFieldPreview.vue
  panel/src/components/Forms/Previews/PagesFieldPreview.vue
  panel/src/components/Misc/Icon.vue
Labels: type: regression ⚡️

#3593 Set files `sort` attribute on upload
  config/api/routes/files.php
  config/sections/files.php
Labels: type: bug 🐛

#3653 Replace field method: No fallback for empty fields
  config/methods.php
  tests/Cms/Fields/FieldMethodsTest.php
Labels: type: bug 🐛

#3635 `upload.js`: use `method parameter`
  panel/src/components/Forms/Upload.vue
  panel/src/helpers/upload.js
Labels: type: bug 🐛
