Repository getkirby/kirby, pull requests merged in 2021-02, with the labels that each got.

#3019 F::niceSize(): Typography and locale improvements
  src/Toolkit/F.php
  tests/Toolkit/DirTest.php
  tests/Toolkit/FTest.php
  tests/Toolkit/FileTest.php
Labels: type: enhancement ✨, type: feature ⭐️

#3131 `isEmpty()` and `isNotEmpty()` methods for layout field
  src/Cms/Layout.php
  src/Cms/LayoutColumn.php
  tests/Cms/Layouts/LayoutColumnTest.php
  tests/Cms/Layouts/LayoutTest.php
Labels: type: feature ⭐️

#3124 Removes opacity from disabled fields #2807
  panel/src/components/Blocks/Block.vue
  panel/src/components/Blocks/Blocks.vue
  panel/src/components/Forms/Field.vue
  panel/src/components/Forms/Field/ListField.vue
  panel/src/components/Forms/Field/StructureField.vue
  panel/src/components/Forms/Field/WriterField.vue
  panel/src/components/Forms/Input.vue
  panel/src/components/Forms/Input/CheckboxInput.vue
  panel/src/components/Forms/Input/ListInput.vue
  panel/src/components/Forms/Input/RadioInput.vue
  panel/src/components/Forms/Input/RangeInput.vue
  panel/src/components/Layout/ListItem.vue
  panel/src/components/Layouter/Layout.vue
  panel/src/components/Layouter/Layouts.vue
  panel/src/components/Misc/Icon.vue
  panel/src/components/Navigation/Tag.vue
Labels: type: enhancement ✨

#3130 Disables `onCodeChanges()` method on language update #3129
  panel/src/components/Dialogs/LanguageUpdateDialog.vue
Labels: difficulty: easy 🤩, type: bug 🐛

#3127 Removes `<p>` tags from list field #3086
  panel/src/components/Forms/Input/ListInput.vue
Labels: difficulty: easy 🤩, type: bug 🐛

#3112 Injects language translations to `kirby()->translations()` #3064
  src/Cms/AppTranslations.php
  tests/Cms/App/AppTranslationsTest.php
Labels: type: enhancement ✨

#3136 Response::redirect(): Consistent arguments
  src/Cms/Response.php
  src/Http/Response.php
  tests/Cms/ResponseTest.php
  tests/Http/ResponseTest.php
Labels: type: bug 🐛, type: refactoring :recycle:

#3143 Use `basename()` method to avoid relative path in cache key
  src/Cache/FileCache.php
  tests/Cache/FileCacheTest.php
Labels: type: refactoring :recycle:

#3146 Adds translation service to new issue list
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: type: translation 🌏

#3150 Checks the language for extensions translations #3149
  src/Cms/AppTranslations.php
  tests/Cms/App/AppTranslationsTest.php
Labels: priority: high 🔥, type: bug 🐛, type: regression ⚡️

#3161 Fix regression in go() helper without args #3160
  config/helpers.php
Labels: type: bug 🐛, type: regression ⚡️

#3152 Reverts default info texts for pages/files sections
  config/sections/files.php
  config/sections/pages.php
Labels: type: regression ⚡️

#3158 Fix regression in FileCache keys that caused overlap of cache keys #3157
  src/Cache/FileCache.php
  tests/Cache/FileCacheTest.php
Labels: priority: high 🔥, type: bug 🐛, type: regression ⚡️

#3173 Reverts removing `p` tags changes #3168
  panel/src/components/Forms/Input/ListInput.vue
Labels: type: bug 🐛, type: regression ⚡️

#3181 Disable `add` menu items when blocks field max #3179
  panel/src/components/Blocks/BlockOptions.vue
  panel/src/components/Forms/Field/BlocksField.vue
Labels: difficulty: easy 🤩, type: enhancement ✨
