Repository getkirby/kirby, pull requests merged in 2021-10, with the labels that each got.

#3741 Reintroduce item slots from PR #3217
  panel/src/components/Layout/Item.vue
Labels: type: regression ⚡️

#3738 Fixes border-radius and box-shadow on image in lists
  panel/src/components/Layout/Item.vue
Labels: type: bug 🐛, difficulty: easy 🤩, type: regression ⚡️

#3748 Multiselect with CMD/CTRL keys for blocks field
  panel/src/components/Forms/Blocks/Blocks.vue
Labels: type: enhancement ✨

#3740 Extending blocks model
  src/Cms/AppPlugins.php
  src/Cms/Block.php
  tests/Cms/Blocks/BlockModelsTest.php
Labels: type: feature ⭐️, difficulty: easy 🤩

#3747 Default model for blocks
  src/Cms/Block.php
  tests/Cms/Blocks/BlockModelsTest.php
Labels: type: feature ⭐️, difficulty: easy 🤩

#3873 Fix blocks field `empty` prop
  panel/src/components/Forms/Blocks/Blocks.vue
Labels: type: bug 🐛, type: regression ⚡️

#3878 Detect server port also via HTTP_HOST
  src/Http/Server.php
  tests/Http/ServerTest.php
Labels: type: bug 🐛, type: regression ⚡️

#3879 Bring back autoprefixer for CSS
  panel/package-lock.json
  panel/package.json
  panel/vite.config.js
Labels: type: regression ⚡️

#3880 CI: Update tool versions
  .github/workflows/ci.yml
  src/Cms/Collection.php
  src/Cms/Model.php
  src/Cms/ModelWithContent.php
Labels: type: refactoring :recycle:

#3883 Fix inline docs for `cardlets` layout option
  config/fields/files.php
  config/fields/mixins/layout.php
  config/fields/pages.php
  config/fields/users.php
  config/sections/files.php
  config/sections/mixins/layout.php
  src/Cms/Core.php
  tests/Cms/CoreTest.php
Labels: type: refactoring :recycle:
