Repository getkirby/kirby, pull requests merged in 2021-06, with the labels that each got.

#3393 More `Kirby\Toolkit\Str` unit tests (+ small bugfixes)
  src/Toolkit/Str.php
  tests/Toolkit/StrTest.php
Labels: type: enhancement ✨

#3389 Fixes overlay jumps top of the page #3387
  panel/src/components/Layout/Overlay.vue
Labels: difficulty: easy 🤩, type: bug 🐛

#2777 Support extending custom file and mime types
  src/Cms/AppPlugins.php
  src/Image/Image.php
  src/Toolkit/F.php
  tests/Cms/App/AppPluginsTest.php
Labels: type: feature ⭐️

#3391 Deprecate `Str::isUrl()` #3386
  src/Toolkit/Html.php
  src/Toolkit/Str.php
Labels: type: refactoring :recycle:

#3401 Codecov in CI: Use token
  .github/workflows/ci.yml
Labels: type: refactoring :recycle:

#3372 Deprecate optional `parent` prop in `Cms\File`
  config/fields/mixins/upload.php
  config/sections/files.php
  src/Cms/File.php
  tests/Cms/Api/collections/FilesApiCollectionTest.php
  tests/Cms/Api/models/FileBlueprintApiModelTest.php
  tests/Cms/Files/FileBlueprintTest.php
  tests/Cms/Files/FilePermissionsTest.php
  tests/Cms/Files/FileTest.php
  tests/Cms/Files/FileVersionTest.php
  tests/Cms/Files/FilesTest.php
  tests/Cms/Files/HasFilesTest.php
  tests/Cms/Media/MediaTest.php
  tests/Cms/Sections/FieldsSectionTest.php
  tests/Cms/Sections/FilesSectionTest.php
  tests/Form/FormTest.php
  tests/Panel/FileTest.php
Labels: type: refactoring :recycle:

#3403 PHPUnit tests: Always pass roots to app instances
  tests/Cms/Users/UserActionsTest.php
  tests/Cms/Users/UserAuthTest.php
  tests/Panel/FileTest.php
Labels: type: refactoring :recycle:

#3408 Codecov in CI: Use token
  .github/workflows/ci.yml
Labels: type: bug 🐛

#3384 Supports countable field objects
  src/Toolkit/V.php
  tests/Toolkit/VTest.php
Labels: type: bug 🐛

#3396 `k-breadcrumb` component
  panel/src/components/Navigation/Breadcrumb.vue
  panel/src/components/Navigation/Topbar.vue
  panel/src/components/Views/FileView.spec.js
  panel/src/components/Views/PageView.spec.js
  panel/src/components/Views/SiteView.spec.js
  panel/src/components/Views/UsersView.spec.js
  panel/src/config/components.js
Labels: type: refactoring :recycle:

#3400 Update page sections on `page.sort` #3399
  panel/src/components/Sections/FilesSection.vue
  panel/src/components/Sections/PagesSection.vue
Labels: type: bug 🐛

#3411 Refactored block table with structure field
  panel/src/components/Blocks/Types/Table.vue
  panel/src/components/Forms/Field/StructureField.vue
  panel/src/mixins/forms/structure.js
Labels: type: bug 🐛, type: refactoring :recycle:

#2763 Pages: Only use findBy('slug') on non-default languages
  src/Cms/Page.php
  src/Cms/Pages.php
  tests/Cms/Pages/PagesTest.php
Labels: missing: discussion 🗣, type: enhancement ✨, type: refactoring :recycle:

#3420 `light` theme for `k-dropdown-content`
  panel/src/components/Forms/FormIndicator.vue
  panel/src/components/Navigation/DropdownContent.vue
  panel/src/components/Navigation/Topbar.vue
Labels: type: enhancement ✨

#3419 Add `k-options-dropdown`
  panel/src/components/Forms/Field/FilesField.vue
  panel/src/components/Forms/Field/PagesField.vue
  panel/src/components/Forms/Field/UsersField.vue
  panel/src/components/Navigation/OptionsDropdown.vue
  panel/src/config/components.js
  panel/src/mixins/forms/picker.js
Labels: type: feature ⭐️

#3426 `Str::contains`: use `strpos` instead
  src/Toolkit/Str.php
Labels: type: enhancement ✨

#3423 `$helper.color` JS helper for using CSS color vars
  panel/src/components/Misc/Icon.vue
  panel/src/helpers/color.js
  panel/src/helpers/color.spec.js
  panel/src/helpers/index.js
Labels: type: enhancement ✨

#3432 Fixes autofocus writer and list field
  panel/src/components/Forms/Input.vue
  panel/src/components/Forms/Input/ListInput.vue
  panel/src/components/Writer/Editor.js
  panel/src/components/Writer/Marks/Link.js
  panel/src/components/Writer/Writer.vue
Labels: type: bug 🐛

#3421 Fixes writer field empty state
  panel/src/components/Writer/Editor.js
Labels: type: bug 🐛

#3431 Use `calc()` where `var()` is used in computation #3415
  panel/src/components/Forms/Input/RangeInput.vue
  panel/src/components/Navigation/ButtonGroup.vue
  panel/src/components/Writer/Toolbar.vue
Labels: type: bug 🐛, type: regression ⚡️

#3427 Silent Fiber requests
  panel/src/components/Forms/FormButtons.vue
  panel/src/config/fiber.js
  panel/src/index.js
Labels: type: regression ⚡️

#3279 Supports HTML for toggle and checkbox field labels
  panel/src/components/Forms/Input/CheckboxInput.vue
  panel/src/components/Forms/Input/ToggleInput.vue
  src/Form/OptionsApi.php
  src/Toolkit/Str.php
Labels: missing: discussion 🗣, type: bug 🐛, type: regression ⚡️

#3439 Update hashes with latest release commit for GitHub workflow
  .github/workflows/ci.yml
Labels: priority: high 🔥, type: refactoring :recycle:

#3437 [3.6.0] Fixes toggle method in files field dropdown
  panel/src/components/Forms/Field/FilesField.vue
Labels: type: bug 🐛, type: regression ⚡️

#3425 Unify `panel()->image()`
  config/api/models/File.php
  config/api/models/Page.php
  config/api/models/User.php
  config/areas/users.php
  config/fields/files.php
  config/fields/pages.php
  config/fields/users.php
  config/sections/files.php
  config/sections/pages.php
  panel/src/components/Forms/Field/FilesField.vue
  panel/src/components/Forms/Field/PagesField.vue
  panel/src/components/Forms/Field/UsersField.vue
  panel/src/components/Layout/Card.vue
  panel/src/components/Layout/FilePreview.vue
  panel/src/components/Layout/ListItem.vue
  panel/src/components/Navigation/Search.vue
  panel/src/config/search.js
  panel/src/helpers/previewThumb.js
  panel/src/helpers/previewThumb.spec.js
  src/Cms/ModelWithContent.php
  src/Cms/Page.php
  src/Panel/File.php
  src/Panel/Model.php
  src/Panel/Page.php
  src/Panel/User.php
  tests/Cms/Api/ApiModelTestCase.php
  tests/Cms/Api/models/FileBlueprintApiModelTest.php
  tests/Cms/Api/models/PageApiModelTest.php
  tests/Cms/Api/models/PageBlueprintApiModelTest.php
  tests/Cms/Api/models/SiteApiModelTest.php
  tests/Cms/Api/models/UserApiModelTest.php
  tests/Cms/Api/models/UserBlueprintApiModelTest.php
  tests/Cms/Sections/PagesSectionTest.php
  tests/Form/Fields/FilesFieldTest.php
  tests/Form/Fields/PagesFieldTest.php
  tests/Form/Fields/UsersFieldTest.php
  tests/Panel/FileTest.php
  tests/Panel/ModelTest.php
  tests/Panel/PageTest.php
  tests/Panel/SiteTest.php
  tests/Panel/UserTest.php
Labels: type: refactoring :recycle:

#3441 Store empty string when blocks and layout field empty
  src/Form/Field/BlocksField.php
  src/Form/Field/LayoutField.php
  tests/Form/Fields/BlocksFieldTest.php
  tests/Form/Fields/LayoutFieldTest.php
Labels: difficulty: easy 🤩, type: enhancement ✨

#3443 Update quote vue
  panel/src/components/Blocks/Types/Quote.vue
Labels: type: bug 🐛

#3444 Supports new assets extensions `map|json|avif|mjs` for plugins
  config/routes.php
Labels: difficulty: easy 🤩, type: enhancement ✨

#3453 Remove false if-statement for silent fiber
  panel/src/config/fiber.js
Labels: type: regression ⚡️

#3451 New vertical alignment of the dropdown menu: `dropup`
  panel/src/components/Navigation/DropdownContent.vue
Labels: type: bug 🐛, type: enhancement ✨

#3454 Str::template() callback support for 3.5.7
  panel/src/components/Forms/Input/CheckboxInput.vue
  panel/src/components/Forms/Input/ToggleInput.vue
  src/Form/OptionsApi.php
  src/Toolkit/Str.php
Labels: type: enhancement ✨, type: feature ⭐️, type: regression ⚡️

#3455 Checks file exists on `Dir::make()`
  src/Toolkit/Dir.php
  tests/Toolkit/DirTest.php
Labels: type: bug 🐛

#3457 Allow extending SVG namespaces in Sane
  src/Sane/Svg.php
Labels: type: enhancement ✨

#3446 Update Panel README
  config/api/authentication.php
  panel/README.md
Labels: type: regression ⚡️

#3447 `Html::encode()`: Use `ENT_QUOTES` #3291
  config/methods.php
  src/Toolkit/Html.php
Labels: type: enhancement ✨

#3397 `k-items` and cardlets
  config/sections/mixins/layout.php
  panel/src/components/Dialogs/FilesDialog.vue
  panel/src/components/Dialogs/PagesDialog.vue
  panel/src/components/Dialogs/UsersDialog.vue
  panel/src/components/Forms/Field/FilesField.vue
  panel/src/components/Forms/Field/PagesField.vue
  panel/src/components/Forms/Field/UsersField.vue
  panel/src/components/Forms/Previews/FilesFieldPreview.vue
  panel/src/components/Layout/AspectRatio.vue
  panel/src/components/Layout/Card.vue
  panel/src/components/Layout/Cards.vue
  panel/src/components/Layout/Collection.vue
  panel/src/components/Layout/Item.vue
  panel/src/components/Layout/ItemImage.vue
  panel/src/components/Layout/Items.vue
  panel/src/components/Layout/List.vue
  panel/src/components/Layout/ListItem.vue
  panel/src/components/Misc/Icon.vue
  panel/src/components/Navigation/OptionsDropdown.vue
  panel/src/components/Navigation/Search.vue
  panel/src/components/Sections/FilesSection.vue
  panel/src/components/Sections/PagesSection.vue
  panel/src/components/Views/PageView.spec.js
  panel/src/components/Views/UsersView.spec.js
  panel/src/components/Views/UsersView.vue
  panel/src/config/components.js
  panel/src/config/search.js
  panel/src/helpers/previewThumb.js
  panel/src/helpers/previewThumb.spec.js
  panel/src/mixins/forms/picker.js
  panel/src/mixins/picker/dialog.js
  src/Panel/Model.php
  tests/Cms/Api/models/UserApiModelTest.php
  tests/Form/Fields/PagesFieldTest.php
  tests/Panel/ModelTest.php
  tests/Panel/PageTest.php
  tests/Panel/SiteTest.php
  tests/Panel/UserTest.php
Labels: type: feature ⭐️

#2779 New `navigation` option for prev/next pages in Panel
  config/api/models/Page.php
  src/Panel/File.php
  src/Panel/Model.php
  src/Panel/Page.php
  src/Panel/User.php
  tests/Panel/FileTest.php
  tests/Panel/ModelTest.php
  tests/Panel/PageTest.php
  tests/Panel/UserTest.php
Labels: type: feature ⭐️

#3460 Fix `Collection::filter()` #3170
  src/Toolkit/Collection.php
Labels: type: refactoring :recycle:

#3445 Set Panel image via blueprint
  panel/src/helpers/color.js
  panel/src/variables.css
  src/Panel/File.php
  src/Panel/Model.php
  src/Panel/Page.php
  src/Panel/User.php
  tests/Cms/Api/models/UserApiModelTest.php
  tests/Form/Fields/PagesFieldTest.php
  tests/Panel/FileTest.php
  tests/Panel/ModelTest.php
  tests/Panel/PageTest.php
  tests/Panel/SiteTest.php
  tests/Panel/UserTest.php
Labels: type: feature ⭐️

#3450 Support alternative thumb file formats
  config/components.php
  src/Cms/FileModifications.php
  src/Cms/FileVersion.php
  src/Filesystem/Filename.php
  src/Image/Darkroom.php
  src/Image/Darkroom/GdLib.php
  src/Image/Darkroom/ImageMagick.php
  src/Toolkit/Mime.php
  tests/Cms/Files/FileModificationsTest.php
  tests/Image/Darkroom/GdLibTest.php
  tests/Image/Darkroom/ImageMagickTest.php
  tests/Image/DarkroomTest.php
Labels: type: feature ⭐️

#3465 Remove remaining custom Panel views code
  panel/public/js/plugins.js
  panel/src/components/Navigation/Topbar.vue
  panel/src/config/plugins.js
  panel/src/store/modules/languages.js
  panel/src/store/modules/system.js
  panel/src/store/modules/translation.js
  panel/src/store/modules/user.js
  panel/src/store/store.js
  src/Panel/Panel.php
Labels: type: refactoring :recycle:

#3467 Fixes `offsetTop` error on new `dropup` feature
  panel/src/components/Forms/Input.vue
  panel/src/components/Navigation/DropdownContent.vue
Labels: type: bug 🐛, type: regression ⚡️

#3466 `url` component: remove `$originalHandler`
  config/components.php
  src/Cms/Url.php
  tests/Cms/App/AppComponentsTest.php
  tests/Panel/PageTest.php
Labels: type: refactoring :recycle:

#3463 Throw exception for non-Closure Panel area
  src/Panel/Panel.php
  tests/Panel/PanelTest.php
Labels: type: enhancement ✨
