Repository getkirby/kirby, pull requests merged in 2021-05, with the labels that each got.

#3274 use shared laminas escaper instance
  src/Toolkit/Escape.php
Labels: difficulty: easy 🤩, type: refactoring :recycle:

#3292 Disable cache on active sessions
  src/Cms/App.php
  src/Cms/Page.php
  src/Cms/Responder.php
  tests/Cms/App/AppTest.php
  tests/Cms/Pages/PageCacheTest.php
  tests/Cms/ResponderTest.php
Labels: type: enhancement ✨, type: feature ⭐️

#3277 `video` kirbytag supports local and remote videos #3104
  config/tags.php
  src/Cms/File.php
  tests/Cms/Files/FileTest.php
  tests/Cms/KirbyText/KirbyTagsTest.php
  tests/Cms/KirbyText/fixtures/kirbytext/video-youtube/expected.html
  tests/Cms/KirbyText/fixtures/kirbytext/video-youtube/test.txt
Labels: type: feature ⭐️

#3284 Fixes writer field preview props in blocks field #3145
  panel/src/components/Blocks/Types/Text.vue
Labels: difficulty: easy 🤩, type: bug 🐛

#3283 `Form\OptionsQuery`: fix props types
  src/Form/OptionsQuery.php
Labels: type: refactoring :recycle:

#3133 Adjust toolbar position when overflow #2971
  panel/src/components/Writer/Writer.vue
Labels: type: bug 🐛

#3294 Improvements to EmailChallenge
  config/templates/emails/auth/login.php
  config/templates/emails/auth/password-reset.php
  phpunit.xml.dist
  src/Cms/App.php
  src/Cms/Auth/EmailChallenge.php
  src/Cms/System.php
  tests/Cms/App/AppTest.php
  tests/Cms/Auth/Challenge/EmailChallengeTest.php
Labels: type: bug 🐛, type: enhancement ✨

#3297 Don't pin Composer installer version
  composer.json
  composer.lock
Labels: difficulty: easy 🤩, type: bug 🐛

#3202 Render the error page on invalid media URLs
  src/Cms/Media.php
  tests/Cms/Media/MediaTest.php
  tests/Cms/Routes/RouterTest.php
Labels: difficulty: easy 🤩, type: enhancement ✨

#3190 Migrate from Vue CLI to Vite
  .github/workflows/ci.yml
  .php_cs
  panel/.eslintrc.js
  panel/.gitignore
  panel/cypress.json
  panel/dist/css/app.css
  panel/dist/css/index.css
  panel/dist/js/app.js
  panel/dist/js/index.js
  panel/dist/js/vendor.js
  panel/index.html
  panel/package-lock.json
  panel/package.json
  panel/src/components/Blocks/index.js
  panel/src/components/Dialogs/FormDialog.vue
  panel/src/components/Forms/Fieldset.vue
  panel/src/components/Forms/Form.vue
  panel/src/components/Forms/Previews/ToggleFieldPreview.vue
  panel/src/components/Layouter/Layout.vue
  panel/src/components/Layouter/Layouts.vue
  panel/src/components/Navigation/Topbar.vue
  panel/src/components/Views/CustomView.vue
  panel/src/config/config.js
  panel/src/config/routes.js
  panel/src/index.js
  panel/src/index.scss
  panel/src/sandbox/Iframe.vue
  panel/src/sandbox/Sandbox.vue
  panel/src/sandbox/components.js
  panel/vite.config.js
  panel/vue.config.js
  views/panel.php
Labels: type: refactoring :recycle:

#2969 Remove vuex-i18n
  panel/package-lock.json
  panel/package.json
  panel/src/api/files.js
  panel/src/api/pages.js
  panel/src/api/roles.js
  panel/src/api/site.js
  panel/src/api/users.js
  panel/src/config/auth.js
  panel/src/config/filters.js
  panel/src/config/i18n.js
  panel/src/helpers/string.js
  panel/src/index.js
  panel/src/store/modules/translation.js
Labels: type: refactoring :recycle:

#3282 `Form\OptionsApi`: fix props types
  src/Form/OptionsApi.php
Labels: type: refactoring :recycle:

#3290 Merge `Kirby\Cms\Dir` into `Kirby\Toolkit\Dir`
  config/aliases.php
  src/Cms/Dir.php
  src/Cms/HasChildren.php
  src/Cms/Page.php
  src/Cms/PageActions.php
  src/Cms/Site.php
  src/Cms/User.php
  src/Toolkit/Dir.php
  tests/Cms/Api/routes/AuthRoutesTest.php
  tests/Cms/Api/routes/LanguagesRoutesTest.php
  tests/Cms/App/AppResolveTest.php
  tests/Cms/App/AppTest.php
  tests/Cms/App/AppTranslationsTest.php
  tests/Cms/Auth/AuthChallengeTest.php
  tests/Cms/Auth/AuthCsrfTest.php
  tests/Cms/Auth/AuthProtectionTest.php
  tests/Cms/Auth/AuthTest.php
  tests/Cms/Content/ContentLockTest.php
  tests/Cms/Content/ContentLocksTest.php
  tests/Cms/Facades/DirTest.php
  tests/Cms/Facades/STest.php
  tests/Cms/Files/FileTest.php
  tests/Cms/Pages/PageActionsTest.php
  tests/Cms/Pages/PageCacheTest.php
  tests/Cms/Pages/PageCreateTest.php
  tests/Cms/Pages/PageDeleteTest.php
  tests/Cms/Pages/PageSortTest.php
  tests/Cms/Pages/PageTest.php
  tests/Cms/Routes/RouterTest.php
  tests/Cms/Site/SiteActionsTest.php
  tests/Cms/Site/SiteTest.php
  tests/Cms/Users/UserActionsTest.php
  tests/Cms/Users/UserTest.php
  tests/Toolkit/DirTest.php
Labels: type: refactoring :recycle:

#3048 Fix types of `page/s()` helper and `$kirby->page()`
  config/helpers.php
  src/Cms/App.php
Labels: type: refactoring :recycle:

#3191 Replace event bus with mitt
  panel/package-lock.json
  panel/package.json
  panel/src/config/events.js
Labels: type: refactoring :recycle:

#3241 More specific type hints
  src/Cms/Page.php
  src/Cms/Site.php
Labels: type: refactoring :recycle:

#3310 FliesSection.vue: remove if from attribute
  panel/src/components/Sections/FilesSection.vue
Labels: type: refactoring :recycle:

#3308 Vue: fix deprecated slot syntax
  panel/src/components/Dialogs/FilesDialog.vue
  panel/src/components/Dialogs/PageRenameDialog.vue
  panel/src/components/Dialogs/PagesDialog.vue
  panel/src/components/Dialogs/UsersDialog.vue
  panel/src/components/Forms/Field/BlocksField.vue
  panel/src/components/Forms/Field/EmailField.vue
  panel/src/components/Forms/Field/FilesField.vue
  panel/src/components/Forms/Field/PagesField.vue
  panel/src/components/Forms/Field/PasswordField.vue
  panel/src/components/Forms/Field/StructureField.vue
  panel/src/components/Forms/Field/TextField.vue
  panel/src/components/Forms/Field/UrlField.vue
  panel/src/components/Forms/Field/UsersField.vue
  panel/src/components/Forms/Input/MultiselectInput.vue
  panel/src/components/Forms/Input/TagsInput.vue
  panel/src/components/Forms/Upload.vue
  panel/src/components/Layout/Bar.vue
  panel/src/components/Layout/Header.vue
  panel/src/components/Misc/Draggable.vue
  panel/src/components/Views/CustomView.vue
  panel/src/components/Views/FileView.vue
  panel/src/components/Views/PageView.vue
  panel/src/components/Views/ResetPasswordView.vue
  panel/src/components/Views/SiteView.vue
  panel/src/components/Views/UserView.vue
  panel/src/components/Views/UsersView.vue
Labels: type: refactoring :recycle:

#3307 Use email as lowercase to consistently on `User::changeEmail()` and `System::register()`
  src/Cms/System.php
  src/Cms/UserActions.php
  tests/Cms/Users/UserActionsTest.php
Labels: difficulty: easy 🤩, type: bug 🐛

#3304 Remove $t() from props default
  panel/src/components/Dialogs/FormDialog.vue
  panel/src/components/Dialogs/RemoveDialog.vue
  panel/src/components/Forms/Input/EmailInput.vue
  panel/src/components/Forms/Input/ToggleInput.vue
  panel/src/components/Navigation/Pagination.vue
  panel/src/config/i18n.js
Labels: type: refactoring :recycle:

#3319 New `Locale::get()` method
  src/Toolkit/Locale.php
  tests/Toolkit/LocaleTest.php
Labels: type: feature ⭐️

#3074 Revamped video URL parsing for PHP and JS #2955
  config/blocks/video/video.php
  config/helpers.php
  config/tags.php
  panel/src/components/Blocks/Types/Video.vue
  panel/src/helpers/embed.js
  panel/src/helpers/embed.spec.js
  panel/src/helpers/index.js
  src/Toolkit/Html.php
  tests/Cms/Fields/FieldMethodsTest.php
  tests/Cms/Helpers/HelpersTest.php
  tests/Text/KirbyTagsTest.php
  tests/Text/fixtures/kirbytext/video-youtube/expected.html
  tests/Text/fixtures/kirbytext/youtube/test.txt
  tests/Toolkit/HtmlTest.php
Labels: type: enhancement ✨

#3238 New `Panel` namespace
  config/api/models/File.php
  config/api/models/Page.php
  config/api/models/User.php
  config/fields/files.php
  config/fields/pages.php
  config/fields/textarea.php
  config/fields/users.php
  config/routes.php
  config/sections/files.php
  config/sections/pages.php
  src/Cms/File.php
  src/Cms/ModelWithContent.php
  src/Cms/Page.php
  src/Cms/Site.php
  src/Cms/User.php
  src/Panel/File.php
  src/Panel/Model.php
  src/Panel/Page.php
  src/Panel/Panel.php
  src/Panel/Plugins.php
  src/Panel/Site.php
  src/Panel/User.php
  tests/Cms/Files/FileTest.php
  tests/Cms/Models/ModelWithContentTest.php
  tests/Cms/Pages/PageTest.php
  tests/Cms/Site/SiteTest.php
  tests/Cms/Users/UserTest.php
  tests/Panel/FileTest.php
  tests/Panel/PageTest.php
  tests/Panel/PanelTest.php
  tests/Panel/PluginsTest.php
  tests/Panel/SiteTest.php
  tests/Panel/UserTest.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_static.php
Labels: type: refactoring :recycle:

#3326 Clean up Html::video() changes #3074
  src/Toolkit/Html.php
  tests/Toolkit/HtmlTest.php
Labels: type: refactoring :recycle:

#3328 Update PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type: refactoring :recycle:

#3285 New `Filesystem` namespace
  config/aliases.php
  config/components.php
  config/helpers.php
  src/Cms/File.php
  src/Cms/FileActions.php
  src/Cms/FileFoundation.php
  src/Cms/FileModifications.php
  src/Cms/FileRules.php
  src/Cms/FileVersion.php
  src/Filesystem/Asset.php
  src/Filesystem/File.php
  src/Filesystem/Filename.php
  src/Filesystem/IsFile.php
  src/Image/Exif.php
  src/Image/Image.php
  src/Panel/File.php
  src/Panel/Model.php
  src/Panel/Page.php
  src/Panel/User.php
  src/Toolkit/File.php
  tests/Cms/Assets/AssetTest.php
  tests/Cms/Files/FileActionsTest.php
  tests/Cms/Files/FileModificationsTest.php
  tests/Cms/Files/FileRulesTest.php
  tests/Cms/Files/FileTest.php
  tests/Cms/Files/FileVersionTest.php
  tests/Cms/Helpers/HelpersTest.php
  tests/Filesystem/AssetTest.php
  tests/Filesystem/FileTest.php
  tests/Filesystem/FilenameTest.php
  tests/Filesystem/IsFileTest.php
  tests/Filesystem/fixtures/blank.pdf
  tests/Filesystem/fixtures/cat.jpg
  tests/Image/ImageTest.php
  tests/Toolkit/FileTest.php
  tests/Toolkit/fixtures/files/cat.jpg
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_static.php
Labels: type: refactoring :recycle:

#3318 Adds missing translations for some labels in panel
  i18n/translations/en.json
  panel/src/components/Writer/Dialogs/LinkDialog.vue
  panel/src/components/Writer/Marks/Bold.js
  panel/src/components/Writer/Marks/Code.js
  panel/src/components/Writer/Marks/Italic.js
  panel/src/components/Writer/Marks/Link.js
  panel/src/components/Writer/Marks/Strike.js
  panel/src/components/Writer/Marks/Underline.js
  panel/src/components/Writer/Nodes/BulletList.js
  panel/src/components/Writer/Nodes/OrderedList.js
Labels: difficulty: easy 🤩, type: bug 🐛

#3312 Merge `Kirby\Cms\Form` into `Kirby\Form\Form`
  config/aliases.php
  config/api/models/File.php
  config/api/models/Page.php
  config/api/models/Site.php
  config/api/models/User.php
  config/fields/structure.php
  config/sections/fields.php
  src/Cms/Api.php
  src/Cms/Content.php
  src/Cms/Fieldset.php
  src/Cms/FileActions.php
  src/Cms/Form.php
  src/Cms/ModelWithContent.php
  src/Cms/PageActions.php
  src/Cms/UserActions.php
  src/Form/Field/BlocksField.php
  src/Form/Field/LayoutField.php
  src/Form/Form.php
  tests/Cms/Forms/FormTest.php
  tests/Form/FormTest.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_static.php
Labels: type: refactoring :recycle:

#3331 Add `A::apply`
  src/Toolkit/A.php
  tests/Toolkit/ATest.php
Labels: type: feature ⭐️

#3336 Adds some missing `@since` tags
  src/Cms/Auth.php
  src/Cms/Auth/Status.php
  src/Cms/Block.php
  src/Cms/BlockConverter.php
  src/Cms/Blocks.php
  src/Cms/Event.php
  src/Cms/Fieldset.php
  src/Cms/Fieldsets.php
  src/Cms/Item.php
  src/Cms/Items.php
  src/Cms/Layout.php
  src/Cms/LayoutColumn.php
  src/Cms/LayoutColumns.php
  src/Cms/Layouts.php
  src/Cms/Responder.php
  src/Sane/Handler.php
  src/Sane/Sane.php
  src/Sane/Svg.php
  src/Sane/Svgz.php
  src/Sane/Xml.php
  src/Toolkit/A.php
  src/Toolkit/Locale.php
  src/Toolkit/Str.php
Labels: type: enhancement ✨

#3335 CI refactoring
  .gitattributes
  .github/workflows/ci.yml
  .gitignore
  .php-cs-fixer.dist.php
  composer.json
  scripts/pre-commit
Labels: type: refactoring :recycle:

#3332 `Collection::values()` with mapping and pagination
  src/Toolkit/Collection.php
  tests/Toolkit/CollectionTest.php
Labels: type: enhancement ✨

#3289 Keeps `cover` option in `ModelWithContent::panelImage()` method
  src/Panel/Model.php
  src/Panel/Site.php
  tests/Panel/FileTest.php
  tests/Panel/PageTest.php
  tests/Panel/SiteTest.php
  tests/Panel/UserTest.php
Labels: type: bug 🐛, type: regression ⚡️

#3345 JS helper improvements
  panel/src/config/i18n.js
  panel/src/helpers/clone.js
  panel/src/helpers/debounce.js
  panel/src/helpers/direction.js
  panel/src/helpers/embed.js
  panel/src/helpers/isUploadEvent.js
  panel/src/helpers/previewThumb.js
  panel/src/helpers/slug.js
  panel/src/helpers/sort.js
  panel/src/helpers/string.js
  panel/src/helpers/uuid.js
  panel/src/helpers/validate.js
Labels: type: refactoring :recycle:

#3349 Fix infinite loop: FileVersion asset methods #3347
  src/Filesystem/IsFile.php
  tests/Cms/Files/FileRulesTest.php
  tests/Cms/Files/FileVersionTest.php
Labels: type: regression ⚡️

#3350 Fix `FileVersion::__toString()` #3333
  src/Cms/FileVersion.php
  src/Filesystem/File.php
  src/Filesystem/IsFile.php
  src/Image/Image.php
  tests/Cms/Files/FileVersionTest.php
  tests/Image/ImageTest.php
Labels: missing: discussion 🗣, type: regression ⚡️

#3358 Fix list input out of sync #3320
  panel/src/components/Forms/Input/ListInput.vue
Labels: type: bug 🐛, type: regression ⚡️

#3359 Fixes browser back button in panel
  panel/src/config/auth.js
Labels: priority: high 🔥, type: bug 🐛

#3357 Upgrade `vue-docgen-api`
  panel/package-lock.json
  panel/package.json
Labels: type: enhancement ✨

#3371 Tags field: adding missing layout prop
  config/fields/tags.php
Labels: type: enhancement ✨

#3352 Remove deprecated code
  config/api/routes/pages.php
  config/api/routes/site.php
  panel/src/api/index.js
  src/Cms/AppTranslations.php
  src/Cms/Block.php
  src/Cms/PageActions.php
  src/Form/FieldClass.php
  src/Toolkit/I18n.php
  tests/Cms/Pages/PageSortTest.php
Labels: type: refactoring :recycle:

#3380 Implements translations prototype
  panel/src/main.js
Labels: type: bug 🐛, type: regression ⚡️

#3268 F::relativepath() when an unrelated base is given, prefix with ../ for relative travel path
  src/Toolkit/F.php
  tests/Toolkit/FTest.php
Labels: type: enhancement ✨

#3383 Fix return type for `App::translation()`
  src/Cms/AppTranslations.php
Labels: type: bug 🐛

#3385 `page.php` API routes: fix check for deprecation
  config/api/routes/pages.php
Labels: type: regression ⚡️
