Repository getkirby/kirby, pull requests merged in 2021-03, with the labels that each got.

#3166 Deprecated: improve docs and warnings
  config/api/routes/pages.php
  config/api/routes/site.php
  config/components.php
  panel/src/api/index.js
  src/Cms/AppTranslations.php
  src/Cms/Block.php
  src/Cms/PageActions.php
  src/Form/FieldClass.php
  src/Toolkit/I18n.php
Labels: type: refactoring :recycle:

#3167 Fix return types: $this, static and self
  src/Api/Api.php
  src/Api/Collection.php
  src/Api/Model.php
  src/Cache/Value.php
  src/Cms/Api.php
  src/Cms/App.php
  src/Cms/Asset.php
  src/Cms/Auth/Status.php
  src/Cms/Blueprint.php
  src/Cms/Collection.php
  src/Cms/Content.php
  src/Cms/ContentTranslation.php
  src/Cms/Field.php
  src/Cms/File.php
  src/Cms/FileActions.php
  src/Cms/FileFoundation.php
  src/Cms/FileVersion.php
  src/Cms/Files.php
  src/Cms/Form.php
  src/Cms/HasChildren.php
  src/Cms/HasFiles.php
  src/Cms/Ingredients.php
  src/Cms/Language.php
  src/Cms/Languages.php
  src/Cms/Model.php
  src/Cms/ModelWithContent.php
  src/Cms/Page.php
  src/Cms/PageActions.php
  src/Cms/Pages.php
  src/Cms/Permissions.php
  src/Cms/Plugin.php
  src/Cms/Responder.php
  src/Cms/Response.php
  src/Cms/Role.php
  src/Cms/Roles.php
  src/Cms/Site.php
  src/Cms/SiteActions.php
  src/Cms/StructureObject.php
  src/Cms/Translation.php
  src/Cms/Translations.php
  src/Cms/User.php
  src/Cms/UserActions.php
  src/Cms/Users.php
  src/Database/Database.php
  src/Database/Query.php
  src/Email/Body.php
  src/Email/Email.php
  src/Form/Fields.php
  src/Form/OptionsApi.php
  src/Form/OptionsQuery.php
  src/Http/Remote.php
  src/Http/Response.php
  src/Http/Uri.php
  src/Image/Dimensions.php
  src/Text/KirbyTag.php
  src/Toolkit/Collection.php
  src/Toolkit/File.php
  src/Toolkit/Pagination.php
  src/Toolkit/Properties.php
Labels: type: refactoring :recycle:

#3196 feat: add excerpt() to block class
  src/Cms/Block.php
  tests/Cms/Blocks/BlockTest.php
  tests/Cms/Blocks/BlocksTest.php
Labels: type: enhancement ✨

#3207 Use `Wrong password` message on login instead `notSame`
  i18n/translations/en.json
  panel/src/components/Views/LoginView.spec.js
  src/Cms/User.php
  tests/Cms/Auth/AuthChallengeTest.php
  tests/Cms/Auth/AuthProtectionTest.php
Labels: difficulty: easy 🤩, type: enhancement ✨

#3199 FileCache: Clean up empty directories on remove() #3162
  src/Cache/FileCache.php
  tests/Cache/FileCacheTest.php
Labels: type: enhancement ✨

#3212 Fix error.page.slug.invalid translation #3205
  i18n/translations/en.json
Labels: difficulty: easy 🤩, type: bug 🐛

#3221 Checks whether the field disabled on `prompt()` method in files field
  panel/src/components/Forms/Field/FilesField.vue
Labels: difficulty: easy 🤩, type: bug 🐛

#3217 Slots for the ListItem component
  panel/src/components/Layout/ListItem.vue
Labels: difficulty: easy 🤩, type: enhancement ✨
