Repository getkirby/kirby, pull requests merged in 2022-07, with the labels that each got.

#4463 Remove `DS` constant definition
  config/setup.php
Labels: type: refactoring :recycle:

#4456 Only show error output when in debug mode
  src/Cms/Block.php
  tests/Cms/Blocks/BlockTest.php
  tests/Cms/Blocks/fixtures/snippets/blocks/debug.php
Labels: type: bug 🐛

#4458 No longer return `$this` on Collection `__set()` method
  src/Cms/Collection.php
  src/Cms/Structure.php
  src/Form/Fields.php
  src/Http/Uri.php
  src/Toolkit/Collection.php
Labels: type: refactoring :recycle:

#4465 Vue 2.7.0
  panel/cypress.config.js
  panel/cypress.json
  panel/package-lock.json
  panel/package.json
  panel/src/components/Navigation/__snapshots__/PrevNext.test.js.snap
  panel/vite.config.js
Labels: type: refactoring :recycle:

#4469 Add dependabot config
  .github/dependabot.yml 
Labels: type: refactoring :recycle:

#4471 Removed unused `ui.js`
  panel/src/ui.js
Labels: type: refactoring :recycle:

#4457 Catch exceptions: remove unused variables
  config/components.php
  config/methods.php
  config/sections/pages.php
  src/Cache/FileCache.php
  src/Cache/Value.php
  src/Cms/App.php
  src/Cms/AppUsers.php
  src/Cms/Auth.php
  src/Cms/Blocks.php
  src/Cms/Blueprint.php
  src/Cms/Collections.php
  src/Cms/Language.php
  src/Cms/LanguageRouter.php
  src/Cms/Layouts.php
  src/Cms/Media.php
  src/Cms/ModelWithContent.php
  src/Cms/Page.php
  src/Cms/Plugin.php
  src/Cms/Role.php
  src/Cms/Site.php
  src/Cms/System.php
  src/Cms/Template.php
  src/Cms/Translation.php
  src/Cms/User.php
  src/Cms/UserActions.php
  src/Filesystem/Dir.php
  src/Filesystem/F.php
  src/Form/Field/BlocksField.php
  src/Form/Field/LayoutField.php
  src/Form/FieldClass.php
  src/Http/Response.php
  src/Http/Router.php
  src/Http/Uri.php
  src/Panel/Dropdown.php
  src/Panel/File.php
  src/Panel/Home.php
  src/Panel/Panel.php
  src/Session/Sessions.php
  src/Toolkit/Component.php
  src/Toolkit/Date.php
  src/Toolkit/Str.php
  src/Toolkit/V.php
  tests/Cms/Auth/AuthTest.php
Labels: type: refactoring :recycle:

#4472 Fix #4383
  panel/src/components/Forms/Writer/Editor.js
Labels: type: bug 🐛

#4349 Fix multi selecting blocks without click
  panel/src/components/Forms/Blocks/Blocks.vue
  panel/src/config/events.js
Labels: type: bug 🐛

#4474 Allow overriding the base URL from env configs
  src/Cms/App.php
  tests/Cms/App/AppTest.php
  tests/Cms/App/fixtures/AppTest/options/config.getkirby.com.php
  tests/Cms/App/fixtures/AppTest/options/config.php
  tests/Cms/App/fixtures/AppTest/options/config.trykirby.com.php
Labels: type: regression 🚨

#4475 `Environment`: Better reverse proxy URL detection
  src/Http/Environment.php
Labels: type: enhancement ✨, type: regression 🚨

#4468 Simplify some if-else statements
  config/api/routes/auth.php
  config/api/routes/files.php
  config/api/routes/system.php
  config/api/routes/users.php
  config/fields/files.php
  src/Api/Api.php
  src/Api/Model.php
  src/Cache/Cache.php
  src/Cache/FileCache.php
  src/Cache/MemoryCache.php
  src/Cache/Value.php
  src/Cms/App.php
  src/Cms/AppTranslations.php
  src/Cms/Auth.php
  src/Cms/Blueprint.php
  src/Cms/Collection.php
  src/Cms/ContentLock.php
  src/Cms/ContentTranslation.php
  src/Cms/Core.php
  src/Cms/Email.php
  src/Cms/Event.php
  src/Cms/File.php
  src/Cms/FilePicker.php
  src/Cms/Find.php
  src/Cms/HasChildren.php
  src/Cms/Language.php
  src/Cms/LanguageRouter.php
  src/Cms/Languages.php
  src/Cms/Loader.php
  src/Cms/Media.php
  src/Cms/ModelPermissions.php
  src/Cms/ModelWithContent.php
  src/Cms/Nest.php
  src/Cms/Page.php
  src/Cms/PagePicker.php
  src/Cms/Site.php
  src/Cms/System.php
  src/Cms/User.php
  src/Session/Session.php
Labels: type: refactoring :recycle:

#4488 Fix `match` for model objects
  src/Cms/FilePicker.php
  src/Cms/PagePicker.php
Labels: type: regression 🚨

#4482 Changed "Login" to "Log in"
  i18n/translations/en.json
  tests/Cms/Loader/LoaderTest.php
  tests/Panel/Areas/LoginTest.php
Labels: type: bug 🐛, type: i18n 🌏

#4470 Upgrade to Vite 3.0
  panel/package-lock.json
  panel/package.json
  panel/src/components/Forms/Blocks/index.js
  panel/vite.config.js
Labels: type: refactoring :recycle:

#4503 fix passing `null` to `trim()`
  src/Parsley/Inline.php
Labels: type: bug 🐛

#4502 Update "quote" block preview to allow paragraphs
  panel/src/components/Forms/Blocks/Types/Quote.vue
Labels: type: enhancement ✨

#4499 New `Users::files()` method
  src/Cms/Files.php
  src/Cms/Users.php
  tests/Cms/Users/UsersTest.php
Labels: type: feature 🎉

#4495 `Toolkit\A`: improve type hinting
  src/Toolkit/A.php
Labels: type: refactoring :recycle:

#4478 Remove deprecated code
  config/aliases.php
  config/api/models/Page.php
  config/components.php
  src/Cms/App.php
  src/Cms/File.php
  src/Cms/Files.php
  src/Cms/ModelWithContent.php
  src/Cms/Page.php
  src/Cms/Pages.php
  src/Cms/Permissions.php
  src/Cms/Site.php
  src/Cms/User.php
  src/Http/Environment.php
  src/Http/Server.php
  src/Panel/Document.php
  src/Toolkit/Str.php
  tests/Cms/App/AppComponentsTest.php
  tests/Http/EnvironmentTest.php
  tests/Http/ServerTest.php
  tests/Panel/FileTest.php
Labels: type: refactoring :recycle:

#4498 `App::impersonate()`: don’t bind callback to `App`
  src/Cms/AppUsers.php
  src/Cms/AppUsersImpersonateProxy.php
  tests/Cms/App/AppUsersTest.php
Labels: type: refactoring :recycle:

#4510 Fix `A::join()` type hint
  src/Toolkit/A.php
Labels: type: bug 🐛, type: refactoring :recycle:

#4507 Fix `Data\Txt::encodeResult()` value trimming
  src/Data/Txt.php
  tests/Data/TxtTest.php
  tests/Data/fixtures/test.txt
Labels: type: enhancement ✨

#4513 Fix 3.7 regression : Add missing onInput listener
  panel/src/components/Forms/Field/StructureField.vue
Labels: type: regression 🚨

#4512 Fix `query` to `searchterm` for sortable
  config/sections/files.php
  config/sections/mixins/search.php
  config/sections/mixins/sort.php
  config/sections/pages.php
  tests/Cms/Sections/mixins/SortMixinTest.php
Labels: type: bug 🐛

#4509 Fix block `->prev()`, `->next()` and `->siblings()`
  src/Cms/Block.php
  tests/Cms/Blocks/BlockTest.php
Labels: type: bug 🐛

#4517 Fix back button in the login challenge view
  config/areas/account/views.php
  config/areas/logout.php
  src/Cms/Core.php
  src/Panel/Panel.php
  tests/Panel/Areas/AccountTest.php
  tests/Panel/Areas/LogoutTest.php
  tests/Panel/PanelTest.php
Labels: type: regression 🚨

#4538 Revert `onInput` listener for structure field
  panel/src/components/Forms/Field/StructureField.vue
Labels: type: regression 🚨
