Repository getkirby/kirby, pull requests merged in 2022-10, with the labels that each got.

#4737 Update check: Normalize and validate plugin versions
  src/Cms/Plugin.php
  src/Cms/System/UpdateStatus.php
  tests/Cms/Plugins/PluginTest.php
  tests/Cms/Plugins/fixtures/plugin-version-invalid/composer.json
  tests/Cms/Plugins/fixtures/plugin-version-prefix/composer.json
Labels: type: bug 🐛, type: refactoring :recycle:

#4728 `NodeI18n`: reuse `I18n` logic
  src/Blueprint/NodeI18n.php
  src/Toolkit/I18n.php
  tests/Blueprint/NodeI18nTest.php
  tests/Toolkit/I18nTest.php
Labels: type: regression 🚨

#4738 Update check: Fixes and remaining unit/integration tests
  src/Cms/System/UpdateStatus.php
  tests/Cms/System/SystemTest.php
  tests/Cms/System/UpdateStatusTest.php
  tests/Cms/System/fixtures/SystemTest/security.json
  tests/Cms/System/fixtures/UpdateStatusTest/getkirby.com/plugins/getkirby/invalid-json.json
  tests/Cms/System/fixtures/UpdateStatusTest/getkirby.com/plugins/getkirby/public.json
  tests/Cms/System/fixtures/UpdateStatusTest/getkirby.com/security.json
  tests/Cms/System/fixtures/UpdateStatusTest/logic/basic.json
  tests/Cms/System/fixtures/UpdateStatusTest/logic/eol-link.json
  tests/Cms/System/fixtures/UpdateStatusTest/logic/incidents-cascade.json
  tests/Cms/System/fixtures/UpdateStatusTest/logic/incidents-loop.json
  tests/Cms/System/fixtures/UpdateStatusTest/logic/incidents-severity.json
  tests/Cms/System/fixtures/UpdateStatusTest/logic/invalid-constraint-incident.json
  tests/Cms/System/fixtures/UpdateStatusTest/logic/invalid-constraint-message.json
  tests/Cms/System/fixtures/UpdateStatusTest/logic/invalid-constraint-url.json
  tests/Cms/System/fixtures/UpdateStatusTest/logic/invalid-constraint-version.json
  tests/Cms/System/fixtures/UpdateStatusTest/logic/missing-constraint-incident.json
  tests/Cms/System/fixtures/UpdateStatusTest/logic/missing-constraint-message.json
  tests/Cms/System/fixtures/UpdateStatusTest/logic/no-incidents.json
  tests/Cms/System/fixtures/UpdateStatusTest/logic/no-latest.json
  tests/Cms/System/fixtures/UpdateStatusTest/logic/no-messages.json
  tests/Cms/System/fixtures/UpdateStatusTest/logic/no-url-entry.json
  tests/Cms/System/fixtures/UpdateStatusTest/logic/no-urls.json
  tests/Cms/System/fixtures/UpdateStatusTest/logic/no-version-entry.json
  tests/Cms/System/fixtures/UpdateStatusTest/logic/no-versions.json
  tests/Cms/System/fixtures/UpdateStatusTest/logic/url-entry-without-changes.json
  tests/Cms/System/fixtures/UpdateStatusTest/logic/version-entry-without-latest.json
  tests/Cms/System/mocks.php
Labels: type: refactoring :recycle:

#4742 `OptionsQuery`: fix for array
  src/Option/OptionsQuery.php
  tests/Option/OptionsQueryTest.php
Labels: type: regression 🚨

#4722 System view: improve console messages
  panel/src/components/Views/SystemView.vue
Labels: type: enhancement ✨

#4746 `Dir::make()`: prevent race condition
  src/Filesystem/Dir.php
Labels: type: enhancement ✨, type: regression 🚨

#4744 System view: responsive version dropdown
  panel/src/components/Layout/TableUpdateStatusCell.vue
Labels: type: bug 🐛

#4753 Fix broken label/headline in info section
  panel/src/components/Sections/InfoSection.vue
Labels: type: regression 🚨

#4761 `Uuid::populate()` only if not yet cached
  src/Uuid/Uuid.php
  tests/Uuid/UuidTest.php
Labels: type: bug 🐛

#4750 Switch from `class_uses()` to duck test for `File::setModel()`
  src/Filesystem/File.php
  src/Filesystem/IsFile.php
  tests/Filesystem/FileTest.php
Labels: type: regression 🚨, needs: two-person review 🧑‍🤝‍🧑

#4763 Also use tabular nums with disabled update check
  panel/src/components/Layout/TableUpdateStatusCell.vue
Labels: type: enhancement ✨

#4759 Fix recursion on blocks field focus when autofocus enabled
  panel/src/components/Forms/Blocks/Blocks.vue
Labels: type: bug 🐛

#4760 Refactor `Helpers::handleErrors()`
  src/Cms/Helpers.php
  src/Filesystem/Dir.php
  src/Filesystem/F.php
  tests/Cms/Helpers/HelpersTest.php
Labels: type: refactoring :recycle:

#4774 System view: fix console message
  panel/src/components/Views/SystemView.vue
Labels: type: bug 🐛

#4751 Retrieve plugin versions from composer data
  src/Cms/Plugin.php
  tests/Cms/Plugins/PluginTest.php
  tests/Cms/Plugins/fixtures/plugin-version-composer-noversionset/composer.json
  tests/Cms/Plugins/fixtures/plugin-version-composer-override/composer.json
  tests/Cms/Plugins/fixtures/plugin-version-composer/composer.json
  tests/Cms/Plugins/fixtures/vendor/composer/installed.php
Labels: type: enhancement ✨

#4770 Panel: silent lock requests
  panel/src/components/Forms/FormButtons.vue
Labels: type: bug 🐛

#4777 Fix border radius for Chrome-autofilled text input
  panel/src/components/Forms/Input.vue
Labels: type: bug 🐛

#4775 Whoops: exceptions to PHP error log
  src/Cms/AppErrors.php
  tests/Cms/App/AppErrorsTest.php
Labels: type: enhancement ✨

#4773 Remove unnecessary `else` statements
  config/api/models/Page.php
  config/fields/toggle.php
  src/Cms/AppUsers.php
  src/Cms/Auth.php
  src/Cms/Auth/Status.php
  src/Cms/Collection.php
  src/Cms/Content.php
  src/Cms/PageSiblings.php
  src/Cms/System.php
  src/Cms/User.php
  src/Cms/UserActions.php
  src/Database/Query.php
  src/Database/Sql.php
  src/Http/Cookie.php
  src/Http/Remote.php
  src/Session/Session.php
  src/Session/SessionData.php
  src/Toolkit/Html.php
  src/Toolkit/Locale.php
  src/Toolkit/Query.php
  src/Toolkit/Silo.php
  src/Toolkit/Xml.php
Labels: type: refactoring :recycle:

#4675 `A::merge`: support multiple arrays
  src/Toolkit/A.php
  tests/Toolkit/ATest.php
Labels: type: enhancement ✨

#4783 Fix `store` description of picker fields
  config/fields/mixins/picker.php
Labels: type: bug 🐛

#4782 Use Kirby\Cms\Url in go helper
  config/helpers.php
Labels: type: regression 🚨

#4755 Disable UUIDs via config option
  config/routes.php
  src/Cms/File.php
  src/Cms/FileActions.php
  src/Cms/ModelWithContent.php
  src/Cms/Page.php
  src/Cms/PageActions.php
  src/Panel/File.php
  src/Panel/Model.php
  src/Panel/Page.php
  src/Uuid/Identifiable.php
  src/Uuid/Uuid.php
  src/Uuid/Uuids.php
  tests/Uuid/UuidTest.php
  tests/Uuid/UuidsTest.php
Labels: type: enhancement ✨

#4790 Fixes generating `uuid` value when `content.uuid` option disabled
  src/Cms/FileActions.php
  src/Cms/PageActions.php
Labels: type: bug 🐛, critical: roadblock 🚧, needs: tests 🧪

#4794 Supports YouTube shorts video urls
  src/Toolkit/Html.php
  tests/Toolkit/HtmlTest.php
Labels: type: enhancement ✨

#4798 Fixes users field when user(s) not found
  src/Uuid/UserUuid.php
  tests/Uuid/UuidTest.php
Labels: type: bug 🐛

#4800 Fix potential content loss during UUID generation
  composer.json
  composer.lock
  panel/dist/js/index.js
  panel/dist/js/vendor.js
  panel/src/components/Sections/FilesSection.vue
  panel/src/components/Sections/PagesSection.vue
  src/Cms/ModelWithContent.php
  src/Data/Handler.php
  src/Filesystem/F.php
  src/Uuid/ModelUuid.php
  tests/Data/HandlerTest.php
  tests/Uuid/FileUuidTest.php
  tests/Uuid/PageUuidTest.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_static.php
  vendor/composer/installed.php
Labels: type: bug 🐛, critical: roadblock 🚧, needs: two-person review 🧑‍🤝‍🧑

#4803 Fix UUID generation on multilang setup
  src/Cms/App.php
  src/Cms/ModelWithContent.php
  src/Uuid/ModelUuid.php
  tests/Cms/Models/ModelWithContentTest.php
  tests/Panel/DropdownTest.php
  tests/Text/KirbyTagsTest.php
  tests/Uuid/FileUuidTest.php
  tests/Uuid/PageUuidTest.php
Labels: type: bug 🐛, critical: roadblock 🚧

#4816 Import `h()` from Vue
  panel/src/components/Misc/ErrorBoundary.vue
  panel/src/index.js
Labels: type: refactoring :recycle:

#4813 Upgrade npm dependencies
  panel/package-lock.json
  panel/package.json
Labels: type: enhancement ✨

#4808 Improve `App::language()` syntax
  src/Cms/App.php
Labels: type: refactoring :recycle:

#4806 Improve `ContentTranslation::content()` syntax
  src/Cms/ContentTranslation.php
Labels: type: refactoring :recycle:
