Repository getkirby/kirby, pull requests merged in 2022-03, with the labels that each got.

#4187 Vimeo video id not extracted for some Urls
  src/Toolkit/Html.php
  tests/Toolkit/HtmlTest.php
Labels: type: enhancement ✨

#4184 Fix phpmailer message body empty exception
  src/Email/Body.php
  src/Email/Email.php
  tests/Email/EmailTest.php
Labels: type: bug 🐛

#4106 Add JPEG size hint to ImageMagick command
  src/Image/Darkroom.php
  src/Image/Darkroom/ImageMagick.php
  tests/Image/Darkroom/GdLibTest.php
  tests/Image/Darkroom/ImageMagickTest.php
Labels: type: enhancement ✨, type: performance ⚡️

#4182 Makes sure whoops is registered while the configurations is being loaded
  src/Cms/App.php
Labels: type: bug 🐛

#4205 Fix vertical alignment for today text in calendar
  panel/src/components/Forms/Calendar.vue
Labels: type: enhancement ✨

#4193 Fix autofocus in picker dialogs search
  panel/src/mixins/picker/dialog.js
Labels: type: bug 🐛

#4190 Query images for image and gallery blocks
  config/blocks/gallery/gallery.yml
  config/blocks/image/image.yml
  src/Cms/ModelWithContent.php
  tests/Cms/Files/FileTest.php
  tests/Cms/Pages/PageTest.php
  tests/Cms/Site/SiteTest.php
  tests/Cms/Users/UserTest.php
Labels: type: enhancement ✨

#4232 Fix droppable files files when disabled
  panel/src/components/Forms/Field/FilesField.vue
Labels: type: bug 🐛

#4223 Fix fields section form content on multi language
  config/sections/fields.php
  tests/Cms/Sections/FieldsSectionTest.php
Labels: type: bug 🐛

#4227 Fixed text field `converter` prop for PHP 8.1
  config/components.php
  config/fields/text.php
  tests/Form/Fields/TextFieldTest.php
Labels: type: bug 🐛

#4224 Improve structure field columns on mobile
  panel/src/components/Forms/Field/StructureField.vue
Labels: type: enhancement ✨

#4238 Fix tabs resize for mobile
  panel/src/components/Layout/Tabs.vue
Labels: type: bug 🐛
