Repository getkirby/kirby, pull requests merged in 2022-09, with the labels that each got.

#4621 Improve stale message
  .github/workflows/stale.yml
Labels: type: docs 📝

#4623 Fix `Remote::json` return type
  src/Http/Remote.php
Labels: type: regression 🚨

#4622 Parent model for filesystem
  src/Filesystem/File.php
  src/Filesystem/IsFile.php
  tests/Filesystem/FileTest.php
  tests/Filesystem/IsFileTest.php
Labels: type: regression 🚨

#4631 Fix table layout heading alignment
  panel/src/components/Layout/Table.vue
Labels: type: bug 🐛

#4616 Missing on form submit event
  panel/src/components/Forms/Field/StructureField.vue
Labels: type: enhancement ✨

#4636 Fix docblocks and type hints related to snippets
  config/components.php
  src/Cms/App.php
Labels: type: refactoring :recycle:

#4637 Bring back default slot for `k-items`
  panel/src/components/Layout/Items.vue
Labels: type: regression 🚨

#4625 Better error messages for blocks and layout fields
  i18n/translations/en.json
  src/Form/Field/BlocksField.php
  src/Form/Field/LayoutField.php
  tests/Form/Fields/BlocksFieldTest.php
  tests/Form/Fields/LayoutFieldTest.php
Labels: type: enhancement ✨, type: i18n 🌏

#4629 Better show multiple error lines for error dialog
  panel/src/components/Dialogs/ErrorDialog.vue
Labels: type: enhancement ✨

#4639 Upgrade npm dependencies
  panel/package-lock.json
  panel/package.json
Labels: type: refactoring :recycle:

#4627 New `Cache::getOrSet()` method
  src/Cache/Cache.php
  tests/Cache/CacheTest.php
Labels: type: feature 🎉

#4645 `Str::excerpt()`: prevent extra space
  src/Toolkit/Str.php
  tests/Toolkit/StrTest.php
Labels: type: bug 🐛

#4643 Fix site search with parameters results
  config/components.php
  tests/Cms/Site/SitePagesTest.php
Labels: type: bug 🐛

#4649 Fix `A::average()` for empty array
  src/Toolkit/A.php
  tests/Toolkit/ATest.php
Labels: type: bug 🐛

#4648 Fix highlighting of item during dragging
  panel/src/components/Layout/Item.vue
Labels: type: enhancement ✨

#4644 JSconfig: experimentalDisableTemplateSupport
  panel/jsconfig.json
Labels: type: refactoring :recycle:

#4647 System view: use `–` for empty cells
  config/areas/system/views.php
  tests/Panel/Areas/SystemTest.php
Labels: type: enhancement ✨

#4646 Fix disabled cache on empty auth header
  src/Cms/Auth.php
  src/Http/Request.php
  tests/Cms/Auth/AuthTest.php
  tests/Http/RequestTest.php
Labels: type: bug 🐛

#4658 System view: Move logic to the backend
  config/areas/system/views.php
  panel/src/components/Layout/Stats.vue
  panel/src/components/Views/SystemView.vue
  tests/Panel/Areas/SystemTest.php
Labels: type: enhancement ✨, type: refactoring :recycle:

#4662 PHP 8: Clean up `Cms\Plugin` class
  src/Cms/Plugin.php
Labels: type: refactoring :recycle:

#4650 `Database\Query`: Separate `$mode` for `filterQuery()`
  src/Database/Query.php
  tests/Database/QueryTest.php
Labels: type: refactoring :recycle:

#4655 Fix disabled styling for picker fields
  panel/src/components/Forms/Field/FilesField.vue
  panel/src/components/Forms/Field/PagesField.vue
  panel/src/components/Forms/Field/UsersField.vue
Labels: type: bug 🐛

#4624 Options refactoring to fix double-escaping issues
  config/fields/mixins/options.php
  config/fields/multiselect.php
  config/fields/tags.php
  panel/src/components/Forms/Input/CheckboxesInput.vue
  panel/src/components/Forms/Input/MultiselectInput.vue
  panel/src/components/Forms/Input/RadioInput.vue
  panel/src/components/Forms/Input/SelectInput.vue
  panel/src/components/Forms/Input/TagsInput.vue
  panel/src/components/Forms/Input/TogglesInput.vue
  panel/src/components/Sections/FieldsSection.vue
  panel/src/store/modules/content.js
  src/Blueprint/Collection.php
  src/Blueprint/Config.php
  src/Blueprint/Extension.php
  src/Blueprint/Factory.php
  src/Blueprint/Node.php
  src/Blueprint/NodeI18n.php
  src/Blueprint/NodeIcon.php
  src/Blueprint/NodeProperty.php
  src/Blueprint/NodeString.php
  src/Blueprint/NodeText.php
  src/Cms/Nest.php
  src/Cms/NestCollection.php
  src/Cms/NestObject.php
  src/Field/FieldOptions.php
  src/Form/Options.php
  src/Form/OptionsApi.php
  src/Form/OptionsQuery.php
  src/Option/Option.php
  src/Option/Options.php
  src/Option/OptionsApi.php
  src/Option/OptionsProvider.php
  src/Option/OptionsQuery.php
  tests/Blueprint/TestCase.php
  tests/Field/FieldOptionsTest.php
  tests/Field/TestCase.php
  tests/Form/Fields/StructureFieldTest.php
  tests/Form/Fields/TagsFieldTest.php
  tests/Option/OptionTest.php
  tests/Option/OptionsApiTest.php
  tests/Option/OptionsQueryTest.php
  tests/Option/OptionsTest.php
  tests/Option/fixtures/data.json
Labels: type: bug 🐛, type: refactoring :recycle:, critical: roadblock 🚧, needs: two-person review 🧑‍🤝‍🧑

#4661 New `$cache->enabled()` method
  src/Cache/ApcuCache.php
  src/Cache/Cache.php
  src/Cache/FileCache.php
  src/Cache/MemCached.php
  src/Cache/MemoryCache.php
  src/Cache/NullCache.php
  tests/Cache/ApcuCacheTest.php
  tests/Cache/CacheTest.php
  tests/Cache/FileCacheTest.php
  tests/Cache/MemCachedTest.php
  tests/Cache/MemoryCacheTest.php
  tests/Cache/NullCacheTest.php
Labels: type: feature 🎉, critical: roadblock 🚧

#4666 Fix creating emtpy nest collection
  src/Cms/Nest.php
  tests/Cms/Nests/NestTest.php
Labels: type: bug 🐛

#4667 Fix editing escaped tags text
  panel/src/components/Forms/Input/TagsInput.vue
  panel/src/helpers/string.escapeHTML.test.js
  panel/src/helpers/string.js
  panel/src/helpers/string.unescapeHTML.test.js
Labels: type: bug 🐛

#4657 Fix `A::append()` with non-associative arrays
  src/Toolkit/A.php
  tests/Toolkit/ATest.php
Labels: type: bug 🐛

#4654 FiberDialog: disabled submit btn while processing
  panel/src/components/Dialogs/Dialog.vue
  panel/src/components/Dialogs/FiberDialog.vue
  panel/src/components/Dialogs/FormDialog.vue
  panel/src/components/Dialogs/RemoveDialog.vue
  panel/src/components/Dialogs/TextDialog.vue
Labels: type: enhancement ✨

#4652 Enhancements for gallery block
  config/blocks/gallery/gallery.php
  config/blocks/gallery/gallery.yml
  panel/src/components/Forms/Blocks/Types/Gallery.vue
  phpunit.xml.dist
Labels: type: enhancement ✨

#4671 `Str::safeTemplate()`: Consistent fallback
  config/methods.php
  src/Cms/ModelWithContent.php
  src/Cms/User.php
  src/Toolkit/Str.php
  tests/Cms/Fields/FieldMethodsTest.php
  tests/Cms/Models/ModelWithContentTest.php
  tests/Toolkit/StrTest.php
Labels: type: enhancement ✨, type: refactoring :recycle:

#4678 URL field preview is better shown with ellipsis when it is long
  panel/src/components/Forms/Previews/UrlFieldPreview.vue
Labels: type: enhancement ✨

#4663 Call language routes that return `false` only once
  src/Cms/LanguageRoutes.php
  tests/Cms/Languages/LanguageRoutesTest.php
Labels: type: bug 🐛

#4680 ContentTranslation: `::exists()` for virtual pages
  src/Cms/ContentTranslation.php
  tests/Cms/Content/ContentTranslationTest.php
Labels: type: bug 🐛

#4640 New object field
  config/fields/object.php
  config/methods.php
  i18n/translations/en.json
  panel/src/components/Drawers/FormDrawer.vue
  panel/src/components/Forms/Field/ObjectField.vue
  panel/src/components/Forms/Field/StructureField.vue
  panel/src/components/Forms/Field/index.js
  panel/src/components/Forms/Fieldset.vue
  panel/src/components/Forms/Previews/ObjectFieldPreview.vue
  panel/src/components/Forms/Previews/UrlFieldPreview.vue
  panel/src/components/Forms/Previews/index.js
  panel/src/components/Layout/Table.vue
  panel/src/components/Layout/TableCell.vue
  panel/src/components/Sections/Sections.vue
  panel/src/helpers/field.js
  panel/src/helpers/index.js
  src/Cms/Core.php
  tests/Cms/Fields/FieldMethodsTest.php
  tests/Form/Fields/ObjectFieldTest.php
Labels: type: feature 🎉

#4684 Fix PHPUnit annotations
  tests/Field/FieldOptionsTest.php
  tests/Option/OptionTest.php
  tests/Option/OptionsApiTest.php
  tests/Option/OptionsQueryTest.php
  tests/Option/OptionsTest.php
Labels: type: tests 🧪

#4683 Fix changing template of home page
  src/Cms/PagePermissions.php
  tests/Cms/Pages/PagePermissionsTest.php
Labels: type: bug 🐛

#4668 `Database\Query`: Where with `AND`/`OR` as values
  src/Database/Query.php
  tests/Database/QueryTest.php
Labels: type: enhancement ✨

#4682 Consistent style for table row while dragging
  panel/src/components/Layout/Table.vue
Labels: type: enhancement ✨

#4689 Hide not saveable fields for object field
  panel/src/components/Forms/Field/ObjectField.vue
Labels: type: bug 🐛

#4697 Fix structure field index number
  panel/src/components/Forms/Field/StructureField.vue
Labels: type: regression 🚨

#4694 `Uuids::generate()`
  src/Uuid/Uuids.php
  tests/Uuid/UuidsTest.php
Labels: type: enhancement ✨

#4691 Fix panel favicon for dark mode
  src/Panel/Document.php
Labels: needs: discussion 🗣, type: enhancement ✨

#4700 Only set values for fields with defaults
  panel/src/components/Forms/Field/ObjectField.vue
Labels: type: bug 🐛

#4685 Fixes object field related console errors
  panel/src/components/Drawers/FormDrawer.vue
  panel/src/components/Forms/Input/MultiselectInput.vue
  panel/src/components/Forms/Input/TagsInput.vue
  panel/src/helpers/string.js
Labels: type: bug 🐛

#4712 UUID: fix changing page slug
  src/Cms/PageActions.php
Labels: type: bug 🐛

#4708 Fix code comment
  src/Uuid/Uuid.php
Labels: type: docs 📝

#4710 Fix `Uuid::is()`
  src/Uuid/Uuid.php
  tests/Uuid/UuidTest.php
Labels: type: bug 🐛

#4719 Remove `mixed` type hint
  src/Api/Api.php
  src/Api/Collection.php
  src/Api/Model.php
  src/Blueprint/Collection.php
  src/Blueprint/Factory.php
  src/Blueprint/Node.php
  src/Cache/ApcuCache.php
  src/Cache/Cache.php
  src/Cache/FileCache.php
  src/Cache/MemCached.php
  src/Cache/MemoryCache.php
  src/Cache/NullCache.php
  src/Cache/Value.php
  src/Cms/Api.php
  src/Cms/Helpers.php
  src/Cms/Nest.php
  src/Cms/Plugin.php
  src/Data/Data.php
  src/Data/Handler.php
  src/Data/Json.php
  src/Data/PHP.php
  src/Data/Txt.php
  src/Data/Xml.php
  src/Data/Yaml.php
  src/Filesystem/F.php
  src/Filesystem/IsFile.php
  src/Http/Environment.php
  src/Http/Remote.php
  src/Http/Request.php
  src/Http/Request/Data.php
  src/Http/Route.php
  src/Http/Router.php
  src/Http/Uri.php
  src/Http/Url.php
  src/Option/OptionsProvider.php
  src/Panel/Dialog.php
  src/Panel/Dropdown.php
  src/Panel/Json.php
  src/Panel/Panel.php
  src/Panel/Search.php
  src/Panel/View.php
  src/Text/KirbyTag.php
  src/Toolkit/A.php
Labels: needs: discussion 🗣, type: refactoring :recycle:

#4711 Fix `->findBy()` for UUID object
  src/Cms/Collection.php
  tests/Cms/Collections/CollectionTest.php
  tests/Uuid/HasUuidsTest.php
Labels: type: bug 🐛

#4729 Remove deprecated `$pages->findByIdRecursive()`
  src/Cms/Pages.php
Labels: type: refactoring :recycle:
