Repository getkirby/kirby, pull requests merged in 2022-11, with the labels that each got.

#4809 Use coalesce equal in more places
  config/api/models/System.php
  src/Cms/App.php
  src/Cms/AppPlugins.php
  src/Cms/AppUsers.php
  src/Cms/Collections.php
  src/Cms/Content.php
  src/Cms/Email.php
  src/Cms/File.php
  src/Cms/Page.php
  src/Cms/PageActions.php
  src/Cms/PageBlueprint.php
  src/Form/Form.php
  src/Http/Url.php
  src/Panel/Model.php
  src/Session/FileSessionStore.php
  src/Session/Sessions.php
  tests/Cms/App/AppTest.php
Labels: type: refactoring :recycle:

#4832 Fix duplicating UUIDs on duplicating pages
  src/Cms/PageActions.php
  tests/Cms/Pages/PageActionsTest.php
Labels: type: bug 🐛

#4525 PHP 8: clean up `Email` package
  src/Email/Body.php
  src/Email/Email.php
  src/Email/PHPMailer.php
Labels: type: refactoring :recycle:, needs: two-person review 🧑‍🤝‍🧑

#4818 Get rid of `$children` usage
  panel/src/components/Navigation/DropdownContent.vue
Labels: type: refactoring :recycle:

#4820 Vue: restructure app setup
  panel/src/components/Dialogs/index.js
  panel/src/components/Drawers/index.js
  panel/src/components/Forms/Blocks/index.js
  panel/src/components/Forms/Field/index.js
  panel/src/components/Forms/Input/index.js
  panel/src/components/Forms/Previews/index.js
  panel/src/components/Forms/index.js
  panel/src/components/Layout/index.js
  panel/src/components/Misc/index.js
  panel/src/components/Navigation/index.js
  panel/src/components/Sections/index.js
  panel/src/components/Views/index.js
  panel/src/components/index.js
  panel/src/config/components.js
  panel/src/index.js
Labels: type: refactoring :recycle:

#4811 More unnecessary else statements
  config/api/routes/auth.php
  src/Cms/App.php
  src/Cms/FileActions.php
  src/Cms/FileBlueprint.php
  src/Cms/FilePicker.php
  src/Cms/Media.php
  src/Http/Request/Body.php
  src/Http/Request/Query.php
  src/Option/Options.php
  src/Panel/Model.php
  src/Panel/Panel.php
  src/Session/AutoSession.php
  src/Toolkit/A.php
  src/Toolkit/Collection.php
  src/Toolkit/I18n.php
  src/Toolkit/Obj.php
  src/Toolkit/Pagination.php
Labels: type: refactoring :recycle:, needs: decision 🗳

#4850 More replace class name strings
  src/Cms/Block.php
  src/Cms/Blocks.php
  src/Cms/Fieldset.php
  src/Cms/Fieldsets.php
  src/Cms/Item.php
  src/Cms/Items.php
  src/Cms/Layout.php
  src/Cms/LayoutColumn.php
  src/Cms/LayoutColumns.php
  src/Cms/Layouts.php
  tests/Api/CollectionTest.php
  tests/Cms/Fields/FieldMethodsTest.php
  tests/Cms/Fieldsets/FieldsetTest.php
  tests/Cms/Media/MediaTest.php
  tests/Cms/Pages/PageRulesTest.php
  tests/Cms/Roles/RolesTest.php
  tests/Database/DatabaseTest.php
  tests/Filesystem/AssetTest.php
  tests/Filesystem/FileTest.php
  tests/Filesystem/IsFileTest.php
  tests/Panel/DocumentTest.php
  tests/Panel/ViewTest.php
Labels: type: refactoring :recycle:

#4847 Stats section `info` prop can be translated
  config/sections/stats.php
  tests/Cms/Sections/StatsSectionTest.php
Labels: type: enhancement ✨

#4849 Fix sanitize options when no options for a value
  config/fields/mixins/options.php
  tests/Form/Fields/MultiselectFieldTest.php
Labels: type: bug 🐛

#4854 `Query`: add support for optional chaining and simple comparisons
  src/Query/Argument.php
  src/Query/Arguments.php
  src/Query/Expression.php
  src/Query/Query.php
  src/Query/Segment.php
  src/Query/Segments.php
  tests/Query/ArgumentTest.php
  tests/Query/ExpressionTest.php
  tests/Query/QueryTest.php
  tests/Query/SegmentTest.php
  tests/Query/SegmentsTest.php
Labels: type: feature 🎉

#4822 Remove `v-model`
  panel/src/components/Dialogs/FilesDialog.vue
  panel/src/components/Dialogs/PagesDialog.vue
  panel/src/components/Dialogs/UsersDialog.vue
  panel/src/components/Forms/Calendar.vue
  panel/src/components/Forms/Counter.vue
  panel/src/components/Forms/Field/DateField.vue
  panel/src/components/Forms/Field/EmailField.vue
  panel/src/components/Forms/Field/FilesField.vue
  panel/src/components/Forms/Field/NumberField.vue
  panel/src/components/Forms/Field/RangeField.vue
  panel/src/components/Forms/Field/SlugField.vue
  panel/src/components/Forms/Field/StructureField.vue
  panel/src/components/Forms/Field/TelField.vue
  panel/src/components/Forms/Field/TextField.vue
  panel/src/components/Forms/Field/TextareaField.vue
  panel/src/components/Forms/Field/TimeField.vue
  panel/src/components/Forms/Field/ToggleField.vue
  panel/src/components/Forms/Field/UrlField.vue
  panel/src/components/Forms/Fieldset.vue
  panel/src/components/Forms/Form.vue
  panel/src/components/Forms/Input/CheckboxInput.vue
  panel/src/components/Forms/Input/DateInput.vue
  panel/src/components/Forms/Input/EmailInput.vue
  panel/src/components/Forms/Input/MultiselectInput.vue
  panel/src/components/Forms/Input/NumberInput.vue
  panel/src/components/Forms/Input/PasswordInput.vue
  panel/src/components/Forms/Input/RangeInput.vue
  panel/src/components/Forms/Input/SlugInput.vue
  panel/src/components/Forms/Input/TagsInput.vue
  panel/src/components/Forms/Input/TelInput.vue
  panel/src/components/Forms/Input/TextInput.vue
  panel/src/components/Forms/Input/TextareaInput.vue
  panel/src/components/Forms/Input/TimeInput.vue
  panel/src/components/Forms/Input/ToggleInput.vue
  panel/src/components/Forms/Input/UrlInput.vue
  panel/src/components/Forms/Login.vue
  panel/src/components/Forms/LoginCode.vue
  panel/src/components/Forms/Toolbar/EmailDialog.vue
  panel/src/components/Forms/Toolbar/LinkDialog.vue
  panel/src/components/Forms/Writer/Dialogs/EmailDialog.vue
  panel/src/components/Forms/Writer/Dialogs/LinkDialog.vue
  panel/src/components/Navigation/Search.vue
  panel/src/components/Sections/ModelsSection.vue
  panel/src/components/Views/InstallationView.vue
  panel/src/components/Views/ResetPasswordView.vue
Labels: type: refactoring :recycle:

#4862 New hook: `page.render:before|after`
  src/Cms/Page.php
  tests/Cms/Pages/PageTest.php
  tests/Cms/Pages/fixtures/PageRenderHookTest/bar.php
  tests/Cms/Pages/fixtures/PageRenderHookTest/foo.php
Labels: type: feature 🎉

#4861 New hooks: `language.*:before|after`
  src/Cms/Language.php
  tests/Cms/Languages/LanguageTest.php
Labels: type: feature 🎉

#4871 Fixes duplicating UUIDs for children and its files
  src/Cms/PageActions.php
  tests/Cms/Pages/PageActionsTest.php
Labels: type: bug 🐛

#4868 Allow UUID v4 mode for generated UUIDs
  src/Uuid/Uuid.php
  tests/Uuid/UuidTest.php
Labels: type: feature 🎉
