Repository getkirby/kirby, pull requests merged in 2022-08, with the labels that each got.

#4542 Fix `subpages` option for pages field
  panel/src/components/Dialogs/PagesDialog.vue
Labels: type: regression 🚨

#4540 Keep `$page->childrenAndDrafts()` updated
  src/Cms/HasChildren.php
  src/Cms/PageActions.php
  tests/Cms/Pages/PageActionsTest.php
Labels: type: bug 🐛

#4496 Panel: decrease loading spinner opacity
  panel/src/components/Navigation/Breadcrumb.vue
Labels: type: enhancement ✨

#4535 Prepare default caches
  src/Cms/AppCaches.php
  src/Cms/Core.php
Labels: type: enhancement ✨, type: refactoring :recycle:

#4515 More deprecated codes
  config/components.php
  config/presets/files.php
  config/presets/page.php
  config/presets/pages.php
  config/sections/info.php
  config/sections/mixins/headline.php
  src/Cms/App.php
  src/Cms/Blueprint.php
  src/Cms/Helpers.php
  src/Data/Yaml.php
  tests/Cms/App/AppComponentsTest.php
  tests/Cms/Blueprints/BlueprintPresetsTest.php
  tests/Cms/Blueprints/BlueprintTest.php
  tests/Cms/CoreTest.php
  tests/Cms/Sections/FilesSectionTest.php
  tests/Cms/Sections/InfoSectionTest.php
  tests/Cms/Sections/PagesSectionTest.php
  tests/Cms/Sections/StatsSectionTest.php
Labels: type: refactoring :recycle:

#4551 PHP 8: clean up `Parsley` package
  src/Parsley/Element.php
  src/Parsley/Inline.php
  src/Parsley/Parsley.php
  src/Parsley/Schema.php
  src/Parsley/Schema/Blocks.php
  src/Parsley/Schema/Plain.php
  tests/Parsley/ParsleyTest.php
  tests/Parsley/Schema/BlocksTest.php
  tests/Parsley/Schema/PlainTest.php
Labels: type: refactoring :recycle:

#4548 PHP 8: clean up `Cache` package
  src/Cache/ApcuCache.php
  src/Cache/Cache.php
  src/Cache/FileCache.php
  src/Cache/MemCached.php
  src/Cache/MemoryCache.php
  src/Cache/NullCache.php
  src/Cache/Value.php
Labels: type: refactoring :recycle:

#4556 Detect `@` alias for IDEs
  panel/jsconfig.json
Labels: type: refactoring :recycle:

#4567 Apply toggles field preview as bubbles
  panel/src/components/Forms/Previews/index.js
Labels: type: enhancement ✨

#4504 First steps code splitting with Vite 3
  panel/dist/js/index.js
  panel/dist/js/vendor.js
  panel/dist/js/vuedraggable.js
  panel/package-lock.json
  panel/package.json
  panel/src/components/Misc/Draggable.vue
Labels: type: enhancement ✨

#4562 docs: fix misleading typos
  panel/src/components/Layout/View.vue
  panel/src/components/Misc/Text.vue
  panel/src/components/Navigation/Pagination.vue
Labels: type: bug 🐛

#4568 Update node dependencies
  panel/package-lock.json
  panel/package.json
Labels: type: enhancement ✨

#4553 Sane\Xml: Allow any domain in basic XML files
  src/Sane/DomHandler.php
  src/Sane/Html.php
  src/Sane/Svg.php
  tests/Sane/XmlTest.php
  tests/Sane/fixtures/xml/allowed/gpx.xml
  tests/Sane/fixtures/xml/sanitized/external-source-1.xml
  tests/Sane/fixtures/xml/sanitized/external-source-1_disallowed.xml
  tests/Sane/fixtures/xml/sanitized/external-source-2.xml
  tests/Sane/fixtures/xml/sanitized/external-source-2_disallowed.xml
Labels: type: bug 🐛

#4561 Some Psalm fixes after refactoring
  src/Cache/Cache.php
  src/Cache/FileCache.php
  src/Cache/Value.php
  src/Cms/App.php
  src/Data/Data.php
  src/Data/PHP.php
  src/Data/Txt.php
  src/Data/Yaml.php
  src/Image/Exif.php
  src/Image/Image.php
  src/Text/KirbyTag.php
  src/Toolkit/Str.php
  tests/Image/ImageTest.php
Labels: type: refactoring :recycle:

#4547 PHP 8: clean up `Api` package
  src/Api/Api.php
  src/Api/Collection.php
  src/Api/Model.php
  src/Cms/Api.php
  src/Cms/App.php
Labels: type: refactoring :recycle:

#4572 Set default locale for intl extension from config
  src/Toolkit/Locale.php
  tests/Toolkit/LocaleTest.php
Labels: type: bug 🐛

#4511 Fix double slashes in asset URLs with base URL `/`
  src/Filesystem/Asset.php
  src/Panel/Document.php
  tests/Filesystem/AssetTest.php
  tests/Panel/ModelTest.php
Labels: type: bug 🐛

#4541 Allow panel plugins to load index.dev.mjs instead of index.js (needed by kirbyup)
  src/Filesystem/Mime.php
  src/Panel/Document.php
  src/Panel/Plugins.php
  tests/Filesystem/MimeTest.php
  tests/Panel/PluginsTest.php
  views/panel.php
Labels: type: feature 🎉

#4575 `Http\Uri`: definable schemes
  src/Http/Uri.php
Labels: type: refactoring :recycle:

#4573 PHP8: Clean up `Sane` package
  src/Sane/DomHandler.php
  src/Sane/Handler.php
  src/Sane/Html.php
  src/Sane/Sane.php
  src/Sane/Svg.php
  src/Sane/Svgz.php
  src/Sane/Xml.php
Labels: type: refactoring :recycle:

#4528 PHP 8: clean up `Http` package
  src/Cms/App.php
  src/Cms/Response.php
  src/Cms/Url.php
  src/Http/Cookie.php
  src/Http/Environment.php
  src/Http/Header.php
  src/Http/Idn.php
  src/Http/Params.php
  src/Http/Path.php
  src/Http/Query.php
  src/Http/Remote.php
  src/Http/Request.php
  src/Http/Request/Auth.php
  src/Http/Request/Auth/BasicAuth.php
  src/Http/Request/Auth/BearerAuth.php
  src/Http/Request/Auth/SessionAuth.php
  src/Http/Request/Body.php
  src/Http/Request/Data.php
  src/Http/Request/Files.php
  src/Http/Request/Query.php
  src/Http/Response.php
  src/Http/Route.php
  src/Http/Router.php
  src/Http/Uri.php
  src/Http/Url.php
  src/Http/Visitor.php
Labels: type: refactoring :recycle:

#4578 Re-enable frontend coding style checks in CI
  .github/workflows/frontend.yml
  panel/src/components/Dialogs/FormDialog.vue
  panel/src/components/Dialogs/TextDialog.vue
  panel/src/components/Forms/Field.vue
  panel/src/components/Forms/Field/HeadlineField.vue
  panel/src/components/Forms/Field/InfoField.vue
  panel/src/components/Forms/Field/TogglesField.vue
  panel/src/components/Forms/FormButtons.vue
  panel/src/components/Forms/Input/MultiselectInput.vue
  panel/src/components/Forms/Input/TogglesInput.vue
  panel/src/components/Forms/Previews/ArrayFieldPreview.vue
  panel/src/components/Forms/Previews/BubblesFieldPreview.vue
  panel/src/components/Forms/Previews/DateFieldPreview.vue
  panel/src/components/Forms/Previews/FilesFieldPreview.vue
  panel/src/components/Forms/Previews/HtmlFieldPreview.vue
  panel/src/components/Forms/Previews/ImageFieldPreview.vue
  panel/src/components/Forms/Previews/PagesFieldPreview.vue
  panel/src/components/Forms/Previews/TimeFieldPreview.vue
  panel/src/components/Forms/Previews/UsersFieldPreview.vue
  panel/src/components/Layout/Box.vue
  panel/src/components/Layout/Collection.vue
  panel/src/components/Layout/Overlay.vue
  panel/src/components/Layout/TableCell.vue
  panel/src/components/Misc/Text.vue
  panel/src/components/Sections/InfoSection.vue
  panel/src/components/Views/SystemView.vue
Labels: type: refactoring :recycle:

#4555 Extendable text block field input
  panel/src/components/Forms/Blocks/Types/Text.vue
Labels: type: enhancement ✨

#4569 New `F::unlink()` safest method
  src/Cms/Helpers.php
  src/Filesystem/Dir.php
  src/Filesystem/F.php
  src/Session/FileSessionStore.php
  tests/Cms/Helpers/HelpersTest.php
  tests/Filesystem/FTest.php
Labels: type: feature 🎉, type: bug 🐛

#4582 Ease deprecation of `headline` option
  config/presets/files.php
  config/sections/mixins/headline.php
Labels: type: enhancement ✨

#4588 Fix unreliable unit tests
  tests/Cms/Blueprints/BlueprintTest.php
  tests/Toolkit/StrTest.php
Labels: type: tests 🧪

#4594 Fix `k-text` with HTML #4587
  panel/src/components/Misc/Text.vue
Labels: type: bug 🐛

#4593 Fix `F::remove()` with non-existing files
  src/Filesystem/F.php
  tests/Filesystem/FTest.php
Labels: type: regression 🚨

#4580 Support for `config/env.php`
  src/Cms/App.php
  tests/Cms/App/AppTest.php
  tests/Cms/App/fixtures/AppTest/options-env1/config.10.1.2.3.php
  tests/Cms/App/fixtures/AppTest/options-env1/config.getkirby.com.php
  tests/Cms/App/fixtures/AppTest/options-env1/config.php
  tests/Cms/App/fixtures/AppTest/options-env1/config.trykirby.com.php
  tests/Cms/App/fixtures/AppTest/options-env1/env.php
  tests/Cms/App/fixtures/AppTest/options-env2/config.10.1.2.3.php
  tests/Cms/App/fixtures/AppTest/options-env2/config.getkirby.com.php
  tests/Cms/App/fixtures/AppTest/options-env2/config.php
  tests/Cms/App/fixtures/AppTest/options-env2/config.trykirby.com.php
  tests/Cms/App/fixtures/AppTest/options-env2/env.php
  tests/Cms/App/fixtures/AppTest/options/config.10.1.2.3.php
Labels: type: feature 🎉

#4604 Remove url field pattern prop (without function)
  config/fields/url.php
Labels: type: docs 📝

#4607 Database\Query: Use strict mode for in_array check
  src/Database/Query.php
  tests/Database/QueryTest.php
Labels: type: bug 🐛

#4606 Disable CI Codecov reporting in fork runs
  .github/workflows/backend.yml
  .github/workflows/frontend.yml
Labels: type: tests 🧪

#4596 Add `playsinline` attribute for videos if `autoplay` is set
  config/tags.php
  tests/Text/KirbyTagsTest.php
Labels: type: enhancement ✨

#4610 Some small psalm fixes
  config/helpers.php
  src/Api/Api.php
  src/Cms/App.php
  src/Text/KirbyTag.php
  src/Toolkit/I18n.php
  src/Toolkit/Str.php
Labels: type: refactoring :recycle:

#4608 Upgrade dependencies
  .github/workflows/backend.yml
  bootstrap.php
  composer.json
  composer.lock
  config/components.php
  config/fields/structure.php
  config/fields/tags.php
  config/presets/pages.php
  config/routes.php
  config/tags.php
  panel/package-lock.json
  panel/package.json
  src/Cache/FileCache.php
  src/Cms/App.php
  src/Cms/Blueprint.php
  src/Cms/Email.php
  src/Cms/FileActions.php
  src/Cms/LanguageRouter.php
  src/Cms/LanguageRoutes.php
  src/Cms/Media.php
  src/Cms/ModelWithContent.php
  src/Cms/PageActions.php
  src/Cms/PageBlueprint.php
  src/Cms/User.php
  src/Database/Database.php
  src/Database/Query.php
  src/Database/Sql.php
  src/Filesystem/Dir.php
  src/Form/Form.php
  src/Panel/Panel.php
  src/Panel/View.php
  src/Toolkit/A.php
  src/Toolkit/Collection.php
  src/Toolkit/Html.php
  src/Toolkit/Pagination.php
  src/Toolkit/Properties.php
  src/Toolkit/Str.php
  tests/Cms/Api/ApiTest.php
  tests/Cms/App/AppPluginsTest.php
  tests/Cms/Permissions/PermissionsTest.php
  tests/Cms/Sections/PagesSectionTest.php
  tests/Form/Fields/InfoFieldTest.php
  tests/Toolkit/ATest.php
  vendor/claviska/simpleimage/src/claviska/SimpleImage.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_static.php
  vendor/composer/installed.json
  vendor/composer/installed.php
  vendor/phpmailer/phpmailer/language/phpmailer.lang-el.php
  vendor/phpmailer/phpmailer/src/PHPMailer.php
  vendor/phpmailer/phpmailer/src/POP3.php
  vendor/phpmailer/phpmailer/src/SMTP.php
Labels: type: enhancement ✨

#4577 Throw user back to login page on challenge expiry
  panel/src/components/Forms/Login.vue
  panel/src/components/Forms/LoginCode.vue
  panel/src/components/Views/LoginView.vue
  src/Cms/Auth.php
  tests/Cms/Auth/AuthChallengeTest.php
Labels: type: enhancement ✨

#4614 Fix API ping
  config/api/routes/auth.php
  panel/src/api/auth.js
  panel/src/api/request.js
  panel/src/config/api.js
Labels: type: bug 🐛

#4611 Fix error messages for field methods
  config/methods.php
  tests/Cms/Fields/FieldMethodsTest.php
Labels: type: refactoring :recycle:
