Repository getkirby/kirby, pull requests merged in 2022-06, with the labels that each got.

#4329 Upgrade Node dependencies
  panel/package-lock.json
  panel/package.json
  panel/src/components/Misc/Progress.test.js
  panel/src/components/Misc/Text.test.js
Labels: type: enhancement ✨

#2945 Handle content case-insensitively
  src/Cms/Content.php
  src/Cms/ContentTranslation.php
  src/Cms/ModelWithContent.php
  tests/Cms/Content/ContentTest.php
  tests/Cms/Pages/PageTranslationsTest.php
  tests/Data/TxtTest.php
Labels: type: bug 🐛, type: refactoring :recycle:

#4326 Remove blocks field migrations: editor and builder
  src/Cms/Block.php
  src/Cms/BlockConverter.php
  src/Cms/Blocks.php
  tests/Cms/Blocks/BlocksTest.php
  tests/Cms/Blocks/EditorImportTest.php
Labels: type: refactoring :recycle:

#4339 New `Str::afterStart()` and `beforeEnd()` methods
  src/Toolkit/Str.php
  tests/Toolkit/StrTest.php
Labels: type: feature 🎉

#4336 Fix file permissions of non-executable files
  panel/dist/img/icons.svg
  panel/public/img/icons.svg
  panel/src/components/Forms/Writer/Marks/Email.js
  tests/Sane/fixtures/svg/allowed/icons/github.svg
Labels: type: refactoring :recycle:

#4334 Disable failing JS unit tests
  panel/src/components/Navigation/PrevNext.test.js
  panel/src/components/Navigation/__snapshots__/PrevNext.test.js.snap
  panel/src/fiber/index.test.tmp
Labels: type: tests 🧪

#4332 Use `search.results.none` for section search
  i18n/translations/en.json
  panel/src/components/Sections/FilesSection.vue
  panel/src/components/Sections/ModelsSection.vue
Labels: type: i18n 🌏

#4340 Add new public static method `increment` for `Str` class
  src/Toolkit/Str.php
  tests/Toolkit/StrTest.php
Labels: type: feature 🎉

#4341 Add new public static method `wrap` for `Str` class and new `json` validator or `V` class
  src/Toolkit/Str.php
  src/Toolkit/V.php
  tests/Toolkit/StrTest.php
  tests/Toolkit/VTest.php
Labels: type: feature 🎉

#4285 New Environment class
  config/areas/system/views.php
  config/components.php
  src/Cms/App.php
  src/Cms/AppErrors.php
  src/Cms/Environment.php
  src/Cms/System.php
  src/Http/Environment.php
  src/Http/Request.php
  src/Http/Server.php
  src/Http/Uri.php
  src/Toolkit/Str.php
  tests/Cms/Api/routes/SystemRoutesTest.php
  tests/Cms/App/AppErrorsTest.php
  tests/Cms/App/AppTest.php
  tests/Cms/Collections/PaginationTest.php
  tests/Cms/Environment/EnvironmentTest.php
  tests/Cms/Helpers/HelperFunctionsTest.php
  tests/Cms/Helpers/HelpersTest.php
  tests/Cms/Ingredients/UrlsTest.php
  tests/Cms/System/SystemTest.php
  tests/Http/EnvironmentTest.php
  tests/Http/PathTest.php
  tests/Http/RequestTest.php
  tests/Http/ServerTest.php
  tests/Http/UriTest.php
  tests/Http/UrlTest.php
  tests/Http/fixtures/EnvironmentTest/config.127.0.0.1.php
  tests/Http/fixtures/EnvironmentTest/config.example.com.php
Labels: type: bug 🐛, type: refactoring :recycle:

#4335 Make `@todo` changes for 3.7.0
  config/api/models/File.php
  config/api/models/Page.php
  config/api/routes/lock.php
  config/api/routes/pages.php
  config/api/routes/site.php
  config/components.php
  config/helpers.php
  config/sections/mixins/headline.php
  panel/src/api/index.js
  src/Cms/App.php
  src/Cms/AppTranslations.php
  src/Cms/Block.php
  src/Cms/File.php
  src/Cms/ModelWithContent.php
  src/Cms/Page.php
  src/Cms/Permissions.php
  src/Cms/Site.php
  src/Cms/User.php
  src/Http/Environment.php
  src/Http/Uri.php
  src/Http/Url.php
  src/Panel/Document.php
  src/Toolkit/I18n.php
  src/Toolkit/Str.php
  src/Toolkit/Xml.php
  tests/Cms/Files/FileRulesTest.php
  tests/Cms/Permissions/PermissionsTest.php
  tests/Toolkit/StrTest.php
  tests/Toolkit/XmlTest.php
Labels: type: refactoring :recycle:

#4356 Fix Environment::sanitzeHost for multibyte
  src/Http/Environment.php
Labels: type: bug 🐛

#4352 Replace `$_SERVER` with new `Environment` class in the core
  src/Api/Api.php
  src/Cms/AppErrors.php
  src/Exception/Exception.php
  src/Http/Environment.php
  src/Http/Header.php
  src/Http/Request.php
  src/Http/Url.php
  src/Http/Visitor.php
  tests/Cms/Api/ApiTest.php
  tests/Cms/App/AppErrorsTest.php
  tests/Cms/Auth/AuthTest.php
  tests/Exception/ExceptionTest.php
  tests/Http/EnvironmentTest.php
  tests/Http/RequestTest.php
  tests/Session/AutoSessionTest.php
  tests/Session/SessionsTest.php
Labels: type: enhancement ✨, type: refactoring :recycle:

#4348 Fix `File::previewUrl` on custom `file::url` component
  src/Cms/AppPlugins.php
  src/Cms/File.php
  tests/Cms/Files/FileTest.php
Labels: type: regression 🚨

#4328 `layout: table` for pages and files sections
  config/sections/files.php
  config/sections/mixins/details.php
  config/sections/mixins/layout.php
  config/sections/mixins/pagination.php
  config/sections/mixins/sort.php
  config/sections/pages.php
  panel/src/components/Forms/Previews/BubblesFieldPreview.vue
  panel/src/components/Forms/Previews/DateFieldPreview.vue
  panel/src/components/Forms/Previews/FlagFieldPreview.vue
  panel/src/components/Forms/Previews/ImageFieldPreview.vue
  panel/src/components/Forms/Previews/TextFieldPreview.vue
  panel/src/components/Forms/Previews/index.js
  panel/src/components/Layout/Collection.vue
  panel/src/components/Layout/Empty.vue
  panel/src/components/Layout/Items.vue
  panel/src/components/Layout/Table.vue
  panel/src/components/Sections/ModelsSection.vue
  src/Cms/Core.php
  src/Cms/ModelWithContent.php
  tests/Cms/Sections/FilesSectionTest.php
  tests/Cms/Sections/PagesSectionTest.php
  tests/Cms/Sections/mixins/LayoutMixinTest.php
  tests/Cms/Sections/mixins/SortMixinTest.php
Labels: type: feature 🎉

#4347 Fix pasting on list block
  panel/src/components/Forms/Writer/Editor.js
  panel/src/components/Forms/Writer/Writer.vue
Labels: type: regression 🚨

#4277 Fine-tuned cache handling based on request data
  src/Cms/App.php
  src/Cms/Page.php
  src/Cms/Responder.php
  src/Http/Cookie.php
  src/Http/Request.php
  src/Panel/Panel.php
  tests/Cms/App/AppTest.php
  tests/Cms/Pages/PageCacheTest.php
  tests/Cms/Pages/fixtures/PageCacheTest/default.php
  tests/Cms/Pages/fixtures/PageCacheTest/disabled.php
  tests/Cms/Pages/fixtures/PageCacheTest/dynamic.php
  tests/Cms/Pages/fixtures/PageCacheTest/expiry.php
  tests/Cms/ResponderTest.php
  tests/Http/CookieTest.php
  tests/Http/RequestTest.php
Labels: type: enhancement ✨, type: feature 🎉, type: bug 🐛

#4357 `Pages`: Consistent find behavior for non-children
  src/Cms/Files.php
  src/Cms/Pages.php
  src/Cms/Users.php
  tests/Cms/Pages/PagesTest.php
Labels: type: enhancement ✨, type: bug 🐛

#4360 GitHub CI workflow updates
  .github/workflows/backend.yml
  .github/workflows/frontend.yml
  .github/workflows/integration.yml
  tests/Cms/Pages/PageCacheTest.php
  tests/Cms/ResponderTest.php
  tests/Cms/Sections/PagesSectionTest.php
Labels: type: refactoring :recycle:

#4375 Don't throw deprecation notice for `kirbytextinline()` and `kti()` helpers
  config/helpers.php
Labels: type: regression 🚨

#4385 Fix centering of flag in table layout #4377
  panel/src/components/Forms/Previews/FlagFieldPreview.vue
Labels: type: bug 🐛

#4382 Sections: change `query` to `searchterm`
  config/sections/files.php
  config/sections/mixins/search.php
  config/sections/pages.php
  panel/src/components/Sections/ModelsSection.vue
  tests/Cms/Sections/FilesSectionTest.php
  tests/Cms/Sections/PagesSectionTest.php
Labels: type: regression 🚨

#4390 Fix `columns` prop type when empty (array)
  panel/src/components/Layout/Collection.vue
  panel/src/components/Layout/Items.vue
  panel/src/components/Sections/ModelsSection.vue
Labels: type: bug 🐛

#4396 Fix deprecation warning for `$app->markdown()`
  config/components.php
  src/Cms/App.php
Labels: type: regression 🚨

#4395 Fix structure field actions
  panel/src/components/Forms/Field/StructureField.vue
  panel/src/components/Layout/Table.vue
  panel/src/components/Navigation/OptionsDropdown.vue
Labels: type: regression 🚨

#4404 Make sure that block content is always an array
  src/Cms/Block.php
  tests/Cms/Blocks/BlockTest.php
Labels: type: refactoring :recycle:, type: regression 🚨

#4399 Fix broken params in URLs
  src/Cms/App.php
  src/Cms/Core.php
  src/Http/Environment.php
  src/Http/Request.php
  src/Http/Uri.php
  src/Panel/View.php
  tests/Cms/App/AppTest.php
  tests/Http/EnvironmentTest.php
  tests/Http/RequestTest.php
  tests/Http/ServerTest.php
  tests/Panel/ViewTest.php
Labels: type: bug 🐛, type: refactoring :recycle:

#4411 Reverts info field height
  panel/src/components/Layout/Box.vue
Labels: type: regression 🚨

#4414 Fix `<figure>` tag `$before` param in image block
  config/blocks/image/image.php
Labels: type: regression 🚨

#4424 Fix cursor on structure field header
  panel/src/components/Forms/Field/StructureField.vue
Labels: type: bug 🐛

#4426 Fix saving content on paginate for structure field
  panel/src/components/Forms/Field/StructureField.vue
Labels: type: regression 🚨

#4429 Better in-code docs for responder use tracking
  src/Http/Cookie.php
  src/Http/Request.php
Labels: type: refactoring :recycle:

#4418 Stale bot for issues
  .github/stale.yml
Labels: type: refactoring :recycle:

#4433 Added boolean type to available columnTypes for createColumn
  src/Database/Sql.php
  src/Database/Sql/Sqlite.php
Labels: type: feature 🎉
