Repository getkirby/kirby, pull requests merged in 2022-12, with the labels that each got.

#4885 PHP 8.2 prep: deprecated dynamic properties
  src/Text/KirbyTag.php
  src/Toolkit/Component.php
  tests/Cms/Blocks/BlockTest.php
  tests/Cms/Blocks/BlocksTest.php
  tests/Cms/Items/ItemTest.php
  tests/Cms/Items/ItemsTest.php
  tests/Cms/Sections/StatsSectionTest.php
  tests/Filesystem/FTest.php
  tests/Uuid/TestCase.php
Labels: type: refactoring :recycle:

#4886 Upgrade dependencies
  .github/workflows/backend.yml
  .github/workflows/frontend.yml
  .github/workflows/integration.yml
  bootstrap.php
  composer.json
  composer.lock
  panel/package-lock.json
  panel/package.json
  src/Toolkit/Iterator.php
  vendor/autoload.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_static.php
  vendor/composer/installed.json
  vendor/composer/installed.php
  vendor/filp/whoops/src/Whoops/Resources/css/prism.css
  vendor/filp/whoops/src/Whoops/Resources/js/prism.js
Labels: type: refactoring :recycle:

#4884 Fix extending existent Vue components
  panel/src/components/Forms/Blocks/index.js
  panel/src/config/plugins.js
  panel/src/index.js
Labels: type: regression 🚨

#4883 Vue: fix various model/input/state issues
  panel/src/components/Dialogs/FormDialog.vue
  panel/src/components/Forms/Field/DateField.vue
  panel/src/components/Forms/Field/StructureField.vue
  panel/src/components/Forms/Form.vue
Labels: type: regression 🚨

#4895 Fix file UUIDs when duplicating within subpages
  src/Cms/PageActions.php
Labels: type: bug 🐛

#4889 PHP 8.2 prep: fix partial callables
  dependencies/parsedown-extra/ParsedownExtra.php
  src/Toolkit/Query.php
Labels: type: refactoring :recycle:

#4892 File picker: name for `id` when parent model
  src/Panel/File.php
  tests/Form/Fields/FilesFieldTest.php
  tests/Form/Fields/Mixins/FilePickerMixinTest.php
  tests/Panel/FileTest.php
Labels: type: regression 🚨

#4882 Fix email field’s redundant `mailto`
  panel/src/components/Navigation/Link.vue
Labels: type: bug 🐛

#4918 Fix Dom issues in CI
  src/Toolkit/Dom.php
  tests/Toolkit/DomTest.php
Labels: critical: roadblock 🚧, needs: two-person review 🧑‍🤝‍🧑

#4911 Case-sensitive `Xml::attr()`
  src/Toolkit/Html.php
  src/Toolkit/Xml.php
  tests/Toolkit/XmlTest.php
Labels: type: bug 🐛

#4921 `Dimensions::forSvg`: support for percentages
  src/Image/Dimensions.php
  tests/Image/DimensionsTest.php
  tests/Image/fixtures/dimensions/circle-abs.svg
  tests/Image/fixtures/dimensions/circle-offset.svg
Labels: type: enhancement ✨

#4917 Fix checkboxes and radio input focus when no options
  panel/src/components/Forms/Input/CheckboxesInput.vue
  panel/src/components/Forms/Input/RadioInput.vue
Labels: type: bug 🐛

#4901 Fix optional chaining on non-null segment
  src/Query/Segments.php
  tests/Query/SegmentsTest.php
Labels: type: bug 🐛

#4915 Automatic `alt` text for assets, file versions
  src/Image/Image.php
  tests/Image/ImageTest.php
Labels: type: enhancement ✨

#4920 Fix resolving paths with trailing dot
  src/Cms/App.php
  tests/Cms/App/AppResolveTest.php
Labels: type: bug 🐛

#4919 DELETE `lock`: fail gracefully if already deleted
  config/api/routes/lock.php
Labels: type: bug 🐛

#4929 `Fieldset.vue`: fix error for missing field type
  i18n/translations/en.json
  panel/src/components/Forms/Fieldset.vue
  src/Form/Field.php
  tests/Form/FormTest.php
Labels: type: bug 🐛

#4928 Pages section: add current label to status flag
  panel/src/components/Sections/PagesSection.vue
Labels: type: enhancement ✨

#4905 Fix `->words()` field method
  config/methods.php
  tests/Cms/Fields/FieldMethodsTest.php
Labels: type: bug 🐛

#4935 `Xml::attr()`: support simple values
  src/Toolkit/Xml.php
  tests/Toolkit/HtmlTest.php
  tests/Toolkit/XmlTest.php
Labels: type: enhancement ✨

#4930 Register dialog: info field for domain, warning for local domain
  config/api/models/System.php
  config/areas/system/dialogs.php
  i18n/translations/en.json
  src/Cms/AppCaches.php
  src/Cms/ContentTranslation.php
  src/Cms/System.php
  src/Cms/User.php
  src/Data/Data.php
  src/Field/FieldOptions.php
  src/Image/Exif.php
  src/Panel/File.php
  src/Panel/Page.php
  src/Query/Arguments.php
  src/Sane/Sane.php
  src/Toolkit/Collection.php
  src/Toolkit/I18n.php
  src/Toolkit/V.php
  tests/Cms/System/SystemTest.php
Labels: type: enhancement ✨

#4926 `Toolkit\Locale`: code improvements
  src/Toolkit/Locale.php
  tests/Toolkit/LocaleTest.php
Labels: type: refactoring :recycle:

#4925 `Toolkit\Escape`: code + tests improvements
  src/Toolkit/Escape.php
  tests/Toolkit/EscapeTest.php
Labels: type: refactoring :recycle:

#4923 `Toolkit\Obj`: code + tests improvements
  src/Toolkit/Obj.php
  tests/Toolkit/ObjTest.php
Labels: type: refactoring :recycle:

#4912 Upgrade to vite 4
  panel/package-lock.json
  panel/package.json
Labels: type: refactoring :recycle:

#4888 PHP 8.2 prep: Fix dynamic properties in search component
  config/components.php
Labels: type: refactoring :recycle:

#4887 PHP 8.2 prep: Parsedown - fix `mb_convert_encoding` deprecation
  dependencies/parsedown-extra/ParsedownExtra.php
Labels: type: refactoring :recycle:

#4944 Some 3.9 todos
  panel/src/styles/animations.css
  panel/src/styles/reset.css
  panel/src/styles/utilities.css
  src/Blueprint/Collection.php
  src/Blueprint/Config.php
  src/Blueprint/Extension.php
  src/Blueprint/Factory.php
  src/Blueprint/Node.php
  src/Blueprint/NodeI18n.php
  src/Blueprint/NodeIcon.php
  src/Blueprint/NodeProperty.php
  src/Blueprint/NodeString.php
  src/Blueprint/NodeText.php
  src/Cms/App.php
  src/Cms/AppUsers.php
  src/Cms/AppUsersImpersonateProxy.php
  src/Session/Session.php
  src/Toolkit/Query.php
  tests/Cms/App/AppTest.php
  tests/Cms/App/AppUsersTest.php
Labels: type: refactoring :recycle:

#4890 Add PHP 8.2 support
  .github/workflows/backend.yml
  bootstrap.php
  composer.json
  composer.lock
  psalm.xml.dist
  src/Cms/System.php
  vendor/autoload.php
  vendor/claviska/simpleimage/src/claviska/SimpleImage.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_static.php
  vendor/composer/installed.json
  vendor/composer/installed.php
Labels: type: feature 🎉

#4934 `Xml::attr()`: deprecate empty string as value
  src/Toolkit/Xml.php
Labels: type: refactoring :recycle:

#4872 `Dir::copy()`: Support skipping the global ignore list
  src/Filesystem/Dir.php
  tests/Filesystem/DirTest.php
  tests/Filesystem/fixtures/dir/copy/subfolder/.gitignore
Labels: type: enhancement ✨

#4910 Snippets with slots
  config/aliases.php
  config/components.php
  config/helpers.php
  src/Cms/App.php
  src/Cms/Email.php
  src/Cms/Page.php
  src/Template/Slot.php
  src/Template/Slots.php
  src/Template/Snippet.php
  src/Template/Template.php
  tests/Cms/App/AppComponentsTest.php
  tests/Cms/Helpers/HelperFunctionsTest.php
  tests/Cms/Helpers/fixtures/HelpersTest/snippet-slots.php
  tests/Cms/Pages/PageTemplateTest.php
  tests/Template/SlotTest.php
  tests/Template/SlotsTest.php
  tests/Template/SnippetTest.php
  tests/Template/TemplateTest.php
  tests/Template/TestCase.php
  tests/Template/templates/data.php
  tests/Template/templates/layout.php
  tests/Template/templates/simple.php
  tests/Template/templates/simple.rss.php
  tests/Template/templates/slots.php
  tests/Template/templates/with-layout.php
Labels: type: feature 🎉

#4939 `Toolkit\I18n`: code improvements
  src/Toolkit/I18n.php
Labels: type: refactoring :recycle:

#4922 `Toolkit\Silo`: code + tests improvements
  src/Toolkit/Silo.php
  tests/Toolkit/SiloTest.php
Labels: type: refactoring :recycle:

#4937 `Toolkit\Controller`: code + tests improvements
  src/Toolkit/Controller.php
  tests/Toolkit/ControllerTest.php
Labels: type: refactoring :recycle:

#4938 `Toolkit\Iterator`: code + tests improvements
  src/Toolkit/Iterator.php
  tests/Toolkit/IteratorTest.php
Labels: type: refactoring :recycle:

#4940 Writer: fix link wrapping
  panel/src/components/Forms/Writer/Writer.vue
Labels: type: bug 🐛

#4933 Add `Content-Type: application/json` for fiber requests
  panel/src/api/request.js
  panel/src/fiber/index.js
  panel/src/helpers/object.js
Labels: type: bug 🐛

#4948 Fix usage of deprecated code in `Html::rel()`
  src/Cms/Helpers.php
  src/Toolkit/Html.php
  tests/Cms/Helpers/HelperFunctionsTest.php
  tests/Cms/Helpers/HelpersTest.php
  tests/Toolkit/HtmlTest.php
  tests/Toolkit/QueryTest.php
  tests/Toolkit/QueryTestUser.php
  tests/Toolkit/XmlTest.php
Labels: type: refactoring :recycle:, type: regression 🚨

#4946 Update composer dependencies
  composer.json
  composer.lock
  vendor/claviska/simpleimage/src/claviska/SimpleImage.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_static.php
  vendor/composer/installed.json
  vendor/composer/installed.php
  vendor/phpmailer/phpmailer/composer.json
  vendor/phpmailer/phpmailer/get_oauth_token.php
  vendor/phpmailer/phpmailer/language/phpmailer.lang-es.php
  vendor/phpmailer/phpmailer/src/PHPMailer.php
  vendor/phpmailer/phpmailer/src/POP3.php
  vendor/phpmailer/phpmailer/src/SMTP.php
  vendor/symfony/polyfill-intl-idn/Idn.php
  vendor/symfony/polyfill-intl-idn/composer.json
  vendor/symfony/polyfill-mbstring/Mbstring.php
  vendor/symfony/polyfill-mbstring/composer.json
Labels: type: enhancement ✨

#4945 Use `SensitiveParameter` attribute
  src/Cms/Auth.php
  src/Cms/Auth/Challenge.php
  src/Cms/User.php
  src/Cms/UserActions.php
  src/Cms/UserRules.php
  src/Http/Request/Auth.php
  src/Http/Request/Auth/BasicAuth.php
  src/Http/Uri.php
Labels: type: enhancement ✨

#4903 i18n/en - feburary fix
  i18n/translations/en.json
Labels: type: i18n 🌏

#4855 Structure field: delete all button
  i18n/translations/en.json
  panel/src/components/Forms/Field/StructureField.vue
  panel/src/components/Layout/Table.vue
Labels: type: feature 🎉

#4960 Bug report template: fix broken link
  CONTRIBUTING.md
Labels: type: docs 📝

#4954 Fix multiselect field search
  panel/src/components/Forms/Counter.vue
  panel/src/components/Forms/Input/MultiselectInput.vue
Labels: type: regression 🚨

#4971 Fixes to refactored code
  src/Cache/Value.php
  src/Http/Environment.php
  src/Http/Response.php
  src/Http/Router.php
  src/Parsley/Element.php
  src/Toolkit/Iterator.php
  tests/Http/EnvironmentTest.php
Labels: type: refactoring :recycle:, type: regression 🚨

#4959 Improve `Toolkit\Xml`
  src/Toolkit/Html.php
  src/Toolkit/Xml.php
  tests/Toolkit/XmlTest.php
Labels: type: refactoring :recycle:

#4956 `Text`: code + tests improvements
  src/Text/KirbyTag.php
  src/Text/KirbyTags.php
  src/Text/Markdown.php
  src/Text/SmartyPants.php
  tests/Text/KirbyTagTest.php
  tests/Text/KirbyTagsTest.php
  tests/Text/MarkdownTest.php
  tests/Text/SmartyPantsTest.php
Labels: type: refactoring :recycle:

#4958 Small code quality improvements
  config/fields/text.php
  src/Api/Collection.php
  src/Blueprint/Factory.php
  src/Cms/Html.php
  src/Cms/ModelWithContent.php
  src/Cms/UserRules.php
  src/Http/Request/Files.php
  src/Toolkit/Html.php
  tests/Toolkit/ATest.php
Labels: type: refactoring :recycle:

#4961 `Toolkit\Str`: clean up
  src/Toolkit/Str.php
  src/Toolkit/Tpl.php
Labels: type: refactoring :recycle:

#4973 PHPUnit: Prevent creation of stray site directory
  tests/Cms/Files/FilesTest.php
  tests/Cms/Pages/PagesTest.php
  tests/Cms/Plugins/PluginTest.php
Labels: type: refactoring :recycle:, type: tests 🧪

#4974 Minor options refactoring; fix double escaping in select field
  config/fields/select.php
  panel/src/components/Sections/FieldsSection.vue
  src/Blueprint/Collection.php
  src/Blueprint/Node.php
  src/Field/FieldOptions.php
  src/Option/Option.php
  src/Option/Options.php
  src/Option/OptionsApi.php
  src/Option/OptionsProvider.php
  src/Option/OptionsQuery.php
  tests/Field/FieldOptionsTest.php
  tests/Form/Fields/SelectFieldTest.php
  tests/Form/Fields/TagsFieldTest.php
  tests/Option/OptionsApiTest.php
  tests/Option/OptionsQueryTest.php
Labels: type: bug 🐛, type: refactoring :recycle:

#4964 CI: Mock for `error_log()` to prevent ghost output
  tests/Cms/App/AppErrorsTest.php
  tests/Cms/TestCase.php
  tests/Cms/mocks.php
Labels: type: refactoring :recycle:, type: tests 🧪

#4976 Minor query refactoring; fix handling of quote escaping
  src/Query/Argument.php
  src/Query/Arguments.php
  src/Query/Expression.php
  src/Query/Query.php
  src/Query/Segment.php
  tests/Query/ArgumentTest.php
Labels: type: bug 🐛, type: refactoring :recycle:

#4969 Fix date field year change issue
  panel/src/components/Forms/Calendar.vue
Labels: type: regression 🚨

#4943 Delete temporary uploaded files after processing
  config/api/routes/files.php
  config/api/routes/users.php
  config/fields/mixins/upload.php
  src/Cms/FileActions.php
  src/Cms/HasFiles.php
  src/Filesystem/F.php
  tests/Cms/Files/FileActionsTest.php
  tests/Cms/Files/HasFilesTest.php
Labels: type: bug 🐛

#4979 Tags input: fix trimming spaces
  panel/src/components/Forms/Input/TagsInput.vue
Labels: type: bug 🐛
