Repository getkirby/kirby, pull requests merged in 2022-05, with the labels that each got.

#4289 Upgrade Vite to 2.9.8
  panel/package-lock.json
  panel/package.json
  panel/vite.config.js
Labels: type: refactoring :recycle:

#4302 Document layout values for `Item` components
  panel/src/components/Layout/Item.vue
  panel/src/components/Layout/ItemImage.vue
Labels: type: docs 📝

#4247 Consistent use of `k-collection`, new `k-models-section`
  panel/src/components/Dialogs/Dialog.vue
  panel/src/components/Dialogs/FilesDialog.vue
  panel/src/components/Dialogs/PagesDialog.vue
  panel/src/components/Dialogs/UsersDialog.vue
  panel/src/components/Forms/Field/FilesField.vue
  panel/src/components/Forms/Field/PagesField.vue
  panel/src/components/Forms/Field/UsersField.vue
  panel/src/components/Layout/Collection.vue
  panel/src/components/Layout/Items.vue
  panel/src/components/Navigation/Search.vue
  panel/src/components/Sections/FieldsSection.vue
  panel/src/components/Sections/FilesSection.vue
  panel/src/components/Sections/InfoSection.vue
  panel/src/components/Sections/ModelsSection.vue
  panel/src/components/Sections/PagesSection.vue
  panel/src/components/Sections/StatsSection.vue
  panel/src/config/plugins.js
  panel/src/mixins/forms/picker.js
  panel/src/mixins/picker/dialog.js
  panel/src/mixins/section.js
  panel/src/mixins/section/collection.js
Labels: type: enhancement ✨, type: refactoring :recycle:

#4308 Use internal `->filter()` method instead loop that unsetting the original data
  config/sections/pages.php
  tests/Cms/Sections/PagesSectionTest.php
Labels: type: bug 🐛

#4314 Fix pagination methods return type hints #4313
  src/Cms/Pagination.php
  tests/Cms/Collections/PaginationTest.php
Labels: type: bug 🐛

#4294 Improved table previews and usage of table component for plugins
  config/areas/system/views.php
  i18n/translations/en.json
  panel/src/components/Forms/Previews/ArrayFieldPreview.vue
  panel/src/components/Forms/Previews/BubblesFieldPreview.vue
  panel/src/components/Forms/Previews/DateFieldPreview.vue
  panel/src/components/Forms/Previews/EmailFieldPreview.vue
  panel/src/components/Forms/Previews/FilesFieldPreview.vue
  panel/src/components/Forms/Previews/HtmlFieldPreview.vue
  panel/src/components/Forms/Previews/ListFieldPreview.vue
  panel/src/components/Forms/Previews/PagesFieldPreview.vue
  panel/src/components/Forms/Previews/TagsFieldPreview.vue
  panel/src/components/Forms/Previews/TextFieldPreview.vue
  panel/src/components/Forms/Previews/TimeFieldPreview.vue
  panel/src/components/Forms/Previews/ToggleFieldPreview.vue
  panel/src/components/Forms/Previews/UrlFieldPreview.vue
  panel/src/components/Forms/Previews/UsersFieldPreview.vue
  panel/src/components/Forms/Previews/WriterFieldPreview.vue
  panel/src/components/Forms/Previews/index.js
  panel/src/components/Layout/Bubble.vue
  panel/src/components/Layout/Bubbles.vue
  panel/src/components/Layout/Table.vue
  panel/src/components/Layout/TableCell.vue
  panel/src/components/Navigation/Link.vue
  panel/src/components/Views/SystemView.vue
  panel/src/config/components.js
  panel/src/mixins/forms/fieldPreview.js
  src/Cms/Plugin.php
  tests/Cms/Plugins/PluginTest.php
  tests/Panel/Areas/SystemTest.php
Labels: type: feature 🎉

#4317 Correct `sort` data when multiple files upload
  panel/src/components/Forms/Upload.vue
Labels: type: bug 🐛

#4295 System health checks
  config/areas/system/views.php
  i18n/translations/en.json
  panel/src/components/Views/SystemView.vue
  src/Cms/App.php
  src/Cms/System.php
  tests/Cms/System/SystemTest.php
Labels: type: feature 🎉

#4315 Use k-stats for system view
  config/sections/stats.php
  i18n/translations/en.json
  panel/src/components/Layout/Stats.vue
  panel/src/components/Sections/StatsSection.vue
  panel/src/components/Views/SystemView.vue
Labels: type: enhancement ✨

#4316 Search feature for pages and files section
  config/sections/files.php
  config/sections/mixins/search.php
  config/sections/pages.php
  i18n/translations/en.json
  panel/src/components/Sections/FilesSection.vue
  panel/src/components/Sections/ModelsSection.vue
  panel/src/components/Sections/Sections.vue
  src/Cms/Core.php
  tests/Cms/Sections/FilesSectionTest.php
  tests/Cms/Sections/PagesSectionTest.php
Labels: type: feature 🎉, needs: tests 🧪
