Repository getkirby/kirby, pull requests merged in 2022-04, with the labels that each got.

#4253 Support SQLite views
  src/Database/Sql/Sqlite.php
  tests/Database/Sql/MysqlTest.php
  tests/Database/Sql/SqliteTest.php
Labels: type: enhancement ✨

#4250 Force `Kirby\Toolkit\Collection` iterator for `Query::page` method
  src/Database/Query.php
  src/Toolkit/Pagination.php
  tests/Database/QueryTest.php
Labels: type: bug 🐛

#4258 Preserve current tab across prev/next navigation
  src/Panel/File.php
  src/Panel/Model.php
  src/Panel/Page.php
  src/Panel/Site.php
  src/Panel/User.php
  tests/Panel/FileTest.php
  tests/Panel/PageTest.php
  tests/Panel/UserTest.php
Labels: type: enhancement ✨

#4208 Support for IntlDateFormatter
  config/methods.php
  src/Cms/File.php
  src/Filesystem/F.php
  src/Filesystem/File.php
  src/Toolkit/Str.php
  tests/Toolkit/StrTest.php
Labels: type: feature 🎉

#4236 Add A::filter, A::without
  src/Toolkit/A.php
  tests/Toolkit/ATest.php
Labels: type: feature 🎉

#4255 Fix DB where callback with reset props
  src/Database/Query.php
  tests/Database/QueryTest.php
Labels: type: bug 🐛

#4262 Prevent upload same file with different template
  src/Cms/FileRules.php
  tests/Cms/Files/FileRulesTest.php
Labels: type: regression 🚨

#4270 Feature: random in `Toolkit\A` and `Toolkit\Collection`
  src/Toolkit/A.php
  src/Toolkit/Collection.php
  tests/Toolkit/ATest.php
  tests/Toolkit/CollectionTest.php
Labels: type: feature 🎉

#4280 Fixed Fiber requests to non-origin urls
  config/areas/site/dialogs.php
  panel/src/fiber/index.js
Labels: type: bug 🐛

#4287 `Uri`: Allow disabling the params parsing
  src/Http/Uri.php
  tests/Http/UriTest.php
Labels: type: enhancement ✨

#4268 `Toolkit\Obj`: support `array` as the `$property` argument for getting multiple properties
  src/Toolkit/Obj.php
  tests/Toolkit/ObjTest.php
Labels: type: feature 🎉

#4281 Fix and support callback option to programmable page and user blueprints
  src/Cms/Blueprint.php
  src/Cms/Roles.php
  tests/Cms/Blueprints/BlueprintTest.php
  tests/Cms/Roles/RolesTest.php
Labels: type: enhancement ✨, type: bug 🐛

#4260 Set router callbacks on initialisation
  src/Cms/App.php
  src/Http/Router.php
  tests/Http/RouterTest.php
Labels: type: refactoring :recycle:

#4264 `Http\Request`: Extensions for the auth types; more secure lookup
  src/Http/Request.php
  src/Http/Request/Auth.php
  src/Http/Request/Auth/BasicAuth.php
  src/Http/Request/Auth/BearerAuth.php
  src/Http/Request/Auth/SessionAuth.php
  tests/Http/Request/Auth/BasicAuthTest.php
  tests/Http/Request/Auth/BearerAuthTest.php
  tests/Http/Request/Auth/SessionAuthTest.php
Labels: type: feature 🎉, type: refactoring :recycle:

#4195 TagsFieldPreview
  panel/src/components/Forms/Previews/TagsFieldPreview.vue
  panel/src/config/components.js
Labels: type: feature 🎉

#4290 Router hooks: Separate `$hooks` argument
  src/Cms/App.php
  src/Http/Router.php
  tests/Http/RouterTest.php
Labels: type: refactoring :recycle:

#4292 Add PHP extensions to `composer.json`
  composer.json
  composer.lock
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_static.php
Labels: type: enhancement ✨

#4291 Fix PHPUnit `@covers` warnings
  tests/Cms/Pages/PageBlueprintTest.php
  tests/Panel/FileTest.php
  tests/Panel/PageTest.php
  tests/Panel/UserTest.php
Labels: type: refactoring :recycle:

#4215 New `k-table` for structure field and block preview
  panel/src/components/Drawers/Drawer.vue
  panel/src/components/Forms/Blocks/Block.vue
  panel/src/components/Forms/Blocks/Types/Table.vue
  panel/src/components/Forms/Field/StructureField.vue
  panel/src/components/Forms/Previews/DateFieldPreview.vue
  panel/src/components/Forms/Previews/TagsFieldPreview.vue
  panel/src/components/Forms/Structure/StructureForm.vue
  panel/src/components/Layout/Empty.vue
  panel/src/components/Layout/Table.vue
  panel/src/components/Layout/TableCell.vue
  panel/src/config/components.js
  panel/src/helpers/object.isEmpty.test.js
  panel/src/helpers/object.js
  panel/src/mixins/forms/structure.js
Labels: type: feature 🎉, type: refactoring :recycle:
