Repository getkirby/kirby, pull requests merged in 2022-01, with the labels that each got.

#4080 k-aspect-ratio: Fix example code
  panel/src/components/Layout/AspectRatio.vue
Labels: type: docs 📝

#4074 Fix selected tab on multi-language
  panel/src/components/Navigation/Languages.vue
Labels: type: regression 🚨

#4075 More reliable solution for color helper
  panel/src/helpers/color.js
  panel/src/helpers/color.test.js
Labels: type: bug 🐛

#4088 Fix collection `prevUnlisted()` method
  src/Cms/PageSiblings.php
  tests/Cms/Pages/PageSiblingsTest.php
Labels: type: bug 🐛

#4089 Upgrade vitest
  panel/package-lock.json
  panel/package.json
Labels: type: refactoring :recycle:

#4046 Refactor date field Vue components
  config/fields/date.php
  panel/src/components/Forms/Calendar.vue
  panel/src/components/Forms/Field/DateField.vue
  panel/src/components/Forms/Field/TimeField.vue
  panel/src/components/Forms/FormButtons.vue
  panel/src/components/Forms/Input/DateInput.vue
  panel/src/components/Forms/Input/DateTimeInput.vue
  panel/src/components/Forms/Input/TimeInput.vue
  panel/src/helpers/index.js
  panel/src/helpers/validate.js
  panel/src/libraries/dayjs-iso.js
  panel/src/libraries/dayjs-merge.js
  panel/src/libraries/dayjs-merge.test.js
  panel/src/libraries/dayjs-pattern.js
  panel/src/libraries/dayjs-pattern.test.js
  panel/src/libraries/dayjs-round.js
  panel/src/libraries/dayjs-validate.js
  panel/src/libraries/dayjs.js
  panel/src/store/modules/content.js
  src/Toolkit/Date.php
  tests/Form/Fields/DateFieldTest.php
  tests/Form/FormTest.php
  tests/Toolkit/DateTest.php
Labels: type: bug 🐛, type: refactoring :recycle:

#4093 Support single string as `panel.favicon` value #4092
  src/Panel/Document.php
  tests/Panel/DocumentTest.php
Labels: type: bug 🐛

#4097 Move `Spyc` library into `/dependencies`
  composer.json
  composer.lock
  dependencies/spyc/Spyc.php
  tests/Data/YamlTest.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_files.php
  vendor/composer/autoload_static.php
  vendor/composer/installed.json
  vendor/composer/installed.php
  vendor/mustangostang/spyc/COPYING
  vendor/mustangostang/spyc/Spyc.php
  vendor/mustangostang/spyc/composer.json
Labels: type: bug 🐛, type: refactoring :recycle:

#4103 Spyc: Minor enhancements to the forked code
  dependencies/spyc/COPYING
  dependencies/spyc/Spyc.php
Labels: type: enhancement ✨, type: refactoring :recycle:

#4091 Add Inuktitut syllabics
  i18n/rules/iu.json
Labels: type: feature 🎉

#4099 Allow `rel="alternate stylesheet"` in css() helper
  config/helpers.php
  tests/Cms/Helpers/HelpersTest.php
Labels: type: enhancement ✨

#4108 Vitest optimizations and CI integration
  .github/workflows/ci.yml
  panel/package.json
  panel/src/components/Misc/Progress.test.js
  panel/src/components/Misc/Text.test.js
  panel/src/components/Navigation/PrevNext.test.js
  panel/src/components/Navigation/__snapshots__/PrevNext.test.js.snap
  panel/src/fiber/dialog.test.js
  panel/src/fiber/dropdown.test.js
  panel/src/fiber/index.test.js
  panel/src/fiber/search.test.js
  panel/src/helpers/color.test.js
  panel/src/helpers/embed.test.js
  panel/src/helpers/object.clone.test.js
  panel/src/helpers/object.merge.test.js
  panel/src/helpers/ratio.test.js
  panel/src/helpers/sort.test.js
  panel/src/helpers/string.camelToKebab.test.js
  panel/src/helpers/string.escapeHTML.test.js
  panel/src/helpers/string.hasEmoji.test.js
  panel/src/helpers/string.lcfirst.test.js
  panel/src/helpers/string.pad.test.js
  panel/src/helpers/string.random.test.js
  panel/src/helpers/string.slug.test.js
  panel/src/helpers/string.stripHTML.test.js
  panel/src/helpers/string.template.test.js
  panel/src/helpers/string.ucfirst.test.js
  panel/src/helpers/string.ucwords.test.js
  panel/src/helpers/string.uuid.test.js
  panel/src/libraries/dayjs-iso.test.js
  panel/src/libraries/dayjs-merge.test.js
  panel/src/libraries/dayjs-pattern.test.js
  panel/src/libraries/dayjs-round.test.js
  panel/src/libraries/dayjs-units.test.js
  panel/src/libraries/dayjs-validate.test.js
  panel/vite.config.js
  panel/vitest.setup.js
Labels: type: refactoring :recycle:, type: tests 🧪

#4109 ImageMagick: Escape shell arguments and update docblock
  src/Image/Darkroom/ImageMagick.php
Labels: type: enhancement ✨, type: refactoring :recycle:

#4117 Fix z-index for item dropdown toggle #4072
  panel/src/components/Layout/Item.vue
  panel/src/styles/variables.css
Labels: type: bug 🐛
