Repository getkirby/kirby, pull requests merged in 2023-04, with the labels that each got.

#5127 Block label: strip HTML
  panel/src/components/Forms/Blocks/BlockTitle.vue
Labels: type: bug 🐛

#5131 Fix `File::contentFileData()`
  src/Cms/File.php
  tests/Cms/Files/FileTest.php
Labels: type: bug 🐛

#5133 fix image alt adoption in default image block template
  config/blocks/image/image.php
  tests/Cms/Blocks/BlockTest.php
  tests/Cms/Blocks/fixtures/files/bar.jpg
  tests/Cms/Blocks/fixtures/files/bar.jpg.txt
  tests/Cms/Blocks/fixtures/files/foo.jpg
Labels: type: bug 🐛

#5119 Fix date changes with adding new interpret formats
  panel/src/libraries/dayjs-interpret.js
  panel/src/libraries/dayjs-interpret.test.js
Labels: type: bug 🐛

#5139 Remove abandoned `phpcpd` dependency
  .github/workflows/backend.yml
  composer.json
Labels: type: refactoring :recycle:

#5137 Fix #5130
  panel/src/components/Navigation/Search.vue
Labels: type: regression 🚨

#5138 Remove `noopener` where not needed
  panel/src/components/Forms/Writer/Marks/Link.js
  src/Parsley/Schema/Blocks.php
  src/Toolkit/Html.php
  tests/Parsley/fixtures/link-with-nested-div.php
  tests/Sane/fixtures/html/allowed/sandbox-blocks.html
  tests/Text/KirbyTagsTest.php
  tests/Text/fixtures/kirbytext/link-with-target/expected.html
  tests/Toolkit/HtmlTest.php
Labels: type: enhancement ✨

#5142 Fix detecting language with locale
  src/Cms/App.php
  tests/Cms/App/AppLanguagesTest.php
Labels: type: bug 🐛

#5143 Inherit `when` for field groups
  src/Cms/Blueprint.php
  tests/Cms/Blueprints/BlueprintFieldTest.php
Labels: type: enhancement ✨

#5144 Fix filling default values while creating new page
  src/Cms/PageActions.php
  tests/Cms/Pages/PageActionsTest.php
Labels: type: bug 🐛

#5078 Clean up `Toolkit` package
  src/Toolkit/A.php
  src/Toolkit/Component.php
  src/Toolkit/Controller.php
  src/Toolkit/Date.php
  src/Toolkit/Facade.php
  src/Toolkit/Html.php
  src/Toolkit/Iterator.php
  src/Toolkit/Obj.php
  src/Toolkit/Pagination.php
  src/Toolkit/Str.php
  src/Toolkit/Tpl.php
  src/Toolkit/V.php
  src/Toolkit/View.php
  src/Toolkit/Xml.php
Labels: type: refactoring :recycle:, needs: two-person review 🧑‍🤝‍🧑

#5155 Keep the language selector in sync
  panel/src/fiber/app.js
Labels: type: bug 🐛

#5159 `HasFiles::file()`: use `$in` also for uuid lookup
  src/Cms/HasFiles.php
Labels: type: bug 🐛

#5158 Externalize at `window.Vue`
  panel/package-lock.json
  panel/package.json
  panel/vite.config.js
  src/Panel/Document.php
  tests/Panel/DocumentTest.php
Labels: type: enhancement ✨
