Repository getkirby/kirby, pull requests merged in 2023-01, with the labels that each got.

#4983 Fix hook parameter for `page.changeSlug`
  src/Cms/PageActions.php
Labels: type: bug 🐛

#4982 [3.8.4] Form & fieldset: revert `v-model` changes
  panel/src/components/Forms/Fieldset.vue
  panel/src/components/Forms/Form.vue
Labels: type: regression 🚨

#4987 OptionsApi: Fix usage without query, add support for simple arrays
  src/Option/OptionsApi.php
  tests/Field/FieldOptionsTest.php
  tests/Option/OptionsApiTest.php
  tests/Option/fixtures/data-nested.json
  tests/Option/fixtures/data-simple-html.json
  tests/Option/fixtures/data-simple.json
  tests/Option/fixtures/data.json
Labels: type: enhancement ✨, type: bug 🐛

#4963 Snippets with slots: Enhancements and fixes
  config/components.php
  src/Template/Slot.php
  src/Template/Slots.php
  src/Template/Snippet.php
  src/Template/Template.php
  tests/Template/SlotTest.php
  tests/Template/SlotsTest.php
  tests/Template/SnippetTest.php
  tests/Template/TemplateTest.php
  tests/Template/TestCase.php
  tests/Template/fixtures/data.php
  tests/Template/fixtures/layout.php
  tests/Template/fixtures/scope.php
  tests/Template/fixtures/simple.php
  tests/Template/fixtures/simple.rss.php
  tests/Template/fixtures/slots.php
  tests/Template/fixtures/with-layout.php
Labels: type: enhancement ✨, type: bug 🐛, type: refactoring :recycle:

#4995 Revert "Get rid of `$children` usage"
  panel/src/components/Navigation/DropdownContent.vue
Labels: type: regression 🚨

#4991 Clean up `Toolkit\View` & `Toolkit\V`
  src/Toolkit/V.php
  src/Toolkit/View.php
Labels: type: refactoring :recycle:

#4999 Fix rendering pages inside snippet's slot
  src/Template/Template.php
  tests/Template/SnippetTest.php
  tests/Template/TemplateTest.php
  tests/Template/fixtures/layout.php
  tests/Template/fixtures/plain.php
  tests/Template/fixtures/render-in-slot-layout.php
  tests/Template/fixtures/render-in-slot.php
  tests/Template/fixtures/render.php
Labels: type: bug 🐛

#5001 Fix `undefined` error on structure field paginating
  panel/src/components/Forms/Field/StructureField.vue
Labels: type: bug 🐛

#5002 Better edge-case handling of the layout snippet detection
  src/Template/Snippet.php
  src/Template/Template.php
  tests/Template/SnippetTest.php
Labels: type: refactoring :recycle:

#4990 Clean up `Http` package
  src/Http/Cookie.php
  src/Http/Environment.php
  src/Http/Header.php
  src/Http/Params.php
  src/Http/Path.php
  src/Http/Remote.php
  src/Http/Request.php
  src/Http/Response.php
  src/Http/Route.php
  src/Http/Router.php
  src/Http/Uri.php
  src/Http/Url.php
  tests/Http/RemoteTest.php
Labels: type: refactoring :recycle:

#5008 Fix ParsedownExtra for emojis
  dependencies/parsedown-extra/ParsedownExtra.php
  tests/Text/fixtures/markdown.html
  tests/Text/fixtures/markdown.md
  tests/Text/fixtures/markdownbreaks.html
  tests/Text/fixtures/markdownextra.html
Labels: type: regression 🚨

#5015 Update README
  README.md
Labels: type: refactoring :recycle:

#5014 Allow deactivating deprecation notices
  src/Cms/Helpers.php
  src/Template/Snippet.php
  src/Toolkit/Query.php
  src/Toolkit/Xml.php
  tests/Cms/Helpers/HelpersTest.php
Labels: type: enhancement ✨

#5016 Fix release CI workflow
  .github/workflows/release.yml
Labels: type: refactoring :recycle:, type: tests 🧪

#5017 Fix HTTPS protocol and badges in README
  README.md
Labels: type: refactoring :recycle:

#5023 Fix uploading avatar
  config/api/routes/users.php
Labels: type: regression 🚨

#5019 Fix invalid cache type translation
  i18n/translations/en.json
  src/Cms/AppCaches.php
  tests/Cms/App/AppCachesTest.php
Labels: type: bug 🐛, type: i18n 🌏

#5021 Fix snippets with `null` argument
  config/components.php
  src/Cms/App.php
  src/Template/Snippet.php
  tests/Cms/Helpers/HelperFunctionsTest.php
  tests/Template/SnippetTest.php
Labels: type: enhancement ✨

#5018 Date field: fix tabbing behavior
  panel/src/components/Forms/Input/DateInput.vue
Labels: type: enhancement ✨, type: bug 🐛
