Repository getkirby/kirby, pull requests merged in 2023-09, with the labels that each got.

#5544 Page move dialog: better Site handling
  config/areas/site/requests.php
  panel/src/components/Navigation/PageTree.vue
Labels: type: enhancement ✨

#5493 Pages field preview: fix escaping
  panel/src/components/Forms/Previews/BubblesFieldPreview.vue
  panel/src/components/Forms/Previews/FilesFieldPreview.vue
  panel/src/components/Forms/Previews/PagesFieldPreview.vue
  panel/src/components/Layout/Bubble.vue
  panel/src/components/Layout/Bubbles.vue
Labels: type: bug 🐛

#5554 CI: Only enable Whoops when it is tested
  phpunit.xml.dist
  src/Cms/AppErrors.php
  tests/Cms/App/AppErrorsTest.php
  tests/Cms/App/AppTest.php
  tests/Cms/Helpers/HelperFunctionsTest.php
  tests/Cms/Helpers/HelpersTest.php
  tests/bootstrap.php
Labels: type: refactoring :recycle:, type: tests 🧪

#5545 Filter icons.svg comment from output
  src/Panel/Assets.php
Labels: type: refactoring :recycle:

#5557 Plugin `assets` extension
  config/routes.php
  src/Cms/Plugin.php
  src/Cms/PluginAssets.php
  tests/Cms/Plugins/PluginAssetsTest.php
  tests/Cms/Plugins/PluginTest.php
  tests/Cms/Plugins/fixtures/plugin-assets/assets/test.css
Labels: type: feature 🎉

#5555 Upload: better async upload queue
  panel/src/components/Dialogs/Elements/Buttons.vue
  panel/src/helpers/queue.js
  panel/src/panel/upload.js
Labels: type: enhancement ✨

#5565 New `translate` icon
  config/areas/languages.php
  config/areas/languages/dialogs.php
  panel/public/img/icons.svg
  panel/src/components/Dropdowns/LanguagesDropdown.vue
  panel/src/components/Views/Languages/LanguageView.vue
  panel/src/components/Views/Languages/LanguagesView.vue
  panel/src/components/Views/Login/InstallationView.vue
  panel/src/components/Views/Users/UserProfile.vue
  src/Panel/Field.php
  src/Panel/User.php
  tests/Panel/FieldTest.php
Labels: type: enhancement ✨

#5558 `Str::template`: support single/double curly brace
  src/Exception/Exception.php
  src/Toolkit/I18n.php
  src/Toolkit/Str.php
  tests/Toolkit/I18nTest.php
  tests/Toolkit/StrTest.php
Labels: type: enhancement ✨

#5562 Items: expose options slot for table layout
  panel/src/components/Collection/Collection.vue
  panel/src/components/Collection/Items.vue
  panel/src/components/Layout/Table.vue
  panel/src/components/Navigation/ButtonGroup.vue
Labels: type: bug 🐛

#5567 Fix `array.sortBy`
  config/fields/structure.php
  panel/src/components/Forms/Field/StructureField.vue
  panel/src/components/Layout/Table.vue
  panel/src/helpers/array.js
Labels: needs: discussion 🗣, type: bug 🐛

#5559 More type hints
  src/Cms/App.php
  src/Cms/Auth/Status.php
  src/Cms/Blueprint.php
  src/Cms/ContentLock.php
  src/Cms/ContentLocks.php
  src/Cms/File.php
  src/Cms/FileActions.php
  src/Cms/Files.php
  src/Cms/Html.php
  src/Cms/Loader.php
  src/Cms/Media.php
  src/Cms/ModelWithContent.php
  src/Cms/Page.php
  src/Cms/PageActions.php
  src/Cms/PageBlueprint.php
  src/Cms/Site.php
  src/Cms/System.php
  src/Cms/User.php
  src/Content/Content.php
  src/Database/Db.php
  src/Database/Query.php
  src/Filesystem/Mime.php
  src/Session/Session.php
  src/Toolkit/Date.php
  tests/Cms/App/AppErrorsTest.php
  tests/Cms/Pages/PageCreateTest.php
  tests/Cms/Pages/PageStatesTest.php
  tests/Cms/mocks.php
  tests/Http/mocks.php
  tests/Panel/ModelTest.php
Labels: type: refactoring :recycle:, type: tests 🧪

#5553 Input CSS refactoring
  panel/src/components/Dialogs/SearchDialog.vue
  panel/src/components/Forms/Field/ColorField.vue
  panel/src/components/Forms/Field/DateField.vue
  panel/src/components/Forms/Field/LinkField.vue
  panel/src/components/Forms/Field/WriterField.vue
  panel/src/components/Forms/Input.vue
  panel/src/components/Forms/Input/ChoiceInput.vue
  panel/src/components/Forms/Input/ColorInput.vue
  panel/src/components/Forms/Input/ListInput.vue
  panel/src/components/Forms/Input/NumberInput.vue
  panel/src/components/Forms/Input/RangeInput.vue
  panel/src/components/Forms/Input/SelectInput.vue
  panel/src/components/Forms/Input/TextInput.vue
  panel/src/components/Forms/Input/TextareaInput.vue
  panel/src/components/Forms/Input/ToggleInput.vue
  panel/src/components/Forms/Input/TogglesInput.vue
  panel/src/components/Forms/Previews/ToggleFieldPreview.vue
  panel/src/components/Forms/Writer/Writer.vue
  panel/src/styles/config/legacy.css
  panel/src/styles/reset.css
Labels: type: refactoring :recycle:

#5579 Color field: add backend validation
  config/fields/color.php
  i18n/translations/en.json
Labels: type: bug 🐛

#5583 More responsive `k-tabs`
  panel/src/components/Layout/Tabs.vue
Labels: type: enhancement ✨

#5578 Clean up `k-pagination`
  panel/src/components/Navigation/Pagination.vue
Labels: type: refactoring :recycle:

#5599 Fix dropdown position in RTL languages
  panel/src/components/Dropdowns/DropdownContent.vue
Labels: type: regression 🚨

#5589 Color field: fix hsl parsing
  config/fields/color.php
  panel/src/libraries/colors-checks.js
  panel/src/libraries/colors-func.js
  panel/src/libraries/colors.js
  panel/src/libraries/colors.test.js
Labels: type: bug 🐛

#5612 ModelsSection: use `Filter` as label
  panel/src/components/Sections/ModelsSection.vue
Labels: type: enhancement ✨, needs: decision 🗳

#5610 Text field: `font` option for monospace
  config/fields/text.php
  panel/src/components/Forms/Input/TextInput.vue
Labels: type: enhancement ✨

#5588 Fix return types for create methods
  src/Cms/FileActions.php
  src/Cms/PageActions.php
  src/Cms/UserActions.php
  src/Cms/Users.php
Labels: type: regression 🚨

#5590 Remove deprecated `DS`
  config/setup.php
Labels: type: refactoring :recycle:

#5601 Notification: suport custom icons
  panel/src/components/Forms/Blocks/Blocks.vue
  panel/src/components/Forms/Layouts/Layouts.vue
  panel/src/components/Forms/Login.vue
  panel/src/components/Forms/LoginCode.vue
  panel/src/components/Views/Login/InstallationView.vue
  panel/src/panel/notification.js
  panel/src/panel/notification.test.js
Labels: type: enhancement ✨

#5602 Support multiple Panel assets and absolute URLs
  src/Panel/Assets.php
  tests/Panel/AssetsTest.php
Labels: type: enhancement ✨

#5584 Use `await this.$nextTick()`
  panel/src/components/Dropdowns/DropdownContent.vue
  panel/src/components/Forms/Blocks/Blocks.vue
  panel/src/components/Forms/Field/LinkField.vue
  panel/src/components/Forms/Input/DateInput.vue
  panel/src/components/Forms/Selector.vue
  panel/src/components/Navigation/FileBrowser.vue
Labels: type: refactoring :recycle:

#5630 Fix regression for automatic plugin assets
  src/Cms/Plugin.php
  tests/Cms/Plugins/PluginAssetsTest.php
  tests/Cms/Plugins/PluginTest.php
Labels: type: regression 🚨

#5624 Fix collection items index
  panel/src/components/Collection/Items.vue
Labels: type: regression 🚨

#5631 Fix `$collection->group()` for case-sensitive
  src/Cms/Collection.php
  src/Toolkit/Collection.php
  tests/Cms/Collections/CollectionTest.php
Labels: type: bug 🐛

#5643 Display `$app->trigger/apply()` in the reference
  src/Cms/App.php
Labels: type: docs 📝

#5645 Tweak Vite setup
  .gitattributes
  panel/scripts/vite-kirby-dev.js
  panel/vite.config.js
Labels: type: refactoring :recycle:

#5646 Fix `RemoteTest` when `curl.cainfo` is actually set
  tests/Http/RemoteTest.php
Labels: type: tests 🧪

#5647 [v3] Fix optional parameter for `Cms\Api::file()`
  src/Cms/Api.php
  src/Cms/Find.php
Labels: type: refactoring :recycle:

#5640 Fix failing first/one/row queries when using fetch closure
  src/Database/Database.php
  src/Database/Query.php
  tests/Database/QueryTest.php
Labels: type: bug 🐛

#5651 Add callable support to $query->fetch()
  src/Database/Query.php
  tests/Database/QueryTest.php
  tests/Database/mocks.php
Labels: type: enhancement ✨

#5649 Use lightningcss
  panel/package-lock.json
  panel/package.json
  panel/vite.config.js
Labels: type: performance ⚡️

#5593 Update filename when changing format on upload
  src/Cms/FileActions.php
  tests/Cms/Files/FileActionsTest.php
Labels: type: bug 🐛

#5663 Fix reading invalid block types
  src/Form/Field/BlocksField.php
  tests/Form/Fields/BlocksFieldTest.php
Labels: type: regression 🚨

#5666 QR codes
  config/helpers.php
  config/methods.php
  src/Image/QrCode.php
  tests/Cms/Helpers/HelperFunctionsTest.php
  tests/Content/FieldMethodsTest.php
  tests/Image/QrCodeTest.php
  tests/Image/fixtures/qr/alphanum.svg
  tests/Image/fixtures/qr/alphanum.txt
  tests/Image/fixtures/qr/emoji.svg
  tests/Image/fixtures/qr/emoji.txt
  tests/Image/fixtures/qr/image-colors.png
  tests/Image/fixtures/qr/image-size.png
  tests/Image/fixtures/qr/image.png
  tests/Image/fixtures/qr/lorem.svg
  tests/Image/fixtures/qr/lorem.txt
  tests/Image/fixtures/qr/num.svg
  tests/Image/fixtures/qr/num.txt
  tests/Image/fixtures/qr/test.gif
  tests/Image/fixtures/qr/test.jpg
  tests/Image/fixtures/qr/test.png
  tests/Image/fixtures/qr/test.svg
  tests/Image/fixtures/qr/test.webp
  tests/Image/fixtures/qr/url.svg
  tests/Image/fixtures/qr/url.txt
Labels: type: feature 🎉

#5655 Fix color field border radius
  panel/src/components/Forms/Element/Color/color.css
Labels: type: bug 🐛

#5673 Fix paste blocks with max option
  panel/src/components/Forms/Blocks/Block.vue
  panel/src/components/Forms/Blocks/BlockOptions.vue
  panel/src/components/Forms/Blocks/Blocks.vue
  src/Form/Field/BlocksField.php
Labels: type: regression 🚨

#5668 Fix SVG fill
  panel/src/styles/reset.css
Labels: type: bug 🐛

#5667 Query: `qr` entry function
  src/Query/Query.php
  tests/Query/QueryDefaultFunctionsTest.php
Labels: type: enhancement ✨

#5678 Fix pasting blocks
  panel/src/components/Forms/Blocks/BlockSelector.vue
  panel/src/components/Forms/Blocks/Blocks.vue
Labels: type: bug 🐛

#5675 Allow string for `$page->search(params: )` again
  src/Cms/Page.php
  tests/Cms/Pages/PageChildrenTest.php
  tests/Cms/Pages/PagesTest.php
Labels: type: regression 🚨

#5688 Revert `Str::short(appendix: false)`
  src/Toolkit/Str.php
  tests/Toolkit/StrTest.php
Labels: type: refactoring :recycle:

#5608 `$app->collection()` & template controllers: Lazy value resolver
  src/Cms/App.php
  src/Cms/Collections.php
  src/Cms/Page.php
  src/Toolkit/Controller.php
  src/Toolkit/LazyValue.php
  tests/Toolkit/LazyValueTest.php
Labels: type: performance ⚡️

#5679 Blocks field: improve UI for no fieldsets
  i18n/translations/en.json
  panel/src/components/Forms/Blocks/Blocks.vue
  panel/src/components/Forms/Field/BlocksField.vue
Labels: type: refactoring :recycle:

#5680 Fix collapsing block fields preview
  panel/src/components/Forms/Blocks/BlockType.vue
  panel/src/components/Forms/Blocks/Types/Fields.vue
Labels: type: bug 🐛

#5677 More input mixins
  panel/src/components/Forms/Field/LinkField.vue
  panel/src/components/Forms/Input/CheckboxesInput.vue
  panel/src/components/Forms/Input/ChoiceInput.vue
  panel/src/components/Forms/Input/ColorInput.vue
  panel/src/components/Forms/Input/DateInput.vue
  panel/src/components/Forms/Input/EmailInput.vue
  panel/src/components/Forms/Input/ListInput.vue
  panel/src/components/Forms/Input/MultiselectInput.vue
  panel/src/components/Forms/Input/NumberInput.vue
  panel/src/components/Forms/Input/PasswordInput.vue
  panel/src/components/Forms/Input/RadioInput.vue
  panel/src/components/Forms/Input/RangeInput.vue
  panel/src/components/Forms/Input/SelectInput.vue
  panel/src/components/Forms/Input/SlugInput.vue
  panel/src/components/Forms/Input/TagsInput.vue
  panel/src/components/Forms/Input/TelInput.vue
  panel/src/components/Forms/Input/TextInput.vue
  panel/src/components/Forms/Input/TextareaInput.vue
  panel/src/components/Forms/Input/ToggleInput.vue
  panel/src/components/Forms/Input/TogglesInput.vue
  panel/src/components/Forms/Input/UrlInput.vue
  panel/src/components/Forms/Input/WriterInput.vue
  panel/src/components/Forms/Writer/Writer.vue
  panel/src/mixins/input.js
  panel/src/mixins/props.js
  panel/src/mixins/props/font.js
  panel/src/mixins/props/maxlength.js
  panel/src/mixins/props/minlength.js
  panel/src/mixins/props/options.js
  panel/src/mixins/props/placeholder.js
  panel/src/mixins/props/spellcheck.js
Labels: type: refactoring :recycle:

#5685 Replace custom color & coords elements with Vue components
  i18n/translations/en.json
  panel/src/components/Forms/Element/Color/color.css
  panel/src/components/Forms/Element/Color/color.js
  panel/src/components/Forms/Element/Coords/coords.css
  panel/src/components/Forms/Element/Coords/coords.js
  panel/src/components/Forms/Element/index.js
  panel/src/components/Forms/Field/ColorField.vue
  panel/src/components/Forms/Input/ColorpickerInput.vue
  panel/src/components/Forms/Input/CoordsInput.vue
  panel/src/components/Forms/Input/index.js
  panel/src/components/Views/Files/FilePreview.vue
Labels: needs: delay ⏳️, type: refactoring :recycle:

#5682 Fix sticky columns
  panel/src/components/Layout/Column.vue
Labels: type: bug 🐛

#5656 Fix layout dropdown in structure field
  panel/src/components/Layouter/Layout.vue
Labels: type: bug 🐛

#5585 Deprecate `k-dropdown`
  panel/src/components/Dialogs/SearchDialog.vue
  panel/src/components/Drawers/Drawer.vue
  panel/src/components/Dropdowns/Dropdown.vue
  panel/src/components/Dropdowns/DropdownContent.vue
  panel/src/components/Dropdowns/LanguagesDropdown.vue
  panel/src/components/Dropdowns/OptionsDropdown.vue
  panel/src/components/Dropdowns/SelectorDropdown.vue
  panel/src/components/Forms/Autocomplete.vue
  panel/src/components/Forms/Blocks/BlockOptions.vue
  panel/src/components/Forms/Field/ColorField.vue
  panel/src/components/Forms/Field/DateField.vue
  panel/src/components/Forms/Field/LinkField.vue
  panel/src/components/Forms/Field/TimeField.vue
  panel/src/components/Forms/Layouts/Layout.vue
  panel/src/components/Forms/Toolbar.vue
  panel/src/components/Forms/Writer/Toolbar.vue
  panel/src/components/Navigation/Breadcrumb.vue
  panel/src/components/Views/Files/FilePreview.vue
  panel/src/components/Views/Files/FileView.vue
  panel/src/components/Views/Pages/PageView.vue
  panel/src/components/Views/System/TableUpdateStatusCell.vue
  panel/src/components/Views/Users/UserAvatar.vue
  panel/src/components/Views/Users/UserView.vue
Labels: type: refactoring :recycle:

#5686 Streamline frame and tag usage
  panel/src/components/Forms/Field/ColorField.vue
  panel/src/components/Forms/Field/LinkField.vue
  panel/src/components/Forms/Previews/ColorFieldPreview.vue
  panel/src/components/Layout/Frame/ColorFrame.vue
  panel/src/components/Layout/Frame/IconFrame.vue
  panel/src/components/Layout/Frame/ImageFrame.vue
  panel/src/components/Layout/index.js
  panel/src/components/Navigation/Tag.vue
  panel/src/components/Navigation/Tags.vue
Labels: type: refactoring :recycle:

#5701 Fix `k-tabs` one more time
  panel/src/components/Layout/Tabs.vue
Labels: type: bug 🐛

#5713 Allow string for `$site->search(params: )` again
  src/Cms/Site.php
  tests/Cms/Site/SiteChildrenTest.php
Labels: type: regression 🚨

#5715 `Str::pool()`: New `base32`/`base32hex` pools
  src/Toolkit/Str.php
  tests/Toolkit/StrTest.php
Labels: type: enhancement ✨
