Repository getkirby/kirby, pull requests merged in 2023-10, with the labels that each got.

#5654 TOTP challenge
  composer.json
  composer.lock
  config/areas/account/dialogs.php
  config/areas/users/dialogs.php
  i18n/translations/en.json
  panel/src/components/Dialogs/TotpDialog.vue
  panel/src/components/Dialogs/index.js
  src/Cms/Auth.php
  src/Cms/Auth/Challenge.php
  src/Cms/Auth/EmailChallenge.php
  src/Cms/Auth/TotpChallenge.php
  src/Cms/Core.php
  src/Cms/System.php
  src/Cms/User.php
  src/Cms/UserActions.php
  src/Cms/UserRules.php
  src/Exception/Exception.php
  src/Panel/PageCreateDialog.php
  src/Panel/User.php
  src/Panel/UserTotpDisableDialog.php
  src/Panel/UserTotpEnableDialog.php
  src/Toolkit/Totp.php
  tests/Cms/Auth/AuthChallengeTest.php
  tests/Cms/Auth/Challenge/EmailChallengeTest.php
  tests/Cms/Auth/Challenge/TotpChallengeTest.php
  tests/Cms/System/SystemTest.php
  tests/Cms/Users/UserActionsTest.php
  tests/Cms/Users/UserRulesTest.php
  tests/Cms/Users/UserTest.php
  tests/Panel/Areas/AccountDropdownsTest.php
  tests/Panel/Areas/UserDropdownsTest.php
  tests/Panel/DialogTest.php
  tests/Panel/UserTest.php
  tests/Panel/UserTotpDisableDialogTest.php
  tests/Panel/UserTotpEnableDialogTest.php
  tests/Toolkit/TotpTest.php
  tests/Toolkit/mocks.php
  vendor/christian-riesen/base32/LICENSE
  vendor/christian-riesen/base32/src/Base32.php
  vendor/christian-riesen/base32/src/Base32Hex.php
  vendor/composer/InstalledVersions.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_psr4.php
  vendor/composer/autoload_static.php
  vendor/composer/installed.json
  vendor/composer/installed.php
Labels: type: feature 🎉

#5721 `panel.menu` config: support Closure
  src/Panel/Menu.php
  tests/Panel/MenuTest.php
Labels: type: enhancement ✨

#5714 Ignore case in `$collection->remove()`
  src/Cms/Collection.php
  src/Toolkit/Collection.php
  tests/Toolkit/CollectionTest.php
Labels: type: bug 🐛

#5724 Implement A::every(), A::some(), A::find()
  src/Toolkit/A.php
  tests/Toolkit/ATest.php
Labels: type: feature 🎉

#5717 Page tree: fix `root: false`
  panel/src/components/Navigation/PageTree.vue
Labels: type: bug 🐛

#5600 Floating notifications
  panel/src/components/View/Inside.vue
  panel/src/components/View/Topbar.vue
Labels: type: enhancement ✨, needs: decision 🗳

#5684 Writer: adding link, insert text when no selected
  panel/src/components/Forms/Writer/Editor.js
  panel/src/components/Forms/Writer/Marks/Email.js
  panel/src/components/Forms/Writer/Marks/Link.js
Labels: type: enhancement ✨, type: bug 🐛

#5739 Fix notification theme
  panel/src/components/Misc/Notification.vue
Labels: type: bug 🐛

#5733 Fix custom writer marks and nodes name
  panel/src/components/Forms/Writer/Writer.vue
Labels: type: bug 🐛

#5759 Don’t override permissions via any roles’ options
  src/Cms/ModelPermissions.php
  tests/Cms/Pages/PagePermissionsTest.php
Labels: type: bug 🐛

#5758 Parsley inline: fix trimming spaces-only elements
  src/Parsley/Inline.php
  tests/Parsley/InlineTest.php
Labels: type: bug 🐛

#5756 Choices: tweak checked styling
  panel/src/styles/reset/choice.css
Labels: type: enhancement ✨

#5742 Improve tags selector
  panel/src/components/Forms/Selector.vue
  panel/src/components/Navigation/Tags.vue
Labels: type: enhancement ✨

#5748 Tags: fix replacable options
  panel/src/components/Forms/Selector.vue
  panel/src/components/Navigation/Tags.vue
Labels: type: enhancement ✨, type: bug 🐛

#5749 Tags: fix disabled state
  panel/src/components/Navigation/Tag.vue
  panel/src/components/Navigation/Tags.vue
Labels: type: bug 🐛

#5687 Page create dialog: add form validation
  config/areas/site/dialogs.php
  src/Cms/PageRules.php
  src/Panel/PageCreateDialog.php
  tests/Panel/Areas/PageCreateDialogTest.php
Labels: type: bug 🐛

#5740 Text block: consistent padding for writer
  panel/src/components/Forms/Blocks/Types/Text.vue
Labels: type: bug 🐛

#5753 `k-navigate` as Vue component
  panel/src/components/Forms/Selector.vue
  panel/src/components/Navigation/Navigate.js
  panel/src/components/Navigation/Navigate.vue
  panel/src/components/Navigation/index.js
Labels: type: refactoring :recycle:

#5762 Selector dropdown: fix glitch when resizing window
  panel/src/components/Dropdowns/DropdownContent.vue
Labels: type: bug 🐛

#5581 Add CLI specific config file
  src/Http/Environment.php
  tests/Http/EnvironmentTest.php
  tests/Http/fixtures/EnvironmentTest/config.cli.php
Labels: type: enhancement ✨

#5745 Heading block: support `toolbar` option for writer
  panel/src/components/Forms/Blocks/Types/Heading.vue
Labels: type: bug 🐛

#5766 Fix DropdownItem after k-navigate
  panel/src/components/Dropdowns/DropdownContent.vue
  panel/src/components/Dropdowns/DropdownItem.vue
Labels: type: regression 🚨

#5768 Panel menu: enable automatically those from config
  src/Panel/Menu.php
Labels: type: enhancement ✨

#5771 `Toolkit\Date`: Allow formatting with the globally configured handler
  config/methods.php
  src/Cms/File.php
  src/Cms/Page.php
  src/Cms/Site.php
  src/Cms/User.php
  src/Filesystem/Dir.php
  src/Filesystem/F.php
  src/Filesystem/File.php
  src/Toolkit/Date.php
  src/Toolkit/Str.php
  tests/Toolkit/DateTest.php
  tests/Toolkit/StrTest.php
  tests/Toolkit/VTest.php
Labels: type: enhancement ✨, type: feature 🎉

#5774 [v4] PHP 8.3 support
  .github/workflows/backend.yml
  .github/workflows/frontend.yml
  bootstrap.php
  composer.json
  composer.lock
  config/helpers.php
  src/Cms/System.php
  src/Content/ContentStorage.php
  src/Http/Response.php
  src/Toolkit/A.php
  vendor/composer/InstalledVersions.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_static.php
  vendor/composer/installed.json
  vendor/composer/installed.php
  vendor/laminas/laminas-escaper/composer.json
  vendor/laminas/laminas-escaper/src/Escaper.php
  vendor/symfony/deprecation-contracts/LICENSE
  vendor/symfony/deprecation-contracts/composer.json
  vendor/symfony/deprecation-contracts/function.php
Labels: type: feature 🎉

#5784 Fix reactivity in the k-fieldset component
  panel/lab/components/fieldset/index.php
  panel/lab/components/fieldset/index.vue
  panel/src/components/Forms/Fieldset.vue
Labels: type: regression 🚨

#5750 Session: Allow write access to moved sessions
  composer.json
  src/Session/Session.php
  src/Toolkit/SymmetricCrypto.php
  tests/Session/SessionTest.php
  tests/Session/mocks.php
  tests/Toolkit/SymmetricCryptoTest.php
Labels: type: enhancement ✨

#5779 Fix paste blocks when fieldset is not available
  src/Form/Field/BlocksField.php
  tests/Form/Fields/BlocksFieldTest.php
Labels: type: regression 🚨

#5641 Proper `PluginAsset` and `PluginAssets` classes
  config/routes.php
  src/Cms/Html.php
  src/Cms/Plugin.php
  src/Cms/PluginAsset.php
  src/Cms/PluginAssets.php
  tests/Cms/Html/HtmlTest.php
  tests/Cms/Html/fixtures/plugin/assets/scripts.js
  tests/Cms/Html/fixtures/plugin/assets/styles.css
  tests/Cms/Html/fixtures/test.svg
  tests/Cms/Plugins/PluginAssetTest.php
  tests/Cms/Plugins/PluginAssetsTest.php
  tests/Cms/Plugins/PluginTest.php
Labels: type: feature 🎉, type: refactoring :recycle:

#5803 Deprecate `k-plugin-view`
  panel/dist/ui/LegacyPluginView.json
  panel/src/components/Views/LegacyPluginView.vue
Labels: type: refactoring :recycle:

#5801 New `k-stat`
  panel/dist/ui/Stat.json
  panel/dist/ui/Stats.json
  panel/lab/components/stats/1_stats/index.php
  panel/lab/components/stats/1_stats/index.vue
  panel/lab/components/stats/2_stat/index.php
  panel/lab/components/stats/2_stat/index.vue
  panel/src/components/Layout/Stat.vue
  panel/src/components/Layout/Stats.vue
  panel/src/components/Layout/index.js
Labels: type: refactoring :recycle:

#5806 Refactor `k-toolbar`
  panel/dist/ui/BlockOptions.json
  panel/dist/ui/ListField.json
  panel/dist/ui/ListInput.json
  panel/dist/ui/TextareaField.json
  panel/dist/ui/TextareaInput.json
  panel/dist/ui/Toolbar.json
  panel/dist/ui/Writer.json
  panel/dist/ui/WriterField.json
  panel/dist/ui/WriterInput.json
  panel/lab/components/toolbar/1_toolbar/index.php
  panel/lab/components/toolbar/1_toolbar/index.vue
  panel/lab/components/toolbar/2_textarea/index.php
  panel/lab/components/toolbar/2_textarea/index.vue
  panel/lab/components/toolbar/3_writer/index.php
  panel/lab/components/toolbar/3_writer/index.vue
  panel/src/components/Forms/Blocks/BlockOptions.vue
  panel/src/components/Forms/Input/TextareaInput.vue
  panel/src/components/Forms/Toolbar.vue
  panel/src/components/Forms/Toolbar/TextareaToolbar.vue
  panel/src/components/Forms/Toolbar/Toolbar.vue
  panel/src/components/Forms/Toolbar/index.js
  panel/src/components/Forms/Writer/Toolbar.vue
  panel/src/components/Forms/Writer/Writer.vue
  panel/src/components/Forms/index.js
Labels: type: refactoring :recycle:

#5757 Fix search type permissions
  config/areas/search/views.php
  panel/src/components/Dialogs/SearchDialog.vue
  panel/src/components/View/Menu.vue
  panel/src/components/Views/SearchView.vue
  src/Panel/View.php
  tests/Panel/ViewTest.php
Labels: type: bug 🐛

#5799 Refactor `k-breadcrumb`
  config/areas/search/views.php
  panel/dist/ui/Breadcrumb.json
  panel/lab/components/breadcrumbs/index.vue
  panel/src/components/Navigation/Breadcrumb.vue
  panel/src/components/View/Topbar.vue
Labels: type: refactoring :recycle:

#5797 Simplify BlockPasteboard
  panel/dist/ui/BlockPasteboard.json
  panel/src/components/Forms/Blocks/BlockPasteboard.vue
Labels: type: refactoring :recycle:

#5804 `k-lab-docs-view` with support for better docs
  config/areas/lab/views.php
  panel/scripts/vite-kirby.mjs
  panel/src/components/Lab/Docs.vue
  panel/src/components/Lab/Docs/Deprecated.vue
  panel/src/components/Lab/Docs/Description.vue
  panel/src/components/Lab/Docs/DocBlock.vue
  panel/src/components/Lab/Docs/Events.vue
  panel/src/components/Lab/Docs/Examples.vue
  panel/src/components/Lab/Docs/Methods.vue
  panel/src/components/Lab/Docs/Props.vue
  panel/src/components/Lab/Docs/Slots.vue
  panel/src/components/Lab/DocsDeprecated.vue
  panel/src/components/Lab/DocsDrawer.vue
  panel/src/components/Lab/DocsParams.vue
  panel/src/components/Lab/DocsTypes.vue
  panel/src/components/Lab/DocsView.vue
  panel/src/components/Lab/IndexView.vue
  panel/src/components/Lab/index.js
  src/Panel/Lab/Docs.php
Labels: type: feature 🎉

#5788 Append copy suffix of duplicated pages
  config/areas/site/dialogs.php
  tests/Panel/Areas/PageDialogsTest.php
Labels: type: enhancement ✨

#5808 Generate UI docs in `panel/tmp` during `dev`
  .gitignore
  panel/package.json
  panel/scripts/docs.mjs
  panel/scripts/vite-kirby.mjs
  src/Panel/Lab/Docs.php
Labels: type: refactoring :recycle:

#5817 Fix `k-tag`
  panel/lab/components/tags/1_tag/index.php
  panel/lab/components/tags/1_tag/index.vue
  panel/src/components/Navigation/Tag.vue
Labels: type: bug 🐛

#5812 Toolbar: fix closing dropdown on click
  panel/src/components/Dialogs/SearchDialog.vue
  panel/src/components/Dropdowns/DropdownContent.vue
  panel/src/components/Forms/Field/BlocksField.vue
  panel/src/components/Forms/Field/LayoutField.vue
  panel/src/components/Forms/Field/LinkField.vue
  panel/src/components/Forms/Field/StructureField.vue
  panel/src/components/Forms/Input/TextareaInput.vue
  panel/src/components/Forms/Layouts/Layout.vue
  panel/src/components/Forms/Toolbar/Toolbar.vue
  panel/src/components/Forms/Writer/Toolbar.vue
  panel/src/components/Layout/Tabs.vue
  panel/src/components/Views/Files/FilePreview.vue
Labels: type: regression 🚨

#5828 Image focus: unpublish media files when changed
  src/Cms/FileActions.php
Labels: type: enhancement ✨

#5825 Toggle field preview: don’t open drawer
  panel/src/components/Forms/Previews/ToggleFieldPreview.vue
  panel/src/components/Layout/TableCell.vue
Labels: type: regression 🚨

#5827 Lab docs: fix index overview
  src/Panel/Lab/Docs.php
Labels: type: bug 🐛

#5823 Deprecate `k-autocomplete`
  panel/src/components/Forms/Autocomplete.vue
Labels: type: refactoring :recycle:

#5829 Fix searching for unicode characters
  config/components.php
Labels: type: bug 🐛

#5839 Fix undo for textarea commands
  panel/src/components/Forms/Input/TextareaInput.vue
Labels: type: regression 🚨

#5837 Textarea: command to toggle wrapping
  panel/src/components/Forms/Input/TextareaInput.vue
  panel/src/components/Forms/Toolbar/TextareaToolbar.vue
Labels: type: enhancement ✨

#5838 Revert StructureObject random ID
  src/Cms/Structure.php
  tests/Cms/Structures/StructureTest.php
Labels: type: regression 🚨

#5840 Fix unfocus blocks
  panel/src/components/Forms/Blocks/Blocks.vue
Labels: type: regression 🚨

#5841 Fix multiselect for nested blocks
  panel/src/components/Forms/Blocks/Blocks.vue
Labels: type: regression 🚨

#5842 Fix Search view
  panel/src/components/Views/SearchView.vue
Labels: type: bug 🐛

#5865 Textarea: properly restore selection after upload
  panel/src/components/Forms/Input/TextareaInput.vue
Labels: type: regression 🚨

#5864 Textarea: fix select files dialog
  panel/src/components/Forms/Input/TextareaInput.vue
  panel/src/components/Forms/Toolbar/TextareaToolbar.vue
Labels: type: regression 🚨

#5863 Fix `Cms\Collection::pagination()` return type
  src/Cms/Collection.php
  src/Toolkit/Collection.php
Labels: type: docs 📝

#5846 Fix textarea scroll jumps
  panel/src/components/Forms/Autosize.js
  panel/src/components/Forms/Input/TextareaInput.vue
Labels: type: bug 🐛

#5870 Textarea: properly restore selection after file select
  panel/src/components/Forms/Input/TextareaInput.vue
Labels: type: regression 🚨

#5861 Fix ItemImage ratio
  panel/src/components/Collection/ItemImage.vue
Labels: type: bug 🐛

#5875 Blocks field: fix multiselect key
  panel/src/components/Forms/Blocks/Blocks.vue
Labels: type: regression 🚨

#5873 Document `full` as item size
  config/fields/mixins/layout.php
  config/sections/mixins/layout.php
  panel/src/components/Collection/Items.vue
Labels: type: enhancement ✨, type: regression 🚨

#5879 Pretty JSON output for unlocked changes
  panel/src/components/Forms/FormButtons.vue
Labels: type: bug 🐛

#5890 Stop lock requests when offline
  panel/src/components/Forms/FormButtons.vue
  panel/src/components/Misc/OfflineWarning.vue
  panel/src/components/View/Panel.vue
  panel/src/panel/events.js
  panel/src/panel/panel.js
Labels: type: enhancement ✨, type: bug 🐛

#5891 Fix `PluginAssets::clean()`
  src/Cms/PluginAssets.php
  tests/Cms/Plugins/PluginAssetsTest.php
Labels: type: bug 🐛

#5889 Writer: rely on Vue defaults, more consistent
  config/fields/writer.php
  panel/src/components/Forms/Writer/Writer.vue
Labels: type: bug 🐛

#5886 Writer: support switch from list to paragraph node
  panel/src/components/Forms/Writer/Nodes/BulletList.js
  panel/src/components/Forms/Writer/Nodes/OrderedList.js
  panel/src/components/Forms/Writer/Nodes/Paragraph.js
Labels: type: enhancement ✨

#5888 Toggles input: fix background when focused
  panel/src/components/Forms/Input/TogglesInput.vue
Labels: type: bug 🐛

#5885 Writer toolbar: fix node dropdown and empty marks
  panel/src/components/Forms/Writer/Toolbar.vue
Labels: type: bug 🐛

#5884 Blocks: fix multi select once more
  panel/src/components/Forms/Blocks/Blocks.vue
Labels: type: regression 🚨
