Repository getkirby/kirby, pull requests merged in 2023-12, with the labels that each got.

#6060 EULA: Format info blocks for GitHub
  LICENSE.md
Labels: type: refactoring :recycle:

#5984 Upgrade to Vite 5
  panel/package-lock.json
  panel/package.json
  panel/src/components/Text/Highlight.vue
  panel/src/components/Text/Label.vue
  panel/vite.config.mjs
Labels: type: enhancement ✨

#6019 Stats section: support for `icon` option
  config/sections/stats.php
  tests/Cms/Sections/StatsSectionTest.php
Labels: type: feature 🎉

#6058 `$store.content`: fix consistent id pattern
  config/areas/site/dialogs.php
  panel/src/store/modules/content.js
Labels: type: bug 🐛

#6056 Color field: options query support
  config/fields/color.php
Labels: type: feature 🎉

#6091 Treat DDEV domains as local
  src/Http/Environment.php
  tests/Http/EnvironmentTest.php
Labels: type: enhancement ✨

#6086 Use `structuredClone`
  panel/lab/components/stats/1_stats/index.vue
  panel/src/components/Forms/Blocks/Blocks.vue
  panel/src/components/Forms/Input/TagsInput.vue
  panel/src/components/Forms/Layouts/Layouts.vue
  panel/src/components/Navigation/Tags.vue
  panel/src/components/Views/System/SystemSecurity.vue
  panel/src/helpers/field.js
  panel/src/helpers/object.js
  panel/src/store/modules/content.js
Labels: type: refactoring :recycle:

#6094 Structure field: clone row on duplicate
  panel/src/components/Forms/Field/StructureField.vue
Labels: type: bug 🐛

#6098 `field.isVisible()`: fix if statement
  panel/src/helpers/field.js
Labels: type: bug 🐛

#6092 `FileActionsTest`: static provider methods
  tests/Cms/Files/FileActionsTest.php
Labels: type: refactoring :recycle:, type: tests 🧪

#6072 Don’t pass kirby as property to models
  src/Cms/App.php
  src/Cms/AppUsers.php
  src/Cms/Files.php
  src/Cms/Pages.php
Labels: type: regression 🚨, needs: two-person review 🧑‍🤝‍🧑

#6093 Refactor deprecation warning tests
  tests/Cms/Helpers/HelperFunctionsTest.php
  tests/Cms/Helpers/HelpersTest.php
  tests/Cms/HelpersTestCase.php
  vendor/composer/ClassLoader.php
Labels: type: refactoring :recycle:, type: tests 🧪

#6105 `Helpers::handleErrors()`: Exception robustness
  src/Cms/Helpers.php
  tests/Cms/Helpers/HelpersTest.php
Labels: type: bug 🐛

#6059 PHPUnit 10
  .github/workflows/backend.yml
  .gitignore
  composer.json
  config/fields/structure.php
  phpunit.xml.dist
  src/Filesystem/F.php
  src/Session/Session.php
  src/Toolkit/A.php
  src/Toolkit/V.php
  tests/Cms/Helpers/HelpersTest.php
  tests/Session/FileSessionStoreTest.php
  tests/Template/SnippetTest.php
  tests/Toolkit/ATest.php
  tests/Uuid/BlockUuidTest.tmp
Labels: type: tests 🧪
