Repository getkirby/kirby, pull requests merged in 2023-06, with the labels that each got.

#5234 Fix type hints for `search` component
  config/components.php
  src/Cms/Collection.php
  src/Cms/Search.php
Labels: type: regression 🚨

#5236 Page create dialog: fix custom fields
  src/Panel/PageCreateDialog.php
  tests/Panel/Areas/PageDialogsTest.php
Labels: type: enhancement ✨, type: bug 🐛

#5228 Simplify some null assignments
  config/api/models/User.php
  src/Blueprint/NodeString.php
  src/Cms/AppUsers.php
  src/Cms/Pages.php
  src/Filesystem/File.php
  src/Form/Field.php
  src/Form/Field/LayoutField.php
  src/Form/FieldClass.php
  src/Http/Environment.php
  src/Http/Request.php
  src/Panel/View.php
Labels: type: refactoring :recycle:

#5227 Fix method order of `Toolkit\A`
  src/Toolkit/A.php
Labels: type: refactoring :recycle:

#5239 Page tree: use blueprint icons
  panel/src/components/Navigation/PageTree.vue
Labels: type: enhancement ✨

#5243 PageCreateDialog: fix supported field types
  src/Panel/PageCreateDialog.php
Labels: type: bug 🐛

#5245 Files `upload`: use `upload.parent` for mime check
  config/fields/mixins/upload.php
Labels: type: bug 🐛

#5259 `->toUrl()` to return `null` on empty fields
  config/components.php
  config/methods.php
  tests/Cms/Fields/FieldMethodsTest.php
Labels: type: bug 🐛

#5260 Color field: fix flex spacing
  panel/src/components/Forms/Element/Color/color.css
  panel/src/components/Forms/Field/ColorField.vue
Labels: type: bug 🐛

#5246 `Toolkit\Str`: add type hints for replace methods
  src/Toolkit/Str.php
  tests/Toolkit/StrTest.php
Labels: type: refactoring :recycle:

#5191 [v4] Panel: add pagination to search results
  config/areas/site/searches.php
  config/areas/users/searches.php
  panel/src/components/Dialogs/SearchDialog.vue
  panel/src/components/Views/SearchView.vue
  panel/src/panel/panel.js
  src/Panel/Panel.php
  src/Panel/Search.php
  src/Panel/View.php
  tests/Panel/Areas/PluginSearchesTest.php
  tests/Panel/ViewTest.php
Labels: type: enhancement ✨, type: performance ⚡️

#5222 Adding Variadic Controller Arguments
  src/Toolkit/Controller.php
  tests/Toolkit/ControllerTest.php
Labels: type: enhancement ✨

#5264 No redirect to logout when already logged out
  panel/src/panel/notification.js
Labels: type: bug 🐛

#5209 Clean some of `Form` package
  src/Form/Field.php
  src/Form/Field/BlocksField.php
  src/Form/Field/LayoutField.php
  src/Form/FieldClass.php
  src/Form/Fields.php
  src/Form/Form.php
  src/Form/Validations.php
  tests/Form/FieldClassTest.php
Labels: type: refactoring :recycle:

#5287 PageCreateDialog: make title label translatable
  src/Panel/PageCreateDialog.php
  tests/Panel/Areas/PageDialogsTest.php
Labels: type: bug 🐛

#5291 Disable change layout if one available
  panel/src/components/Forms/Layouts/Layout.vue
  panel/src/components/Forms/Layouts/Layouts.vue
Labels: type: bug 🐛

#5310 Stats section: add more i18n support
  config/sections/stats.php
  tests/Cms/Sections/StatsSectionTest.php
Labels: type: enhancement ✨

#5308 `Find::parent()`: fix for file with `files` parent
  src/Cms/Find.php
  tests/Cms/FindTest.php
Labels: type: bug 🐛

#5307 Fix overwriting of `Query::$entries`
  src/Query/Argument.php
  src/Query/Query.php
  src/Query/Segment.php
  tests/Query/ArgumentTest.php
  tests/Query/ArgumentsTest.php
  tests/Query/ExpressionTest.php
  tests/Query/QueryDefaultFunctionsTest.php
  tests/Query/SegmentsTest.php
Labels: type: bug 🐛

#5303 Disable structure options btn when form open
  panel/src/components/Forms/Field/StructureField.vue
Labels: type: bug 🐛

#5299 Block default model: change key to `default`
  src/Cms/Block.php
  tests/Cms/Blocks/BlockModelsTest.php
Labels: type: refactoring :recycle:, needs: decision 🗳

#5296 Writer: preserve whitespace
  panel/src/components/Forms/Writer/Writer.vue
Labels: type: regression 🚨

#5313 Fix panel url redirect issue when running on subfolder
  src/Panel/Home.php
  src/Panel/Panel.php
  tests/Panel/HomeTest.php
Labels: type: bug 🐛

#5305 Color field preview
  panel/src/components/Forms/Field/ColorField.vue
  panel/src/components/Forms/Previews/ColorFieldPreview.vue
  panel/src/components/Forms/Previews/index.js
  panel/src/components/Layout/Bubble.vue
Labels: type: enhancement ✨

#5170 Fix number field blur issue
  config/fields/number.php
  panel/src/components/Forms/Input/NumberInput.vue
  tests/Form/Fields/NumberFieldTest.php
  tests/Form/Fields/RangeFieldTest.php
Labels: type: bug 🐛

#5304 Uploader: allow to add more files via drop
  panel/src/panel/upload.js
Labels: type: enhancement ✨

#5298 `Structure` to extend `Item` classes
  config/methods.php
  src/Cms/AppPlugins.php
  src/Cms/Block.php
  src/Cms/Blocks.php
  src/Cms/Fieldset.php
  src/Cms/Fieldsets.php
  src/Cms/Item.php
  src/Cms/Items.php
  src/Cms/Layout.php
  src/Cms/LayoutColumn.php
  src/Cms/Layouts.php
  src/Cms/Structure.php
  src/Cms/StructureObject.php
  tests/Cms/Structures/StructureMethodsTest.php
  tests/Cms/Structures/StructureObjectMethodsTest.php
  tests/Cms/Structures/StructureObjectTest.php
  tests/Cms/Structures/StructureTest.php
Labels: type: refactoring :recycle:

#5322 New `templatesIgnore` for pages section
  config/sections/pages.php
  tests/Cms/Sections/PagesSectionTest.php
Labels: type: feature 🎉

#5306 Link field improvements
  config/fields/link.php
  i18n/translations/en.json
  panel/public/img/icons.svg
  panel/src/components/Forms/Field/LinkField.vue
Labels: needs: discussion 🗣, type: enhancement ✨

#5325 Fix language detect with custom locale
  src/Cms/App.php
  tests/Cms/App/AppLanguagesTest.php
Labels: type: bug 🐛

#5297 Clean up `search` component
  config/components.php
  tests/Cms/Collections/SearchTest.php
Labels: type: refactoring :recycle:

#5330 Add `Kql` endpoint to core
  config/api/routes/kql.php
Labels: type: refactoring :recycle:

#5336 Fix conflicting block keyboard shortcuts
  panel/src/components/Forms/Blocks/Block.vue
  panel/src/components/Forms/Blocks/Blocks.vue
Labels: type: bug 🐛

#5329 File blueprint `focus` option
  panel/src/components/Layout/FilePreview.vue
  panel/src/components/Views/FileView.vue
  src/Panel/File.php
  tests/Panel/FileTest.php
Labels: type: enhancement ✨

#5300 Fix block collapsing inside layouts
  panel/src/components/Forms/Blocks/Types/Text.vue
  panel/src/components/Forms/Layouts/LayoutColumn.vue
Labels: type: enhancement ✨

#5283 Content storage (backend PR 1)
  config/aliases.php
  src/Cms/ContentLocks.php
  src/Cms/File.php
  src/Cms/FileActions.php
  src/Cms/Helpers.php
  src/Cms/Language.php
  src/Cms/ModelWithContent.php
  src/Cms/Page.php
  src/Cms/PageActions.php
  src/Cms/Site.php
  src/Cms/System.php
  src/Cms/Translations.php
  src/Cms/User.php
  src/Content/Content.php
  src/Content/ContentStorage.php
  src/Content/ContentTranslation.php
  src/Content/Field.php
  src/Content/PlainTextContentStorage.php
  tests/Cms/Content/ContentTranslationTest.php
  tests/Cms/Files/FileActionsTest.php
  tests/Cms/Pages/PageActionsTest.php
  tests/Content/ContentTest.php
  tests/Content/ContentTranslationTest.php
  tests/Content/FieldMethodsTest.php
  tests/Content/FieldTest.php
  tests/Content/PlainTextContentStorageTest.php
  tests/Content/fixtures/files/a.png
  tests/Content/fixtures/files/b.png
  tests/Option/OptionsQueryTest.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_static.php
Labels: type: refactoring :recycle:
