Repository getkirby/kirby, pull requests merged in 2023-03, with the labels that each got.

#5077 Panel: more shortcuts for search
  panel/src/components/Navigation/Search.vue
Labels: type: enhancement ✨

#5095 Reverts #5072 blueprint i18n issue
  src/Cms/Blueprint.php
  src/Cms/Role.php
  src/Toolkit/I18n.php
  tests/Cms/Blueprints/BlueprintTest.php
  tests/Toolkit/I18nTest.php
Labels: type: regression 🚨

#5082 Clean up helpers
  config/helpers.php
Labels: type: refactoring :recycle:

#5032 Some missing A::functions
  src/Toolkit/A.php
  tests/Toolkit/ATest.php
Labels: type: feature 🎉

#5099 Never escape Unicode characters in blocks/layout fields
  src/Form/FieldClass.php
  tests/Form/Fields/BlocksFieldTest.php
  tests/Form/Fields/LayoutFieldTest.php
Labels: type: enhancement ✨

#5116 Update composer dependencies
  composer.json
  composer.lock
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_static.php
  vendor/composer/installed.json
  vendor/composer/installed.php
  vendor/filp/whoops/src/Whoops/Exception/Formatter.php
  vendor/filp/whoops/src/Whoops/Exception/Frame.php
  vendor/filp/whoops/src/Whoops/Exception/FrameCollection.php
  vendor/filp/whoops/src/Whoops/Exception/Inspector.php
  vendor/filp/whoops/src/Whoops/Handler/Handler.php
  vendor/filp/whoops/src/Whoops/Handler/HandlerInterface.php
  vendor/filp/whoops/src/Whoops/Handler/JsonResponseHandler.php
  vendor/filp/whoops/src/Whoops/Handler/PlainTextHandler.php
  vendor/filp/whoops/src/Whoops/Handler/PrettyPageHandler.php
  vendor/filp/whoops/src/Whoops/Handler/XmlResponseHandler.php
  vendor/filp/whoops/src/Whoops/Inspector/InspectorFactory.php
  vendor/filp/whoops/src/Whoops/Inspector/InspectorFactoryInterface.php
  vendor/filp/whoops/src/Whoops/Inspector/InspectorInterface.php
  vendor/filp/whoops/src/Whoops/Run.php
  vendor/filp/whoops/src/Whoops/RunInterface.php
  vendor/filp/whoops/src/Whoops/Util/TemplateHelper.php
  vendor/phpmailer/phpmailer/language/phpmailer.lang-hi.php
  vendor/phpmailer/phpmailer/src/DSNConfigurator.php
  vendor/phpmailer/phpmailer/src/PHPMailer.php
  vendor/phpmailer/phpmailer/src/POP3.php
  vendor/phpmailer/phpmailer/src/SMTP.php
Labels: type: enhancement ✨

#5105 Fix wrong sort number when using limit in files section
  config/sections/files.php
  tests/Cms/Sections/FilesSectionTest.php
Labels: type: bug 🐛

#5113 Fix zero number in param
  src/Http/Params.php
  tests/Http/ParamsTest.php
Labels: type: bug 🐛

#5110 Fix pasting blocks in block selector
  panel/src/components/Forms/Blocks/Blocks.vue
Labels: type: regression 🚨

#5121 Upgrade SimpleImage
  composer.json
  composer.lock
  src/Image/Darkroom/GdLib.php
  vendor/claviska/simpleimage/composer.json
  vendor/claviska/simpleimage/composer.lock
  vendor/claviska/simpleimage/src/claviska/SimpleImage.php
  vendor/composer/ClassLoader.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_psr4.php
  vendor/composer/autoload_real.php
  vendor/composer/autoload_static.php
  vendor/composer/installed.json
  vendor/composer/installed.php
  vendor/league/color-extractor/composer.json
  vendor/league/color-extractor/src/Color.php
  vendor/league/color-extractor/src/ColorExtractor.php
  vendor/league/color-extractor/src/Palette.php
Labels: type: enhancement ✨

#5115 Fix blocks and layout field default values
  src/Form/Field/BlocksField.php
  src/Form/Field/LayoutField.php
  tests/Form/Fields/BlocksFieldTest.php
  tests/Form/Fields/LayoutFieldTest.php
Labels: type: bug 🐛
