Repository getkirby/kirby, pull requests merged in 2023-02, with the labels that each got.

#4989 Add asset methods for plugins
  src/Cms/AppPlugins.php
  src/Filesystem/Asset.php
  tests/Filesystem/AssetTest.php
Labels: type: feature 🎉

#5035 Show most relevant search results with `flip` and `sortBy`
  config/sections/files.php
  config/sections/pages.php
  tests/Cms/Sections/FilesSectionTest.php
  tests/Cms/Sections/PagesSectionTest.php
Labels: type: enhancement ✨

#5052 Simplify `App::controllerLookup()`
  src/Cms/App.php
Labels: type: refactoring :recycle:

#5055 Update CI workflow dependencies
  .github/workflows/backend.yml
  .github/workflows/frontend.yml
  .github/workflows/integration.yml
  .github/workflows/stale.yml
Labels: type: enhancement ✨

#5054 Fix updating file template
  src/Cms/File.php
  tests/Cms/Files/FileActionsTest.php
Labels: type: bug 🐛

#5053 Provide `$field` prop to block/layout objects
  config/methods.php
  src/Cms/Item.php
  src/Cms/Items.php
  src/Cms/Layout.php
  src/Cms/LayoutColumn.php
  src/Cms/Layouts.php
  tests/Cms/Fields/FieldMethodsTest.php
  tests/Cms/Items/ItemTest.php
  tests/Cms/Items/ItemsTest.php
Labels: type: feature 🎉

#5044 Fix for issue #5042 Page::create ignores isDraft prop
  src/Cms/PageActions.php
  tests/Cms/Pages/PageCreateTest.php
Labels: type: bug 🐛

#5043 Allow individual isDraft in props to work
  src/Cms/Pages.php
  tests/Cms/Pages/PagesTest.php
Labels: type: bug 🐛

#5066 Fix `alt` attribute issue for `asset()` helper
  src/Image/Image.php
  tests/Filesystem/AssetTest.php
Labels: type: regression 🚨

#5063 Fix `->inline()`, `->nl2br()` and `->toTimestamp()` field methods when field is empty or not exists
  config/methods.php
  tests/Cms/Fields/FieldMethodsTest.php
Labels: type: bug 🐛

#5059 Fix and improve the youtube embed helper
  panel/src/helpers/embed.js
  panel/src/helpers/embed.test.js
Labels: type: enhancement ✨, type: bug 🐛

#5040 A::keyBy()
  src/Toolkit/A.php
  tests/Toolkit/ATest.php
Labels: type: feature 🎉

#5036 `A::fill()` accept callable as fill value
  src/Toolkit/A.php
  tests/Toolkit/ATest.php
Labels: type: enhancement ✨

#5068 `OptionsApi`: nest all data to allow field methods
  src/Option/OptionsApi.php
  src/Query/Query.php
  tests/Option/OptionsApiTest.php
  tests/Option/fixtures/data-nested.json
Labels: type: regression 🚨

#5051 Bring back `BlockConverter`
  src/Cms/Block.php
  src/Cms/BlockConverter.php
  src/Cms/Blocks.php
  tests/Cms/Blocks/BlockTest.php
  tests/Cms/Blocks/BlocksTest.php
  vendor/autoload.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_static.php
Labels: type: enhancement ✨

#5047 Correct "Logout" menu label to "Log out"
  i18n/translations/en.json
  tests/Panel/ViewTest.php
Labels: type: enhancement ✨, type: i18n 🌏

#5076 Panel: Fix `field.isVisible` helper
  panel/src/components/Forms/Field/ObjectField.vue
  panel/src/components/Forms/Field/StructureField.vue
  panel/src/helpers/field.js
Labels: type: bug 🐛

#5075 Fix console errors when unautenticated
  panel/src/api/request.js
  panel/src/config/api.js
Labels: type: bug 🐛

#5079 Clean up `Toolkit\Dom`
  src/Toolkit/Dom.php
Labels: type: refactoring :recycle:

#5074 Fix copy&paste for nested blocks
  panel/src/components/Forms/Blocks/Block.vue
  panel/src/components/Forms/Blocks/Blocks.vue
Labels: type: bug 🐛

#5072 Fix translated blueprint title
  src/Cms/Blueprint.php
  src/Cms/Role.php
  src/Toolkit/I18n.php
  tests/Cms/Blueprints/BlueprintTest.php
  tests/Toolkit/I18nTest.php
Labels: type: bug 🐛, type: refactoring :recycle:

#5069 `Dir::index()`: fix `$ignore` parameter
  src/Filesystem/Dir.php
  tests/Filesystem/DirTest.php
Labels: type: bug 🐛
