Repository getkirby/kirby, pull requests merged in 2023-07, with the labels that each got.

#5339 `FileActions`: consistent multi-lang handling
  src/Cms/FileActions.php
  src/Cms/Languages.php
  tests/Cms/Languages/LanguagesTest.php
Labels: type: refactoring :recycle:

#5337 `App::models()`
  src/Cms/App.php
  src/Cms/Language.php
  tests/Cms/App/AppTest.php
Labels: type: enhancement ✨, type: refactoring :recycle:

#5340 More `Cms` namespace type hinting/clean up
  src/Cms/Auth.php
  src/Cms/Language.php
  src/Cms/LanguageRouter.php
  src/Cms/LanguageRoutes.php
  src/Cms/LanguageRules.php
  src/Cms/Languages.php
Labels: type: refactoring :recycle:

#5343 Fix default language handling
  src/Cms/App.php
  src/Cms/Language.php
  tests/Cms/Languages/LanguageTest.php
Labels: type: bug 🐛

#5350 Fix duplicated layout issues
  panel/src/components/Forms/Layouts/Layouts.vue
Labels: type: regression 🚨

#5352 Fix additional divider on writer field
  panel/src/components/Forms/Writer/Toolbar.vue
Labels: type: bug 🐛

#5361 Fix `panel.get()` for redirects
  panel/src/panel/panel.js
  panel/src/panel/request.js
Labels: type: bug 🐛

#5363 Upgrade GitHub Actions
  .github/workflows/backend.yml
  .github/workflows/frontend.yml
  .github/workflows/integration.yml
Labels: type: refactoring :recycle:

#5315 New `access` and `list` permissions for files
  config/api/routes/files.php
  config/areas/site/searches.php
  config/sections/files.php
  src/Cms/Api.php
  src/Cms/File.php
  src/Cms/FileBlueprint.php
  src/Cms/FilePicker.php
  src/Cms/Find.php
  src/Cms/Permissions.php
  tests/Cms/Api/ApiTest.php
  tests/Cms/Files/FileBlueprintTest.php
  tests/Cms/Files/FileTest.php
  tests/Cms/Sections/FilesSectionTest.php
  tests/Form/Fields/Mixins/FilePickerMixinTest.php
  tests/Panel/FileTest.php
Labels: type: feature 🎉

#5357 Unescape block title label
  panel/src/components/Forms/Blocks/BlockTitle.vue
Labels: type: bug 🐛

#5366 Fix user blueprint home option and running on subfolder
  src/Panel/Home.php
  src/Panel/Panel.php
  tests/Panel/HomeTest.php
Labels: type: bug 🐛, type: regression 🚨

#5368 Fix `->toUrl()` method for invalid uuids
  config/components.php
  config/methods.php
  tests/Cms/App/AppComponentsTest.php
  tests/Cms/Fields/FieldMethodsTest.php
  tests/Form/Fields/LinkFieldTest.php
Labels: type: bug 🐛

#5372 Use `uri` instead `id` on changeSlug dialog
  config/areas/site/dialogs.php
Labels: type: bug 🐛

#5360 Add type hints to `Form` namespace
  src/Cms/Section.php
  src/Form/Field.php
  src/Form/Field/BlocksField.php
  src/Form/Field/LayoutField.php
  src/Form/FieldClass.php
  src/Form/Form.php
  src/Form/Mixin/EmptyState.php
  src/Form/Mixin/Max.php
  src/Form/Mixin/Min.php
  src/Form/Validations.php
  src/Toolkit/Component.php
  tests/Form/FieldClassTest.php
  tests/Form/FormTest.php
Labels: type: refactoring :recycle:

#5376 Rename Romanian slug rules to ro.json
  i18n/rules/ro.json
Labels: type: bug 🐛

#5344 Writer: `quote` node
  config/fields/writer.php
  panel/src/components/Forms/Blocks/Types/Quote.vue
  panel/src/components/Forms/Writer/Nodes/OrderedList.js
  panel/src/components/Forms/Writer/Nodes/Quote.js
  panel/src/components/Forms/Writer/Utils/index.js
  panel/src/components/Forms/Writer/Utils/toggleWrap.js
  panel/src/components/Forms/Writer/Writer.vue
Labels: type: feature 🎉

#5394 [v4] Fix structure field responsive breakpoint
  panel/src/components/Layout/Table.vue
Labels: type: regression 🚨

#5398 [v4] Page create dialog: allow custom status for anyone
  src/Panel/PageCreateDialog.php
Labels: type: bug 🐛

#5356 [v4] Remove `twitter`
  config/helpers.php
  config/tags.php
  panel/dist/img/icons.svg
  panel/public/img/icons.svg
  tests/Cms/CoreTest.php
  tests/Cms/Helpers/HelperFunctionsTest.php
  tests/Query/SegmentsTest.php
  tests/Query/TestUser.php
  tests/Sane/fixtures/svg/allowed/icons/mastodon.svg
  tests/Sane/fixtures/svg/allowed/icons/twitter.svg
  tests/Text/KirbyTagsTest.php
  tests/Text/fixtures/kirbytext/twitter/expected.html
  tests/Text/fixtures/kirbytext/twitter/test.txt
Labels: type: refactoring :recycle:

#5400 [v4] Fix Panel menu gaps
  panel/src/components/View/Menu.vue
Labels: type: bug 🐛

#5387 [v4] Improvements language translations editor
  config/areas/languages/dialogs.php
  config/areas/languages/views.php
  i18n/translations/en.json
  panel/src/components/Views/Languages/LanguageView.vue
  panel/src/components/Views/Languages/LanguagesView.vue
  src/Cms/Language.php
  src/Cms/LanguageVariable.php
  tests/Cms/Languages/LanguageTest.php
Labels: type: enhancement ✨, type: feature 🎉, type: bug 🐛

#5386 [v4] Customizable layout selector
  panel/src/components/Dialogs/Dialog.vue
  panel/src/components/Forms/Field/LayoutField.vue
  panel/src/components/Forms/Layouts/LayoutSelector.vue
  panel/src/components/Forms/Layouts/Layouts.vue
  src/Form/Field/LayoutField.php
Labels: type: enhancement ✨, type: bug 🐛

#5414 Remove cypress
  .gitattributes
  .github/workflows/integration.yml
  .github/workflows/release.yml
  .gitignore
  CONTRIBUTING.md
  panel/.eslintrc.js
  panel/README.md
  panel/cypress.config.js
  panel/package-lock.json
  panel/package.json
  panel/src/components/Forms/Blocks/Blocks.e2e.js
  panel/src/components/Forms/Field/DateField.e2e.js
  panel/src/components/Views/FileView.e2e.js
  panel/src/components/Views/InstallationView.e2e.js
  panel/src/components/Views/LoginView.e2e.js
  panel/src/components/Views/PageView.e2e.js
  panel/src/components/Views/SiteView.e2e.js
  panel/src/components/Views/UsersView.e2e.js
Labels: type: refactoring :recycle:

#5418 [v4] Fix structure field validation
  config/fields/structure.php
  i18n/translations/en.json
  tests/Form/Fields/StructureFieldTest.php
Labels: type: regression 🚨

#5410 Fix centering icon in `k-frame`
  panel/src/components/Layout/Frame/Frame.vue
Labels: type: bug 🐛

#5413 Text field: use `text` input if no specific input
  panel/src/components/Forms/Field/TextField.vue
Labels: type: bug 🐛

#5403 Whoops: Add support for `whoops.blocklist` config option
  src/Cms/AppErrors.php
Labels: needs: tests 🧪

#5407 Fix longer help texts
  panel/src/components/Collection/Collection.vue
Labels: type: bug 🐛

#5431 New `panel.frameAncestors` option
  src/Panel/Document.php
  tests/Panel/DocumentTest.php
Labels: type: regression 🚨

#5429 Fix nullable search query
  config/components.php
  tests/Cms/Collections/SearchTest.php
Labels: type: regression 🚨
