Repository getkirby/kirby, pull requests merged in 2023-05, with the labels that each got.

#5166 Fix `Database::lastError()`
  src/Database/Database.php
  tests/Database/DatabaseTest.php
Labels: type: bug 🐛

#5173 Fix retrieving numeric parameters
  src/Http/Request.php
  tests/Http/RequestTest.php
Labels: type: bug 🐛

#5175 Fix type hints for `HasSiblings`; fix behavior of `$collection->indexOf()`
  src/Cms/Collection.php
  src/Cms/HasSiblings.php
  tests/Cms/Collections/CollectionTest.php
Labels: type: bug 🐛

#5176 Fix link style for structure field
  panel/src/components/Forms/Previews/HtmlFieldPreview.vue
Labels: type: bug 🐛

#5179 Remove return type for `collection()` helper
  config/helpers.php
  src/Cms/App.php
  src/Cms/Collections.php
Labels: type: regression 🚨

#5177 Add edit button for structure field
  panel/src/components/Forms/Field/StructureField.vue
Labels: type: enhancement ✨

#5192 [v4] Fix `isFile` return types
  src/Cms/File.php
  src/Filesystem/IsFile.php
Labels: type: regression 🚨

#5196 Fix typo `I18n::translate` method name
  composer.json
  config/areas/languages/views.php
Labels: type: bug 🐛

#5207 `Query` package: remove strict types again
  src/Query/Argument.php
  src/Query/Arguments.php
  src/Query/Expression.php
  src/Query/Query.php
  src/Query/Segment.php
  src/Query/Segments.php
Labels: type: regression 🚨

#5199 Fix link dialog in textarea field
  panel/src/components/Forms/Field/LinkField.vue
Labels: type: bug 🐛

#5202 Fix extending Vue components
  panel/src/config/errorhandling.js
  panel/src/index.js
  panel/src/legacy/index.js
Labels: type: regression 🚨

#5203 CSS `:has()` polyfill
  panel/package-lock.json
  panel/package.json
  panel/src/index.js
  panel/vite.config.js
Labels: type: enhancement ✨

#5217 Panel: fix language and content (re-)loading
  panel/src/api/index.js
  panel/src/components/Navigation/LanguagesDropdown.vue
  panel/src/components/Navigation/index.js
  panel/src/components/Sections/FieldsSection.vue
  panel/src/components/Views/ModelView.vue
Labels: type: regression 🚨

#5221 Page move: consider section parent in rules
  src/Cms/PageRules.php
  tests/Cms/Pages/PageRulesTest.php
Labels: type: bug 🐛

#5206 Panel `feature`: silent loading
  panel/src/panel/feature.js
Labels: type: regression 🚨

#5212 Rename Panel API
  panel/src/components/Layout/Panel.vue
  panel/src/mixins/dialog.js
  panel/src/mixins/drawer.js
  panel/src/panel/dialog.js
  panel/src/panel/dialog.test.js
  panel/src/panel/drag.js
  panel/src/panel/drawer.js
  panel/src/panel/drawer.test.js
  panel/src/panel/feature.js
  panel/src/panel/language.js
  panel/src/panel/modal.js
  panel/src/panel/modal.test.js
  panel/src/panel/module.test.js
  panel/src/panel/notification.js
  panel/src/panel/panel.js
  panel/src/panel/state.js
  panel/src/panel/state.test.js
  panel/src/panel/system.js
  panel/src/panel/translation.js
  panel/src/panel/upload.js
  panel/src/panel/user.js
Labels: type: refactoring :recycle:
