Repository getkirby/kirby, pull requests merged in 2023-11, with the labels that each got.

#5892 Fix Writer toolbar positioning
  panel/src/components/Forms/Writer/Toolbar.vue
Labels: needs: discussion 🗣, type: bug 🐛

#5900 Better way to handle default values for objects
  panel/src/components/Forms/Field/ObjectField.vue
  panel/src/helpers/field.js
  panel/src/helpers/field.test.js
Labels: type: regression 🚨

#5887 Toolbar: fix btn not clickable in Safari
  panel/src/components/Forms/Blocks/BlockOptions.vue
  panel/src/components/Forms/Toolbar/Toolbar.vue
  panel/src/components/Forms/Writer/Extensions/Toolbar.js
  panel/src/components/Forms/Writer/Writer.vue
Labels: type: bug 🐛

#5909 Exclude UI docs and lab from regular bundle
  .gitattributes
  config/areas/lab/drawers.php
  config/areas/lab/views.php
  panel/src/components/Lab/IndexView.vue
  src/Panel/Lab/Category.php
  src/Panel/Lab/Docs.php
Labels: type: enhancement ✨

#5908 Icon for `k-stat`
  config/areas/system/views.php
  panel/lab/components/stats/1_stats/index.vue
  panel/lab/components/stats/2_stat/index.vue
  panel/src/components/Layout/Stat.vue
  tests/Panel/Areas/SystemTest.php
Labels: type: enhancement ✨

#5917 Fix CalendarInput
  panel/src/components/Forms/Field/DateField.vue
  panel/src/components/Forms/Input/CalendarInput.vue
Labels: type: bug 🐛

#5914 autosize library
  panel/package-lock.json
  panel/package.json
  panel/src/components/Forms/Autosize.js
  panel/src/components/Forms/Input/TextareaInput.vue
  panel/src/components/Forms/index.js
  panel/src/libraries/index.js
Labels: type: regression 🚨

#5916 Tweak style of Toggle input
  panel/src/styles/reset/choice.css
Labels: type: enhancement ✨

#5920 Include max date in error msg for date.between
  config/fields/date.php
  tests/Form/Fields/DateFieldTest.php
Labels: type: bug 🐛

#5915 Fix drag to empty blocks list
  panel/src/components/Forms/Blocks/Blocks.vue
Labels: type: regression 🚨

#5926 Switch to “Activate” wording
  config/areas/system/dialogs.php
  config/areas/system/views.php
  i18n/translations/en.json
  tests/Panel/Areas/LanguagesDialogsTest.php
  tests/Panel/Areas/SystemDialogsTest.php
  tests/Panel/Areas/SystemTest.php
Labels: type: i18n 🌏

#5928 Fix UUID links in writer field in subfolder setups
  src/Sane/DomHandler.php
  src/Sane/Handler.php
  src/Sane/Html.php
  src/Sane/Sane.php
  src/Sane/Svg.php
  src/Sane/Svgz.php
  src/Sane/Xml.php
  src/Toolkit/Dom.php
  tests/Form/Fields/TestCase.php
  tests/Form/Fields/WriterFieldTest.php
  tests/Sane/DomHandlerTest.php
  tests/Sane/HandlerTest.php
  tests/Sane/HtmlTest.php
  tests/Sane/SaneTest.php
  tests/Sane/SvgTest.php
  tests/Sane/SvgzTest.php
  tests/Sane/TestCase.php
  tests/Sane/XmlTest.php
  tests/Sane/fixtures/html/disallowed/link-subfolder.html
  tests/Sane/fixtures/html/sanitized/link-subfolder.html
  tests/Sane/fixtures/sane/xlink-subfolder.sanitized.svg
  tests/Sane/fixtures/sane/xlink-subfolder.svg
  tests/Sane/fixtures/svg/allowed/internal-source.svg
  tests/Sane/fixtures/svg/allowed/style-url-valid.svg
  tests/Sane/fixtures/svg/allowed/xlink-valid-3.svg
  tests/Sane/fixtures/svg/disallowed/style-url-external.svg
  tests/Sane/fixtures/svg/disallowed/xlink-subfolder.svg
  tests/Sane/fixtures/svg/sanitized/xlink-subfolder.svg
  tests/Sane/fixtures/svgz/disallowed/xlink-subfolder.svg
  tests/Sane/fixtures/svgz/disallowed/xlink-subfolder.svgz
  tests/Sane/fixtures/svgz/sanitized/xlink-subfolder.svg
  tests/Sane/fixtures/xml/allowed/internal-source.xml
  tests/Sane/fixtures/xml/allowed/xlink-valid-3.xml
  tests/Sane/fixtures/xml/disallowed/xlink-subfolder.xml
  tests/Sane/fixtures/xml/sanitized/xlink-subfolder.xml
  tests/Toolkit/DomTest.php
Labels: type: enhancement ✨, type: bug 🐛

#5943 Fix click on dropdown page for pagination component
  panel/src/components/Navigation/Pagination.vue
Labels: type: regression 🚨

#5822 Picklist input for tags and multiselect
  i18n/translations/en.json
  panel/dist/ui/PicklistInput.json
  panel/dist/ui/SelectorInput.json
  panel/lab/components/dropdowns/4_picklist/index.php
  panel/lab/components/dropdowns/4_picklist/index.vue
  panel/lab/components/dropdowns/4_selector/index.php
  panel/lab/components/dropdowns/4_selector/index.vue
  panel/lab/components/inputs/multiselect/index.vue
  panel/lab/components/inputs/picklist/index.php
  panel/lab/components/inputs/picklist/index.vue
  panel/lab/components/tags/1_tag/index.vue
  panel/lab/components/tags/2_tags/index.php
  panel/lab/components/tags/2_tags/index.vue
  panel/src/components/Dropdowns/PicklistDropdown.vue
  panel/src/components/Dropdowns/SelectorDropdown.vue
  panel/src/components/Dropdowns/index.js
  panel/src/components/Forms/Input/MultiselectInput.vue
  panel/src/components/Forms/Input/PicklistInput.vue
  panel/src/components/Forms/Input/TagsInput.vue
  panel/src/components/Forms/Input/index.js
  panel/src/components/Forms/Selector.vue
  panel/src/components/Forms/index.js
  panel/src/components/Navigation/Tags.vue
  panel/src/mixins/props/options.js
Labels: type: enhancement ✨, type: refactoring :recycle:

#5951 Fix structure field footer
  panel/lab/components/tables/1_horizontal/index.vue
  panel/src/components/Layout/Table.vue
Labels: type: regression 🚨

#5967 `k-tabs`: fix badge
  panel/lab/components/tabs/index.vue
  panel/src/components/Layout/Tabs.vue
Labels: type: regression 🚨

#5978 Phase out `k-bar`
  panel/lab/components/collections/1_list/index.vue
  panel/lab/components/collections/2_cards/index.vue
  panel/lab/components/collections/3_cardlets/index.vue
  panel/lab/components/collections/index.php
  panel/src/components/Collection/Collection.vue
  panel/src/components/Forms/Field.vue
  panel/src/components/Forms/Field/BlocksField.vue
  panel/src/components/Forms/Field/LayoutField.vue
  panel/src/components/Forms/Field/StructureField.vue
  panel/src/components/Navigation/Pagination.vue
  panel/src/components/Sections/Section.vue
Labels: type: bug 🐛, type: refactoring :recycle:

#5979 Blocks: keep selected sort order
  panel/src/components/Forms/Blocks/Blocks.vue
Labels: type: regression 🚨

#5976 `$field->permalinksToUrls()`
  config/methods.php
  src/Uuid/Uuid.php
  tests/Content/FieldMethodsTest.php
  tests/Uuid/UuidTest.php
Labels: type: enhancement ✨

#5987 Add missing class aliases
  config/aliases.php
Labels: type: refactoring :recycle:

#5986 Fix HTML rendering bugs
  config/areas/languages/views.php
  panel/lab/basics/design/colors/index.vue
  panel/lab/basics/design/font-family/index.vue
  panel/lab/basics/design/font-size/index.vue
  panel/lab/basics/design/font-weight/index.vue
  panel/lab/basics/design/height/index.vue
  panel/lab/basics/design/rounded/index.vue
  panel/lab/basics/design/shadow/index.vue
  panel/lab/basics/design/spacing/index.vue
  panel/lab/basics/design/z-index/index.vue
  panel/src/components/Forms/Input/CheckboxesInput.vue
  panel/src/components/Forms/Input/RadioInput.vue
  panel/src/components/Forms/Input/TogglesInput.vue
  panel/src/components/Forms/Layouts/LayoutColumn.vue
  panel/src/components/Forms/Layouts/LayoutSelector.vue
  panel/src/components/Layout/Box.vue
  panel/src/components/Layout/Column.vue
  panel/src/components/Layout/Frame/ColorFrame.vue
  panel/src/components/Layout/Table.vue
  src/Panel/ChangesDialog.php
  src/Panel/UserTotpDisableDialog.php
  tests/Toolkit/StrTest.php
Labels: type: bug 🐛, type: refactoring :recycle:

#5989 Block selector: fix for empty groups
  panel/src/components/Forms/Blocks/BlockSelector.vue
Labels: type: bug 🐛

#5990 Object field: fix disabled table style
  panel/src/components/Forms/Field/ObjectField.vue
Labels: type: bug 🐛

#5992 Link field: fix model preview for too long titles
  panel/src/components/Forms/Field/LinkField.vue
Labels: type: bug 🐛

#5991 Slug field: respect custom slug allow from `Str`
  panel/src/helpers/string.js
  panel/src/helpers/string.slug.test.js
  src/Panel/Field.php
  tests/Panel/FieldTest.php
Labels: type: bug 🐛, type: regression 🚨

#5994 Fix header wrapping for fields and sections
  panel/lab/components/field/index.vue
  panel/lab/components/section/index.php
  panel/lab/components/section/index.vue
  panel/src/components/Forms/Field.vue
  panel/src/components/Sections/Section.vue
  panel/src/components/Text/Label.vue
Labels: type: bug 🐛

#5997 Fix ColornameInput for more flexible color notations
  panel/src/components/Forms/Input/ColornameInput.vue
  panel/src/libraries/colors-checks.js
  panel/src/libraries/colors-checks.test.js
  panel/src/libraries/colors-func.js
  panel/src/libraries/colors.js
  panel/src/libraries/colors.test.js
Labels: type: enhancement ✨, type: bug 🐛

#5996 Models fields: add disable style
  panel/lab/components/item/1_list/index.vue
  panel/lab/components/item/2_cards/index.vue
  panel/lab/components/item/3_cardlets/index.vue
  panel/src/components/Collection/Collection.vue
  panel/src/components/Collection/Item.vue
  panel/src/components/Collection/Items.vue
  panel/src/components/Forms/Field/ModelsField.vue
Labels: type: bug 🐛

#6001 Postpone todo comments
  src/Cms/Auth/TotpChallenge.php
  src/Cms/Collections.php
Labels: type: refactoring :recycle:

#6004 More detailed security policy for GitHub
  SECURITY.md
Labels: type: refactoring :recycle:

#6000 `Xml::attr()`: Support empty string as empty value
  config/tags.php
  src/Cms/Helpers.php
  src/Toolkit/Html.php
  src/Toolkit/Xml.php
  tests/Toolkit/HtmlTest.php
  tests/Toolkit/XmlTest.php
Labels: type: enhancement ✨

#6027 Fix slug field in file rename dialog
  config/areas/files/dialogs.php
  panel/lab/components/fields/slug/index.vue
Labels: type: regression 🚨

#6022 Update CONTRIBUTING for new branches
  CONTRIBUTING.md
Labels: type: docs 📝

#6018 Fixes for sticky table headers
  panel/lab/components/blocks/table/index.vue
  panel/src/components/Forms/Blocks/Types/Table.vue
  panel/src/components/Layout/Header.vue
  panel/src/components/View/Panel.vue
Labels: type: bug 🐛

#6009 Slug field: fix wizard button
  panel/src/components/Forms/Field/SlugField.vue
Labels: type: bug 🐛
