Repository getkirby/kirby, pull requests merged in 2024-09, with the labels that each got.

#6642 Fix `site/tree/parents` request for link dialogs
  config/areas/site/requests.php
  panel/src/components/Navigation/PageTree.vue
Labels: type: regression 🚨

#6635 Calendar input: first day of week based on locale
  panel/src/components/Forms/Input/CalendarInput.vue
  panel/src/panel/translation.js
  panel/src/panel/translation.test.js
  src/Panel/View.php
  src/Toolkit/Date.php
  tests/Cms/Translations/TranslationTest.php
  tests/Toolkit/DateTest.php
Labels: type: enhancement ✨

#6638 Improve `$field->isEmpty()`
  src/Content/Field.php
  tests/Content/FieldTest.php
Labels: type: bug 🐛

#6648 Fix docblocks for `$panel.dialog`/`$panel.drawer`
  panel/src/panel/dialog.js
  panel/src/panel/drawer.js
Labels: type: docs 📝

#6652 Video blocks: better attributes for autoplay
  config/blocks/video/video.php
Labels: type: enhancement ✨

#6660 Mark all `*Rules` class methods void
  src/Cms/FileRules.php
  src/Cms/PageRules.php
  src/Cms/SiteRules.php
  src/Cms/UserActions.php
  src/Cms/UserRules.php
  tests/Cms/Files/FileRulesTest.php
  tests/Cms/Pages/PageRulesTest.php
  tests/Cms/Site/SiteRulesTest.php
  tests/Cms/Users/UserRulesTest.php
Labels: type: refactoring :recycle:

#6659 Refactor `LanguageRules`
  src/Cms/Language.php
  src/Cms/LanguageRules.php
  tests/Cms/Languages/LanguageRulesTest.php
Labels: type: refactoring :recycle:

#6618 Exceptions: support named arguments
  src/Exception/AuthException.php
  src/Exception/BadMethodCallException.php
  src/Exception/DuplicateException.php
  src/Exception/ErrorPageException.php
  src/Exception/Exception.php
  src/Exception/InvalidArgumentException.php
  src/Exception/LogicException.php
  src/Exception/NotFoundException.php
  src/Exception/PermissionException.php
  tests/Exception/BadMethodCallExceptionTest.php
  tests/Exception/ExceptionTest.php
  tests/Exception/InvalidArgumentExceptionTest.php
Labels: type: refactoring :recycle:

#6656 Align `User::create()` and `User::role()`
  src/Cms/User.php
Labels: type: enhancement ✨

#6625 Audio & video file preview
  panel/lab/components/filepreviews/2_audio/index.php
  panel/lab/components/filepreviews/2_audio/index.vue
  panel/lab/components/filepreviews/3_image/index.php
  panel/lab/components/filepreviews/3_image/index.vue
  panel/lab/components/filepreviews/4_video/index.php
  panel/lab/components/filepreviews/4_video/index.vue
  panel/lab/components/filepreviews/5_preview-thumb/index.php
  panel/lab/components/filepreviews/5_preview-thumb/index.vue
  panel/lab/components/filepreviews/6_preview-details/index.php
  panel/lab/components/filepreviews/6_preview-details/index.vue
  panel/src/components/Views/Files/AudioFilePreview.vue
  panel/src/components/Views/Files/DefaultFilePreview.vue
  panel/src/components/Views/Files/ImageFilePreview.vue
  panel/src/components/Views/Files/VideoFilePreview.vue
  panel/src/components/Views/Files/index.js
  src/Cms/Core.php
  src/Panel/Ui/FilePreviews/AudioFilePreview.php
  src/Panel/Ui/FilePreviews/VideoFilePreview.php
  tests/Cms/App/AppPluginsTest.php
  tests/Cms/CoreTest.php
  tests/Panel/Ui/FilePreviews/AudioFilePreviewTest.php
  tests/Panel/Ui/FilePreviews/DefaultFilePreviewTest.php
  tests/Panel/Ui/FilePreviews/ImageFilePreviewTest.php
  tests/Panel/Ui/FilePreviews/VideoFilePreviewTest.php
Labels: type: feature 🎉

#6617 `Url::slug()` that obeys `maxlength` option
  config/areas/site/dialogs.php
  src/Cms/PageActions.php
  src/Cms/Url.php
  src/Toolkit/Str.php
  tests/Cms/Facades/UrlTest.php
  tests/Toolkit/StrTest.php
Labels: type: bug 🐛

#6651 `Obj::toKeys()`
  src/Toolkit/Obj.php
  tests/Toolkit/ObjTest.php
Labels: type: enhancement ✨

#6626 Improve code style `Collection::sort()`
  src/Toolkit/Collection.php
Labels: type: refactoring :recycle:

#6655 Improve `Roles` filter methods check
  src/Cms/Roles.php
  tests/Cms/Roles/RolesTest.php
Labels: type: enhancement ✨

#6646 Language view buttons (incl. permission check)
  config/areas/languages/buttons.php
  config/areas/languages/views.php
  config/areas/site/buttons.php
  config/areas/users/buttons.php
  config/areas/users/views.php
  panel/src/components/View/Buttons/LanguagesDropdown.vue
  panel/src/components/View/Buttons/index.js
  src/Panel/Ui/Buttons/LanguageCreateButton.php
  src/Panel/Ui/Buttons/LanguageDeleteButton.php
  src/Panel/Ui/Buttons/LanguageSettingsButton.php
  src/Panel/Ui/Buttons/LanguagesDropdown.php
  tests/Panel/Ui/Buttons/LanguageCreateButtonTest.php
  tests/Panel/Ui/Buttons/LanguageDeleteButtonTest.php
  tests/Panel/Ui/Buttons/LanguageSettingsButtonTest.php
  tests/Panel/Ui/Buttons/LanguagesDropdownTest.php
Labels: type: enhancement ✨, type: regression 🚨

#6669 Page create dialog: allow toggle field
  src/Panel/PageCreateDialog.php
Labels: type: bug 🐛

#6670 Add `avif` to resizable image types
  src/Image/Image.php
Labels: type: enhancement ✨

#6653 Fix `$user->roles($purpose)`
  config/api/routes/users.php
  src/Cms/User.php
  tests/Cms/Users/UserTest.php
Labels: type: enhancement ✨, type: bug 🐛

#6657 Clean up `UserRules`
  src/Cms/UserPermissions.php
  src/Cms/UserRules.php
  tests/Cms/Users/UserRulesTest.php
Labels: type: refactoring :recycle:

#6567 Duplicating page: replace UUIDs with new ones
  src/Cms/PageActions.php
  src/Cms/PageCopy.php
  src/Content/ContentStorageHandler.php
  tests/Cms/Pages/PageCopyTest.php
  tests/Content/ContentStorageHandlerTest.php
  tests/Content/MemoryContentStorageHandlerTest.php
Labels: type: enhancement ✨

#6691 Show offline component only system is not local env
  panel/src/components/Misc/OfflineWarning.vue
Labels: type: bug 🐛

#6643 PageCreateDialog: prevent tmp using actual page
  src/Panel/PageCreateDialog.php
Labels: type: bug 🐛

#6658 Remove roles count check from `UserPermissions`
  src/Cms/UserPermissions.php
  src/Panel/User.php
  tests/Cms/Roles/RolesTest.php
  tests/Panel/UserTest.php
Labels: type: refactoring :recycle:

#6672 Better contrast for current item in light dropdown
  panel/lab/components/dropdowns/1_themes/index.vue
  panel/src/components/Dropdowns/DropdownContent.vue
  panel/src/components/Dropdowns/DropdownItem.vue
Labels: type: a11y 👐

#6693 Fix `User::roles()` for last admin
  src/Cms/User.php
  tests/Cms/Users/UserTest.php
Labels: type: bug 🐛

#6699 Fix default columns for radio input
  panel/src/components/Forms/Input/RadioInput.vue
Labels: type: bug 🐛

#6694 `UserRules::create()` validate roles
  src/Cms/UserRules.php
  tests/Cms/Users/UserRulesTest.php
Labels: type: enhancement ✨

#6668 Multilang permalinks for Writer field
  panel/src/api/pages.js
  panel/src/components/Dialogs/LinkDialog.vue
  panel/src/helpers/link.js
  panel/src/helpers/link.test.js
  src/Uuid/FileUuid.php
  src/Uuid/ModelUuid.php
  src/Uuid/PageUuid.php
  tests/Uuid/FileUuidTest.php
  tests/Uuid/PageUuidTest.php
Labels: type: bug 🐛

#6701 Better content storage `::move()` + new `::copy()`
  src/Cms/FileActions.php
  src/Content/ContentStorageHandler.php
  src/Content/ImmutableMemoryContentStorageHandler.php
  src/Content/PlainTextContentStorageHandler.php
  src/Content/Version.php
  tests/Content/ContentStorageHandlerTest.php
  tests/Content/ImmutableMemoryContentStorageHandlerTest.php
  tests/Content/PlainTextContentStorageHandlerTest.php
  tests/Content/VersionTest.php
Labels: type: refactoring :recycle:
