Repository getkirby/kirby, pull requests merged in 2024-02, with the labels that each got.

#6233 Fix wrapping button group
  panel/lab/components/buttons/4_groups/index.vue
  panel/src/components/Navigation/ButtonGroup.vue
  panel/src/components/Text/Label.vue
Labels: type: bug 🐛

#6207 Improve input disabled styles
  panel/src/components/Forms/Field/LinkField.vue
  panel/src/components/Forms/Input/ChoiceInput.vue
  panel/src/components/Forms/Input/DateInput.vue
  panel/src/components/Forms/Input/TextInput.vue
  panel/src/components/Forms/Input/TimeInput.vue
  panel/src/components/Forms/Input/ToggleInput.vue
Labels: type: bug 🐛

#6234 Fix invalid date in table layout
  panel/lab/components/fieldpreviews/date/index.vue
  panel/lab/components/filepreview/index.vue
  panel/src/components/Forms/Previews/DateFieldPreview.vue
Labels: type: regression 🚨

#6270 Fix prettier setup
  .github/workflows/frontend.yml
  panel/.prettierignore
Labels: type: tests 🧪

#6272 Upgrade GitHub workflow actions
  .github/workflows/backend.yml
  .github/workflows/frontend.yml
Labels: type: tests 🧪

#6271 Disable license dialog in demo mode
  src/Cms/LicenseStatus.php
Labels: type: bug 🐛

#6252 Fix alpha/hue input’s min/max
  panel/src/components/Forms/Input/AlphaInput.vue
  panel/src/components/Forms/Input/HueInput.vue
Labels: type: bug 🐛

#6255 `Colorname` input: unset inherited props
  panel/src/components/Forms/Input/ColornameInput.vue
Labels: type: refactoring :recycle:

#6256 `search` input: unset props
  panel/lab/components/inputs/search/index.vue
  panel/src/components/Forms/Input/SearchInput.vue
Labels: type: bug 🐛

#6287 Lab: docs for `$helpers.string`
  panel/lab/internals/helpers/array/index.vue
  panel/lab/internals/helpers/color/index.vue
  panel/lab/internals/helpers/debounce/index.vue
  panel/lab/internals/helpers/embed/index.vue
  panel/lab/internals/helpers/field/index.vue
  panel/lab/internals/helpers/file/index.vue
  panel/lab/internals/helpers/focus/index.vue
  panel/lab/internals/helpers/isComponent/index.vue
  panel/lab/internals/helpers/isUploadEvent/index.vue
  panel/lab/internals/helpers/keyboard/index.vue
  panel/lab/internals/helpers/link/index.vue
  panel/lab/internals/helpers/object/index.vue
  panel/lab/internals/helpers/page/index.vue
  panel/lab/internals/helpers/queue/index.vue
  panel/lab/internals/helpers/ratio/index.vue
  panel/lab/internals/helpers/regex/index.vue
  panel/lab/internals/helpers/sort/index.vue
  panel/lab/internals/helpers/string/index.vue
  panel/lab/internals/helpers/upload/index.vue
  panel/lab/internals/helpers/url/index.vue
  panel/src/components/Lab/PlaygroundView.vue
  panel/src/helpers/string.js
Labels: type: docs 📝

#6220 Some unit test improvements
  src/Text/KirbyTag.php
  src/Toolkit/Dom.php
  tests/Option/OptionTest.php
  tests/Option/OptionsQueryTest.php
  tests/Query/ArgumentTest.php
  tests/Query/ArgumentsTest.php
  tests/Query/ExpressionTest.php
  tests/Query/QueryDefaultFunctionsTest.php
  tests/Query/QueryTest.php
  tests/Query/SegmentTest.php
  tests/Query/SegmentsTest.php
  tests/Text/DateKirbyTagTest.php
  tests/Text/EmailKirbyTagTest.php
  tests/Text/FileKirbyTagTest.php
  tests/Text/ImageKirbyTagTest.php
  tests/Text/KirbyTagTest.php
  tests/Text/KirbyTagsTest.php
  tests/Text/LinkKirbyTagTest.php
  tests/Text/MarkdownTest.php
  tests/Text/VideoKirbyTagTest.php
  tests/Text/fixtures/inline.html
  tests/Text/fixtures/inline.md
  tests/Toolkit/CollectionTest.php
  tests/Toolkit/ComponentTest.php
  tests/Toolkit/ControllerTest.php
  tests/Toolkit/DateTest.php
  tests/Toolkit/DomTest.php
  tests/Toolkit/ObjTest.php
Labels: type: tests 🧪

#6290 Throw out reviewdog from CI
  .github/workflows/backend.yml
  .github/workflows/frontend.yml
Labels: type: refactoring :recycle:

#6262 Fix to handle invalid PHP version strings
  src/Cms/System/UpdateStatus.php
Labels: type: enhancement ✨, needs: decision 🗳

#6293 `Remote::json()` Psalm conditional return type
  src/Http/Remote.php
Labels: type: tests 🧪

#6292 Fix support for BETWEEN predicate in database class
  src/Database/Query.php
  tests/Database/QueryTest.php
Labels: type: bug 🐛

#6297 Improved parameter binding for inserts and selects
  src/Database/Database.php
  src/Database/Query.php
  tests/Database/DbTest.php
  tests/Database/QueryTest.php
Labels: type: bug 🐛

#6295 Lab: add GitHub source links
  config/areas/lab/views.php
  panel/lab/basics/design/colors/index.php
  panel/lab/basics/design/font-family/index.php
  panel/lab/basics/design/font-size/index.php
  panel/lab/basics/design/font-weight/index.php
  panel/lab/basics/design/height/index.php
  panel/lab/basics/design/opacity/index.php
  panel/lab/basics/design/rounded/index.php
  panel/lab/basics/design/shadow/index.php
  panel/lab/basics/design/spacing/index.php
  panel/lab/basics/design/z-index/index.php
  panel/lab/basics/icons/1_iconset/index.php
  panel/lab/internals/helpers/array/index.php
  panel/lab/internals/helpers/color/index.php
  panel/lab/internals/helpers/debounce/index.php
  panel/lab/internals/helpers/embed/index.php
  panel/lab/internals/helpers/field/index.php
  panel/lab/internals/helpers/file/index.php
  panel/lab/internals/helpers/focus/index.php
  panel/lab/internals/helpers/isComponent/index.php
  panel/lab/internals/helpers/isUploadEvent/index.php
  panel/lab/internals/helpers/keyboard/index.php
  panel/lab/internals/helpers/link/index.php
  panel/lab/internals/helpers/object/index.php
  panel/lab/internals/helpers/queue/index.php
  panel/lab/internals/helpers/ratio/index.php
  panel/lab/internals/helpers/regex/index.php
  panel/lab/internals/helpers/sort/index.php
  panel/lab/internals/helpers/string/index.php
  panel/lab/internals/helpers/upload/index.php
  panel/lab/internals/helpers/url/index.php
  panel/lab/internals/library.colors/index.php
  panel/lab/internals/library.dayjs/1_dayjs/index.php
  panel/lab/internals/library.dayjs/2_format/index.php
  panel/lab/internals/library.dayjs/3_interpret/index.php
  panel/lab/internals/library.dayjs/4_iso/index.php
  panel/lab/internals/library.dayjs/5_validate/index.php
  panel/lab/internals/panel/api/index.php
  panel/lab/internals/panel/config/index.php
  panel/lab/internals/panel/dialog/index.php
  panel/lab/internals/panel/drag/index.php
  panel/lab/internals/panel/drawer/index.php
  panel/lab/internals/panel/dropdown/index.php
  panel/lab/internals/panel/events/index.php
  panel/lab/internals/panel/language/index.php
  panel/lab/internals/panel/notification/index.php
  panel/lab/internals/panel/panel/index.php
  panel/lab/internals/panel/system/index.php
  panel/lab/internals/panel/translation/index.php
  panel/lab/internals/panel/upload/index.php
  panel/lab/internals/panel/urls/index.php
  panel/lab/internals/panel/user/index.php
  panel/lab/internals/panel/view/index.php
  panel/src/components/Lab/PlaygroundView.vue
  src/Panel/Lab/Example.php
Labels: type: docs 📝

#6296 Lab: better call signature for `$helper`
  panel/lab/internals/helpers/array/index.vue
  panel/lab/internals/helpers/string/index.vue
Labels: type: docs 📝

#6206 Clean up `Cms\Blueprint` class
  psalm.xml.dist
  src/Cms/Blueprint.php
Labels: type: refactoring :recycle:, needs: decision 🗳

#6253 Add native validity to `range` input
  panel/lab/components/inputs/alpha/index.vue
  panel/lab/components/inputs/hue/index.vue
  panel/lab/components/inputs/range/index.vue
  panel/src/components/Forms/Input/RangeInput.vue
  panel/src/components/Lab/PlaygroundView.vue
Labels: type: enhancement ✨, type: refactoring :recycle:

#6254 Native validaty for `date`/`time` inputs
  panel/lab/components/inputs/calendar/index.vue
  panel/lab/components/inputs/date/index.vue
  panel/lab/components/inputs/time/index.vue
  panel/lab/components/inputs/timeoptions/index.vue
  panel/src/components/Forms/Input/CalendarInput.vue
  panel/src/components/Forms/Input/DateInput.vue
  panel/src/components/Forms/Input/TimeInput.vue
  panel/src/components/Forms/Input/TimeoptionsInput.vue
  panel/src/libraries/dayjs-iso.js
Labels: type: enhancement ✨, type: bug 🐛, type: refactoring :recycle:

#6302 Fix header offset when no sticky header
  panel/src/components/Drawers/Drawer.vue
  panel/src/components/Layout/Header.vue
Labels: type: bug 🐛

#6315 Fix emoji overflow issue in k-icon-frame
  panel/src/components/Layout/Frame/IconFrame.vue
Labels: type: bug 🐛
