Repository getkirby/kirby, pull requests merged in 2024-12, with the labels that each got.

#6821 Preview tokens 1: Groundwork A (Testing)
  tests/Cms/Pages/PageCacheTest.php
  tests/Cms/Pages/PageRenderTest.php
  tests/Cms/Pages/PageTest.php
  tests/Cms/Pages/fixtures/PageRenderTest/controllers/controller.php
  tests/Cms/Pages/fixtures/PageRenderTest/templates/cache-data.php
  tests/Cms/Pages/fixtures/PageRenderTest/templates/cache-default.php
  tests/Cms/Pages/fixtures/PageRenderTest/templates/cache-disabled.php
  tests/Cms/Pages/fixtures/PageRenderTest/templates/cache-dynamic.php
  tests/Cms/Pages/fixtures/PageRenderTest/templates/cache-expiry.php
  tests/Cms/Pages/fixtures/PageRenderTest/templates/cache-metadata.php
  tests/Cms/Pages/fixtures/PageRenderTest/templates/controller.php
  tests/Cms/Pages/fixtures/PageRenderTest/templates/hook-bar.php
  tests/Cms/Pages/fixtures/PageRenderTest/templates/hook-foo.php
  tests/Cms/Pages/fixtures/PageRenderTest/templates/representation.json.php
  tests/Cms/Pages/fixtures/PageRenderTest/templates/representation.php
Labels: type: refactoring :recycle:

#6822 Preview tokens 2: Groundwork B (Core)
  src/Cms/App.php
  src/Cms/Page.php
  tests/Cms/App/AppTest.php
Labels: type: enhancement ✨, type: bug 🐛

#6823 Preview tokens 3: Preview URL refactoring
  src/Cms/App.php
  src/Cms/Page.php
  src/Cms/Site.php
  src/Content/Version.php
  tests/Cms/App/AppResolveTest.php
  tests/Cms/Pages/PageTest.php
  tests/Content/TestCase.php
  tests/Content/VersionTest.php
Labels: type: refactoring :recycle:

#6824 Preview tokens 4: `VersionId::render()`
  src/Content/VersionId.php
  tests/Content/VersionIdTest.php
Labels: type: feature 🎉

#6825 Preview tokens 5: Version-based rendering
  src/Cms/App.php
  src/Cms/Page.php
  tests/Cms/Pages/PageRenderTest.php
  tests/Cms/Pages/fixtures/PageRenderTest/templates/version-exception.php
  tests/Cms/Pages/fixtures/PageRenderTest/templates/version-recursive.php
  tests/Cms/Pages/fixtures/PageRenderTest/templates/version.php
Labels: type: enhancement ✨, type: refactoring :recycle:

#6828 Preview tokens 6a: Fix preview token of the site model
  src/Content/Version.php
  tests/Content/TestCase.php
  tests/Content/VersionTest.php
Labels: type: bug 🐛

#6829 Preview tokens 7: Main feature
  src/Cms/App.php
  src/Cms/Page.php
  src/Cms/Site.php
  src/Content/Version.php
  tests/Cms/Pages/PageRenderTest.php
  tests/Cms/Pages/PageTest.php
  tests/Content/VersionTest.php
  tests/Panel/Areas/SiteTest.php
Labels: type: enhancement ✨, type: refactoring :recycle:

#6836 Preview tokens 8: New structure for preview tokens
  src/Content/Version.php
  tests/Cms/Pages/PageRenderTest.php
  tests/Cms/Pages/PageTest.php
  tests/Content/VersionTest.php
Labels: type: enhancement ✨

#6838 Gallery block: make CSS selector more specific
  panel/src/components/Forms/Blocks/Types/Gallery.vue
Labels: type: bug 🐛

#6837 Preview tokens 9: Blueprint-based custom preview URLs
  src/Content/Version.php
  tests/Cms/Pages/PageTest.php
  tests/Content/VersionTest.php
Labels: type: enhancement ✨

#6806 [v5] PHP 8.4 support
  .github/workflows/backend.yml
  bootstrap.php
  composer.json
  composer.lock
  dependencies/parsedown-extra/ParsedownExtra.php
  dependencies/parsedown/Parsedown.php
  src/Cms/System.php
  tests/Cms/System/UpdateStatusTest.php
  vendor/claviska/simpleimage/src/claviska/SimpleImage.php
  vendor/composer/installed.json
  vendor/composer/installed.php
Labels: type: enhancement ✨

#6857 Hide language selector for single language
  src/Panel/Ui/Buttons/LanguagesDropdown.php
  tests/Panel/Ui/Buttons/LanguagesDropdownTest.php
Labels: type: regression 🚨

#6855 Fix alt attribute for `FileVersion` instances
  src/Image/Image.php
  tests/Cms/Files/FileVersionTest.php
Labels: type: bug 🐛

#6858 Allow disable all page buttons via `buttons: false`
  src/Cms/Blueprint.php
  src/Panel/Ui/Buttons/ViewButtons.php
  tests/Cms/Blueprints/BlueprintTest.php
  tests/Panel/Ui/Buttons/ViewButtonsTest.php
Labels: type: enhancement ✨

#6859 Improve search input for dark mode
  panel/src/components/Views/SearchView.vue
Labels: type: enhancement ✨

#6856 Fix for homepage preview URLs on proper domains
  src/Content/Version.php
  tests/Content/VersionTest.php
Labels: type: bug 🐛

#6846 Writer toolbar: hide when no buttons
  panel/src/components/Forms/Toolbar/Toolbar.vue
  panel/src/components/Forms/Writer/Toolbar.vue
Labels: type: bug 🐛

#6840 Fix sqlite driver using double quotes for string literals
  src/Database/Sql/Sqlite.php
  tests/Database/Sql/SqliteTest.php
Labels: type: bug 🐛

#6874 Access permissions 1: Refactor access to roles
  config/areas/languages/views.php
  src/Cms/App.php
  src/Cms/AppUsers.php
  src/Cms/File.php
  src/Cms/Page.php
  tests/Cms/App/AppRolesTest.php
  tests/Cms/App/AppUsersTest.php
Labels: type: feature 🎉, type: refactoring :recycle:
