Repository getkirby/kirby, pull requests merged in 2024-05, with the labels that each got.

#6419 Unit test for `$system->isOk()`
  tests/Cms/System/SystemTest.php
Labels: type: tests 🧪

#6431 Code quality improvements
  config/presets/page.php
  config/presets/pages.php
  src/Api/Model.php
  src/Cms/App.php
  src/Cms/AppPlugins.php
  src/Cms/AppTranslations.php
  src/Cms/Auth.php
  src/Cms/Blueprint.php
  src/Cms/FileVersion.php
  src/Cms/LanguageRules.php
  src/Cms/ModelWithContent.php
  src/Cms/PagePicker.php
  src/Database/Sql.php
  src/Filesystem/F.php
  src/Http/Request/Query.php
  src/Panel/Lab/Example.php
  src/Session/Sessions.php
  src/Text/KirbyTag.php
  src/Toolkit/Component.php
  src/Toolkit/Dom.php
  src/Toolkit/Escape.php
  src/Toolkit/Html.php
  src/Toolkit/Str.php
  src/Uuid/BlockUuid.php
  src/Uuid/FieldUuid.php
  src/Uuid/FileUuid.php
  src/Uuid/ModelUuid.php
  src/Uuid/PageUuid.php
  src/Uuid/SiteUuid.php
  src/Uuid/StructureUuid.php
  src/Uuid/UserUuid.php
Labels: type: refactoring :recycle:

#6429 File upload: fix sort number
  panel/src/panel/upload.js
Labels: type: regression 🚨

#6428 Fix tab badges
  panel/src/components/Layout/Tabs.vue
Labels: type: bug 🐛

#6425 CalendarInput: fix when no value
  panel/src/components/Forms/Input/CalendarInput.vue
Labels: type: bug 🐛

#6426 DateInput: fix clearing
  panel/src/components/Forms/Field/DateField.vue
Labels: type: bug 🐛

#6411 DropdownContent: support global events for `click`
  panel/src/components/Dropdowns/DropdownContent.vue
Labels: type: enhancement ✨

#6433 Add `Stringable` interface to classes
  src/Cms/Auth/Status.php
  src/Cms/Block.php
  src/Cms/Event.php
  src/Cms/Language.php
  src/Cms/ModelWithContent.php
  src/Cms/PluginAsset.php
  src/Cms/Responder.php
  src/Cms/Role.php
  src/Content/Field.php
  src/Filesystem/File.php
  src/Filesystem/Filename.php
  src/Http/Params.php
  src/Http/Query.php
  src/Http/Request/Auth.php
  src/Http/Request/Body.php
  src/Http/Request/Query.php
  src/Http/Response.php
  src/Http/Uri.php
  src/Image/Camera.php
  src/Image/Dimensions.php
  src/Image/Location.php
  src/Image/QrCode.php
  src/Template/Slot.php
  src/Template/Template.php
  src/Toolkit/Collection.php
  src/Toolkit/Date.php
  src/Toolkit/View.php
  src/Uuid/Uuid.php
Labels: type: refactoring :recycle:

#6423 Panel notifications: support for theme
  panel/lab/internals/panel/notification/index.vue
  panel/src/panel/modal.test.js
  panel/src/panel/notification.js
  panel/src/panel/notification.test.js
Labels: type: enhancement ✨

#6424 Upload dialog: improve preview icon
  panel/lab/components/uploads/1_upload-items/index.php
  panel/lab/components/uploads/1_upload-items/index.vue
  panel/lab/components/uploads/2_upload-item/index.php
  panel/lab/components/uploads/2_upload-item/index.vue
  panel/lab/components/uploads/3_upload-item-preview/index.php
  panel/lab/components/uploads/3_upload-item-preview/index.vue
  panel/src/components/Dialogs/UploadDialog.vue
  panel/src/components/Dialogs/UploadReplaceDialog.vue
  panel/src/components/Uploads/UploadItem.vue
  panel/src/components/Uploads/UploadItemPreview.vue
  panel/src/components/Uploads/UploadItems.vue
  panel/src/components/Uploads/index.js
  panel/src/components/index.js
Labels: type: enhancement ✨

#6432 Make `contentToken` independent from `num` in root
  src/Cms/App.php
  tests/Cms/App/AppTest.php
  tests/Cms/Pages/PageTest.php
Labels: type: performance ⚡️

#6359 File: fix not creating PDF as different format
  src/Cms/FileActions.php
Labels: type: bug 🐛

#6445 QrCode: `border` argument
  src/Image/QrCode.php
  tests/Image/QrCodeTest.php
  tests/Image/fixtures/qr/image-border.png
Labels: type: enhancement ✨

#6365 Login lab examples
  panel/lab/components/login/login-code/index.php
  panel/lab/components/login/login-code/index.vue
  panel/lab/components/login/login/index.php
  panel/lab/components/login/login/index.vue
  panel/src/components/Forms/Login.vue
  panel/src/components/Forms/LoginCode.vue
  panel/src/components/Views/Login/LoginView.vue
Labels: type: refactoring :recycle:, type: docs 📝

#6393 Custom Panel view buttons
  config/areas/languages/views.php
  config/areas/system/views.php
  config/areas/users/views.php
  panel/public/js/plugins.js
  panel/src/components/Dropdowns/index.js
  panel/src/components/View/Buttons/AddButton.vue
  panel/src/components/View/Buttons/AddLanguagesButton.vue
  panel/src/components/View/Buttons/AddUsersButton.vue
  panel/src/components/View/Buttons/Buttons.vue
  panel/src/components/View/Buttons/LanguagesButton.vue
  panel/src/components/View/Buttons/PreviewButton.vue
  panel/src/components/View/Buttons/RemoveButton.vue
  panel/src/components/View/Buttons/RemoveLanguageButton.vue
  panel/src/components/View/Buttons/SettingsButton.vue
  panel/src/components/View/Buttons/StatusButton.vue
  panel/src/components/View/Buttons/ThemeButton.vue
  panel/src/components/View/Buttons/index.js
  panel/src/components/View/index.js
  panel/src/components/Views/Files/FileView.vue
  panel/src/components/Views/Languages/LanguageView.vue
  panel/src/components/Views/Languages/LanguagesView.vue
  panel/src/components/Views/ModelView.vue
  panel/src/components/Views/Pages/PageView.vue
  panel/src/components/Views/Pages/SiteView.vue
  panel/src/components/Views/System/SystemView.vue
  panel/src/components/Views/Users/UserView.vue
  panel/src/components/Views/Users/UsersView.vue
  panel/src/components/Views/index.js
  panel/src/helpers/page.js
  panel/src/panel/plugins.js
  panel/src/panel/plugins.test.js
  panel/src/panel/view.js
  src/Cms/Blueprint.php
  src/Panel/File.php
  src/Panel/Model.php
  src/Panel/Page.php
  src/Panel/Site.php
  src/Panel/User.php
  tests/Cms/Blueprints/BlueprintTest.php
  tests/Panel/FileTest.php
  tests/Panel/ModelTest.php
  tests/Panel/PageTest.php
  tests/Panel/SiteTest.php
  tests/Panel/UserTest.php
Labels: type: feature 🎉

#6337 Plugin registration: named arguments
  src/Cms/AppPlugins.php
  src/Cms/Helpers.php
  src/Cms/Plugin.php
  tests/Cms/Plugins/PluginTest.php
Labels: type: enhancement ✨, type: refactoring :recycle:

#6453 Fix non existing file links
  src/Cms/Media.php
  tests/Cms/Media/MediaTest.php
Labels: type: bug 🐛

#6459 Select field: remove undocumented empty prop
  config/fields/radio.php
  config/fields/select.php
  panel/lab/components/inputs/select/index.vue
  panel/src/components/Forms/Input/SelectInput.vue
Labels: type: enhancement ✨, type: refactoring :recycle:
