Repository getkirby/kirby, pull requests merged in 2024-07, with the labels that each got.

#6512 Changes A: `k-form-controls`
  i18n/translations/en.json
  panel/lab/components/formcontrols/index.php
  panel/lab/components/formcontrols/index.vue
  panel/src/components/Forms/Controls/Controls.vue
  panel/src/components/Forms/index.js
  panel/src/components/Lab/PlaygroundView.vue
Labels: type: refactoring :recycle:

#6513 Changes B: `panel.content`
  panel/src/components/Forms/FormButtons.vue
  panel/src/components/Navigation/ModelTabs.vue
  panel/src/components/Sections/FieldsSection.vue
  panel/src/components/Sections/Sections.vue
  panel/src/components/Views/Files/FileView.vue
  panel/src/components/Views/Pages/PageView.vue
  panel/src/components/Views/Pages/SiteView.vue
  panel/src/components/Views/Users/UserView.vue
  panel/src/panel/content.js
  panel/src/panel/panel.js
Labels: type: enhancement ✨

#6515 Changes C: `panel.content.isLocked`
  panel/src/components/Forms/FormButtons.vue
  panel/src/components/View/Buttons/SettingsButton.vue
  panel/src/components/View/Buttons/StatusButton.vue
  panel/src/components/Views/ModelView.vue
  panel/src/panel/content.js
  panel/src/panel/view.js
Labels: type: refactoring :recycle:

#6522 Vite: make HTTPS default
  panel/.env.example
  panel/vite.config.mjs
Labels: type: refactoring :recycle:, needs: two-person review 🧑‍🤝‍🧑

#6518 New `google` icon
  panel/public/img/icons.svg
Labels: type: feature 🎉

#6532 `View::data()` use `Language::toArray()`
  src/Cms/Language.php
  src/Panel/View.php
  tests/Panel/ViewTest.php
Labels: type: refactoring :recycle:

#6528 Panel theme: allow resetting to system default
  i18n/translations/en.json
  panel/src/components/View/Buttons/ThemeButton.vue
  panel/src/panel/theme.js
Labels: type: enhancement ✨

#6527 Remove container query polyfill
  panel/package-lock.json
  panel/package.json
  panel/src/index.js
Labels: type: refactoring :recycle:

#6517 Changes D: set all values onInput
  panel/src/components/Sections/FieldsSection.vue
  panel/src/panel/content.js
Labels: type: refactoring :recycle:

#6535 Make `Api\Upload` readonly
  src/Api/Upload.php
Labels: type: refactoring :recycle:

#6553 `App::io()`: redirect `NotFoundException` to error
  src/Cms/App.php
Labels: type: enhancement ✨

#6539 Buttons 1: basic `Panel\Ui` component classes
  src/Panel/Ui/Button.php
  src/Panel/Ui/Component.php
  tests/Panel/Ui/ButtonTest.php
  tests/Panel/Ui/ComponentTest.php
Labels: type: refactoring :recycle:

#6540 Buttons 2: `k-view-button` component
  panel/lab/components/buttons/5_view-button/index.php
  panel/lab/components/buttons/5_view-button/index.vue
  panel/src/components/View/Buttons/Button.vue
  panel/src/components/View/Buttons/index.js
Labels: type: enhancement ✨

#6550 Link field preview: fix overflow
  panel/lab/components/fieldpreviews/link/index.vue
  panel/src/components/Forms/Previews/LinkFieldPreview.vue
Labels: type: bug 🐛

#6552 Tags input: don't open dropdown when max reached
  panel/src/components/Forms/Input/TagsInput.vue
Labels: type: bug 🐛

#6554 `k-link-field`: preselect current page for files
  config/areas/site/requests.php
  panel/lab/components/browsers/files/index.vue
  panel/lab/components/trees/index.vue
  panel/src/components/Forms/Field/LinkField.vue
  panel/src/components/Navigation/FileBrowser.vue
  panel/src/components/Navigation/PageTree.vue
  panel/src/components/Navigation/Tree.vue
  src/Panel/File.php
  src/Panel/Page.php
  src/Panel/Site.php
  src/Panel/User.php
Labels: type: enhancement ✨

#6551 Text block: fix padding for textarea input
  panel/src/components/Forms/Blocks/Types/Text.vue
Labels: type: bug 🐛

#6541 Buttons 3: Panel area `buttons` extension
  src/Panel/Panel.php
  src/Panel/View.php
  tests/Panel/PanelTest.php
Labels: type: enhancement ✨

#6529 Turn `panel` JS modules fully reactive
  panel/src/panel/activiation.js
  panel/src/panel/content.js
  panel/src/panel/dialog.js
  panel/src/panel/drag.js
  panel/src/panel/drawer.js
  panel/src/panel/dropdown.js
  panel/src/panel/feature.js
  panel/src/panel/history.js
  panel/src/panel/language.js
  panel/src/panel/menu.js
  panel/src/panel/modal.js
  panel/src/panel/notification.js
  panel/src/panel/state.js
  panel/src/panel/theme.js
  panel/src/panel/translation.js
  panel/src/panel/upload.js
  panel/src/panel/view.js
Labels: type: refactoring :recycle:

#6543 Buttons 5: Use `k-view-button` for view buttons
  panel/src/components/View/Buttons/AddButton.vue
  panel/src/components/View/Buttons/AddLanguagesButton.vue
  panel/src/components/View/Buttons/AddUsersButton.vue
  panel/src/components/View/Buttons/LanguagesButton.vue
  panel/src/components/View/Buttons/PreviewButton.vue
  panel/src/components/View/Buttons/RemoveButton.vue
  panel/src/components/View/Buttons/RemoveLanguageButton.vue
  panel/src/components/View/Buttons/SettingsButton.vue
  panel/src/components/View/Buttons/StatusButton.vue
  panel/src/components/View/Buttons/ThemeButton.vue
Labels: type: refactoring :recycle:

#6559 Fix overflowing topbar with very long breadcrumb
  panel/src/components/Navigation/Breadcrumb.vue
  panel/src/components/View/Topbar.vue
Labels: type: bug 🐛

#6555 `A::random()`: exception if $count exceeds array
  src/Toolkit/A.php
  tests/Toolkit/ATest.php
Labels: type: enhancement ✨

#6563 Models dialogs: use choice input instead icons
  panel/src/components/Dialogs/ModelsDialog.vue
Labels: type: enhancement ✨

#6558 Fix `focus` helper for non-native inputs
  panel/src/components/Forms/Field/BlocksField.vue
  panel/src/components/Forms/Field/LayoutField.vue
  panel/src/components/Forms/Input/TagsInput.vue
  panel/src/helpers/focus.js
Labels: type: bug 🐛

#6566 UUIDs: case-insensitive IDs
  src/Uuid/Uuid.php
  tests/Uuid/UuidTest.php
Labels: type: enhancement ✨, type: bug 🐛

#6562 Writer field: fix content with non-breaking space
  config/fields/writer.php
Labels: type: bug 🐛

#6556 `k-button`: add `aria-label`
  panel/src/components/Navigation/Button.vue
Labels: type: a11y 👐

#6542 Buttons 4: View button PHP classes
  src/Panel/Model.php
  src/Panel/Ui/Button.php
  src/Panel/Ui/Buttons/ViewButton.php
  src/Panel/Ui/Buttons/ViewButtons.php
  tests/Panel/ModelTest.php
  tests/Panel/Ui/Buttons/ViewButtonTest.php
  tests/Panel/Ui/Buttons/ViewButtonsTest.php
Labels: type: enhancement ✨

#6545 Buttons 7: Backend classes for core view buttons
  src/Panel/Ui/Buttons/LanguagesButton.php
  src/Panel/Ui/Buttons/PageStatusButton.php
  src/Panel/Ui/Buttons/PreviewButton.php
  src/Panel/Ui/Buttons/SettingsButton.php
  tests/Panel/Ui/Buttons/LanguagesButtonTest.php
  tests/Panel/Ui/Buttons/PageStatusButtonTest.php
  tests/Panel/Ui/Buttons/PreviewButtonTest.php
  tests/Panel/Ui/Buttons/SettingsButtonTest.php
Labels: type: enhancement ✨

#6560 Fix `new Uri()` for relative URLs with param colon
  src/Http/Environment.php
  src/Http/Uri.php
  tests/Http/EnvironmentTest.php
  tests/Http/UriTest.php
Labels: type: bug 🐛

#6546 Buttons 8: Connect frontend with view button classes
  config/areas/account.php
  config/areas/account/buttons.php
  config/areas/files/buttons.php
  config/areas/languages.php
  config/areas/languages/buttons.php
  config/areas/languages/views.php
  config/areas/site.php
  config/areas/site/buttons.php
  config/areas/system/views.php
  config/areas/users.php
  config/areas/users/buttons.php
  config/areas/users/views.php
  panel/src/components/View/Buttons/Buttons.vue
  panel/src/components/View/Buttons/LanguagesButton.vue
  panel/src/components/View/Buttons/SettingsButton.vue
  panel/src/components/View/Buttons/StatusButton.vue
  panel/src/components/View/Buttons/ThemeButton.vue
  panel/src/components/Views/Languages/LanguageView.vue
  panel/src/components/Views/Pages/PageView.vue
  phpunit.xml.dist
  src/Panel/File.php
  src/Panel/Model.php
  src/Panel/Page.php
  src/Panel/Site.php
  src/Panel/User.php
  tests/Panel/Areas/SiteTest.php
  tests/Panel/FileTest.php
  tests/Panel/PageTest.php
  tests/Panel/SiteTest.php
  tests/Panel/UserTest.php
Labels: type: feature 🎉

#6547 Buttons 9: Use view button from backend for Lab
  config/areas/lab/views.php
  panel/lab/components/buttons/5_view-button/index.vue
  panel/src/components/Lab/DocsView.vue
  panel/src/components/Lab/PlaygroundView.vue
  panel/src/components/View/Buttons/AddButton.vue
  panel/src/components/View/Buttons/AddLanguagesButton.vue
  panel/src/components/View/Buttons/AddUsersButton.vue
  panel/src/components/View/Buttons/PreviewButton.vue
  panel/src/components/View/Buttons/RemoveButton.vue
  panel/src/components/View/Buttons/RemoveLanguageButton.vue
  panel/src/components/View/Buttons/index.js
  phpunit.xml.dist
Labels: type: refactoring :recycle:

#6571 Models fields: default empty string for single
  i18n/translations/en.json
  panel/src/components/Forms/Field/FilesField.vue
  panel/src/components/Forms/Field/PagesField.vue
  panel/src/components/Forms/Field/UsersField.vue
Labels: type: enhancement ✨

#6312 Add language specific UUID URLs
  src/Cms/LanguageRouter.php
  tests/Cms/Languages/LanguageRouterTest.php
Labels: type: bug 🐛

#6430 Image blocks: add pattern background
  i18n/translations/en.json
  panel/lab/components/block/3_figure/index.vue
  panel/lab/components/frames/4_color/index.vue
  panel/src/components/Forms/Blocks/Block.vue
  panel/src/components/Forms/Blocks/Elements/BlockBackgroundDropdown.vue
  panel/src/components/Forms/Blocks/Elements/BlockFigure.vue
  panel/src/components/Forms/Blocks/Elements/BlockFigureCaption.vue
  panel/src/components/Forms/Blocks/Types/Fields.vue
  panel/src/components/Forms/Blocks/Types/Gallery.vue
  panel/src/components/Forms/Blocks/Types/Image.vue
  panel/src/components/Forms/Blocks/index.js
  panel/src/components/Layout/Frame/ColorFrame.vue
Labels: type: enhancement ✨

#6583 `rawvalues` option for pages section tables
  config/sections/mixins/layout.php
Labels: type: regression 🚨

#6590 Unlink tmp file for failed uploads
  src/Api/Upload.php
  tests/Api/UploadTest.php
Labels: type: enhancement ✨, type: bug 🐛

#6574 Previews 1 - `filePreviews` extension
  src/Cms/AppPlugins.php
  src/Cms/Core.php
  tests/Cms/App/AppPluginsTest.php
  tests/Cms/CoreTest.php
Labels: type: feature 🎉
