Repository getkirby/kirby, pull requests merged in 2024-10, with the labels that each got.

#6710 `Search` Panel controller class
  config/areas/site/searches.php
  config/areas/users/searches.php
  src/Panel/Controller/Search.php
  tests/Panel/Controller/SearchTest.php
Labels: type: bug 🐛, type: refactoring :recycle:, type: tests 🧪

#6650 `api.methodOverwrite` config option and check
  config/api/routes/system.php
  i18n/translations/en.json
  panel/src/api/index.js
  panel/src/components/Views/System/SystemSecurity.vue
  src/Panel/View.php
Labels: type: enhancement ✨

#6717 Move page: allow parent without any pages sections
  src/Cms/PageRules.php
  tests/Cms/Pages/PageRulesTest.php
Labels: type: enhancement ✨, type: bug 🐛

#6720 Fix cache for $page->isListable() etc
  src/Cms/File.php
  src/Cms/Page.php
  tests/Form/Fields/Mixins/PagePickerMixinTest.php
Labels: type: bug 🐛, needs: two-person review 🧑‍🤝‍🧑

#6723 Normalize license code
  src/Cms/License.php
  tests/Cms/System/LicenseTest.php
Labels: type: enhancement ✨

#6726 Fix `PageRules::move()`
  i18n/translations/en.json
  src/Cms/PageRules.php
  tests/Cms/Pages/PageRulesTest.php
Labels: type: regression 🚨, critical: roadblock 🚧, needs: two-person review 🧑‍🤝‍🧑

#6729 Fix `PageRules::move()` one more time
  src/Cms/PageRules.php
  tests/Cms/Pages/PageRulesTest.php
Labels: type: bug 🐛

#6709 `PageTree` controller class
  config/areas/site/requests.php
  src/Panel/Controller/PageTree.php
  tests/Panel/Controller/PageTreeTest.php
Labels: type: refactoring :recycle:, type: tests 🧪

#6654 `Panel\Field::role()` allow passing `$roles`
  config/areas/users/dialogs.php
  config/areas/users/views.php
  panel/src/components/Views/Users/UserAvatar.vue
  panel/src/components/Views/Users/UserProfile.vue
  panel/src/components/Views/Users/UserView.vue
  panel/src/components/Views/Users/UsersView.vue
  src/Cms/Roles.php
  src/Cms/User.php
  src/Cms/UserRules.php
  src/Panel/Field.php
  src/Panel/User.php
  tests/Cms/Users/UserTest.php
  tests/Panel/Areas/UsersDialogsTest.php
Labels: type: enhancement ✨, critical: roadblock 🚧

#6755 Badge for `k-button`
  config/areas/site/buttons.php
  panel/lab/components/buttons/4_badge/index.vue
  panel/lab/components/buttons/5_groups/index.php
  panel/lab/components/buttons/5_groups/index.vue
  panel/lab/components/buttons/6_view-button/index.php
  panel/lab/components/buttons/6_view-button/index.vue
  panel/src/components/Layout/Tabs.vue
  panel/src/components/Navigation/Button.vue
  src/Panel/File.php
  src/Panel/Page.php
  src/Panel/Site.php
  src/Panel/Ui/Button.php
  src/Panel/Ui/Buttons/LanguagesDropdown.php
  src/Panel/Ui/Buttons/ViewButton.php
  src/Panel/User.php
Labels: type: enhancement ✨

#6760 Rename `VersionId::published()` to `::latest()`
  src/Cms/File.php
  src/Cms/ModelWithContent.php
  src/Cms/PageActions.php
  src/Cms/System.php
  src/Cms/User.php
  src/Content/Changes.php
  src/Content/PlainTextContentStorageHandler.php
  src/Content/Version.php
  src/Content/VersionId.php
  src/Panel/Controller/Changes.php
  src/Panel/Model.php
  tests/Cms/Files/FileActionsTest.php
  tests/Cms/Models/ModelWithContentTest.php
  tests/Cms/Pages/PageActionsTest.php
  tests/Content/ContentStorageHandlerTest.php
  tests/Content/ImmutableMemoryContentStorageHandlerTest.php
  tests/Content/MemoryContentStorageHandlerTest.php
  tests/Content/PlainTextContentStorageHandlerTest.php
  tests/Content/VersionIdTest.php
  tests/Content/VersionTest.php
Labels: type: refactoring :recycle:

#6762 LanguagesDropdown: run via Fiber route
  config/areas/account/dropdowns.php
  config/areas/files/dropdowns.php
  config/areas/site/buttons.php
  config/areas/site/dropdowns.php
  config/areas/users/dropdowns.php
  panel/src/components/View/Buttons/LanguagesDropdown.vue
  src/Panel/Ui/Buttons/LanguagesDropdown.php
  tests/Panel/Areas/AccountDropdownsTest.php
  tests/Panel/Areas/AreaTestCase.php
  tests/Panel/Areas/FileDropdownsTest.php
  tests/Panel/Areas/SiteDropdownsTest.php
  tests/Panel/Areas/UserDropdownsTest.php
  tests/Panel/Ui/Buttons/LanguagesDropdownTest.php
Labels: type: refactoring :recycle:

#6765 Languages dropdown: badge for translation changes
  panel/src/components/Layout/Tabs.vue
  panel/src/components/Navigation/Button.vue
  panel/src/components/View/Buttons/LanguagesDropdown.vue
  src/Panel/Ui/Buttons/LanguagesDropdown.php
  tests/Panel/Ui/Buttons/LanguagesDropdownTest.php
Labels: type: enhancement ✨

#6773 Fix creating first user on installation
  src/Cms/UserRules.php
  tests/Cms/Users/UserRulesTest.php
Labels: type: bug 🐛
