Repository getkirby/kirby, pull requests merged in 2024-04, with the labels that each got.

#6376 New `callback` validation
  src/Toolkit/V.php
  tests/Toolkit/VTest.php
Labels: type: feature 🎉

#6382 Writer: support for node and mark views
  panel/src/components/Forms/Writer/Editor.js
  panel/src/components/Forms/Writer/Extensions.js
Labels: type: feature 🎉

#6375 Require PHP 8.2
  .github/workflows/backend.yml
  .github/workflows/frontend.yml
  .php-cs-fixer.dist.php
  bootstrap.php
  composer.json
  composer.lock
  config/components.php
  src/Cms/FileRules.php
  src/Cms/System.php
  src/Database/Sql.php
  src/Toolkit/Dom.php
  vendor/composer/installed.php
Labels: type: refactoring :recycle:

#6379 Fix table column regressions
  config/sections/mixins/layout.php
  panel/src/components/Layout/Table.vue
  panel/src/components/Layout/TableCell.vue
Labels: type: regression 🚨

#6391 Type hinting for collections
  src/Blueprint/Collection.php
  src/Cms/Block.php
  src/Cms/Blocks.php
  src/Cms/Collection.php
  src/Cms/Fieldset.php
  src/Cms/Fieldsets.php
  src/Cms/File.php
  src/Cms/Files.php
  src/Cms/HasSiblings.php
  src/Cms/Item.php
  src/Cms/Items.php
  src/Cms/Language.php
  src/Cms/Languages.php
  src/Cms/Layout.php
  src/Cms/LayoutColumn.php
  src/Cms/LayoutColumns.php
  src/Cms/Layouts.php
  src/Cms/NestCollection.php
  src/Cms/Page.php
  src/Cms/PageSiblings.php
  src/Cms/Pages.php
  src/Cms/PluginAssets.php
  src/Cms/Roles.php
  src/Cms/Structure.php
  src/Cms/StructureObject.php
  src/Cms/Translations.php
  src/Cms/User.php
  src/Cms/Users.php
  src/Form/FieldClass.php
  src/Form/Fields.php
  src/Http/Path.php
  src/Option/Options.php
  src/Query/Arguments.php
  src/Query/Segments.php
  src/Toolkit/Collection.php
  src/Toolkit/Iterator.php
  tests/Toolkit/CollectionTest.php
Labels: type: refactoring :recycle:

#6396 Upgrade to eslint 9
  panel/.eslintrc.js
  panel/eslint.config.mjs
  panel/package-lock.json
  panel/package.json
  panel/src/components/Dialogs/LicenseDialog.vue
  panel/src/components/Dialogs/SearchDialog.vue
  panel/src/components/Forms/Field/ObjectField.vue
  panel/src/components/Forms/FormButtons.vue
  panel/src/components/Forms/Input/ColornameInput.vue
  panel/src/components/Forms/Writer/Utils/markPasteRule.js
  panel/src/components/Navigation/Pagination.vue
  panel/src/components/Views/SearchView.vue
  panel/src/helpers/embed.js
  panel/src/helpers/link.js
  panel/src/helpers/upload.js
  panel/src/helpers/url.js
  panel/src/store/modules/content.js
Labels: type: tests 🧪

#6387 `k-draggable` directly built on top of SortableJS
  panel/lab/components/draggables/index.vue
  panel/lab/components/tags/2_tags/index.vue
  panel/package-lock.json
  panel/package.json
  panel/src/components/Forms/Blocks/Blocks.vue
  panel/src/components/Forms/Input/WriterInput.vue
  panel/src/components/Forms/Layouts/Layouts.vue
  panel/src/components/Misc/Draggable.vue
  panel/src/components/Navigation/Tags.vue
Labels: type: refactoring :recycle:, needs: two-person review 🧑‍🤝‍🧑

#6395 Update searches.php: Fixing panel search when uuids are disabled
  config/areas/site/searches.php
Labels: type: bug 🐛

#6405 Update check: Support for new license model
  src/Cms/System/UpdateStatus.php
  tests/Cms/System/UpdateStatusTest.php
  tests/Cms/System/fixtures/UpdateStatusTest/getkirby.com/security.json
  tests/Cms/System/fixtures/UpdateStatusTest/logic/basic.json
Labels: type: enhancement ✨

#6374 New text vertical align icons
  panel/public/img/icons.svg
Labels: type: enhancement ✨

#6383 Editor: add `insertNode` util
  panel/src/components/Forms/Writer/Nodes/HardBreak.js
  panel/src/components/Forms/Writer/Nodes/HorizontalRule.js
  panel/src/components/Forms/Writer/Utils/index.js
  panel/src/components/Forms/Writer/Utils/insertNode.js
Labels: type: enhancement ✨

#6385 Fix `nodeInputRule`
  panel/src/components/Forms/Writer/Nodes/HorizontalRule.js
  panel/src/components/Forms/Writer/Utils/nodeInputRule.js
Labels: type: bug 🐛

#6386 Writer: fix nodes for `inline: true`
  panel/src/components/Forms/Writer/Writer.vue
Labels: type: bug 🐛

#6407 CSS `data-theme` with color names
  panel/lab/basics/utilities/theme/index.vue
  panel/src/styles/utilities/theme.css
Labels: type: enhancement ✨

#6394 `k-button`: New `theme` notations w/ `-icon` suffix for only colored icon
  panel/lab/components/buttons/2_themes/index.php
  panel/lab/components/buttons/2_themes/index.vue
  panel/src/components/Navigation/Button.vue
  panel/src/components/Views/Pages/PageView.vue
  panel/src/helpers/page.js
  panel/src/styles/utilities/theme.css
Labels: type: enhancement ✨

#6410 Remove deprecated Content methods
  src/Cms/File.php
  src/Cms/Helpers.php
  src/Cms/ModelWithContent.php
  src/Cms/Page.php
  src/Cms/Site.php
  src/Cms/User.php
  tests/Cms/Models/ModelWithContentTest.php
Labels: type: refactoring :recycle:

#6413 Video KirbyTag: support `disablepictureinpicture`
  config/tags.php
  tests/Text/VideoKirbyTagTest.php
Labels: type: enhancement ✨

#6415 Remove server allowlist
  i18n/translations/en.json
  src/Cms/System.php
  tests/Cms/Api/routes/SystemRoutesTest.php
  tests/Cms/System/SystemTest.php
  tests/Panel/Areas/InstallationTest.php
Labels: type: enhancement ✨

#6416 System view: copy info
  config/areas/system/views.php
  i18n/translations/en.json
  panel/src/components/Views/System/SystemView.vue
  src/Cms/System.php
  tests/Cms/System/SystemTest.php
Labels: type: feature 🎉

#6412 Merge `site` controller with page controllers
  src/Cms/App.php
  tests/Cms/App/AppTest.php
Labels: type: enhancement ✨

#6417 DRY button props
  panel/src/components/Dropdowns/DropdownItem.vue
  panel/src/components/Navigation/Button.vue
  panel/src/components/Navigation/Link.vue
Labels: type: refactoring :recycle:

#6406 Fix email dialog title prop translation
  panel/src/components/Dialogs/EmailDialog.vue
  panel/src/components/Forms/Toolbar/EmailDialog.vue
Labels: type: enhancement ✨

#6414 Page section: show Add based on `create` status
  config/sections/pages.php
  tests/Cms/Sections/PagesSectionTest.php
Labels: type: enhancement ✨
