Repository getkirby/kirby, pull requests merged in 2024-06, with the labels that each got.

#6463 Move all login components into same location
  panel/lab/components/login/1_login-form/index.php
  panel/lab/components/login/1_login-form/index.vue
  panel/lab/components/login/2_login-code-form/index.php
  panel/lab/components/login/2_login-code-form/index.vue
  panel/lab/components/login/login-code/index.php
  panel/lab/components/login/login/index.php
  panel/src/components/Forms/index.js
  panel/src/components/Views/Files/index.js
  panel/src/components/Views/Installation/InstallationView.vue
  panel/src/components/Views/Installation/index.js
  panel/src/components/Views/Languages/index.js
  panel/src/components/Views/Login/LoginAlert.vue
  panel/src/components/Views/Login/LoginCodeForm.vue
  panel/src/components/Views/Login/LoginForm.vue
  panel/src/components/Views/Login/LoginView.vue
  panel/src/components/Views/Login/index.js
  panel/src/components/Views/Pages/index.js
  panel/src/components/Views/System/index.js
  panel/src/components/Views/Users/ResetPasswordView.vue
  panel/src/components/Views/Users/UserInfo.vue
  panel/src/components/Views/Users/index.js
  panel/src/components/Views/index.js
Labels: type: refactoring :recycle:

#6462 Upload dialog: fix allowed characters for filename
  panel/src/components/Uploads/UploadItem.vue
  panel/src/helpers/string.js
  panel/src/helpers/string.slug.test.js
  src/Cms/FileActions.php
  src/Filesystem/F.php
  tests/Filesystem/FTest.php
  tests/Toolkit/StrTest.php
Labels: type: bug 🐛

#6452 fix line break when label in block preview fields is too long
  panel/src/components/Forms/Blocks/Types/Fields.vue
Labels: type: bug 🐛

#6475 Replace `get_class()` with `::class`
  src/Api/Api.php
  src/Api/Model.php
  src/Cms/App.php
  src/Cms/AppErrors.php
  src/Option/OptionsQuery.php
  src/Parsley/Parsley.php
  src/Sane/Sane.php
  src/Uuid/Uuid.php
  tests/Database/QueryTest.php
  tests/Image/Darkroom/GdLibTest.php
  tests/Image/Darkroom/ImageMagickTest.php
Labels: type: refactoring :recycle:

#6479 Revert: deprecating `this.$helper.object.clone`
  panel/lab/components/stats/1_stats/index.vue
  panel/src/components/Forms/Blocks/Blocks.vue
  panel/src/components/Forms/Field/StructureField.vue
  panel/src/components/Forms/Input/TagsInput.vue
  panel/src/components/Forms/Layouts/Layouts.vue
  panel/src/components/Navigation/Tags.vue
  panel/src/components/Views/System/SystemSecurity.vue
  panel/src/helpers/object.js
Labels: type: refactoring :recycle:

#6478 Draggable: fix footer
  panel/src/components/Misc/Draggable.vue
Labels: type: bug 🐛, type: refactoring :recycle:

#6476 Use modern string functions
  config/components.php
  src/Cms/AppCaches.php
  src/Cms/AppPlugins.php
  src/Cms/HasFiles.php
  src/Cms/Pages.php
  src/Cms/Roles.php
  src/Database/Sql.php
  src/Filesystem/Dir.php
  src/Filesystem/F.php
  src/Http/Cookie.php
  src/Http/Environment.php
  src/Http/Params.php
  src/Http/Request.php
  src/Http/Request/Body.php
  src/Http/Response.php
  src/Http/Route.php
  src/Http/Uri.php
  src/Http/Url.php
  src/Query/Argument.php
  src/Text/KirbyTag.php
  src/Toolkit/A.php
  src/Toolkit/Collection.php
  src/Toolkit/Str.php
  src/Toolkit/Xml.php
  tests/Panel/AssetsTest.php
Labels: type: refactoring :recycle:

#6480 Models sections: non-mutating `items` computed
  panel/src/components/Sections/FilesSection.vue
  panel/src/components/Sections/PagesSection.vue
Labels: type: refactoring :recycle:

#6487 Fix menu blur when not inside Panel
  panel/src/panel/menu.js
Labels: type: bug 🐛

#6493 `Filesystem\Mime`: more readable if logic
  src/Filesystem/Mime.php
  tests/Filesystem/MimeTest.php
Labels: type: refactoring :recycle:

#6503 `License`: Allow access to the version history
  src/Cms/License.php
Labels: type: enhancement ✨

#6516 Load .env file in Vite builds
  panel/.env.example
  panel/vite.config.mjs
Labels: type: regression 🚨

#6421 Chunked file uploads
  config/api/routes/files.php
  panel/src/helpers/upload.js
  panel/src/panel/upload.js
  src/Api/Api.php
  src/Api/Upload.php
  src/Panel/Panel.php
  src/Panel/View.php
  tests/Api/ApiTest.php
  tests/Api/UploadTest.php
  tests/Api/mocks.php
  tests/bootstrap.php
Labels: type: feature 🎉, needs: two-person review 🧑‍🤝‍🧑
