Repository getkirby/kirby, pull requests merged in 2024-03, with the labels that each got.

#6113 Video block: support for local video files
  config/blocks/video/video.php
  config/blocks/video/video.yml
  i18n/translations/en.json
  panel/src/components/Forms/Blocks/Types/Video.vue
Labels: type: enhancement ✨

#6310 Fix commands for custom textarea buttons
  panel/src/components/Forms/Toolbar/TextareaToolbar.vue
Labels: type: bug 🐛

#6289 Lab: more `$helper` docs
  panel/lab/internals/helpers/color/index.vue
  panel/lab/internals/helpers/debounce/index.vue
  panel/lab/internals/helpers/embed/index.vue
  panel/lab/internals/helpers/field/index.php
  panel/lab/internals/helpers/field/index.vue
  panel/lab/internals/helpers/file/index.vue
  panel/lab/internals/helpers/focus/index.php
  panel/lab/internals/helpers/focus/index.vue
  panel/lab/internals/helpers/isComponent/index.vue
  panel/lab/internals/helpers/isUploadEvent/index.vue
  panel/lab/internals/helpers/keyboard/index.vue
  panel/lab/internals/helpers/link/index.vue
  panel/lab/internals/helpers/object/index.vue
  panel/lab/internals/helpers/page/index.vue
  panel/lab/internals/helpers/queue/index.php
  panel/lab/internals/helpers/queue/index.vue
  panel/lab/internals/helpers/ratio/index.vue
  panel/lab/internals/helpers/regex/index.vue
  panel/lab/internals/helpers/sort/index.vue
  panel/lab/internals/helpers/upload/index.vue
  panel/lab/internals/helpers/url/index.vue
  panel/lab/internals/library.colors/index.vue
  panel/src/helpers/field.js
  panel/src/helpers/file.js
  panel/src/helpers/link.js
  panel/src/helpers/object.js
  panel/src/helpers/page.js
  panel/src/helpers/ratio.js
  panel/src/helpers/url.js
  panel/src/libraries/colors.js
Labels: type: docs 📝

#6306 Improved column creation for tables.
  src/Database/Sql.php
  src/Database/Sql/Sqlite.php
  tests/Database/SqlTest.php
Labels: type: enhancement ✨

#6325 Improve `k-user-avatar`
  panel/src/components/Views/Users/UserAvatar.vue
  panel/src/components/Views/Users/UserProfile.vue
Labels: type: refactoring :recycle:

#6324 Fix `k-tabs` inline variable assignment
  panel/lab/components/tabs/index.vue
  panel/src/components/Layout/Tabs.vue
Labels: type: refactoring :recycle:

#6329 Translatable panel menu titles
  src/Panel/Menu.php
  tests/Panel/MenuTest.php
Labels: type: enhancement ✨

#6323 Fix WriterField counter
  panel/src/components/Forms/Field/WriterField.vue
  panel/src/components/Forms/Input/WriterInput.vue
  panel/src/mixins/forms/counter.js
Labels: type: bug 🐛

#6333 Fix `v-bind` order
  panel/src/components/Dialogs/PageMoveDialog.vue
  panel/src/components/Dialogs/SearchDialog.vue
  panel/src/components/Drawers/FiberDrawer.vue
  panel/src/components/Forms/Blocks/Block.vue
  panel/src/components/Navigation/Button.vue
Labels: type: bug 🐛, type: refactoring :recycle:

#6263 Allow unknown file extensions to be selected in file open dialog
  config/fields/mixins/upload.php
  config/sections/files.php
  src/Cms/FileBlueprint.php
  src/Filesystem/Mime.php
  tests/Cms/Blueprints/FileBlueprintTest.php
  tests/Filesystem/MimeTest.php
Labels: type: bug 🐛

#6336 Use `mounted` lifecycle hook
  panel/src/components/Dialogs/ModelsDialog.vue
  panel/src/components/Dropdowns/Dropdown.vue
  panel/src/components/Dropdowns/DropdownContent.vue
  panel/src/components/Forms/Autocomplete.vue
  panel/src/components/Forms/Blocks/BlockSelector.vue
  panel/src/components/Forms/Blocks/Blocks.vue
  panel/src/components/Forms/Field/FilesField.vue
  panel/src/components/Forms/Field/LinkField.vue
  panel/src/components/Forms/FormButtons.vue
  panel/src/components/Forms/Input/DateInput.vue
  panel/src/components/Layout/AspectRatio.vue
  panel/src/components/Layout/Bubble.vue
  panel/src/components/Layout/Grid.vue
  panel/src/components/Layout/Header.vue
  panel/src/components/Layout/View.vue
  panel/src/components/Misc/Loader.vue
  panel/src/components/Navigation/Breadcrumb.vue
  panel/src/components/Navigation/Button.vue
  panel/src/components/Navigation/ButtonDisabled.vue
  panel/src/components/Navigation/ButtonLink.vue
  panel/src/components/Navigation/ButtonNative.vue
  panel/src/components/Navigation/PageTree.vue
  panel/src/components/Sections/FieldsSection.vue
  panel/src/components/Sections/FilesSection.vue
  panel/src/components/Sections/InfoSection.vue
  panel/src/components/Sections/ModelsSection.vue
  panel/src/components/Sections/PagesSection.vue
  panel/src/components/Sections/StatsSection.vue
  panel/src/components/Text/Headline.vue
  panel/src/components/Text/Text.vue
  panel/src/components/Views/LegacyPluginView.vue
  panel/src/components/Views/Login/LoginView.vue
  panel/src/components/Views/ModelView.vue
  panel/src/components/Views/System/SystemSecurity.vue
  panel/src/components/Views/System/SystemView.vue
Labels: type: refactoring :recycle:

#6321 `k-input-validator`
  panel/lab/components/fields/blocks/index.vue
  panel/lab/components/fields/checkboxes/index.vue
  panel/lab/components/fields/color/index.vue
  panel/lab/components/fields/date/index.vue
  panel/lab/components/fields/email/index.vue
  panel/lab/components/fields/files/index.vue
  panel/lab/components/fields/headline/index.vue
  panel/lab/components/fields/info/index.vue
  panel/lab/components/fields/layout/index.vue
  panel/lab/components/fields/line/index.vue
  panel/lab/components/fields/link/index.vue
  panel/lab/components/fields/list/index.vue
  panel/lab/components/fields/multiselect/index.vue
  panel/lab/components/fields/number/index.vue
  panel/lab/components/fields/object/index.vue
  panel/lab/components/fields/pages/index.vue
  panel/lab/components/fields/password/index.vue
  panel/lab/components/fields/radio/index.vue
  panel/lab/components/fields/range/index.vue
  panel/lab/components/fields/select/index.vue
  panel/lab/components/fields/slug/index.vue
  panel/lab/components/fields/structure/index.vue
  panel/lab/components/fields/tags/index.vue
  panel/lab/components/fields/tel/index.vue
  panel/lab/components/fields/text/index.vue
  panel/lab/components/fields/textarea/index.vue
  panel/lab/components/fields/time/index.vue
  panel/lab/components/fields/toggle/index.vue
  panel/lab/components/fields/toggles/index.vue
  panel/lab/components/fields/url/index.vue
  panel/lab/components/fields/users/index.vue
  panel/lab/components/fields/writer/index.vue
  panel/lab/components/inputs/picklist/index.vue
  panel/src/components/Forms/Blocks/Blocks.vue
  panel/src/components/Forms/Field/BlocksField.vue
  panel/src/components/Forms/Field/LayoutField.vue
  panel/src/components/Forms/Field/LinkField.vue
  panel/src/components/Forms/Field/ModelsField.vue
  panel/src/components/Forms/Field/ObjectField.vue
  panel/src/components/Forms/Field/StructureField.vue
  panel/src/components/Forms/Input/CheckboxesInput.vue
  panel/src/components/Forms/Input/MultiselectInput.vue
  panel/src/components/Forms/Input/PicklistInput.vue
  panel/src/components/Forms/Input/RadioInput.vue
  panel/src/components/Forms/Input/TagsInput.vue
  panel/src/components/Forms/Input/TogglesInput.vue
  panel/src/components/Forms/Input/Validator.js
  panel/src/components/Forms/Input/WriterInput.vue
  panel/src/components/Forms/Input/index.js
  panel/src/components/Forms/Layouts/Layouts.vue
  panel/src/components/Lab/PlaygroundView.vue
  panel/src/components/Text/Label.vue
Labels: type: enhancement ✨, type: refactoring :recycle:

#6343 ChoiceInput: disable when full
  panel/src/components/Forms/Input/CheckboxesInput.vue
  panel/src/components/Forms/Input/ChoiceInput.vue
Labels: type: enhancement ✨

#6334 Keep title when switching template in create dialog
  src/Panel/PageCreateDialog.php
Labels: type: regression 🚨

#6099 Goodbye `vuelidate`
  panel/package-lock.json
  panel/package.json
  panel/src/components/Dialogs/Elements/Fields.vue
  panel/src/components/Dialogs/FormDialog.vue
  panel/src/components/Dialogs/PageCreateDialog.vue
  panel/src/components/Dialogs/TotpDialog.vue
  panel/src/components/Dialogs/UploadDialog.vue
  panel/src/components/Drawers/Elements/Fields.vue
  panel/src/components/Forms/Field/DateField.vue
  panel/src/components/Forms/Field/LinkField.vue
  panel/src/components/Forms/Field/ModelsField.vue
  panel/src/components/Forms/Field/ObjectField.vue
  panel/src/components/Forms/Field/StructureField.vue
  panel/src/components/Forms/Fieldset.vue
  panel/src/components/Forms/Form.vue
  panel/src/components/Forms/Input.vue
  panel/src/components/Forms/Input/CheckboxesInput.vue
  panel/src/components/Forms/Input/DateInput.vue
  panel/src/components/Forms/Input/EmailInput.vue
  panel/src/components/Forms/Input/MultiselectInput.vue
  panel/src/components/Forms/Input/NumberInput.vue
  panel/src/components/Forms/Input/PasswordInput.vue
  panel/src/components/Forms/Input/PicklistInput.vue
  panel/src/components/Forms/Input/RadioInput.vue
  panel/src/components/Forms/Input/RangeInput.vue
  panel/src/components/Forms/Input/SelectInput.vue
  panel/src/components/Forms/Input/SlugInput.vue
  panel/src/components/Forms/Input/StringInput.vue
  panel/src/components/Forms/Input/TelInput.vue
  panel/src/components/Forms/Input/TextInput.vue
  panel/src/components/Forms/Input/TextareaInput.vue
  panel/src/components/Forms/Input/ToggleInput.vue
  panel/src/components/Forms/Input/TogglesInput.vue
  panel/src/components/Forms/Input/UrlInput.vue
  panel/src/components/Forms/Input/WriterInput.vue
  panel/src/components/Forms/Login.vue
  panel/src/components/Forms/LoginCode.vue
  panel/src/components/Text/Label.vue
  panel/src/components/Views/Login/InstallationView.vue
  panel/src/index.js
  panel/src/mixins/props.js
  panel/src/mixins/props/invalid.js
  panel/vite.config.mjs
Labels: type: enhancement ✨, type: refactoring :recycle:

#6340 Pagination for the file browser component
  panel/lab/components/browsers/files/index.vue
  panel/src/components/Navigation/FileBrowser.vue
  panel/src/components/Navigation/Pagination.vue
Labels: type: bug 🐛

#6364 Allow to prefill the login form
  panel/src/components/Forms/Login.vue
  panel/src/components/Forms/LoginCode.vue
  panel/src/components/Views/Login/LoginView.vue
Labels: type: enhancement ✨

#6352 Panel fields: fix direction for content lanuage
  panel/src/config/i18n.js
Labels: type: bug 🐛

#6353 Tags input: split on separator
  panel/src/components/Forms/Input/TagsInput.vue
Labels: type: enhancement ✨, type: bug 🐛

#6360 Page create dialog via section in user/file model
  src/Panel/PageCreateDialog.php
Labels: type: bug 🐛

#6362 Dayjs: add more formats for interpreting inputs
  panel/src/libraries/dayjs-interpret.js
  panel/src/libraries/dayjs-interpret.test.js
Labels: type: enhancement ✨

#6361 Object field: no inline edit when field disabled
  panel/lab/components/fieldpreviews/toggle/index.vue
  panel/src/components/Forms/Previews/ToggleFieldPreview.vue
Labels: type: bug 🐛

#6357 Table layout: allow modifying default columns
  config/sections/mixins/layout.php
  tests/Cms/Sections/FilesSectionTest.php
  tests/Cms/Sections/PagesSectionTest.php
  tests/Cms/Sections/mixins/LayoutMixinTest.php
Labels: type: enhancement ✨

#6367 Fix toggle field preview value error
  config/sections/mixins/layout.php
  panel/src/components/Forms/Previews/ToggleFieldPreview.vue
Labels: type: bug 🐛
