Repository getkirby/kirby, pull requests merged in 2024-01, with the labels that each got.

#6118 PHPUnit reliability refactoring (part 1)
  .gitignore
  phpunit.xml.dist
  src/Api/Api.php
  src/Cms/Core.php
  src/Form/Form.php
  src/Http/Environment.php
  tests/Cms/Ingredients/RootsTest.php
  tests/Cms/Site/SiteActionsTest.php
  tests/Cms/System/LicenseTest.php
  tests/Data/tmp/.gitkeep
  tests/Data/tmp/data.json
  tests/Data/tmp/data.txt
  tests/Data/tmp/data.yml
  tests/Database/DatabaseTest.php
  tests/Filesystem/FileTest.php
  tests/Form/FormTest.php
  tests/Http/CookieTest.php
  tests/Option/OptionsApiTest.php
  tests/Panel/PluginsTest.php
  tests/Panel/UserTest.php
  tests/PhpUnitExtension.php
  tests/Query/QueryDefaultFunctionsTest.php
  tests/Text/KirbyTagTest.php
  tests/Toolkit/DomTest.php
  tests/bootstrap.php
Labels: type: refactoring :recycle:, type: tests 🧪

#6090 Allow activation of legacy and inactive licenses
  src/Cms/License.php
  src/Cms/LicenseStatus.php
  tests/Cms/System/LicenseTest.php
Labels: type: bug 🐛

#6100 Replace `instanceof Vue`
  panel/src/components/Dropdowns/DropdownContent.vue
Labels: type: refactoring :recycle:

#6111 Fix `$store.content.id` when deleting page
  panel/src/store/modules/content.js
Labels: type: regression 🚨

#6107 Replace Vue `$listeners`
  panel/src/components/Forms/Field/BlocksField.vue
  panel/src/components/Forms/Field/CheckboxesField.vue
  panel/src/components/Forms/Field/EmailField.vue
  panel/src/components/Forms/Field/MultiselectField.vue
  panel/src/components/Forms/Field/NumberField.vue
  panel/src/components/Forms/Field/PasswordField.vue
  panel/src/components/Forms/Field/RadioField.vue
  panel/src/components/Forms/Field/RangeField.vue
  panel/src/components/Forms/Field/SelectField.vue
  panel/src/components/Forms/Field/SlugField.vue
  panel/src/components/Forms/Field/TagsField.vue
  panel/src/components/Forms/Field/TelField.vue
  panel/src/components/Forms/Field/TextField.vue
  panel/src/components/Forms/Field/TextareaField.vue
  panel/src/components/Forms/Field/ToggleField.vue
  panel/src/components/Forms/Field/TogglesField.vue
  panel/src/components/Forms/Field/UrlField.vue
  panel/src/components/Forms/Input.vue
  panel/src/components/Forms/Input/NumberInput.vue
  panel/src/components/Forms/Input/SelectInput.vue
  panel/src/components/Forms/Input/TextInput.vue
  panel/src/components/Layout/Frame/ImageFrame.vue
  panel/src/components/Sections/ModelsSection.vue
Labels: type: refactoring :recycle:

#6108 Fix `counter.js` for stricter Vue 3 checks
  panel/lab/components/counter/index.vue
  panel/src/components/Forms/Counter.vue
  panel/src/mixins/forms/counter.js
Labels: type: refactoring :recycle:

#6125 Use more PHP arrow functions
  src/Cms/ModelWithContent.php
  src/Cms/PageActions.php
  src/Cms/Pages.php
  src/Cms/SiteActions.php
  src/Toolkit/A.php
  src/Toolkit/Collection.php
  tests/Cms/App/AppErrorsTest.php
  tests/Cms/App/fixtures/fields/DummyField.php
  tests/Cms/Blocks/BlockMethodsTest.php
  tests/Cms/Collections/fixtures/collections/nested/test.php
  tests/Cms/Collections/fixtures/collections/test.php
  tests/Cms/Files/FileMethodsTest.php
  tests/Cms/Files/FileModificationsTest.php
  tests/Cms/Files/FileTest.php
  tests/Cms/Helpers/HelperFunctionsTest.php
  tests/Cms/Ingredients/IngredientsTest.php
  tests/Cms/Loader/LoaderTest.php
  tests/Toolkit/ATest.php
  tests/Toolkit/ComponentTest.php
  tests/Toolkit/SymmetricCryptoTest.php
  tests/Toolkit/fixtures/controller/controller.php
Labels: type: refactoring :recycle:

#6029 `Panel\Model::image()`: fix `false` from blueprint
  src/Panel/Model.php
  tests/Panel/ModelTest.php
Labels: type: bug 🐛

#6097 Replace `this._uid`
  panel/src/components/Dropdowns/DropdownContent.vue
  panel/src/components/Forms/Blocks/Blocks.vue
  panel/src/components/Forms/Field/CheckboxesField.vue
  panel/src/components/Forms/Field/ColorField.vue
  panel/src/components/Forms/Field/DateField.vue
  panel/src/components/Forms/Field/EmailField.vue
  panel/src/components/Forms/Field/InfoField.vue
  panel/src/components/Forms/Field/LinkField.vue
  panel/src/components/Forms/Field/ListField.vue
  panel/src/components/Forms/Field/MultiselectField.vue
  panel/src/components/Forms/Field/NumberField.vue
  panel/src/components/Forms/Field/PasswordField.vue
  panel/src/components/Forms/Field/RadioField.vue
  panel/src/components/Forms/Field/RangeField.vue
  panel/src/components/Forms/Field/SelectField.vue
  panel/src/components/Forms/Field/SlugField.vue
  panel/src/components/Forms/Field/StructureField.vue
  panel/src/components/Forms/Field/TagsField.vue
  panel/src/components/Forms/Field/TelField.vue
  panel/src/components/Forms/Field/TextField.vue
  panel/src/components/Forms/Field/TextareaField.vue
  panel/src/components/Forms/Field/TimeField.vue
  panel/src/components/Forms/Field/ToggleField.vue
  panel/src/components/Forms/Field/TogglesField.vue
  panel/src/components/Forms/Field/UrlField.vue
  panel/src/components/Forms/Field/WriterField.vue
  panel/src/components/Forms/Input/CheckboxesInput.vue
  panel/src/components/Forms/Input/ColoroptionsInput.vue
  panel/src/components/Forms/Input/RadioInput.vue
  panel/src/components/Forms/Layouts/Layouts.vue
  panel/src/components/Navigation/Pagination.vue
Labels: type: refactoring :recycle:

#6128 Fix overflow in narrow LayoutColumn with fields
  panel/src/components/Forms/Blocks/Types/Fields.vue
Labels: type: bug 🐛

#5826 Blocks: disabled field preview
  panel/lab/components/blocks/code/index.php
  panel/lab/components/blocks/default/index.php
  panel/lab/components/blocks/fields/index.php
  panel/lab/components/blocks/gallery/index.php
  panel/lab/components/blocks/heading/index.php
  panel/lab/components/blocks/image/index.php
  panel/lab/components/blocks/line/index.php
  panel/lab/components/blocks/list/index.php
  panel/lab/components/blocks/markdown/index.php
  panel/lab/components/blocks/quote/index.php
  panel/lab/components/blocks/table/index.php
  panel/lab/components/blocks/text/index.php
  panel/lab/components/blocks/video/index.php
  panel/public/js/plugins.js
  panel/src/components/Forms/Blocks/Block.vue
  panel/src/components/Forms/Blocks/BlockOptions.vue
  panel/src/components/Forms/Blocks/BlockSelector.vue
  panel/src/components/Forms/Blocks/BlockType.vue
  panel/src/components/Forms/Blocks/Blocks.vue
  panel/src/components/Forms/Blocks/Elements/BlockFigure.vue
  panel/src/components/Forms/Blocks/Elements/BlockTitle.vue
  panel/src/components/Forms/Blocks/Types/Code.vue
  panel/src/components/Forms/Blocks/Types/Default.vue
  panel/src/components/Forms/Blocks/Types/Fields.vue
  panel/src/components/Forms/Blocks/Types/Gallery.vue
  panel/src/components/Forms/Blocks/Types/Heading.vue
  panel/src/components/Forms/Blocks/Types/Image.vue
  panel/src/components/Forms/Blocks/Types/Line.vue
  panel/src/components/Forms/Blocks/Types/List.vue
  panel/src/components/Forms/Blocks/Types/Markdown.vue
  panel/src/components/Forms/Blocks/Types/Quote.vue
  panel/src/components/Forms/Blocks/Types/Table.vue
  panel/src/components/Forms/Blocks/Types/Text.vue
  panel/src/components/Forms/Blocks/Types/Video.vue
  panel/src/components/Forms/Blocks/index.js
  panel/src/components/Forms/Field/BlocksField.vue
  panel/src/components/Forms/Field/LayoutField.vue
  panel/src/components/Forms/Layouts/Layout.vue
  panel/src/components/Forms/Layouts/LayoutColumn.vue
  panel/src/components/Forms/Layouts/Layouts.vue
Labels: type: bug 🐛, type: refactoring :recycle:

#6109 Fix CSS selectors for boolean attributes
  panel/lab/components/tables/1_horizontal/index.vue
  panel/lab/components/tables/2_vertical/index.vue
  panel/src/components/Dialogs/PagesDialog.vue
  panel/src/components/Dialogs/UploadDialog.vue
  panel/src/components/Drawers/Elements/Header.vue
  panel/src/components/Drawers/Elements/Tabs.vue
  panel/src/components/Drawers/FiberDrawer.vue
  panel/src/components/Dropdowns/DropdownItem.vue
  panel/src/components/Forms/Blocks/BlockSelector.vue
  panel/src/components/Forms/Input/ChoiceInput.vue
  panel/src/components/Forms/Input/CoordsInput.vue
  panel/src/components/Forms/Input/ToggleInput.vue
  panel/src/components/Forms/Layouts/LayoutSelector.vue
  panel/src/components/Forms/Toolbar/Toolbar.vue
  panel/src/components/Lab/Example.vue
  panel/src/components/Layout/Overlay.vue
  panel/src/components/Layout/Table.vue
  panel/src/components/Layout/Tabs.vue
  panel/src/components/Navigation/Button.vue
  panel/src/components/Navigation/Tag.vue
  panel/src/components/Navigation/Tree.vue
  panel/src/components/Text/Label.vue
  panel/src/components/View/Menu.vue
Labels: type: bug 🐛, type: refactoring :recycle:

#6139 More PHPUnit refactoring
  tests/Cache/ApcuCacheTest.php
  tests/Cache/CacheTest.php
  tests/Cache/FileCacheTest.php
  tests/Cache/MemCachedTest.php
  tests/Cache/MemoryCacheTest.php
  tests/Cache/ValueTest.php
  tests/Cms/App/AppErrorsTest.php
  tests/Cms/App/AppPluginsTest.php
  tests/Cms/Auth/AuthChallengeTest.php
  tests/Cms/Auth/AuthProtectionTest.php
  tests/Cms/ResponderTest.php
  tests/Cms/System/UpdateStatusTest.php
  tests/Cms/TestCase.php
  tests/Data/DataTest.php
  tests/Data/HandlerTest.php
  tests/Database/QueryTest.php
  tests/Database/SqlTest.php
  tests/Filesystem/FTest.php
  tests/Filesystem/FileTest.php
  tests/Http/RemoteTest.php
  tests/Http/ResponseTest.php
  tests/Sane/DomHandlerTest.php
  tests/Sane/HandlerTest.php
  tests/Sane/SaneTest.php
  tests/Session/AutoSessionTest.php
  tests/Session/FileSessionStoreTest.php
  tests/Session/SessionDataTest.php
  tests/Session/SessionTest.php
  tests/Session/SessionsTest.php
  tests/Template/TestCase.php
  tests/Toolkit/TotpTest.php
  tests/bootstrap.php
Labels: type: refactoring :recycle:

#6145 Fix default type if `url` option not available
  panel/src/components/Forms/Field/LinkField.vue
Labels: type: bug 🐛

#6138 License dialog: Always use `date` handler
  config/areas/system/dialogs.php
  src/Cms/License.php
  tests/Cms/System/LicenseTest.php
Labels: type: bug 🐛

#6140 Deprecate `Array.prototype` functions
  panel/src/components/Forms/Field/StructureField.vue
  panel/src/components/View/Menu.vue
  panel/src/helpers/array.js
Labels: type: refactoring :recycle:

#6130 Pass `languageCode` argument for some missing hooks
  src/Cms/PageActions.php
  src/Cms/SiteActions.php
  tests/Cms/Pages/PageActionsTest.php
  tests/Cms/Site/SiteActionsTest.php
Labels: type: regression 🚨

#6085 Improve link kirbytag behavior when uuid point to non-existing page
  config/tags.php
  tests/Text/KirbyTagsTest.php
Labels: type: bug 🐛

#6149 Writer toolbar: fix when implicitly inline
  panel/src/components/Forms/Writer/Writer.vue
Labels: type: bug 🐛

#6143 Support dimensions for `avif` images
  src/Image/Image.php
  tests/Image/DimensionsTest.php
  tests/Image/fixtures/image/onigiri-adobe-rgb-gps.avif
Labels: type: enhancement ✨

#6150 Files section: fix `NaN` after file sort
  config/sections/files.php
Labels: type: regression 🚨

#6148 PageCreateDialog: use field defaults
  src/Panel/PageCreateDialog.php
  tests/Panel/PageCreateDialogTest.php
Labels: type: bug 🐛

#6152 Color field: fix options from query
  config/fields/color.php
  src/Option/OptionsQuery.php
  tests/Form/Fields/ColorFieldTest.php
Labels: type: bug 🐛, critical: roadblock 🚧, needs: two-person review 🧑‍🤝‍🧑

#6147 Pages section table: add field types for columns
  config/sections/files.php
  config/sections/mixins/layout.php
  config/sections/pages.php
  panel/src/components/Collection/Collection.vue
  panel/src/components/Collection/Items.vue
  panel/src/components/Sections/ModelsSection.vue
Labels: type: enhancement ✨

#6156 Fix column block gap
  panel/src/components/Layout/Grid.vue
Labels: type: bug 🐛

#6155 Table layout: fix `mobile` columns
  panel/lab/components/tables/3_height/index.vue
  panel/src/components/Layout/Table.vue
Labels: type: regression 🚨

#6154 Page create dialog: hide `title` and/or `slug`
  panel/src/panel/modal.js
  panel/src/panel/panel.js
  src/Panel/PageCreateDialog.php
  tests/Panel/PageCreateDialogTest.php
Labels: type: feature 🎉

#6162 BlockTitle: use `label` as fallback for `name`
  panel/lab/components/block/4_title/index.vue
  panel/src/components/Forms/Blocks/Elements/BlockTitle.vue
Labels: type: enhancement ✨

#6158 Panel search: support dialog open with spec type
  panel/src/components/Dialogs/SearchDialog.vue
  panel/src/panel/panel.js
Labels: type: enhancement ✨

#6171 Update PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type: docs 📝

#6174 Raise `ecmaVersion` for eslint parser
  panel/.eslintrc.js
Labels: type: tests 🧪

#6175 Cache `Blueprint` sections
  src/Cms/Blueprint.php
Labels: type: performance ⚡️

#6181 Structure: Fix regressions from `Items` refactoring
  config/methods.php
  src/Cms/Structure.php
  tests/Cms/Structures/StructureTest.php
  tests/Content/FieldMethodsTest.php
Labels: type: regression 🚨

#6178 `file` KirbyTag: fix fallback for not found file
  config/tags.php
  tests/Text/KirbyTagsTest.php
Labels: type: bug 🐛

#5834 Link field preview
  panel/lab/components/fieldpreviews/link/index.php
  panel/lab/components/fieldpreviews/link/index.vue
  panel/lab/components/tags/1_tag/index.vue
  panel/public/img/icons.svg
  panel/src/components/Forms/Field/LinkField.vue
  panel/src/components/Forms/Previews/LinkFieldPreview.vue
  panel/src/components/Forms/Previews/index.js
  panel/src/components/Layout/Bubble.vue
  panel/src/components/Navigation/Button.vue
  panel/src/components/Navigation/Tag.vue
  panel/src/helpers/index.js
  panel/src/helpers/link.js
  panel/src/helpers/link.test.js
Labels: type: enhancement ✨

#6173 Remove `hasErrors()` method from `k-fieldset`
  panel/src/components/Forms/Fieldset.vue
Labels: type: refactoring :recycle:

#6172 Merge `k-writer` into `k-writer-input`
  panel/lab/components/toolbar/3_writer/index.vue
  panel/src/components/Forms/Blocks/Blocks.vue
  panel/src/components/Forms/Blocks/Elements/BlockFigure.vue
  panel/src/components/Forms/Blocks/Types/Gallery.vue
  panel/src/components/Forms/Blocks/Types/Heading.vue
  panel/src/components/Forms/Blocks/Types/Quote.vue
  panel/src/components/Forms/Blocks/Types/Text.vue
  panel/src/components/Forms/Input/ListInput.vue
  panel/src/components/Forms/Input/WriterInput.vue
  panel/src/components/Forms/Input/index.js
  panel/src/components/Forms/Toolbar/index.js
  panel/src/components/Forms/Writer/Toolbar.vue
  panel/src/components/Forms/Writer/Writer.vue
  panel/src/components/Forms/Writer/index.js
  panel/src/components/Forms/index.js
Labels: type: refactoring :recycle:

#5781 Don't change uuid if exact same file
  src/Cms/FileActions.php
  tests/Cms/Files/FileActionsTest.php
Labels: needs: discussion 🗣, type: bug 🐛, needs: tests 🧪

#6191 RangeInput: fix tooltip max width
  panel/src/components/Forms/Input/RangeInput.vue
Labels: type: bug 🐛

#6192 LinkField: fix dropdown for only option
  panel/src/components/Forms/Field/LinkField.vue
Labels: type: bug 🐛

#6200 Fix structure field sort method
  panel/src/components/Forms/Field/StructureField.vue
Labels: type: regression 🚨

#6103 Use `StringInput` for all text inputs
  panel/src/components/Forms/Input/EmailInput.vue
  panel/src/components/Forms/Input/PasswordInput.vue
  panel/src/components/Forms/Input/SlugInput.vue
  panel/src/components/Forms/Input/StringInput.vue
  panel/src/components/Forms/Input/TelInput.vue
  panel/src/components/Forms/Input/TextInput.vue
  panel/src/components/Forms/Input/UrlInput.vue
Labels: type: refactoring :recycle:

#6205 ImageMagick: remove optimization that breaks focus
  src/Image/Darkroom/ImageMagick.php
Labels: type: regression 🚨

#6180 Performance testing with `phpbench`
  .gitattributes
  .gitignore
  bench/bootstrap.php
  composer.json
  phpbench.json
Labels: type: tests 🧪

#6217 Fix type hint on `Panel::area()`
  src/Panel/Panel.php
Labels: type: bug 🐛

#6219 Fix `A::prepend()`
  src/Toolkit/A.php
  tests/Toolkit/ATest.php
Labels: type: bug 🐛

#6215 Fix `Str::excerpt()` for text without spaces
  src/Toolkit/Str.php
  tests/Toolkit/StrTest.php
Labels: type: bug 🐛

#6227 `$file->sharpen()`
  src/Cms/FileModifications.php
  tests/Cms/Files/FileModificationsTest.php
Labels: type: enhancement ✨
